// Code generated by fastbelt. DO NOT EDIT.

package arithmetics

import (
	"sync"
	"typefox.dev/fastbelt/parser"
)

const (
	StateNumber__Module__Start = iota
	StateNumber__Module__Stop
	StateNumber__Statement__Start
	StateNumber__Statement__Stop
	StateNumber__Definition__Start
	StateNumber__Definition__Stop
	StateNumber__DeclaredParameter__Start
	StateNumber__DeclaredParameter__Stop
	StateNumber__Evaluation__Start
	StateNumber__Evaluation__Stop
	StateNumber__Expression__Start
	StateNumber__Expression__Stop
	StateNumber__Addition__Start
	StateNumber__Addition__Stop
	StateNumber__Multiplication__Start
	StateNumber__Multiplication__Stop
	StateNumber__Exponentiation__Start
	StateNumber__Exponentiation__Stop
	StateNumber__Modulo__Start
	StateNumber__Modulo__Stop
	StateNumber__PrimaryExpression__Start
	StateNumber__PrimaryExpression__Stop
	StateNumber__Module_MODULE
	StateNumber__Module_Name_ID
	StateNumber__Module__Basic_0
	StateNumber__Module__Basic_1
	StateNumber__Module__LoopEntry
	StateNumber__Module__LoopEnd
	StateNumber__Module__LoopBack
	StateNumber__Statement__Basic_0
	StateNumber__Statement__Basic_1
	StateNumber__Statement__Basic_2
	StateNumber__Statement__Basic_3
	StateNumber__Statement__Basic_4
	StateNumber__Statement__BlockEnd
	StateNumber__Definition_DEF
	StateNumber__Definition_Name_ID
	StateNumber__Definition_LPAREN
	StateNumber__Definition__Basic_0
	StateNumber__Definition_COMMA
	StateNumber__Definition__Basic_1
	StateNumber__Definition__Basic_2
	StateNumber__Definition__LoopEntry
	StateNumber__Definition__LoopEnd
	StateNumber__Definition__LoopBack
	StateNumber__Definition_RPAREN
	StateNumber__Definition__Basic_3
	StateNumber__Definition__Basic_4
	StateNumber__Definition_COLON
	StateNumber__Definition__Basic_5
	StateNumber__Definition_SEMICOLON
	StateNumber__Definition__Basic_6
	StateNumber__DeclaredParameter_Name_ID
	StateNumber__DeclaredParameter__Basic
	StateNumber__Evaluation__Basic_0
	StateNumber__Evaluation_SEMICOLON
	StateNumber__Evaluation__Basic_1
	StateNumber__Expression__Basic_0
	StateNumber__Expression__Basic_1
	StateNumber__Addition__Basic_0
	StateNumber__Addition_Operator_PLUS
	StateNumber__Addition__Basic_1
	StateNumber__Addition_Operator_MINUS
	StateNumber__Addition__Basic_2
	StateNumber__Addition__Basic_3
	StateNumber__Addition__BlockEnd
	StateNumber__Addition__Basic_4
	StateNumber__Addition__Basic_5
	StateNumber__Addition__LoopEntry
	StateNumber__Addition__LoopEnd
	StateNumber__Addition__LoopBack
	StateNumber__Multiplication__Basic_0
	StateNumber__Multiplication_Operator_STAR
	StateNumber__Multiplication__Basic_1
	StateNumber__Multiplication_Operator_SLASH
	StateNumber__Multiplication__Basic_2
	StateNumber__Multiplication__Basic_3
	StateNumber__Multiplication__BlockEnd
	StateNumber__Multiplication__Basic_4
	StateNumber__Multiplication__Basic_5
	StateNumber__Multiplication__LoopEntry
	StateNumber__Multiplication__LoopEnd
	StateNumber__Multiplication__LoopBack
	StateNumber__Exponentiation__Basic_0
	StateNumber__Exponentiation_Operator_CARET
	StateNumber__Exponentiation__Basic_1
	StateNumber__Exponentiation__Basic_2
	StateNumber__Exponentiation__LoopEntry
	StateNumber__Exponentiation__LoopEnd
	StateNumber__Exponentiation__LoopBack
	StateNumber__Modulo__Basic_0
	StateNumber__Modulo_Operator_PERCENT
	StateNumber__Modulo__Basic_1
	StateNumber__Modulo__Basic_2
	StateNumber__Modulo__LoopEntry
	StateNumber__Modulo__LoopEnd
	StateNumber__Modulo__LoopBack
	StateNumber__PrimaryExpression_LPAREN_0
	StateNumber__PrimaryExpression__Basic_0
	StateNumber__PrimaryExpression_RPAREN_0
	StateNumber__PrimaryExpression__Basic_1
	StateNumber__PrimaryExpression_Value_NUMBER
	StateNumber__PrimaryExpression__Basic_2
	StateNumber__PrimaryExpression_Callable_ID
	StateNumber__PrimaryExpression_LPAREN_1
	StateNumber__PrimaryExpression__Basic_3
	StateNumber__PrimaryExpression_COMMA
	StateNumber__PrimaryExpression__Basic_4
	StateNumber__PrimaryExpression__Basic_5
	StateNumber__PrimaryExpression__LoopEntry
	StateNumber__PrimaryExpression__LoopEnd
	StateNumber__PrimaryExpression__LoopBack
	StateNumber__PrimaryExpression_RPAREN_1
	StateNumber__PrimaryExpression__Basic_6
	StateNumber__PrimaryExpression__Basic_7
	StateNumber__PrimaryExpression__Basic_8
	StateNumber__PrimaryExpression__BlockEnd
)

var once sync.Once
var atn *parser.RuntimeATN

func ATN() *parser.RuntimeATN {
	once.Do(func() {
		atn = BuildATN()
	})
	return atn
}
func BuildATN() *parser.RuntimeATN {
	states := make([]*parser.RuntimeATNState, 117)
	states[StateNumber__Module__Start] = parser.NewATNState(StateNumber__Module__Start, parser.ATNRuleStart, true)
	states[StateNumber__Module__Stop] = parser.NewATNState(StateNumber__Module__Stop, parser.ATNRuleStop, false)
	states[StateNumber__Statement__Start] = parser.NewATNState(StateNumber__Statement__Start, parser.ATNRuleStart, true)
	states[StateNumber__Statement__Stop] = parser.NewATNState(StateNumber__Statement__Stop, parser.ATNRuleStop, false)
	states[StateNumber__Definition__Start] = parser.NewATNState(StateNumber__Definition__Start, parser.ATNRuleStart, true)
	states[StateNumber__Definition__Stop] = parser.NewATNState(StateNumber__Definition__Stop, parser.ATNRuleStop, false)
	states[StateNumber__DeclaredParameter__Start] = parser.NewATNState(StateNumber__DeclaredParameter__Start, parser.ATNRuleStart, true)
	states[StateNumber__DeclaredParameter__Stop] = parser.NewATNState(StateNumber__DeclaredParameter__Stop, parser.ATNRuleStop, false)
	states[StateNumber__Evaluation__Start] = parser.NewATNState(StateNumber__Evaluation__Start, parser.ATNRuleStart, true)
	states[StateNumber__Evaluation__Stop] = parser.NewATNState(StateNumber__Evaluation__Stop, parser.ATNRuleStop, false)
	states[StateNumber__Expression__Start] = parser.NewATNState(StateNumber__Expression__Start, parser.ATNRuleStart, true)
	states[StateNumber__Expression__Stop] = parser.NewATNState(StateNumber__Expression__Stop, parser.ATNRuleStop, false)
	states[StateNumber__Addition__Start] = parser.NewATNState(StateNumber__Addition__Start, parser.ATNRuleStart, true)
	states[StateNumber__Addition__Stop] = parser.NewATNState(StateNumber__Addition__Stop, parser.ATNRuleStop, false)
	states[StateNumber__Multiplication__Start] = parser.NewATNState(StateNumber__Multiplication__Start, parser.ATNRuleStart, true)
	states[StateNumber__Multiplication__Stop] = parser.NewATNState(StateNumber__Multiplication__Stop, parser.ATNRuleStop, false)
	states[StateNumber__Exponentiation__Start] = parser.NewATNState(StateNumber__Exponentiation__Start, parser.ATNRuleStart, true)
	states[StateNumber__Exponentiation__Stop] = parser.NewATNState(StateNumber__Exponentiation__Stop, parser.ATNRuleStop, false)
	states[StateNumber__Modulo__Start] = parser.NewATNState(StateNumber__Modulo__Start, parser.ATNRuleStart, true)
	states[StateNumber__Modulo__Stop] = parser.NewATNState(StateNumber__Modulo__Stop, parser.ATNRuleStop, false)
	states[StateNumber__PrimaryExpression__Start] = parser.NewATNState(StateNumber__PrimaryExpression__Start, parser.ATNRuleStart, true)
	states[StateNumber__PrimaryExpression__Stop] = parser.NewATNState(StateNumber__PrimaryExpression__Stop, parser.ATNRuleStop, false)
	states[StateNumber__Module_MODULE] = parser.NewATNState(StateNumber__Module_MODULE, parser.ATNBasic, false)
	states[StateNumber__Module_Name_ID] = parser.NewATNState(StateNumber__Module_Name_ID, parser.ATNBasic, false)
	states[StateNumber__Module__Basic_0] = parser.NewATNState(StateNumber__Module__Basic_0, parser.ATNBasic, true)
	states[StateNumber__Module__Basic_1] = parser.NewATNState(StateNumber__Module__Basic_1, parser.ATNBasic, true)
	states[StateNumber__Module__LoopEntry] = parser.NewATNState(StateNumber__Module__LoopEntry, parser.ATNLoopEntry, true).SetDecision(0)
	states[StateNumber__Module__LoopEnd] = parser.NewATNState(StateNumber__Module__LoopEnd, parser.ATNLoopEnd, true)
	states[StateNumber__Module__LoopBack] = parser.NewATNState(StateNumber__Module__LoopBack, parser.ATNLoopBack, true)
	states[StateNumber__Statement__Basic_0] = parser.NewATNState(StateNumber__Statement__Basic_0, parser.ATNBasic, true)
	states[StateNumber__Statement__Basic_1] = parser.NewATNState(StateNumber__Statement__Basic_1, parser.ATNBasic, true)
	states[StateNumber__Statement__Basic_2] = parser.NewATNState(StateNumber__Statement__Basic_2, parser.ATNBasic, true)
	states[StateNumber__Statement__Basic_3] = parser.NewATNState(StateNumber__Statement__Basic_3, parser.ATNBasic, true)
	states[StateNumber__Statement__Basic_4] = parser.NewATNState(StateNumber__Statement__Basic_4, parser.ATNBasic, true).SetDecision(1)
	states[StateNumber__Statement__BlockEnd] = parser.NewATNState(StateNumber__Statement__BlockEnd, parser.ATNBlockEnd, true)
	states[StateNumber__Definition_DEF] = parser.NewATNState(StateNumber__Definition_DEF, parser.ATNBasic, false)
	states[StateNumber__Definition_Name_ID] = parser.NewATNState(StateNumber__Definition_Name_ID, parser.ATNBasic, false)
	states[StateNumber__Definition_LPAREN] = parser.NewATNState(StateNumber__Definition_LPAREN, parser.ATNBasic, false)
	states[StateNumber__Definition__Basic_0] = parser.NewATNState(StateNumber__Definition__Basic_0, parser.ATNBasic, true)
	states[StateNumber__Definition_COMMA] = parser.NewATNState(StateNumber__Definition_COMMA, parser.ATNBasic, false)
	states[StateNumber__Definition__Basic_1] = parser.NewATNState(StateNumber__Definition__Basic_1, parser.ATNBasic, true)
	states[StateNumber__Definition__Basic_2] = parser.NewATNState(StateNumber__Definition__Basic_2, parser.ATNBasic, true)
	states[StateNumber__Definition__LoopEntry] = parser.NewATNState(StateNumber__Definition__LoopEntry, parser.ATNLoopEntry, true).SetDecision(2)
	states[StateNumber__Definition__LoopEnd] = parser.NewATNState(StateNumber__Definition__LoopEnd, parser.ATNLoopEnd, true)
	states[StateNumber__Definition__LoopBack] = parser.NewATNState(StateNumber__Definition__LoopBack, parser.ATNLoopBack, true)
	states[StateNumber__Definition_RPAREN] = parser.NewATNState(StateNumber__Definition_RPAREN, parser.ATNBasic, false)
	states[StateNumber__Definition__Basic_3] = parser.NewATNState(StateNumber__Definition__Basic_3, parser.ATNBasic, true)
	states[StateNumber__Definition__Basic_4] = parser.NewATNState(StateNumber__Definition__Basic_4, parser.ATNBasic, true).SetDecision(3)
	states[StateNumber__Definition_COLON] = parser.NewATNState(StateNumber__Definition_COLON, parser.ATNBasic, false)
	states[StateNumber__Definition__Basic_5] = parser.NewATNState(StateNumber__Definition__Basic_5, parser.ATNBasic, true)
	states[StateNumber__Definition_SEMICOLON] = parser.NewATNState(StateNumber__Definition_SEMICOLON, parser.ATNBasic, false)
	states[StateNumber__Definition__Basic_6] = parser.NewATNState(StateNumber__Definition__Basic_6, parser.ATNBasic, true)
	states[StateNumber__DeclaredParameter_Name_ID] = parser.NewATNState(StateNumber__DeclaredParameter_Name_ID, parser.ATNBasic, false)
	states[StateNumber__DeclaredParameter__Basic] = parser.NewATNState(StateNumber__DeclaredParameter__Basic, parser.ATNBasic, true)
	states[StateNumber__Evaluation__Basic_0] = parser.NewATNState(StateNumber__Evaluation__Basic_0, parser.ATNBasic, true)
	states[StateNumber__Evaluation_SEMICOLON] = parser.NewATNState(StateNumber__Evaluation_SEMICOLON, parser.ATNBasic, false)
	states[StateNumber__Evaluation__Basic_1] = parser.NewATNState(StateNumber__Evaluation__Basic_1, parser.ATNBasic, true)
	states[StateNumber__Expression__Basic_0] = parser.NewATNState(StateNumber__Expression__Basic_0, parser.ATNBasic, true)
	states[StateNumber__Expression__Basic_1] = parser.NewATNState(StateNumber__Expression__Basic_1, parser.ATNBasic, true)
	states[StateNumber__Addition__Basic_0] = parser.NewATNState(StateNumber__Addition__Basic_0, parser.ATNBasic, true)
	states[StateNumber__Addition_Operator_PLUS] = parser.NewATNState(StateNumber__Addition_Operator_PLUS, parser.ATNBasic, false)
	states[StateNumber__Addition__Basic_1] = parser.NewATNState(StateNumber__Addition__Basic_1, parser.ATNBasic, true)
	states[StateNumber__Addition_Operator_MINUS] = parser.NewATNState(StateNumber__Addition_Operator_MINUS, parser.ATNBasic, false)
	states[StateNumber__Addition__Basic_2] = parser.NewATNState(StateNumber__Addition__Basic_2, parser.ATNBasic, true)
	states[StateNumber__Addition__Basic_3] = parser.NewATNState(StateNumber__Addition__Basic_3, parser.ATNBasic, true).SetDecision(4)
	states[StateNumber__Addition__BlockEnd] = parser.NewATNState(StateNumber__Addition__BlockEnd, parser.ATNBlockEnd, true)
	states[StateNumber__Addition__Basic_4] = parser.NewATNState(StateNumber__Addition__Basic_4, parser.ATNBasic, true)
	states[StateNumber__Addition__Basic_5] = parser.NewATNState(StateNumber__Addition__Basic_5, parser.ATNBasic, true)
	states[StateNumber__Addition__LoopEntry] = parser.NewATNState(StateNumber__Addition__LoopEntry, parser.ATNLoopEntry, true).SetDecision(5)
	states[StateNumber__Addition__LoopEnd] = parser.NewATNState(StateNumber__Addition__LoopEnd, parser.ATNLoopEnd, true)
	states[StateNumber__Addition__LoopBack] = parser.NewATNState(StateNumber__Addition__LoopBack, parser.ATNLoopBack, true)
	states[StateNumber__Multiplication__Basic_0] = parser.NewATNState(StateNumber__Multiplication__Basic_0, parser.ATNBasic, true)
	states[StateNumber__Multiplication_Operator_STAR] = parser.NewATNState(StateNumber__Multiplication_Operator_STAR, parser.ATNBasic, false)
	states[StateNumber__Multiplication__Basic_1] = parser.NewATNState(StateNumber__Multiplication__Basic_1, parser.ATNBasic, true)
	states[StateNumber__Multiplication_Operator_SLASH] = parser.NewATNState(StateNumber__Multiplication_Operator_SLASH, parser.ATNBasic, false)
	states[StateNumber__Multiplication__Basic_2] = parser.NewATNState(StateNumber__Multiplication__Basic_2, parser.ATNBasic, true)
	states[StateNumber__Multiplication__Basic_3] = parser.NewATNState(StateNumber__Multiplication__Basic_3, parser.ATNBasic, true).SetDecision(6)
	states[StateNumber__Multiplication__BlockEnd] = parser.NewATNState(StateNumber__Multiplication__BlockEnd, parser.ATNBlockEnd, true)
	states[StateNumber__Multiplication__Basic_4] = parser.NewATNState(StateNumber__Multiplication__Basic_4, parser.ATNBasic, true)
	states[StateNumber__Multiplication__Basic_5] = parser.NewATNState(StateNumber__Multiplication__Basic_5, parser.ATNBasic, true)
	states[StateNumber__Multiplication__LoopEntry] = parser.NewATNState(StateNumber__Multiplication__LoopEntry, parser.ATNLoopEntry, true).SetDecision(7)
	states[StateNumber__Multiplication__LoopEnd] = parser.NewATNState(StateNumber__Multiplication__LoopEnd, parser.ATNLoopEnd, true)
	states[StateNumber__Multiplication__LoopBack] = parser.NewATNState(StateNumber__Multiplication__LoopBack, parser.ATNLoopBack, true)
	states[StateNumber__Exponentiation__Basic_0] = parser.NewATNState(StateNumber__Exponentiation__Basic_0, parser.ATNBasic, true)
	states[StateNumber__Exponentiation_Operator_CARET] = parser.NewATNState(StateNumber__Exponentiation_Operator_CARET, parser.ATNBasic, false)
	states[StateNumber__Exponentiation__Basic_1] = parser.NewATNState(StateNumber__Exponentiation__Basic_1, parser.ATNBasic, true)
	states[StateNumber__Exponentiation__Basic_2] = parser.NewATNState(StateNumber__Exponentiation__Basic_2, parser.ATNBasic, true)
	states[StateNumber__Exponentiation__LoopEntry] = parser.NewATNState(StateNumber__Exponentiation__LoopEntry, parser.ATNLoopEntry, true).SetDecision(8)
	states[StateNumber__Exponentiation__LoopEnd] = parser.NewATNState(StateNumber__Exponentiation__LoopEnd, parser.ATNLoopEnd, true)
	states[StateNumber__Exponentiation__LoopBack] = parser.NewATNState(StateNumber__Exponentiation__LoopBack, parser.ATNLoopBack, true)
	states[StateNumber__Modulo__Basic_0] = parser.NewATNState(StateNumber__Modulo__Basic_0, parser.ATNBasic, true)
	states[StateNumber__Modulo_Operator_PERCENT] = parser.NewATNState(StateNumber__Modulo_Operator_PERCENT, parser.ATNBasic, false)
	states[StateNumber__Modulo__Basic_1] = parser.NewATNState(StateNumber__Modulo__Basic_1, parser.ATNBasic, true)
	states[StateNumber__Modulo__Basic_2] = parser.NewATNState(StateNumber__Modulo__Basic_2, parser.ATNBasic, true)
	states[StateNumber__Modulo__LoopEntry] = parser.NewATNState(StateNumber__Modulo__LoopEntry, parser.ATNLoopEntry, true).SetDecision(9)
	states[StateNumber__Modulo__LoopEnd] = parser.NewATNState(StateNumber__Modulo__LoopEnd, parser.ATNLoopEnd, true)
	states[StateNumber__Modulo__LoopBack] = parser.NewATNState(StateNumber__Modulo__LoopBack, parser.ATNLoopBack, true)
	states[StateNumber__PrimaryExpression_LPAREN_0] = parser.NewATNState(StateNumber__PrimaryExpression_LPAREN_0, parser.ATNBasic, false)
	states[StateNumber__PrimaryExpression__Basic_0] = parser.NewATNState(StateNumber__PrimaryExpression__Basic_0, parser.ATNBasic, true)
	states[StateNumber__PrimaryExpression_RPAREN_0] = parser.NewATNState(StateNumber__PrimaryExpression_RPAREN_0, parser.ATNBasic, false)
	states[StateNumber__PrimaryExpression__Basic_1] = parser.NewATNState(StateNumber__PrimaryExpression__Basic_1, parser.ATNBasic, true)
	states[StateNumber__PrimaryExpression_Value_NUMBER] = parser.NewATNState(StateNumber__PrimaryExpression_Value_NUMBER, parser.ATNBasic, false)
	states[StateNumber__PrimaryExpression__Basic_2] = parser.NewATNState(StateNumber__PrimaryExpression__Basic_2, parser.ATNBasic, true)
	states[StateNumber__PrimaryExpression_Callable_ID] = parser.NewATNState(StateNumber__PrimaryExpression_Callable_ID, parser.ATNBasic, false)
	states[StateNumber__PrimaryExpression_LPAREN_1] = parser.NewATNState(StateNumber__PrimaryExpression_LPAREN_1, parser.ATNBasic, false)
	states[StateNumber__PrimaryExpression__Basic_3] = parser.NewATNState(StateNumber__PrimaryExpression__Basic_3, parser.ATNBasic, true)
	states[StateNumber__PrimaryExpression_COMMA] = parser.NewATNState(StateNumber__PrimaryExpression_COMMA, parser.ATNBasic, false)
	states[StateNumber__PrimaryExpression__Basic_4] = parser.NewATNState(StateNumber__PrimaryExpression__Basic_4, parser.ATNBasic, true)
	states[StateNumber__PrimaryExpression__Basic_5] = parser.NewATNState(StateNumber__PrimaryExpression__Basic_5, parser.ATNBasic, true)
	states[StateNumber__PrimaryExpression__LoopEntry] = parser.NewATNState(StateNumber__PrimaryExpression__LoopEntry, parser.ATNLoopEntry, true).SetDecision(10)
	states[StateNumber__PrimaryExpression__LoopEnd] = parser.NewATNState(StateNumber__PrimaryExpression__LoopEnd, parser.ATNLoopEnd, true)
	states[StateNumber__PrimaryExpression__LoopBack] = parser.NewATNState(StateNumber__PrimaryExpression__LoopBack, parser.ATNLoopBack, true)
	states[StateNumber__PrimaryExpression_RPAREN_1] = parser.NewATNState(StateNumber__PrimaryExpression_RPAREN_1, parser.ATNBasic, false)
	states[StateNumber__PrimaryExpression__Basic_6] = parser.NewATNState(StateNumber__PrimaryExpression__Basic_6, parser.ATNBasic, true)
	states[StateNumber__PrimaryExpression__Basic_7] = parser.NewATNState(StateNumber__PrimaryExpression__Basic_7, parser.ATNBasic, true).SetDecision(11)
	states[StateNumber__PrimaryExpression__Basic_8] = parser.NewATNState(StateNumber__PrimaryExpression__Basic_8, parser.ATNBasic, true).SetDecision(12)
	states[StateNumber__PrimaryExpression__BlockEnd] = parser.NewATNState(StateNumber__PrimaryExpression__BlockEnd, parser.ATNBlockEnd, true)
	states[StateNumber__Module__Start].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Module_MODULE]),
	)
	states[StateNumber__Statement__Start].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Statement__Basic_4]),
	)
	states[StateNumber__Definition__Start].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Definition_DEF]),
	)
	states[StateNumber__DeclaredParameter__Start].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__DeclaredParameter_Name_ID]),
	)
	states[StateNumber__Evaluation__Start].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Evaluation__Basic_0]),
	)
	states[StateNumber__Expression__Start].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Expression__Basic_0]),
	)
	states[StateNumber__Addition__Start].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Addition__Basic_0]),
	)
	states[StateNumber__Multiplication__Start].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Multiplication__Basic_0]),
	)
	states[StateNumber__Exponentiation__Start].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Exponentiation__Basic_0]),
	)
	states[StateNumber__Modulo__Start].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Modulo__Basic_0]),
	)
	states[StateNumber__PrimaryExpression__Start].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__PrimaryExpression__Basic_8]),
	)
	states[StateNumber__Module_MODULE].AppendTransitions(
		parser.NewAtomTransition(states[StateNumber__Module_Name_ID], Token_MODULE, nil),
	)
	states[StateNumber__Module_Name_ID].AppendTransitions(
		parser.NewAtomTransition(states[StateNumber__Module__LoopEntry], Token_ID, nil),
	)
	states[StateNumber__Module__Basic_0].AppendTransitions(
		parser.NewRuleTransition(states[StateNumber__Statement__Start], states[StateNumber__Module__Basic_1], nil),
	)
	states[StateNumber__Module__Basic_1].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Module__LoopBack]),
	)
	states[StateNumber__Module__LoopEntry].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Module__Basic_0]),
		parser.NewEpsilonTransition(states[StateNumber__Module__LoopEnd]),
	)
	states[StateNumber__Module__LoopEnd].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Module__Stop]),
	)
	states[StateNumber__Module__LoopBack].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Module__LoopEntry]),
	)
	states[StateNumber__Statement__Basic_0].AppendTransitions(
		parser.NewRuleTransition(states[StateNumber__Definition__Start], states[StateNumber__Statement__Basic_1], nil),
	)
	states[StateNumber__Statement__Basic_1].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Statement__BlockEnd]),
	)
	states[StateNumber__Statement__Basic_2].AppendTransitions(
		parser.NewRuleTransition(states[StateNumber__Evaluation__Start], states[StateNumber__Statement__Basic_3], nil),
	)
	states[StateNumber__Statement__Basic_3].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Statement__BlockEnd]),
	)
	states[StateNumber__Statement__Basic_4].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Statement__Basic_0]),
		parser.NewEpsilonTransition(states[StateNumber__Statement__Basic_2]),
	)
	states[StateNumber__Statement__BlockEnd].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Statement__Stop]),
	)
	states[StateNumber__Definition_DEF].AppendTransitions(
		parser.NewAtomTransition(states[StateNumber__Definition_Name_ID], Token_DEF, nil),
	)
	states[StateNumber__Definition_Name_ID].AppendTransitions(
		parser.NewAtomTransition(states[StateNumber__Definition__Basic_4], Token_ID, nil),
	)
	states[StateNumber__Definition_LPAREN].AppendTransitions(
		parser.NewAtomTransition(states[StateNumber__Definition__Basic_0], Token_LPAREN, nil),
	)
	states[StateNumber__Definition__Basic_0].AppendTransitions(
		parser.NewRuleTransition(states[StateNumber__DeclaredParameter__Start], states[StateNumber__Definition__LoopEntry], nil),
	)
	states[StateNumber__Definition_COMMA].AppendTransitions(
		parser.NewAtomTransition(states[StateNumber__Definition__Basic_1], Token_COMMA, nil),
	)
	states[StateNumber__Definition__Basic_1].AppendTransitions(
		parser.NewRuleTransition(states[StateNumber__DeclaredParameter__Start], states[StateNumber__Definition__Basic_2], nil),
	)
	states[StateNumber__Definition__Basic_2].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Definition__LoopBack]),
	)
	states[StateNumber__Definition__LoopEntry].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Definition_COMMA]),
		parser.NewEpsilonTransition(states[StateNumber__Definition__LoopEnd]),
	)
	states[StateNumber__Definition__LoopEnd].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Definition_RPAREN]),
	)
	states[StateNumber__Definition__LoopBack].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Definition__LoopEntry]),
	)
	states[StateNumber__Definition_RPAREN].AppendTransitions(
		parser.NewAtomTransition(states[StateNumber__Definition__Basic_3], Token_RPAREN, nil),
	)
	states[StateNumber__Definition__Basic_3].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Definition_COLON]),
	)
	states[StateNumber__Definition__Basic_4].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Definition_LPAREN]),
		parser.NewEpsilonTransition(states[StateNumber__Definition__Basic_3]),
	)
	states[StateNumber__Definition_COLON].AppendTransitions(
		parser.NewAtomTransition(states[StateNumber__Definition__Basic_5], Token_COLON, nil),
	)
	states[StateNumber__Definition__Basic_5].AppendTransitions(
		parser.NewRuleTransition(states[StateNumber__Expression__Start], states[StateNumber__Definition_SEMICOLON], nil),
	)
	states[StateNumber__Definition_SEMICOLON].AppendTransitions(
		parser.NewAtomTransition(states[StateNumber__Definition__Basic_6], Token_SEMICOLON, nil),
	)
	states[StateNumber__Definition__Basic_6].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Definition__Stop]),
	)
	states[StateNumber__DeclaredParameter_Name_ID].AppendTransitions(
		parser.NewAtomTransition(states[StateNumber__DeclaredParameter__Basic], Token_ID, nil),
	)
	states[StateNumber__DeclaredParameter__Basic].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__DeclaredParameter__Stop]),
	)
	states[StateNumber__Evaluation__Basic_0].AppendTransitions(
		parser.NewRuleTransition(states[StateNumber__Expression__Start], states[StateNumber__Evaluation_SEMICOLON], nil),
	)
	states[StateNumber__Evaluation_SEMICOLON].AppendTransitions(
		parser.NewAtomTransition(states[StateNumber__Evaluation__Basic_1], Token_SEMICOLON, nil),
	)
	states[StateNumber__Evaluation__Basic_1].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Evaluation__Stop]),
	)
	states[StateNumber__Expression__Basic_0].AppendTransitions(
		parser.NewRuleTransition(states[StateNumber__Addition__Start], states[StateNumber__Expression__Basic_1], nil),
	)
	states[StateNumber__Expression__Basic_1].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Expression__Stop]),
	)
	states[StateNumber__Addition__Basic_0].AppendTransitions(
		parser.NewRuleTransition(states[StateNumber__Multiplication__Start], states[StateNumber__Addition__LoopEntry], nil),
	)
	states[StateNumber__Addition_Operator_PLUS].AppendTransitions(
		parser.NewAtomTransition(states[StateNumber__Addition__Basic_1], Token_PLUS, nil),
	)
	states[StateNumber__Addition__Basic_1].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Addition__BlockEnd]),
	)
	states[StateNumber__Addition_Operator_MINUS].AppendTransitions(
		parser.NewAtomTransition(states[StateNumber__Addition__Basic_2], Token_MINUS, nil),
	)
	states[StateNumber__Addition__Basic_2].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Addition__BlockEnd]),
	)
	states[StateNumber__Addition__Basic_3].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Addition_Operator_PLUS]),
		parser.NewEpsilonTransition(states[StateNumber__Addition_Operator_MINUS]),
	)
	states[StateNumber__Addition__BlockEnd].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Addition__Basic_4]),
	)
	states[StateNumber__Addition__Basic_4].AppendTransitions(
		parser.NewRuleTransition(states[StateNumber__Multiplication__Start], states[StateNumber__Addition__Basic_5], nil),
	)
	states[StateNumber__Addition__Basic_5].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Addition__LoopBack]),
	)
	states[StateNumber__Addition__LoopEntry].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Addition__Basic_3]),
		parser.NewEpsilonTransition(states[StateNumber__Addition__LoopEnd]),
	)
	states[StateNumber__Addition__LoopEnd].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Addition__Stop]),
	)
	states[StateNumber__Addition__LoopBack].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Addition__LoopEntry]),
	)
	states[StateNumber__Multiplication__Basic_0].AppendTransitions(
		parser.NewRuleTransition(states[StateNumber__Exponentiation__Start], states[StateNumber__Multiplication__LoopEntry], nil),
	)
	states[StateNumber__Multiplication_Operator_STAR].AppendTransitions(
		parser.NewAtomTransition(states[StateNumber__Multiplication__Basic_1], Token_STAR, nil),
	)
	states[StateNumber__Multiplication__Basic_1].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Multiplication__BlockEnd]),
	)
	states[StateNumber__Multiplication_Operator_SLASH].AppendTransitions(
		parser.NewAtomTransition(states[StateNumber__Multiplication__Basic_2], Token_SLASH, nil),
	)
	states[StateNumber__Multiplication__Basic_2].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Multiplication__BlockEnd]),
	)
	states[StateNumber__Multiplication__Basic_3].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Multiplication_Operator_STAR]),
		parser.NewEpsilonTransition(states[StateNumber__Multiplication_Operator_SLASH]),
	)
	states[StateNumber__Multiplication__BlockEnd].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Multiplication__Basic_4]),
	)
	states[StateNumber__Multiplication__Basic_4].AppendTransitions(
		parser.NewRuleTransition(states[StateNumber__Exponentiation__Start], states[StateNumber__Multiplication__Basic_5], nil),
	)
	states[StateNumber__Multiplication__Basic_5].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Multiplication__LoopBack]),
	)
	states[StateNumber__Multiplication__LoopEntry].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Multiplication__Basic_3]),
		parser.NewEpsilonTransition(states[StateNumber__Multiplication__LoopEnd]),
	)
	states[StateNumber__Multiplication__LoopEnd].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Multiplication__Stop]),
	)
	states[StateNumber__Multiplication__LoopBack].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Multiplication__LoopEntry]),
	)
	states[StateNumber__Exponentiation__Basic_0].AppendTransitions(
		parser.NewRuleTransition(states[StateNumber__Modulo__Start], states[StateNumber__Exponentiation__LoopEntry], nil),
	)
	states[StateNumber__Exponentiation_Operator_CARET].AppendTransitions(
		parser.NewAtomTransition(states[StateNumber__Exponentiation__Basic_1], Token_CARET, nil),
	)
	states[StateNumber__Exponentiation__Basic_1].AppendTransitions(
		parser.NewRuleTransition(states[StateNumber__Modulo__Start], states[StateNumber__Exponentiation__Basic_2], nil),
	)
	states[StateNumber__Exponentiation__Basic_2].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Exponentiation__LoopBack]),
	)
	states[StateNumber__Exponentiation__LoopEntry].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Exponentiation_Operator_CARET]),
		parser.NewEpsilonTransition(states[StateNumber__Exponentiation__LoopEnd]),
	)
	states[StateNumber__Exponentiation__LoopEnd].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Exponentiation__Stop]),
	)
	states[StateNumber__Exponentiation__LoopBack].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Exponentiation__LoopEntry]),
	)
	states[StateNumber__Modulo__Basic_0].AppendTransitions(
		parser.NewRuleTransition(states[StateNumber__PrimaryExpression__Start], states[StateNumber__Modulo__LoopEntry], nil),
	)
	states[StateNumber__Modulo_Operator_PERCENT].AppendTransitions(
		parser.NewAtomTransition(states[StateNumber__Modulo__Basic_1], Token_PERCENT, nil),
	)
	states[StateNumber__Modulo__Basic_1].AppendTransitions(
		parser.NewRuleTransition(states[StateNumber__PrimaryExpression__Start], states[StateNumber__Modulo__Basic_2], nil),
	)
	states[StateNumber__Modulo__Basic_2].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Modulo__LoopBack]),
	)
	states[StateNumber__Modulo__LoopEntry].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Modulo_Operator_PERCENT]),
		parser.NewEpsilonTransition(states[StateNumber__Modulo__LoopEnd]),
	)
	states[StateNumber__Modulo__LoopEnd].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Modulo__Stop]),
	)
	states[StateNumber__Modulo__LoopBack].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Modulo__LoopEntry]),
	)
	states[StateNumber__PrimaryExpression_LPAREN_0].AppendTransitions(
		parser.NewAtomTransition(states[StateNumber__PrimaryExpression__Basic_0], Token_LPAREN, nil),
	)
	states[StateNumber__PrimaryExpression__Basic_0].AppendTransitions(
		parser.NewRuleTransition(states[StateNumber__Expression__Start], states[StateNumber__PrimaryExpression_RPAREN_0], nil),
	)
	states[StateNumber__PrimaryExpression_RPAREN_0].AppendTransitions(
		parser.NewAtomTransition(states[StateNumber__PrimaryExpression__Basic_1], Token_RPAREN, nil),
	)
	states[StateNumber__PrimaryExpression__Basic_1].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__PrimaryExpression__BlockEnd]),
	)
	states[StateNumber__PrimaryExpression_Value_NUMBER].AppendTransitions(
		parser.NewAtomTransition(states[StateNumber__PrimaryExpression__Basic_2], Token_NUMBER, nil),
	)
	states[StateNumber__PrimaryExpression__Basic_2].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__PrimaryExpression__BlockEnd]),
	)
	states[StateNumber__PrimaryExpression_Callable_ID].AppendTransitions(
		parser.NewAtomTransition(states[StateNumber__PrimaryExpression__Basic_7], Token_ID, &parser.CompletionHint{Field: "FunctionCall.Callable", PrecedingAction: &parser.ActionInfo{TargetType: "FunctionCall", Property: ""}}),
	)
	states[StateNumber__PrimaryExpression_LPAREN_1].AppendTransitions(
		parser.NewAtomTransition(states[StateNumber__PrimaryExpression__Basic_3], Token_LPAREN, nil),
	)
	states[StateNumber__PrimaryExpression__Basic_3].AppendTransitions(
		parser.NewRuleTransition(states[StateNumber__Expression__Start], states[StateNumber__PrimaryExpression__LoopEntry], nil),
	)
	states[StateNumber__PrimaryExpression_COMMA].AppendTransitions(
		parser.NewAtomTransition(states[StateNumber__PrimaryExpression__Basic_4], Token_COMMA, nil),
	)
	states[StateNumber__PrimaryExpression__Basic_4].AppendTransitions(
		parser.NewRuleTransition(states[StateNumber__Expression__Start], states[StateNumber__PrimaryExpression__Basic_5], nil),
	)
	states[StateNumber__PrimaryExpression__Basic_5].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__PrimaryExpression__LoopBack]),
	)
	states[StateNumber__PrimaryExpression__LoopEntry].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__PrimaryExpression_COMMA]),
		parser.NewEpsilonTransition(states[StateNumber__PrimaryExpression__LoopEnd]),
	)
	states[StateNumber__PrimaryExpression__LoopEnd].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__PrimaryExpression_RPAREN_1]),
	)
	states[StateNumber__PrimaryExpression__LoopBack].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__PrimaryExpression__LoopEntry]),
	)
	states[StateNumber__PrimaryExpression_RPAREN_1].AppendTransitions(
		parser.NewAtomTransition(states[StateNumber__PrimaryExpression__Basic_6], Token_RPAREN, nil),
	)
	states[StateNumber__PrimaryExpression__Basic_6].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__PrimaryExpression__BlockEnd]),
	)
	states[StateNumber__PrimaryExpression__Basic_7].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__PrimaryExpression_LPAREN_1]),
		parser.NewEpsilonTransition(states[StateNumber__PrimaryExpression__Basic_6]),
	)
	states[StateNumber__PrimaryExpression__Basic_8].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__PrimaryExpression_LPAREN_0]),
		parser.NewEpsilonTransition(states[StateNumber__PrimaryExpression_Value_NUMBER]),
		parser.NewEpsilonTransition(states[StateNumber__PrimaryExpression_Callable_ID]),
	)
	states[StateNumber__PrimaryExpression__BlockEnd].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__PrimaryExpression__Stop]),
	)
	decisionStates := make([]*parser.RuntimeATNState, 13)
	decisionStates[0] = states[StateNumber__Module__LoopEntry]
	decisionStates[1] = states[StateNumber__Statement__Basic_4]
	decisionStates[2] = states[StateNumber__Definition__LoopEntry]
	decisionStates[3] = states[StateNumber__Definition__Basic_4]
	decisionStates[4] = states[StateNumber__Addition__Basic_3]
	decisionStates[5] = states[StateNumber__Addition__LoopEntry]
	decisionStates[6] = states[StateNumber__Multiplication__Basic_3]
	decisionStates[7] = states[StateNumber__Multiplication__LoopEntry]
	decisionStates[8] = states[StateNumber__Exponentiation__LoopEntry]
	decisionStates[9] = states[StateNumber__Modulo__LoopEntry]
	decisionStates[10] = states[StateNumber__PrimaryExpression__LoopEntry]
	decisionStates[11] = states[StateNumber__PrimaryExpression__Basic_7]
	decisionStates[12] = states[StateNumber__PrimaryExpression__Basic_8]
	decisionMap := make([]*parser.RuntimeATNState, 13)
	decisionMap[0] = states[StateNumber__Module__LoopEntry]
	decisionMap[1] = states[StateNumber__Statement__Basic_4]
	decisionMap[2] = states[StateNumber__Definition__LoopEntry]
	decisionMap[3] = states[StateNumber__Definition__Basic_4]
	decisionMap[4] = states[StateNumber__Addition__Basic_3]
	decisionMap[5] = states[StateNumber__Addition__LoopEntry]
	decisionMap[6] = states[StateNumber__Multiplication__Basic_3]
	decisionMap[7] = states[StateNumber__Multiplication__LoopEntry]
	decisionMap[8] = states[StateNumber__Exponentiation__LoopEntry]
	decisionMap[9] = states[StateNumber__Modulo__LoopEntry]
	decisionMap[10] = states[StateNumber__PrimaryExpression__LoopEntry]
	decisionMap[11] = states[StateNumber__PrimaryExpression__Basic_7]
	decisionMap[12] = states[StateNumber__PrimaryExpression__Basic_8]
	return parser.NewRuntimeATN(states, decisionStates, decisionMap)
}
