// Code generated by typefox.dev/fastbelt/cmd/fastbelt. DO NOT EDIT.

package arithmetics

import (
	"sync"
	core "typefox.dev/fastbelt"
	"typefox.dev/fastbelt/parser"
	"typefox.dev/fastbelt/util/service"
)

type CompletionParser struct {
	state     *parser.ParserState
	cp        *parser.CompletionParserState
	sc        *service.Container
	atn       func() *parser.RuntimeATN
	lookahead ArithmeticsParserLookahead
}

func NewCompletionParser(sc *service.Container) *CompletionParser {
	return &CompletionParser{
		sc:  sc,
		atn: sync.OnceValue(BuildATN),
	}
}

// Parse runs the completion parser over the given prefix tokens (typically
// the document's tokens up to the cursor) and returns the recorded
// snapshots and rule stack. The completion provider feeds that result into
// the ATN simulator.
func (p *CompletionParser) Parse(tokens []core.Token) *parser.CompletionParseResult {
	messages := service.MustGet[parser.ErrorMessageProvider](p.sc)
	recovery := service.MustGet[parser.ErrorRecoveryStrategy](p.sc)
	lookahead := service.MustGet[ArithmeticsParserLookahead](p.sc)
	cp := &CompletionParser{sc: p.sc, atn: p.atn, lookahead: lookahead}
	cp.state = parser.NewParserState(tokens, p.atn(), recovery, messages)
	cp.cp = parser.NewCompletionParserState(cp.state)
	cp.ParseModule()
	return cp.cp.Result(tokens)
}

func (p *CompletionParser) ParseModule() {
	p.cp.EnterRule("Module", StateNumber__Module__Start)
	defer p.cp.ExitRule()
	{
		p.state.Consume(Token_MODULE)
	}
	{
		p.cp.MarkAssignment("Name")
		p.state.Consume(Token_ID)
		p.cp.ClearAssignment()
	}
	{
		p.cp.RecordSnapshot(StateNumber__Module__LoopEntry)
		p.state.Sync(StateNumber__Module__LoopEntry)
		for p.lookahead.ModuleStatementsLoop(p.state) {
			p.cp.MarkAssignment("Statements")
			p.state.EnterRule(StateNumber__Module__Basic_1)
			p.ParseStatement()
			p.state.ExitRule()
			p.cp.ClearAssignment()
			p.cp.RecordSnapshot(StateNumber__Module__LoopEntry)
			p.state.Sync(StateNumber__Module__LoopEntry)
		}
	}
}

func (p *CompletionParser) ParseStatement() {
	p.cp.EnterRule("Statement", StateNumber__Statement__Start)
	defer p.cp.ExitRule()
	switch prediction, failure := p.lookahead.StatementAlternatives(p.state); prediction {
	case 0:
		{
			p.state.EnterRule(StateNumber__Statement__Basic_1)
			p.ParseDefinition()
			p.state.ExitRule()
		}
	case 1:
		{
			p.state.EnterRule(StateNumber__Statement__Basic_3)
			p.ParseEvaluation()
			p.state.ExitRule()
		}
	default:
		p.state.AppendError(p.state.Messages().NoViableAlternative(failure), failure.Token)
	}
}

func (p *CompletionParser) ParseDefinition() {
	p.cp.EnterRule("Definition", StateNumber__Definition__Start)
	defer p.cp.ExitRule()
	{
		p.state.Consume(Token_DEF)
	}
	{
		p.cp.MarkAssignment("Name")
		p.state.Consume(Token_ID)
		p.cp.ClearAssignment()
	}
	p.cp.RecordSnapshot(StateNumber__Definition__Basic_4)
	p.state.Sync(StateNumber__Definition__Basic_4)
	if p.lookahead.DefinitionOptional(p.state) {
		{
			p.state.Consume(Token_LPAREN)
		}
		{
			p.cp.MarkAssignment("Args")
			p.state.EnterRule(StateNumber__Definition__LoopEntry)
			p.ParseDeclaredParameter()
			p.state.ExitRule()
			p.cp.ClearAssignment()
		}
		p.cp.RecordSnapshot(StateNumber__Definition__LoopEntry)
		p.state.Sync(StateNumber__Definition__LoopEntry)
		for p.lookahead.DefinitionLoop(p.state) {
			{
				p.state.Consume(Token_COMMA)
			}
			{
				p.cp.MarkAssignment("Args")
				p.state.EnterRule(StateNumber__Definition__Basic_2)
				p.ParseDeclaredParameter()
				p.state.ExitRule()
				p.cp.ClearAssignment()
			}
			p.cp.RecordSnapshot(StateNumber__Definition__LoopEntry)
			p.state.Sync(StateNumber__Definition__LoopEntry)
		}
		{
			p.state.Consume(Token_RPAREN)
		}
	}
	{
		p.state.Consume(Token_COLON)
	}
	{
		p.cp.MarkAssignment("Expression")
		p.state.EnterRule(StateNumber__Definition_SEMICOLON)
		p.ParseExpression()
		p.state.ExitRule()
		p.cp.ClearAssignment()
	}
	{
		p.state.Consume(Token_SEMICOLON)
	}
}

func (p *CompletionParser) ParseDeclaredParameter() {
	p.cp.EnterRule("DeclaredParameter", StateNumber__DeclaredParameter__Start)
	defer p.cp.ExitRule()
	{
		p.cp.MarkAssignment("Name")
		p.state.Consume(Token_ID)
		p.cp.ClearAssignment()
	}
}

func (p *CompletionParser) ParseEvaluation() {
	p.cp.EnterRule("Evaluation", StateNumber__Evaluation__Start)
	defer p.cp.ExitRule()
	{
		p.cp.MarkAssignment("Expression")
		p.state.EnterRule(StateNumber__Evaluation_SEMICOLON)
		p.ParseExpression()
		p.state.ExitRule()
		p.cp.ClearAssignment()
	}
	{
		p.state.Consume(Token_SEMICOLON)
	}
}

func (p *CompletionParser) ParseExpression() {
	p.cp.EnterRule("Expression", StateNumber__Expression__Start)
	defer p.cp.ExitRule()
	{
		p.state.EnterRule(StateNumber__Expression__Basic_1)
		p.ParseAddition()
		p.state.ExitRule()
	}
}

func (p *CompletionParser) ParseAddition() {
	p.cp.EnterRule("Addition", StateNumber__Addition__Start)
	defer p.cp.ExitRule()
	{
		p.state.EnterRule(StateNumber__Addition__LoopEntry)
		p.ParseMultiplication()
		p.state.ExitRule()
	}
	p.cp.RecordSnapshot(StateNumber__Addition__LoopEntry)
	p.state.Sync(StateNumber__Addition__LoopEntry)
	for p.lookahead.AdditionLoop(p.state) {
		{
			p.cp.MarkAssignment("Operator")
			switch prediction, _ := p.lookahead.AdditionOperatorAlternatives(p.state); prediction {
			case 0:
				p.state.Consume(Token_PLUS)
			case 1:
				p.state.Consume(Token_MINUS)
			}
			p.cp.ClearAssignment()
		}
		{
			p.cp.MarkAssignment("Right")
			p.state.EnterRule(StateNumber__Addition__Basic_5)
			p.ParseMultiplication()
			p.state.ExitRule()
			p.cp.ClearAssignment()
		}
		p.cp.RecordSnapshot(StateNumber__Addition__LoopEntry)
		p.state.Sync(StateNumber__Addition__LoopEntry)
	}
}

func (p *CompletionParser) ParseMultiplication() {
	p.cp.EnterRule("Multiplication", StateNumber__Multiplication__Start)
	defer p.cp.ExitRule()
	{
		p.state.EnterRule(StateNumber__Multiplication__LoopEntry)
		p.ParseExponentiation()
		p.state.ExitRule()
	}
	p.cp.RecordSnapshot(StateNumber__Multiplication__LoopEntry)
	p.state.Sync(StateNumber__Multiplication__LoopEntry)
	for p.lookahead.MultiplicationLoop(p.state) {
		{
			p.cp.MarkAssignment("Operator")
			switch prediction, _ := p.lookahead.MultiplicationOperatorAlternatives(p.state); prediction {
			case 0:
				p.state.Consume(Token_STAR)
			case 1:
				p.state.Consume(Token_SLASH)
			}
			p.cp.ClearAssignment()
		}
		{
			p.cp.MarkAssignment("Right")
			p.state.EnterRule(StateNumber__Multiplication__Basic_5)
			p.ParseExponentiation()
			p.state.ExitRule()
			p.cp.ClearAssignment()
		}
		p.cp.RecordSnapshot(StateNumber__Multiplication__LoopEntry)
		p.state.Sync(StateNumber__Multiplication__LoopEntry)
	}
}

func (p *CompletionParser) ParseExponentiation() {
	p.cp.EnterRule("Exponentiation", StateNumber__Exponentiation__Start)
	defer p.cp.ExitRule()
	{
		p.state.EnterRule(StateNumber__Exponentiation__LoopEntry)
		p.ParseModulo()
		p.state.ExitRule()
	}
	p.cp.RecordSnapshot(StateNumber__Exponentiation__LoopEntry)
	p.state.Sync(StateNumber__Exponentiation__LoopEntry)
	for p.lookahead.ExponentiationLoop(p.state) {
		{
			p.cp.MarkAssignment("Operator")
			p.state.Consume(Token_CARET)
			p.cp.ClearAssignment()
		}
		{
			p.cp.MarkAssignment("Right")
			p.state.EnterRule(StateNumber__Exponentiation__Basic_2)
			p.ParseModulo()
			p.state.ExitRule()
			p.cp.ClearAssignment()
		}
		p.cp.RecordSnapshot(StateNumber__Exponentiation__LoopEntry)
		p.state.Sync(StateNumber__Exponentiation__LoopEntry)
	}
}

func (p *CompletionParser) ParseModulo() {
	p.cp.EnterRule("Modulo", StateNumber__Modulo__Start)
	defer p.cp.ExitRule()
	{
		p.state.EnterRule(StateNumber__Modulo__LoopEntry)
		p.ParsePrimaryExpression()
		p.state.ExitRule()
	}
	p.cp.RecordSnapshot(StateNumber__Modulo__LoopEntry)
	p.state.Sync(StateNumber__Modulo__LoopEntry)
	for p.lookahead.ModuloLoop(p.state) {
		{
			p.cp.MarkAssignment("Operator")
			p.state.Consume(Token_PERCENT)
			p.cp.ClearAssignment()
		}
		{
			p.cp.MarkAssignment("Right")
			p.state.EnterRule(StateNumber__Modulo__Basic_2)
			p.ParsePrimaryExpression()
			p.state.ExitRule()
			p.cp.ClearAssignment()
		}
		p.cp.RecordSnapshot(StateNumber__Modulo__LoopEntry)
		p.state.Sync(StateNumber__Modulo__LoopEntry)
	}
}

func (p *CompletionParser) ParsePrimaryExpression() {
	p.cp.EnterRule("PrimaryExpression", StateNumber__PrimaryExpression__Start)
	defer p.cp.ExitRule()
	switch prediction, failure := p.lookahead.PrimaryExpressionAlternatives(p.state); prediction {
	case 0:
		{
			p.state.Consume(Token_LPAREN)
		}
		{
			p.state.EnterRule(StateNumber__PrimaryExpression_RPAREN_0)
			p.ParseExpression()
			p.state.ExitRule()
		}
		{
			p.state.Consume(Token_RPAREN)
		}
	case 1:
		{
			p.cp.MarkAssignment("Value")
			p.state.Consume(Token_NUMBER)
			p.cp.ClearAssignment()
		}
	case 2:
		{
			p.cp.MarkAssignment("Callable")
			p.state.Consume(Token_ID)
			p.cp.ClearAssignment()
		}
		p.cp.RecordSnapshot(StateNumber__PrimaryExpression__Basic_7)
		p.state.Sync(StateNumber__PrimaryExpression__Basic_7)
		if p.lookahead.PrimaryExpressionOptional(p.state) {
			{
				p.state.Consume(Token_LPAREN)
			}
			{
				p.cp.MarkAssignment("Args")
				p.state.EnterRule(StateNumber__PrimaryExpression__LoopEntry)
				p.ParseExpression()
				p.state.ExitRule()
				p.cp.ClearAssignment()
			}
			p.cp.RecordSnapshot(StateNumber__PrimaryExpression__LoopEntry)
			p.state.Sync(StateNumber__PrimaryExpression__LoopEntry)
			for p.lookahead.PrimaryExpressionLoop(p.state) {
				{
					p.state.Consume(Token_COMMA)
				}
				{
					p.cp.MarkAssignment("Args")
					p.state.EnterRule(StateNumber__PrimaryExpression__Basic_5)
					p.ParseExpression()
					p.state.ExitRule()
					p.cp.ClearAssignment()
				}
				p.cp.RecordSnapshot(StateNumber__PrimaryExpression__LoopEntry)
				p.state.Sync(StateNumber__PrimaryExpression__LoopEntry)
			}
			{
				p.state.Consume(Token_RPAREN)
			}
		}
	default:
		p.state.AppendError(p.state.Messages().NoViableAlternative(failure), failure.Token)
	}
}
