// Code generated by typefox.dev/fastbelt/cmd/fastbelt. DO NOT EDIT.

package arithmetics

import (
	"encoding/json"
	"fmt"
	"reflect"

	core "typefox.dev/fastbelt"
)

func newToken(tokenType *core.TokenType, view string) *core.Token {
	token := core.NewToken(tokenType, view, 0, 0, 0, 0, 0, 0)
	return &token
}

func (i *ModuleImpl) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		T__        string      `json:"$type"`
		Name       string      `json:"name"`
		Statements []Statement `json:"statements"`
	}{
		T__:        "Module",
		Name:       i.Name(),
		Statements: i.Statements(),
	})
}

func (i *StatementImpl) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		T__ string `json:"$type"`
	}{
		T__: "Statement",
	})
}

func (i *AbstractDefinitionImpl) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		T__  string `json:"$type"`
		Name string `json:"name"`
	}{
		T__:  "AbstractDefinition",
		Name: i.Name(),
	})
}

func (i *DefinitionImpl) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		T__        string              `json:"$type"`
		Name       string              `json:"name"`
		Args       []DeclaredParameter `json:"args"`
		Expression Expression          `json:"expression"`
	}{
		T__:        "Definition",
		Name:       i.Name(),
		Args:       i.Args(),
		Expression: i.Expression(),
	})
}

func (i *DeclaredParameterImpl) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		T__  string `json:"$type"`
		Name string `json:"name"`
	}{
		T__:  "DeclaredParameter",
		Name: i.Name(),
	})
}

func (i *EvaluationImpl) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		T__        string     `json:"$type"`
		Expression Expression `json:"expression"`
	}{
		T__:        "Evaluation",
		Expression: i.Expression(),
	})
}

func (i *ExpressionImpl) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		T__ string `json:"$type"`
	}{
		T__: "Expression",
	})
}

func (i *BinaryExpressionImpl) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		T__      string     `json:"$type"`
		Left     Expression `json:"left"`
		Operator string     `json:"operator"`
		Right    Expression `json:"right"`
	}{
		T__:      "BinaryExpression",
		Left:     i.Left(),
		Operator: i.Operator(),
		Right:    i.Right(),
	})
}

func (i *FunctionCallImpl) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		T__      string                              `json:"$type"`
		Args     []Expression                        `json:"args"`
		Callable *core.Reference[AbstractDefinition] `json:"callable"`
	}{
		T__:      "FunctionCall",
		Args:     i.Args(),
		Callable: i.Callable(),
	})
}

func (i *NumberLiteralImpl) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		T__   string `json:"$type"`
		Value string `json:"value"`
	}{
		T__:   "NumberLiteral",
		Value: i.Value(),
	})
}

func (i *ModuleImpl) UnmarshalJSON(data []byte) error {
	aux := &struct {
		T__        string            `json:"$type"`
		Name       string            `json:"name"`
		Statements []json.RawMessage `json:"statements"`
	}{}
	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	i.SetName(newToken(Token_ID, aux.Name))
	i.statements = []Statement{}
	for _, item := range aux.Statements {
		node, err := Unmarshal[Statement](item)
		if err != nil {
			return err
		}
		i.SetStatementsItem(node)
	}
	return nil
}

func (i *StatementImpl) UnmarshalJSON(data []byte) error {
	return nil
}

func (i *AbstractDefinitionImpl) UnmarshalJSON(data []byte) error {
	aux := &struct {
		T__  string `json:"$type"`
		Name string `json:"name"`
	}{}
	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	i.SetName(newToken(Token_ID, aux.Name))
	return nil
}

func (i *DefinitionImpl) UnmarshalJSON(data []byte) error {
	aux := &struct {
		T__        string            `json:"$type"`
		Name       string            `json:"name"`
		Args       []json.RawMessage `json:"args"`
		Expression json.RawMessage   `json:"expression"`
	}{}
	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	i.SetName(newToken(Token_ID, aux.Name))
	i.args = []DeclaredParameter{}
	for _, item := range aux.Args {
		node, err := Unmarshal[DeclaredParameter](item)
		if err != nil {
			return err
		}
		i.SetArgsItem(node)
	}
	expression, err := Unmarshal[Expression](aux.Expression)
	if err != nil {
		return err
	}
	i.SetExpression(expression)
	return nil
}

func (i *DeclaredParameterImpl) UnmarshalJSON(data []byte) error {
	aux := &struct {
		T__  string `json:"$type"`
		Name string `json:"name"`
	}{}
	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	i.SetName(newToken(Token_ID, aux.Name))
	return nil
}

func (i *EvaluationImpl) UnmarshalJSON(data []byte) error {
	aux := &struct {
		T__        string          `json:"$type"`
		Expression json.RawMessage `json:"expression"`
	}{}
	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	expression, err := Unmarshal[Expression](aux.Expression)
	if err != nil {
		return err
	}
	i.SetExpression(expression)
	return nil
}

func (i *ExpressionImpl) UnmarshalJSON(data []byte) error {
	return nil
}

func (i *BinaryExpressionImpl) UnmarshalJSON(data []byte) error {
	aux := &struct {
		T__      string          `json:"$type"`
		Left     json.RawMessage `json:"left"`
		Operator string          `json:"operator"`
		Right    json.RawMessage `json:"right"`
	}{}
	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	left, err := Unmarshal[Expression](aux.Left)
	if err != nil {
		return err
	}
	i.SetLeft(left)
	i.SetOperator(newToken(Token_ID, aux.Operator))
	right, err := Unmarshal[Expression](aux.Right)
	if err != nil {
		return err
	}
	i.SetRight(right)
	return nil
}

func (i *FunctionCallImpl) UnmarshalJSON(data []byte) error {
	aux := &struct {
		T__      string            `json:"$type"`
		Args     []json.RawMessage `json:"args"`
		Callable json.RawMessage   `json:"callable"`
	}{}
	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	i.args = []Expression{}
	for _, item := range aux.Args {
		node, err := Unmarshal[Expression](item)
		if err != nil {
			return err
		}
		i.SetArgsItem(node)
	}
	callable := core.NewReference[AbstractDefinition](i, nil, nil)
	if err := json.Unmarshal(aux.Callable, &callable); err != nil {
		return err
	}
	i.SetCallable(callable)
	return nil
}

func (i *NumberLiteralImpl) UnmarshalJSON(data []byte) error {
	aux := &struct {
		T__   string `json:"$type"`
		Value string `json:"value"`
	}{}
	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	i.SetValue(newToken(Token_ID, aux.Value))
	return nil
}

// Unmarshal decodes data into an instance of type T by reading the "$type" field,
// selecting a corresponding factory, creating an instance, and unmarshaling its content.
func Unmarshal[T core.AstNode](data []byte) (T, error) {
	node := &struct {
		Type string `json:"$type"`
	}{}
	if err := json.Unmarshal(data, node); err != nil {
		var zero T
		return zero, fmt.Errorf("unmarshal: %w", err)
	}
	factory, ok := ArithmeticsSyntheticFactories[node.Type]
	if !ok {
		var zero T
		return zero, fmt.Errorf("unmarshal: unknown type %q", node.Type)
	}
	instance := factory()
	casted, ok := instance.(T)
	if !ok {
		var zero T
		return zero, fmt.Errorf("unmarshal: %T is not convertible to type %s", instance, reflect.TypeFor[T]())
	}
	if err := json.Unmarshal(data, casted); err != nil {
		var zero T
		return zero, fmt.Errorf("unmarshal %s: %w", node.Type, err)
	}
	return casted, nil
}
