// Code generated by typefox.dev/fastbelt/cmd/fastbelt. DO NOT EDIT.

package arithmetics

import (
	core "typefox.dev/fastbelt"
	"typefox.dev/fastbelt/parser"
	"typefox.dev/fastbelt/util/service"
)

type Parser struct {
	state                 *parser.ParserState
	sc                    *service.Container
	referencesConstructor ArithmeticsReferencesConstructor
	lookahead             ArithmeticsParserLookahead
}

func (p *Parser) Parse(document *core.Document) *parser.ParseResult {
	recovery := service.MustGet[parser.ErrorRecoveryStrategy](p.sc)
	messages := service.MustGet[parser.ErrorMessageProvider](p.sc)
	referencesConstructor := service.MustGet[ArithmeticsReferencesConstructor](p.sc)
	lookahead := service.MustGet[ArithmeticsParserLookahead](p.sc)
	cp := &Parser{sc: p.sc, referencesConstructor: referencesConstructor, lookahead: lookahead, state: parser.NewParserState(document.Tokens, ATN(), recovery, messages)}
	result := cp.ParseModule()
	cp.state.ExpectEndOfInput()
	return &parser.ParseResult{Node: result, Errors: cp.state.Errors()}
}

func NewParser(sc *service.Container) *Parser {
	return &Parser{
		sc: sc,
	}
}

func (p *Parser) ParseModule() Module {
	current := NewModule()
	current.SetTextRangeStart(p.state.LA(1).Range.Start)
	{
		{
			token := p.state.Consume(Keyword_module)
			core.AssignToken(current, token, Module_module)
		}
		{
			token := p.state.Consume(Token_ID)
			core.AssignToken(current, token, Module_Name_ID)
			if token != nil {
				current.SetName(token)
			}
		}
		{
			p.state.Sync(Module__LoopEntry)
			for p.lookahead.ModuleStatementsLoop(p.state) {
				p.state.EnterRule(Module__Basic_1)
				result := p.ParseStatement()
				p.state.ExitRule()
				if result != nil {
					current.SetStatementsItem(result)
				}
				p.state.Sync(Module__LoopEntry)
			}
		}
	}
	current.SetTextRangeEnd(p.state.LA(0).Range.End)
	return current
}

func (p *Parser) ParseStatement() Statement {
	startPos := p.state.LA(1).Range.Start
	var current Statement
	{
		switch prediction, failure := p.lookahead.StatementAlternatives(p.state); prediction {
		case 0:
			{
				p.state.EnterRule(Statement__Basic_1)
				result := p.ParseDefinition()
				p.state.ExitRule()
				current = result
			}
		case 1:
			{
				p.state.EnterRule(Statement__Basic_3)
				result := p.ParseEvaluation()
				p.state.ExitRule()
				current = result
			}
		default:
			p.state.AppendError(p.state.Messages().NoViableAlternative(failure), failure.Token)
		}
		if current == nil {
			current = NewStatement()
			current.SetTextRangeStart(startPos)
		}
	}
	current.SetTextRangeEnd(p.state.LA(0).Range.End)
	return current
}

func (p *Parser) ParseDefinition() Definition {
	current := NewDefinition()
	current.SetTextRangeStart(p.state.LA(1).Range.Start)
	{
		{
			token := p.state.Consume(Keyword_def)
			core.AssignToken(current, token, Definition_def)
		}
		{
			token := p.state.Consume(Token_ID)
			core.AssignToken(current, token, Definition_Name_ID)
			if token != nil {
				current.SetName(token)
			}
		}
		p.state.Sync(Definition__Basic_4)
		if p.lookahead.DefinitionOptional(p.state) {
			{
				token := p.state.Consume(Keyword_LeftParen)
				core.AssignToken(current, token, Definition_LeftParen)
			}
			{
				p.state.EnterRule(Definition__LoopEntry)
				result := p.ParseDeclaredParameter()
				p.state.ExitRule()
				if result != nil {
					current.SetArgsItem(result)
				}
			}
			p.state.Sync(Definition__LoopEntry)
			for p.lookahead.DefinitionLoop(p.state) {
				{
					token := p.state.Consume(Keyword_Comma)
					core.AssignToken(current, token, Definition_Comma)
				}
				{
					p.state.EnterRule(Definition__Basic_2)
					result := p.ParseDeclaredParameter()
					p.state.ExitRule()
					if result != nil {
						current.SetArgsItem(result)
					}
				}
				p.state.Sync(Definition__LoopEntry)
			}
			{
				token := p.state.Consume(Keyword_RightParen)
				core.AssignToken(current, token, Definition_RightParen)
			}
		}
		{
			token := p.state.Consume(Keyword_Colon)
			core.AssignToken(current, token, Definition_Colon)
		}
		{
			p.state.EnterRule(Definition_Semicolon)
			result := p.ParseExpression()
			p.state.ExitRule()
			if result != nil {
				current.SetExpression(result)
			}
		}
		{
			token := p.state.Consume(Keyword_Semicolon)
			core.AssignToken(current, token, Definition_Semicolon)
		}
	}
	current.SetTextRangeEnd(p.state.LA(0).Range.End)
	return current
}

func (p *Parser) ParseDeclaredParameter() DeclaredParameter {
	current := NewDeclaredParameter()
	current.SetTextRangeStart(p.state.LA(1).Range.Start)
	{
		{
			token := p.state.Consume(Token_ID)
			core.AssignToken(current, token, DeclaredParameter_Name_ID)
			if token != nil {
				current.SetName(token)
			}
		}
	}
	current.SetTextRangeEnd(p.state.LA(0).Range.End)
	return current
}

func (p *Parser) ParseEvaluation() Evaluation {
	current := NewEvaluation()
	current.SetTextRangeStart(p.state.LA(1).Range.Start)
	{
		{
			p.state.EnterRule(Evaluation_Semicolon)
			result := p.ParseExpression()
			p.state.ExitRule()
			if result != nil {
				current.SetExpression(result)
			}
		}
		{
			token := p.state.Consume(Keyword_Semicolon)
			core.AssignToken(current, token, Evaluation_Semicolon)
		}
	}
	current.SetTextRangeEnd(p.state.LA(0).Range.End)
	return current
}

func (p *Parser) ParseExpression() Expression {
	current := NewExpression()
	current.SetTextRangeStart(p.state.LA(1).Range.Start)
	{
		{
			p.state.EnterRule(Expression__Basic_1)
			result := p.ParseBinaryExpression()
			p.state.ExitRule()
			core.MergeTokens(result, current.Tokens())
			current = result
		}
	}
	current.SetTextRangeEnd(p.state.LA(0).Range.End)
	return current
}

func (p *Parser) ParsePrimaryExpression() Expression {
	startPos := p.state.LA(1).Range.Start
	var current Expression
	{
		switch prediction, failure := p.lookahead.PrimaryExpressionAlternatives(p.state); prediction {
		case 0:
			{
				current = NewExpression()
				current.SetTextRangeStart(startPos)
				token := p.state.Consume(Keyword_LeftParen)
				core.AssignToken(current, token, PrimaryExpression_LeftParen_0)
			}
			{
				p.state.EnterRule(PrimaryExpression_RightParen_0)
				result := p.ParseExpression()
				p.state.ExitRule()
				core.MergeTokens(result, current.Tokens())
				current = result
			}
			{
				token := p.state.Consume(Keyword_RightParen)
				core.AssignToken(current, token, PrimaryExpression_RightParen_0)
			}
		case 1:
			{
				result := NewNumberLiteral()
				result.SetTextRangeStart(startPos)
				current = result
			}
			current := current.(NumberLiteral)
			{
				token := p.state.Consume(Token_NUMBER)
				core.AssignToken(current, token, PrimaryExpression_Value_NUMBER)
				if token != nil {
					current.SetValue(token)
				}
			}
		case 2:
			{
				result := NewFunctionCall()
				result.SetTextRangeStart(startPos)
				current = result
			}
			current := current.(FunctionCall)
			{
				token := p.state.Consume(Token_ID)
				core.AssignToken(current, token, PrimaryExpression_Callable_ID)
				if token != nil {
					current.SetCallable(p.referencesConstructor.FunctionCallCallable(current, token))
				}
			}
			p.state.Sync(PrimaryExpression__Basic_7)
			if p.lookahead.PrimaryExpressionOptional(p.state) {
				{
					token := p.state.Consume(Keyword_LeftParen)
					core.AssignToken(current, token, PrimaryExpression_LeftParen_1)
				}
				{
					p.state.EnterRule(PrimaryExpression__LoopEntry)
					result := p.ParseExpression()
					p.state.ExitRule()
					if result != nil {
						current.SetArgsItem(result)
					}
				}
				p.state.Sync(PrimaryExpression__LoopEntry)
				for p.lookahead.PrimaryExpressionLoop(p.state) {
					{
						token := p.state.Consume(Keyword_Comma)
						core.AssignToken(current, token, PrimaryExpression_Comma)
					}
					{
						p.state.EnterRule(PrimaryExpression__Basic_5)
						result := p.ParseExpression()
						p.state.ExitRule()
						if result != nil {
							current.SetArgsItem(result)
						}
					}
					p.state.Sync(PrimaryExpression__LoopEntry)
				}
				{
					token := p.state.Consume(Keyword_RightParen)
					core.AssignToken(current, token, PrimaryExpression_RightParen_1)
				}
			}
		default:
			p.state.AppendError(p.state.Messages().NoViableAlternative(failure), failure.Token)
		}
		if current == nil {
			current = NewExpression()
			current.SetTextRangeStart(startPos)
		}
	}
	current.SetTextRangeEnd(p.state.LA(0).Range.End)
	return current
}

var BinaryExpressionPrecedence = map[int]parser.InfixPrecedence{
	Keyword_Percent_Idx:  {Level: 0},
	Keyword_Caret_Idx:    {Level: 1, Right: true},
	Keyword_Asterisk_Idx: {Level: 2},
	Keyword_Slash_Idx:    {Level: 2},
	Keyword_Dash_Idx:     {Level: 3},
	Keyword_Plus_Idx:     {Level: 3},
}

func (p *Parser) ParseBinaryExpression() Expression {
	var parts []Expression
	var operators []*core.Token
	{
		p.state.EnterRule(BinaryExpression__LoopEntry)
		result := p.ParsePrimaryExpression()
		p.state.ExitRule()
		parts = append(parts, result)
	}
	p.state.Sync(BinaryExpression__LoopEntry)
	for p.lookahead.BinaryExpressionLoop(p.state) {
		if token := p.state.Consume(Token_BinaryExpressionOperator); token != nil {
			operators = append(operators, token)
		}
		{
			p.state.EnterRule(BinaryExpression__Basic_2)
			result := p.ParsePrimaryExpression()
			p.state.ExitRule()
			parts = append(parts, result)
		}
		p.state.Sync(BinaryExpression__LoopEntry)
	}
	if len(parts) == 1 {
		// A lone operand is returned unchanged; no binary node is created.
		return parts[0]
	}
	return parser.BuildInfixTree(parts, operators, BinaryExpressionPrecedence, func(left Expression, operator *core.Token, right Expression) Expression {
		result := NewBinaryExpression()
		if left != nil {
			result.SetLeft(left)
			result.SetTextRangeStart(left.TextRange().Start)
		}
		if operator != nil {
			core.AssignToken(result, operator, BinaryExpression_BinaryExpressionOperator)
			result.SetOperator(operator)
			result.SetTextRangeEnd(operator.Range.End)
		}
		if right != nil {
			result.SetRight(right)
			result.SetTextRangeEnd(right.TextRange().End)
		}
		return result
	})
}
