// Code generated by typefox.dev/fastbelt/cmd/fastbelt. DO NOT EDIT.

package statemachine

import (
	"context"
	"reflect"
	"slices"

	core "typefox.dev/fastbelt"
	"typefox.dev/fastbelt/linking"
	"typefox.dev/fastbelt/util/extiter"
	"typefox.dev/fastbelt/util/service"
)

type StatemachineModelScopeProvider interface {
	ScopeStatemachineInit(ctx context.Context, reference *core.Reference[State]) core.Scope
	ScopeStateActions(ctx context.Context, reference *core.Reference[Command]) core.Scope
	ScopeTransitionEvent(ctx context.Context, reference *core.Reference[Event]) core.Scope
	ScopeTransitionState(ctx context.Context, reference *core.Reference[State]) core.Scope
}

type DefaultStatemachineModelScopeProvider struct {
	sc *service.Container
}

func NewDefaultStatemachineModelScopeProvider(sc *service.Container) StatemachineModelScopeProvider {
	return &DefaultStatemachineModelScopeProvider{sc: sc}
}

func (s *DefaultStatemachineModelScopeProvider) ScopeStatemachineInit(ctx context.Context, reference *core.Reference[State]) core.Scope {
	return linking.DefaultScopeOfType[State](reference.Owner())
}

func (s *DefaultStatemachineModelScopeProvider) ScopeStateActions(ctx context.Context, reference *core.Reference[Command]) core.Scope {
	return linking.DefaultScopeOfType[Command](reference.Owner())
}

func (s *DefaultStatemachineModelScopeProvider) ScopeTransitionEvent(ctx context.Context, reference *core.Reference[Event]) core.Scope {
	return linking.DefaultScopeOfType[Event](reference.Owner())
}

func (s *DefaultStatemachineModelScopeProvider) ScopeTransitionState(ctx context.Context, reference *core.Reference[State]) core.Scope {
	return linking.DefaultScopeOfType[State](reference.Owner())
}

type StatemachineModelReferenceLinker interface {
	LinkStatemachineInit(ctx context.Context, reference *core.Reference[State]) (*core.SymbolDescription, *core.ReferenceError)
	LinkStateActions(ctx context.Context, reference *core.Reference[Command]) (*core.SymbolDescription, *core.ReferenceError)
	LinkTransitionEvent(ctx context.Context, reference *core.Reference[Event]) (*core.SymbolDescription, *core.ReferenceError)
	LinkTransitionState(ctx context.Context, reference *core.Reference[State]) (*core.SymbolDescription, *core.ReferenceError)
}

type DefaultStatemachineModelReferenceLinker struct {
	sc *service.Container
}

func NewDefaultStatemachineModelReferenceLinker(sc *service.Container) StatemachineModelReferenceLinker {
	return &DefaultStatemachineModelReferenceLinker{sc: sc}
}

func (s *DefaultStatemachineModelReferenceLinker) LinkStatemachineInit(ctx context.Context, reference *core.Reference[State]) (*core.SymbolDescription, *core.ReferenceError) {
	scopeProvider := service.MustGet[StatemachineModelScopeProvider](s.sc)
	scope := scopeProvider.ScopeStatemachineInit(ctx, reference)
	return core.DefaultLink(scope, reference.Text())
}

func (s *DefaultStatemachineModelReferenceLinker) LinkStateActions(ctx context.Context, reference *core.Reference[Command]) (*core.SymbolDescription, *core.ReferenceError) {
	scopeProvider := service.MustGet[StatemachineModelScopeProvider](s.sc)
	scope := scopeProvider.ScopeStateActions(ctx, reference)
	return core.DefaultLink(scope, reference.Text())
}

func (s *DefaultStatemachineModelReferenceLinker) LinkTransitionEvent(ctx context.Context, reference *core.Reference[Event]) (*core.SymbolDescription, *core.ReferenceError) {
	scopeProvider := service.MustGet[StatemachineModelScopeProvider](s.sc)
	scope := scopeProvider.ScopeTransitionEvent(ctx, reference)
	return core.DefaultLink(scope, reference.Text())
}

func (s *DefaultStatemachineModelReferenceLinker) LinkTransitionState(ctx context.Context, reference *core.Reference[State]) (*core.SymbolDescription, *core.ReferenceError) {
	scopeProvider := service.MustGet[StatemachineModelScopeProvider](s.sc)
	scope := scopeProvider.ScopeTransitionState(ctx, reference)
	return core.DefaultLink(scope, reference.Text())
}

type StatemachineModelReferencesConstructor interface {
	StatemachineInit(owner core.AstNode, unit core.StringUnit) *core.Reference[State]
	StateActions(owner core.AstNode, unit core.StringUnit) *core.Reference[Command]
	TransitionEvent(owner core.AstNode, unit core.StringUnit) *core.Reference[Event]
	TransitionState(owner core.AstNode, unit core.StringUnit) *core.Reference[State]
}

type DefaultStatemachineModelReferencesConstructor struct {
	sc *service.Container
}

func NewDefaultStatemachineModelReferencesConstructor(sc *service.Container) StatemachineModelReferencesConstructor {
	return &DefaultStatemachineModelReferencesConstructor{sc: sc}
}

func (s *DefaultStatemachineModelReferencesConstructor) StatemachineInit(owner core.AstNode, unit core.StringUnit) *core.Reference[State] {
	referenceLinker := service.MustGet[StatemachineModelReferenceLinker](s.sc)
	fn := referenceLinker.LinkStatemachineInit
	return core.NewReference(owner, unit, fn)
}

func (s *DefaultStatemachineModelReferencesConstructor) StateActions(owner core.AstNode, unit core.StringUnit) *core.Reference[Command] {
	referenceLinker := service.MustGet[StatemachineModelReferenceLinker](s.sc)
	fn := referenceLinker.LinkStateActions
	return core.NewReference(owner, unit, fn)
}

func (s *DefaultStatemachineModelReferencesConstructor) TransitionEvent(owner core.AstNode, unit core.StringUnit) *core.Reference[Event] {
	referenceLinker := service.MustGet[StatemachineModelReferenceLinker](s.sc)
	fn := referenceLinker.LinkTransitionEvent
	return core.NewReference(owner, unit, fn)
}

func (s *DefaultStatemachineModelReferencesConstructor) TransitionState(owner core.AstNode, unit core.StringUnit) *core.Reference[State] {
	referenceLinker := service.MustGet[StatemachineModelReferenceLinker](s.sc)
	fn := referenceLinker.LinkTransitionState
	return core.NewReference(owner, unit, fn)
}

type StatemachineModelSymbolContainers struct{}

func (c *StatemachineModelSymbolContainers) New() core.SymbolContainer {
	return &StatemachineModelSymbolContainer{}
}

func NewSymbolContainers() *StatemachineModelSymbolContainers {
	return &StatemachineModelSymbolContainers{}
}

type StatemachineModelSymbolContainer struct {
	States   []*core.SymbolDescription
	Events   []*core.SymbolDescription
	Commands []*core.SymbolDescription
}

func (sc *StatemachineModelSymbolContainer) Put(desc *core.SymbolDescription) bool {
	switch desc.Node.(type) {
	case State:
		sc.States = append(sc.States, desc)
		return true
	case Event:
		sc.Events = append(sc.Events, desc)
		return true
	case Command:
		sc.Commands = append(sc.Commands, desc)
		return true
	}
	return false
}

func (sc *StatemachineModelSymbolContainer) All() core.SymbolSeq {
	return extiter.Concat(
		slices.Values(sc.States),
		slices.Values(sc.Events),
		slices.Values(sc.Commands),
	)
}

var TypeFor_State = reflect.TypeFor[State]()
var TypeFor_Event = reflect.TypeFor[Event]()
var TypeFor_Command = reflect.TypeFor[Command]()

func (sc *StatemachineModelSymbolContainer) ForType(t reflect.Type) core.SymbolSeq {
	switch t {
	case TypeFor_State:
		return slices.Values(sc.States)
	case TypeFor_Event:
		return slices.Values(sc.Events)
	case TypeFor_Command:
		return slices.Values(sc.Commands)
	}
	return core.EmptySymbolDescriptions
}
