// Code generated by typefox.dev/fastbelt/cmd/fastbelt. DO NOT EDIT.

package token_modes

import (
	core "typefox.dev/fastbelt"
	"typefox.dev/fastbelt/parser"
)

var PrimaryAlternatives = parser.LL1Lookahead{
	Types:  []*core.TokenType{Token_ID, Token_INT, Keyword_Backtick, Keyword_LeftParen},
	Lookup: []int{2: 4, 6: 3, 8: 1, 9: 2},
}

var StringContentAlternatives = parser.LL1Lookahead{
	Types:  []*core.TokenType{Token_STRING_CONTENT, Keyword_HashLeftBrace},
	Lookup: []int{1: 2, 13: 1},
}

var StringLiteralContentLoop = parser.LL1Lookahead{
	Types:  []*core.TokenType{Keyword_HashLeftBrace, Token_STRING_CONTENT},
	Lookup: []int{1: 1, 13: 1},
}

// TokenModesParserLookahead abstracts every lookahead/prediction decision performed by
// the generated parser. Each method corresponds to a single decision point;
// implementations may override individual decisions while delegating the rest
// to DefaultTokenModesParserLookahead.
type TokenModesParserLookahead interface {
	parser.ParserLookahead

	AdditiveLoop(state *parser.ParserState) bool
	ModelStatementsLoop(state *parser.ParserState) bool
	PrimaryAlternatives(state *parser.ParserState) (int, *parser.PredictionFailure)
	StringContentAlternatives(state *parser.ParserState) (int, *parser.PredictionFailure)
	StringLiteralContentLoop(state *parser.ParserState) bool
}

// DefaultTokenModesParserLookahead resolves every decision with the parser state's built-in
// static LL(1) and adaptive ALL(*) prediction.
type DefaultTokenModesParserLookahead struct {
	parser.DefaultParserLookahead
}

func NewDefaultTokenModesParserLookahead() TokenModesParserLookahead {
	return &DefaultTokenModesParserLookahead{}
}

func (l *DefaultTokenModesParserLookahead) AdditiveLoop(state *parser.ParserState) bool {
	return state.LA(1).Type == Keyword_Plus
}

func (l *DefaultTokenModesParserLookahead) ModelStatementsLoop(state *parser.ParserState) bool {
	return state.LA(1).Type == Token_ID
}

func (l *DefaultTokenModesParserLookahead) PrimaryAlternatives(state *parser.ParserState) (int, *parser.PredictionFailure) {
	return state.Lookahead(PrimaryAlternatives)
}

func (l *DefaultTokenModesParserLookahead) StringContentAlternatives(state *parser.ParserState) (int, *parser.PredictionFailure) {
	return state.Lookahead(StringContentAlternatives)
}

func (l *DefaultTokenModesParserLookahead) StringLiteralContentLoop(state *parser.ParserState) bool {
	prediction, _ := state.Lookahead(StringLiteralContentLoop)
	return prediction == 0
}
