// Code generated by typefox.dev/fastbelt/cmd/fastbelt. DO NOT EDIT.

package token_modes

import (
	core "typefox.dev/fastbelt"
	"typefox.dev/fastbelt/lexer"
	"typefox.dev/fastbelt/parser"
	"typefox.dev/fastbelt/util/service"
)

// SetupGeneratedServices sets up the generated services for this grammar.
// If any service is already set, it's not overwritten.
func SetupGeneratedServices(sc *service.Container) {
	if !service.Has[TokenModesScopeProvider](sc) {
		service.Put(sc, NewDefaultTokenModesScopeProvider(sc))
	}
	if !service.Has[TokenModesReferenceLinker](sc) {
		service.Put(sc, NewDefaultTokenModesReferenceLinker(sc))
	}
	if !service.Has[TokenModesReferencesConstructor](sc) {
		service.Put(sc, NewDefaultTokenModesReferencesConstructor(sc))
	}
	if !service.Has[TokenModesParserLookahead](sc) {
		service.Put(sc, NewDefaultTokenModesParserLookahead())
	}
	if !service.Has[lexer.Lexer](sc) {
		service.Put(sc, NewLexer())
	}
	if !service.Has[parser.Parser](sc) {
		service.Put[parser.Parser](sc, NewParser(sc))
	}
	if !service.Has[parser.ErrorRecoveryStrategy](sc) {
		service.Put[parser.ErrorRecoveryStrategy](sc, parser.NewDefaultErrorRecovery())
	}
	if !service.Has[parser.ErrorMessageProvider](sc) {
		service.Put[parser.ErrorMessageProvider](sc, parser.NewDefaultErrorMessageProvider())
	}
	if !service.Has[core.SymbolContainers](sc) {
		service.Put[core.SymbolContainers](sc, NewSymbolContainers())
	}
}

// SetupGeneratedServerServices sets up the generated language server services for this grammar.
// If any service is already set, it's not overwritten.
func SetupGeneratedServerServices(sc *service.Container) {
	if !service.Has[TokenModesCompletionFilter](sc) {
		service.Put(sc, NewDefaultTokenModesCompletionFilter())
	}
	if !service.Has[parser.LanguageCompletionAdapter](sc) {
		service.Put[parser.LanguageCompletionAdapter](sc, NewTokenModesCompletionAdapter(sc))
	}
}
