// Code generated by fastbelt. DO NOT EDIT.

package grammar

import "typefox.dev/fastbelt/parser"

func BuildATN() *parser.RuntimeATN {
	states := make([]*parser.RuntimeATNState, 311)
	states[0] = &parser.RuntimeATNState{
		StateNumber:            0,
		Type:                   parser.ATNRuleStart,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[1] = &parser.RuntimeATNState{
		StateNumber: 1,
		Type:        parser.ATNRuleStop,
		Decision:    -1,
	}
	states[2] = &parser.RuntimeATNState{
		StateNumber:            2,
		Type:                   parser.ATNRuleStart,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[3] = &parser.RuntimeATNState{
		StateNumber: 3,
		Type:        parser.ATNRuleStop,
		Decision:    -1,
	}
	states[4] = &parser.RuntimeATNState{
		StateNumber:            4,
		Type:                   parser.ATNRuleStart,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[5] = &parser.RuntimeATNState{
		StateNumber: 5,
		Type:        parser.ATNRuleStop,
		Decision:    -1,
	}
	states[6] = &parser.RuntimeATNState{
		StateNumber:            6,
		Type:                   parser.ATNRuleStart,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[7] = &parser.RuntimeATNState{
		StateNumber: 7,
		Type:        parser.ATNRuleStop,
		Decision:    -1,
	}
	states[8] = &parser.RuntimeATNState{
		StateNumber:            8,
		Type:                   parser.ATNRuleStart,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[9] = &parser.RuntimeATNState{
		StateNumber: 9,
		Type:        parser.ATNRuleStop,
		Decision:    -1,
	}
	states[10] = &parser.RuntimeATNState{
		StateNumber:            10,
		Type:                   parser.ATNRuleStart,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[11] = &parser.RuntimeATNState{
		StateNumber: 11,
		Type:        parser.ATNRuleStop,
		Decision:    -1,
	}
	states[12] = &parser.RuntimeATNState{
		StateNumber:            12,
		Type:                   parser.ATNRuleStart,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[13] = &parser.RuntimeATNState{
		StateNumber: 13,
		Type:        parser.ATNRuleStop,
		Decision:    -1,
	}
	states[14] = &parser.RuntimeATNState{
		StateNumber:            14,
		Type:                   parser.ATNRuleStart,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[15] = &parser.RuntimeATNState{
		StateNumber: 15,
		Type:        parser.ATNRuleStop,
		Decision:    -1,
	}
	states[16] = &parser.RuntimeATNState{
		StateNumber:            16,
		Type:                   parser.ATNRuleStart,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[17] = &parser.RuntimeATNState{
		StateNumber: 17,
		Type:        parser.ATNRuleStop,
		Decision:    -1,
	}
	states[18] = &parser.RuntimeATNState{
		StateNumber:            18,
		Type:                   parser.ATNRuleStart,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[19] = &parser.RuntimeATNState{
		StateNumber: 19,
		Type:        parser.ATNRuleStop,
		Decision:    -1,
	}
	states[20] = &parser.RuntimeATNState{
		StateNumber:            20,
		Type:                   parser.ATNRuleStart,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[21] = &parser.RuntimeATNState{
		StateNumber: 21,
		Type:        parser.ATNRuleStop,
		Decision:    -1,
	}
	states[22] = &parser.RuntimeATNState{
		StateNumber:            22,
		Type:                   parser.ATNRuleStart,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[23] = &parser.RuntimeATNState{
		StateNumber: 23,
		Type:        parser.ATNRuleStop,
		Decision:    -1,
	}
	states[24] = &parser.RuntimeATNState{
		StateNumber:            24,
		Type:                   parser.ATNRuleStart,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[25] = &parser.RuntimeATNState{
		StateNumber: 25,
		Type:        parser.ATNRuleStop,
		Decision:    -1,
	}
	states[26] = &parser.RuntimeATNState{
		StateNumber:            26,
		Type:                   parser.ATNRuleStart,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[27] = &parser.RuntimeATNState{
		StateNumber: 27,
		Type:        parser.ATNRuleStop,
		Decision:    -1,
	}
	states[28] = &parser.RuntimeATNState{
		StateNumber:            28,
		Type:                   parser.ATNRuleStart,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[29] = &parser.RuntimeATNState{
		StateNumber: 29,
		Type:        parser.ATNRuleStop,
		Decision:    -1,
	}
	states[30] = &parser.RuntimeATNState{
		StateNumber:            30,
		Type:                   parser.ATNRuleStart,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[31] = &parser.RuntimeATNState{
		StateNumber: 31,
		Type:        parser.ATNRuleStop,
		Decision:    -1,
	}
	states[32] = &parser.RuntimeATNState{
		StateNumber:            32,
		Type:                   parser.ATNRuleStart,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[33] = &parser.RuntimeATNState{
		StateNumber: 33,
		Type:        parser.ATNRuleStop,
		Decision:    -1,
	}
	states[34] = &parser.RuntimeATNState{
		StateNumber:            34,
		Type:                   parser.ATNRuleStart,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[35] = &parser.RuntimeATNState{
		StateNumber: 35,
		Type:        parser.ATNRuleStop,
		Decision:    -1,
	}
	states[36] = &parser.RuntimeATNState{
		StateNumber:            36,
		Type:                   parser.ATNRuleStart,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[37] = &parser.RuntimeATNState{
		StateNumber: 37,
		Type:        parser.ATNRuleStop,
		Decision:    -1,
	}
	states[38] = &parser.RuntimeATNState{
		StateNumber:            38,
		Type:                   parser.ATNRuleStart,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[39] = &parser.RuntimeATNState{
		StateNumber: 39,
		Type:        parser.ATNRuleStop,
		Decision:    -1,
	}
	states[40] = &parser.RuntimeATNState{
		StateNumber:            40,
		Type:                   parser.ATNRuleStart,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[41] = &parser.RuntimeATNState{
		StateNumber: 41,
		Type:        parser.ATNRuleStop,
		Decision:    -1,
	}
	states[42] = &parser.RuntimeATNState{
		StateNumber:            42,
		Type:                   parser.ATNRuleStart,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[43] = &parser.RuntimeATNState{
		StateNumber: 43,
		Type:        parser.ATNRuleStop,
		Decision:    -1,
	}
	states[44] = &parser.RuntimeATNState{
		StateNumber:            44,
		Type:                   parser.ATNRuleStart,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[45] = &parser.RuntimeATNState{
		StateNumber: 45,
		Type:        parser.ATNRuleStop,
		Decision:    -1,
	}
	states[46] = &parser.RuntimeATNState{
		StateNumber:            46,
		Type:                   parser.ATNRuleStart,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[47] = &parser.RuntimeATNState{
		StateNumber: 47,
		Type:        parser.ATNRuleStop,
		Decision:    -1,
	}
	states[48] = &parser.RuntimeATNState{
		StateNumber:            48,
		Type:                   parser.ATNRuleStart,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[49] = &parser.RuntimeATNState{
		StateNumber: 49,
		Type:        parser.ATNRuleStop,
		Decision:    -1,
	}
	states[50] = &parser.RuntimeATNState{
		StateNumber:            50,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[51] = &parser.RuntimeATNState{
		StateNumber:            51,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[52] = &parser.RuntimeATNState{
		StateNumber:            52,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[53] = &parser.RuntimeATNState{
		StateNumber:            53,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[54] = &parser.RuntimeATNState{
		StateNumber:            54,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[55] = &parser.RuntimeATNState{
		StateNumber:            55,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[56] = &parser.RuntimeATNState{
		StateNumber: 56,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[57] = &parser.RuntimeATNState{
		StateNumber:            57,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[58] = &parser.RuntimeATNState{
		StateNumber:            58,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[59] = &parser.RuntimeATNState{
		StateNumber:            59,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[60] = &parser.RuntimeATNState{
		StateNumber: 60,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[61] = &parser.RuntimeATNState{
		StateNumber:            61,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[62] = &parser.RuntimeATNState{
		StateNumber:            62,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[63] = &parser.RuntimeATNState{
		StateNumber:            63,
		Type:                   parser.ATNBlockEnd,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[64] = &parser.RuntimeATNState{
		StateNumber:            64,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[65] = &parser.RuntimeATNState{
		StateNumber:            65,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[66] = &parser.RuntimeATNState{
		StateNumber: 66,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[67] = &parser.RuntimeATNState{
		StateNumber:            67,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[68] = &parser.RuntimeATNState{
		StateNumber:            68,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[69] = &parser.RuntimeATNState{
		StateNumber:            69,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[70] = &parser.RuntimeATNState{
		StateNumber:            70,
		Type:                   parser.ATNPlusLoopBack,
		Decision:               0,
		EpsilonOnlyTransitions: true,
	}
	states[71] = &parser.RuntimeATNState{
		StateNumber:            71,
		Type:                   parser.ATNLoopEnd,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[72] = &parser.RuntimeATNState{
		StateNumber: 72,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[73] = &parser.RuntimeATNState{
		StateNumber:            73,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[74] = &parser.RuntimeATNState{
		StateNumber: 74,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[75] = &parser.RuntimeATNState{
		StateNumber:            75,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[76] = &parser.RuntimeATNState{
		StateNumber: 76,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[77] = &parser.RuntimeATNState{
		StateNumber:            77,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[78] = &parser.RuntimeATNState{
		StateNumber: 78,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[79] = &parser.RuntimeATNState{
		StateNumber:            79,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[80] = &parser.RuntimeATNState{
		StateNumber:            80,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[81] = &parser.RuntimeATNState{
		StateNumber:            81,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[82] = &parser.RuntimeATNState{
		StateNumber: 82,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[83] = &parser.RuntimeATNState{
		StateNumber:            83,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[84] = &parser.RuntimeATNState{
		StateNumber: 84,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[85] = &parser.RuntimeATNState{
		StateNumber:            85,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[86] = &parser.RuntimeATNState{
		StateNumber: 86,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[87] = &parser.RuntimeATNState{
		StateNumber:            87,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[88] = &parser.RuntimeATNState{
		StateNumber:            88,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[89] = &parser.RuntimeATNState{
		StateNumber:            89,
		Type:                   parser.ATNBlockEnd,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[90] = &parser.RuntimeATNState{
		StateNumber: 90,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[91] = &parser.RuntimeATNState{
		StateNumber:            91,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[92] = &parser.RuntimeATNState{
		StateNumber: 92,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[93] = &parser.RuntimeATNState{
		StateNumber:            93,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[94] = &parser.RuntimeATNState{
		StateNumber: 94,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[95] = &parser.RuntimeATNState{
		StateNumber:            95,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[96] = &parser.RuntimeATNState{
		StateNumber: 96,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[97] = &parser.RuntimeATNState{
		StateNumber:            97,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[98] = &parser.RuntimeATNState{
		StateNumber: 98,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[99] = &parser.RuntimeATNState{
		StateNumber:            99,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[100] = &parser.RuntimeATNState{
		StateNumber: 100,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[101] = &parser.RuntimeATNState{
		StateNumber:            101,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[102] = &parser.RuntimeATNState{
		StateNumber: 102,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[103] = &parser.RuntimeATNState{
		StateNumber:            103,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[104] = &parser.RuntimeATNState{
		StateNumber: 104,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[105] = &parser.RuntimeATNState{
		StateNumber:            105,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[106] = &parser.RuntimeATNState{
		StateNumber: 106,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[107] = &parser.RuntimeATNState{
		StateNumber:            107,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[108] = &parser.RuntimeATNState{
		StateNumber: 108,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[109] = &parser.RuntimeATNState{
		StateNumber:            109,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[110] = &parser.RuntimeATNState{
		StateNumber: 110,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[111] = &parser.RuntimeATNState{
		StateNumber:            111,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[112] = &parser.RuntimeATNState{
		StateNumber: 112,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[113] = &parser.RuntimeATNState{
		StateNumber:            113,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[114] = &parser.RuntimeATNState{
		StateNumber:            114,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[115] = &parser.RuntimeATNState{
		StateNumber:            115,
		Type:                   parser.ATNBlockEnd,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[116] = &parser.RuntimeATNState{
		StateNumber: 116,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[117] = &parser.RuntimeATNState{
		StateNumber:            117,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[118] = &parser.RuntimeATNState{
		StateNumber: 118,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[119] = &parser.RuntimeATNState{
		StateNumber:            119,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[120] = &parser.RuntimeATNState{
		StateNumber:            120,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[121] = &parser.RuntimeATNState{
		StateNumber:            121,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[122] = &parser.RuntimeATNState{
		StateNumber: 122,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[123] = &parser.RuntimeATNState{
		StateNumber:            123,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[124] = &parser.RuntimeATNState{
		StateNumber:            124,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[125] = &parser.RuntimeATNState{
		StateNumber:            125,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[126] = &parser.RuntimeATNState{
		StateNumber:            126,
		Type:                   parser.ATNPlusLoopBack,
		Decision:               1,
		EpsilonOnlyTransitions: true,
	}
	states[127] = &parser.RuntimeATNState{
		StateNumber:            127,
		Type:                   parser.ATNLoopEnd,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[128] = &parser.RuntimeATNState{
		StateNumber:            128,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[129] = &parser.RuntimeATNState{
		StateNumber:            129,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[130] = &parser.RuntimeATNState{
		StateNumber:            130,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[131] = &parser.RuntimeATNState{
		StateNumber:            131,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[132] = &parser.RuntimeATNState{
		StateNumber:            132,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[133] = &parser.RuntimeATNState{
		StateNumber:            133,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[134] = &parser.RuntimeATNState{
		StateNumber:            134,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[135] = &parser.RuntimeATNState{
		StateNumber:            135,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[136] = &parser.RuntimeATNState{
		StateNumber:            136,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[137] = &parser.RuntimeATNState{
		StateNumber:            137,
		Type:                   parser.ATNBlockEnd,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[138] = &parser.RuntimeATNState{
		StateNumber: 138,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[139] = &parser.RuntimeATNState{
		StateNumber:            139,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[140] = &parser.RuntimeATNState{
		StateNumber: 140,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[141] = &parser.RuntimeATNState{
		StateNumber:            141,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[142] = &parser.RuntimeATNState{
		StateNumber: 142,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[143] = &parser.RuntimeATNState{
		StateNumber:            143,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[144] = &parser.RuntimeATNState{
		StateNumber:            144,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[145] = &parser.RuntimeATNState{
		StateNumber:            145,
		Type:                   parser.ATNBlockEnd,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[146] = &parser.RuntimeATNState{
		StateNumber:            146,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[147] = &parser.RuntimeATNState{
		StateNumber:            147,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[148] = &parser.RuntimeATNState{
		StateNumber: 148,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[149] = &parser.RuntimeATNState{
		StateNumber:            149,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[150] = &parser.RuntimeATNState{
		StateNumber:            150,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[151] = &parser.RuntimeATNState{
		StateNumber:            151,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[152] = &parser.RuntimeATNState{
		StateNumber:            152,
		Type:                   parser.ATNPlusLoopBack,
		Decision:               2,
		EpsilonOnlyTransitions: true,
	}
	states[153] = &parser.RuntimeATNState{
		StateNumber:            153,
		Type:                   parser.ATNLoopEnd,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[154] = &parser.RuntimeATNState{
		StateNumber:            154,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[155] = &parser.RuntimeATNState{
		StateNumber:            155,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[156] = &parser.RuntimeATNState{
		StateNumber:            156,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[157] = &parser.RuntimeATNState{
		StateNumber:            157,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[158] = &parser.RuntimeATNState{
		StateNumber:            158,
		Type:                   parser.ATNPlusLoopBack,
		Decision:               3,
		EpsilonOnlyTransitions: true,
	}
	states[159] = &parser.RuntimeATNState{
		StateNumber:            159,
		Type:                   parser.ATNLoopEnd,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[160] = &parser.RuntimeATNState{
		StateNumber:            160,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[161] = &parser.RuntimeATNState{
		StateNumber:            161,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[162] = &parser.RuntimeATNState{
		StateNumber:            162,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[163] = &parser.RuntimeATNState{
		StateNumber:            163,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[164] = &parser.RuntimeATNState{
		StateNumber:            164,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[165] = &parser.RuntimeATNState{
		StateNumber:            165,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[166] = &parser.RuntimeATNState{
		StateNumber:            166,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[167] = &parser.RuntimeATNState{
		StateNumber:            167,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[168] = &parser.RuntimeATNState{
		StateNumber: 168,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[169] = &parser.RuntimeATNState{
		StateNumber:            169,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[170] = &parser.RuntimeATNState{
		StateNumber:            170,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[171] = &parser.RuntimeATNState{
		StateNumber:            171,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[172] = &parser.RuntimeATNState{
		StateNumber: 172,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[173] = &parser.RuntimeATNState{
		StateNumber:            173,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[174] = &parser.RuntimeATNState{
		StateNumber:            174,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[175] = &parser.RuntimeATNState{
		StateNumber:            175,
		Type:                   parser.ATNBlockEnd,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[176] = &parser.RuntimeATNState{
		StateNumber: 176,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[177] = &parser.RuntimeATNState{
		StateNumber:            177,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[178] = &parser.RuntimeATNState{
		StateNumber: 178,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[179] = &parser.RuntimeATNState{
		StateNumber:            179,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[180] = &parser.RuntimeATNState{
		StateNumber: 180,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[181] = &parser.RuntimeATNState{
		StateNumber:            181,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[182] = &parser.RuntimeATNState{
		StateNumber:            182,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[183] = &parser.RuntimeATNState{
		StateNumber:            183,
		Type:                   parser.ATNBlockEnd,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[184] = &parser.RuntimeATNState{
		StateNumber:            184,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[185] = &parser.RuntimeATNState{
		StateNumber:            185,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[186] = &parser.RuntimeATNState{
		StateNumber:            186,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[187] = &parser.RuntimeATNState{
		StateNumber:            187,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[188] = &parser.RuntimeATNState{
		StateNumber:            188,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[189] = &parser.RuntimeATNState{
		StateNumber:            189,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[190] = &parser.RuntimeATNState{
		StateNumber:            190,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[191] = &parser.RuntimeATNState{
		StateNumber:            191,
		Type:                   parser.ATNBlockEnd,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[192] = &parser.RuntimeATNState{
		StateNumber: 192,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[193] = &parser.RuntimeATNState{
		StateNumber:            193,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[194] = &parser.RuntimeATNState{
		StateNumber: 194,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[195] = &parser.RuntimeATNState{
		StateNumber:            195,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[196] = &parser.RuntimeATNState{
		StateNumber: 196,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[197] = &parser.RuntimeATNState{
		StateNumber:            197,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[198] = &parser.RuntimeATNState{
		StateNumber:            198,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[199] = &parser.RuntimeATNState{
		StateNumber:            199,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[200] = &parser.RuntimeATNState{
		StateNumber: 200,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[201] = &parser.RuntimeATNState{
		StateNumber:            201,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[202] = &parser.RuntimeATNState{
		StateNumber: 202,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[203] = &parser.RuntimeATNState{
		StateNumber:            203,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[204] = &parser.RuntimeATNState{
		StateNumber: 204,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[205] = &parser.RuntimeATNState{
		StateNumber:            205,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[206] = &parser.RuntimeATNState{
		StateNumber: 206,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[207] = &parser.RuntimeATNState{
		StateNumber:            207,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[208] = &parser.RuntimeATNState{
		StateNumber:            208,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[209] = &parser.RuntimeATNState{
		StateNumber:            209,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[210] = &parser.RuntimeATNState{
		StateNumber: 210,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[211] = &parser.RuntimeATNState{
		StateNumber:            211,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[212] = &parser.RuntimeATNState{
		StateNumber: 212,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[213] = &parser.RuntimeATNState{
		StateNumber:            213,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[214] = &parser.RuntimeATNState{
		StateNumber: 214,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[215] = &parser.RuntimeATNState{
		StateNumber:            215,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[216] = &parser.RuntimeATNState{
		StateNumber: 216,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[217] = &parser.RuntimeATNState{
		StateNumber:            217,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[218] = &parser.RuntimeATNState{
		StateNumber:            218,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[219] = &parser.RuntimeATNState{
		StateNumber:            219,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[220] = &parser.RuntimeATNState{
		StateNumber:            220,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[221] = &parser.RuntimeATNState{
		StateNumber:            221,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[222] = &parser.RuntimeATNState{
		StateNumber:            222,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[223] = &parser.RuntimeATNState{
		StateNumber:            223,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[224] = &parser.RuntimeATNState{
		StateNumber:            224,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[225] = &parser.RuntimeATNState{
		StateNumber:            225,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[226] = &parser.RuntimeATNState{
		StateNumber:            226,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[227] = &parser.RuntimeATNState{
		StateNumber:            227,
		Type:                   parser.ATNBlockEnd,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[228] = &parser.RuntimeATNState{
		StateNumber:            228,
		Type:                   parser.ATNStarLoopEntry,
		Decision:               4,
		EpsilonOnlyTransitions: true,
	}
	states[229] = &parser.RuntimeATNState{
		StateNumber:            229,
		Type:                   parser.ATNLoopEnd,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[230] = &parser.RuntimeATNState{
		StateNumber:            230,
		Type:                   parser.ATNStarLoopBack,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[231] = &parser.RuntimeATNState{
		StateNumber: 231,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[232] = &parser.RuntimeATNState{
		StateNumber:            232,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[233] = &parser.RuntimeATNState{
		StateNumber: 233,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[234] = &parser.RuntimeATNState{
		StateNumber:            234,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[235] = &parser.RuntimeATNState{
		StateNumber: 235,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[236] = &parser.RuntimeATNState{
		StateNumber:            236,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[237] = &parser.RuntimeATNState{
		StateNumber: 237,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[238] = &parser.RuntimeATNState{
		StateNumber:            238,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[239] = &parser.RuntimeATNState{
		StateNumber: 239,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[240] = &parser.RuntimeATNState{
		StateNumber:            240,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[241] = &parser.RuntimeATNState{
		StateNumber: 241,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[242] = &parser.RuntimeATNState{
		StateNumber:            242,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[243] = &parser.RuntimeATNState{
		StateNumber:            243,
		Type:                   parser.ATNStarLoopEntry,
		Decision:               5,
		EpsilonOnlyTransitions: true,
	}
	states[244] = &parser.RuntimeATNState{
		StateNumber:            244,
		Type:                   parser.ATNLoopEnd,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[245] = &parser.RuntimeATNState{
		StateNumber:            245,
		Type:                   parser.ATNStarLoopBack,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[246] = &parser.RuntimeATNState{
		StateNumber: 246,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[247] = &parser.RuntimeATNState{
		StateNumber:            247,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[248] = &parser.RuntimeATNState{
		StateNumber:            248,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[249] = &parser.RuntimeATNState{
		StateNumber:            249,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[250] = &parser.RuntimeATNState{
		StateNumber:            250,
		Type:                   parser.ATNStarLoopEntry,
		Decision:               6,
		EpsilonOnlyTransitions: true,
	}
	states[251] = &parser.RuntimeATNState{
		StateNumber:            251,
		Type:                   parser.ATNLoopEnd,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[252] = &parser.RuntimeATNState{
		StateNumber:            252,
		Type:                   parser.ATNStarLoopBack,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[253] = &parser.RuntimeATNState{
		StateNumber: 253,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[254] = &parser.RuntimeATNState{
		StateNumber:            254,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[255] = &parser.RuntimeATNState{
		StateNumber: 255,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[256] = &parser.RuntimeATNState{
		StateNumber:            256,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[257] = &parser.RuntimeATNState{
		StateNumber:            257,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[258] = &parser.RuntimeATNState{
		StateNumber:            258,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[259] = &parser.RuntimeATNState{
		StateNumber: 259,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[260] = &parser.RuntimeATNState{
		StateNumber:            260,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[261] = &parser.RuntimeATNState{
		StateNumber: 261,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[262] = &parser.RuntimeATNState{
		StateNumber:            262,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[263] = &parser.RuntimeATNState{
		StateNumber: 263,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[264] = &parser.RuntimeATNState{
		StateNumber:            264,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[265] = &parser.RuntimeATNState{
		StateNumber: 265,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[266] = &parser.RuntimeATNState{
		StateNumber:            266,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[267] = &parser.RuntimeATNState{
		StateNumber:            267,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[268] = &parser.RuntimeATNState{
		StateNumber:            268,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[269] = &parser.RuntimeATNState{
		StateNumber:            269,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[270] = &parser.RuntimeATNState{
		StateNumber:            270,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[271] = &parser.RuntimeATNState{
		StateNumber:            271,
		Type:                   parser.ATNPlusLoopBack,
		Decision:               7,
		EpsilonOnlyTransitions: true,
	}
	states[272] = &parser.RuntimeATNState{
		StateNumber:            272,
		Type:                   parser.ATNLoopEnd,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[273] = &parser.RuntimeATNState{
		StateNumber:            273,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[274] = &parser.RuntimeATNState{
		StateNumber:            274,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[275] = &parser.RuntimeATNState{
		StateNumber:            275,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[276] = &parser.RuntimeATNState{
		StateNumber:            276,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[277] = &parser.RuntimeATNState{
		StateNumber: 277,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[278] = &parser.RuntimeATNState{
		StateNumber:            278,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[279] = &parser.RuntimeATNState{
		StateNumber:            279,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[280] = &parser.RuntimeATNState{
		StateNumber:            280,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[281] = &parser.RuntimeATNState{
		StateNumber: 281,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[282] = &parser.RuntimeATNState{
		StateNumber:            282,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[283] = &parser.RuntimeATNState{
		StateNumber:            283,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[284] = &parser.RuntimeATNState{
		StateNumber:            284,
		Type:                   parser.ATNBlockEnd,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[285] = &parser.RuntimeATNState{
		StateNumber: 285,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[286] = &parser.RuntimeATNState{
		StateNumber:            286,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[287] = &parser.RuntimeATNState{
		StateNumber: 287,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[288] = &parser.RuntimeATNState{
		StateNumber:            288,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[289] = &parser.RuntimeATNState{
		StateNumber: 289,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[290] = &parser.RuntimeATNState{
		StateNumber:            290,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[291] = &parser.RuntimeATNState{
		StateNumber:            291,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[292] = &parser.RuntimeATNState{
		StateNumber:            292,
		Type:                   parser.ATNBlockEnd,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[293] = &parser.RuntimeATNState{
		StateNumber: 293,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[294] = &parser.RuntimeATNState{
		StateNumber:            294,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[295] = &parser.RuntimeATNState{
		StateNumber: 295,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[296] = &parser.RuntimeATNState{
		StateNumber:            296,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[297] = &parser.RuntimeATNState{
		StateNumber:            297,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[298] = &parser.RuntimeATNState{
		StateNumber:            298,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[299] = &parser.RuntimeATNState{
		StateNumber: 299,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[300] = &parser.RuntimeATNState{
		StateNumber:            300,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[301] = &parser.RuntimeATNState{
		StateNumber: 301,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[302] = &parser.RuntimeATNState{
		StateNumber:            302,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[303] = &parser.RuntimeATNState{
		StateNumber: 303,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[304] = &parser.RuntimeATNState{
		StateNumber:            304,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[305] = &parser.RuntimeATNState{
		StateNumber: 305,
		Type:        parser.ATNBasic,
		Decision:    -1,
	}
	states[306] = &parser.RuntimeATNState{
		StateNumber:            306,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[307] = &parser.RuntimeATNState{
		StateNumber:            307,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[308] = &parser.RuntimeATNState{
		StateNumber:            308,
		Type:                   parser.ATNBlockEnd,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[309] = &parser.RuntimeATNState{
		StateNumber:            309,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[310] = &parser.RuntimeATNState{
		StateNumber:            310,
		Type:                   parser.ATNBasic,
		Decision:               -1,
		EpsilonOnlyTransitions: true,
	}
	states[0].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[212]},
	}
	states[2].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[231]},
	}
	states[4].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[255]},
	}
	states[6].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[136]},
	}
	states[8].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[293]},
	}
	states[10].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[259]},
	}
	states[12].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[263]},
	}
	states[14].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[144]},
	}
	states[16].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[72]},
	}
	states[18].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[88]},
	}
	states[20].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[146]},
	}
	states[22].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[154]},
	}
	states[24].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[174]},
	}
	states[26].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[100]},
	}
	states[28].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[299]},
	}
	states[30].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[62]},
	}
	states[32].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[190]},
	}
	states[34].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[64]},
	}
	states[36].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[192]},
	}
	states[38].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[265]},
	}
	states[40].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[102]},
	}
	states[42].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[202]},
	}
	states[44].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[120]},
	}
	states[46].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[267]},
	}
	states[48].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[283]},
	}
	states[50].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeRuleTransition{Target: states[26], FollowState: states[51]},
	}
	states[51].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[63]},
	}
	states[52].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeRuleTransition{Target: states[38], FollowState: states[53]},
	}
	states[53].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[63]},
	}
	states[54].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeRuleTransition{Target: states[36], FollowState: states[55]},
	}
	states[55].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[63]},
	}
	states[56].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[57], TokenTypeID: 1, CategoryMatches: nil},
	}
	states[57].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[58]},
	}
	states[58].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeRuleTransition{Target: states[34], FollowState: states[59]},
	}
	states[59].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[60]},
	}
	states[60].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[61], TokenTypeID: 2, CategoryMatches: nil},
	}
	states[61].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[63]},
	}
	states[62].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[50]},
		&parser.RuntimeEpsilonTransition{Target: states[52]},
		&parser.RuntimeEpsilonTransition{Target: states[54]},
		&parser.RuntimeEpsilonTransition{Target: states[56]},
	}
	states[63].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[31]},
	}
	states[64].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeRuleTransition{Target: states[32], FollowState: states[65]},
	}
	states[65].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[66]},
	}
	states[66].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[67], TokenTypeID: 27, CategoryMatches: nil},
		&parser.RuntimeEpsilonTransition{Target: states[71]},
	}
	states[67].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[68]},
	}
	states[68].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeRuleTransition{Target: states[32], FollowState: states[69]},
	}
	states[69].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[70]},
	}
	states[70].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[66]},
		&parser.RuntimeEpsilonTransition{Target: states[71]},
	}
	states[71].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[35]},
	}
	states[72].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[73], TokenTypeID: 32, CategoryMatches: nil},
	}
	states[73].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[74]},
	}
	states[74].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[75], TokenTypeID: 23, CategoryMatches: nil},
		&parser.RuntimeEpsilonTransition{Target: states[77]},
	}
	states[75].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[76]},
	}
	states[76].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[77], TokenTypeID: 32, CategoryMatches: nil},
	}
	states[77].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[78]},
	}
	states[78].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[79], TokenTypeID: 8, CategoryMatches: nil},
	}
	states[79].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[80]},
	}
	states[80].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeRuleTransition{Target: states[20], FollowState: states[81]},
	}
	states[81].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[82]},
	}
	states[82].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[83], TokenTypeID: 9, CategoryMatches: nil},
	}
	states[83].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[17]},
	}
	states[84].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[85], TokenTypeID: 21, CategoryMatches: nil},
	}
	states[85].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[89]},
	}
	states[86].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[87], TokenTypeID: 16, CategoryMatches: nil},
	}
	states[87].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[89]},
	}
	states[88].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[84]},
		&parser.RuntimeEpsilonTransition{Target: states[86]},
		&parser.RuntimeEpsilonTransition{Target: states[89]},
	}
	states[89].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[90]},
	}
	states[90].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[91], TokenTypeID: 25, CategoryMatches: nil},
	}
	states[91].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[92]},
	}
	states[92].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[93], TokenTypeID: 32, CategoryMatches: nil},
	}
	states[93].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[94]},
	}
	states[94].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[95], TokenTypeID: 8, CategoryMatches: nil},
	}
	states[95].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[96]},
	}
	states[96].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[97], TokenTypeID: 33, CategoryMatches: nil},
	}
	states[97].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[98]},
	}
	states[98].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[99], TokenTypeID: 9, CategoryMatches: nil},
	}
	states[99].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[19]},
	}
	states[100].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[101], TokenTypeID: 31, CategoryMatches: nil},
	}
	states[101].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[27]},
	}
	states[102].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[103], TokenTypeID: 26, CategoryMatches: nil},
	}
	states[103].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[104]},
	}
	states[104].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[105], TokenTypeID: 32, CategoryMatches: nil},
	}
	states[105].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[106]},
	}
	states[106].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[107], TokenTypeID: 7, CategoryMatches: nil},
		&parser.RuntimeEpsilonTransition{Target: states[117]},
	}
	states[107].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[108]},
	}
	states[108].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[109], TokenTypeID: 32, CategoryMatches: nil},
	}
	states[109].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[114]},
	}
	states[110].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[111], TokenTypeID: 5, CategoryMatches: nil},
	}
	states[111].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[115]},
	}
	states[112].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[113], TokenTypeID: 10, CategoryMatches: nil},
	}
	states[113].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[115]},
	}
	states[114].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[110]},
		&parser.RuntimeEpsilonTransition{Target: states[112]},
	}
	states[115].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[116]},
	}
	states[116].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[117], TokenTypeID: 18, CategoryMatches: nil},
	}
	states[117].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[118]},
	}
	states[118].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[119], TokenTypeID: 28, CategoryMatches: nil},
	}
	states[119].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[41]},
	}
	states[120].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeRuleTransition{Target: states[46], FollowState: states[121]},
	}
	states[121].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[122]},
	}
	states[122].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[123], TokenTypeID: 27, CategoryMatches: nil},
		&parser.RuntimeEpsilonTransition{Target: states[127]},
	}
	states[123].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[124]},
	}
	states[124].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeRuleTransition{Target: states[46], FollowState: states[125]},
	}
	states[125].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[126]},
	}
	states[126].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[122]},
		&parser.RuntimeEpsilonTransition{Target: states[127]},
	}
	states[127].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[45]},
	}
	states[128].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeRuleTransition{Target: states[12], FollowState: states[129]},
	}
	states[129].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[137]},
	}
	states[130].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeRuleTransition{Target: states[10], FollowState: states[131]},
	}
	states[131].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[137]},
	}
	states[132].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeRuleTransition{Target: states[8], FollowState: states[133]},
	}
	states[133].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[137]},
	}
	states[134].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeRuleTransition{Target: states[14], FollowState: states[135]},
	}
	states[135].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[137]},
	}
	states[136].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[128]},
		&parser.RuntimeEpsilonTransition{Target: states[130]},
		&parser.RuntimeEpsilonTransition{Target: states[132]},
		&parser.RuntimeEpsilonTransition{Target: states[134]},
	}
	states[137].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[7]},
	}
	states[138].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[139], TokenTypeID: 24, CategoryMatches: nil},
	}
	states[139].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[145]},
	}
	states[140].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[141], TokenTypeID: 15, CategoryMatches: nil},
	}
	states[141].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[145]},
	}
	states[142].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[143], TokenTypeID: 17, CategoryMatches: nil},
	}
	states[143].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[145]},
	}
	states[144].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[138]},
		&parser.RuntimeEpsilonTransition{Target: states[140]},
		&parser.RuntimeEpsilonTransition{Target: states[142]},
	}
	states[145].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[15]},
	}
	states[146].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeRuleTransition{Target: states[22], FollowState: states[147]},
	}
	states[147].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[148]},
	}
	states[148].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[149], TokenTypeID: 27, CategoryMatches: nil},
		&parser.RuntimeEpsilonTransition{Target: states[153]},
	}
	states[149].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[150]},
	}
	states[150].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeRuleTransition{Target: states[22], FollowState: states[151]},
	}
	states[151].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[152]},
	}
	states[152].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[148]},
		&parser.RuntimeEpsilonTransition{Target: states[153]},
	}
	states[153].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[21]},
	}
	states[154].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeRuleTransition{Target: states[24], FollowState: states[155]},
	}
	states[155].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[156]},
	}
	states[156].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeRuleTransition{Target: states[24], FollowState: states[157]},
		&parser.RuntimeEpsilonTransition{Target: states[159]},
	}
	states[157].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[158]},
	}
	states[158].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[156]},
		&parser.RuntimeEpsilonTransition{Target: states[159]},
	}
	states[159].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[23]},
	}
	states[160].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeRuleTransition{Target: states[26], FollowState: states[161]},
	}
	states[161].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[175]},
	}
	states[162].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeRuleTransition{Target: states[28], FollowState: states[163]},
	}
	states[163].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[175]},
	}
	states[164].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeRuleTransition{Target: states[38], FollowState: states[165]},
	}
	states[165].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[175]},
	}
	states[166].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeRuleTransition{Target: states[40], FollowState: states[167]},
	}
	states[167].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[175]},
	}
	states[168].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[169], TokenTypeID: 1, CategoryMatches: nil},
	}
	states[169].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[170]},
	}
	states[170].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeRuleTransition{Target: states[20], FollowState: states[171]},
	}
	states[171].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[172]},
	}
	states[172].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[173], TokenTypeID: 2, CategoryMatches: nil},
	}
	states[173].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[175]},
	}
	states[174].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[160]},
		&parser.RuntimeEpsilonTransition{Target: states[162]},
		&parser.RuntimeEpsilonTransition{Target: states[164]},
		&parser.RuntimeEpsilonTransition{Target: states[166]},
		&parser.RuntimeEpsilonTransition{Target: states[168]},
	}
	states[175].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[182]},
	}
	states[176].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[177], TokenTypeID: 3, CategoryMatches: nil},
	}
	states[177].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[183]},
	}
	states[178].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[179], TokenTypeID: 4, CategoryMatches: nil},
	}
	states[179].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[183]},
	}
	states[180].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[181], TokenTypeID: 11, CategoryMatches: nil},
	}
	states[181].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[183]},
	}
	states[182].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[176]},
		&parser.RuntimeEpsilonTransition{Target: states[178]},
		&parser.RuntimeEpsilonTransition{Target: states[180]},
		&parser.RuntimeEpsilonTransition{Target: states[183]},
	}
	states[183].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[25]},
	}
	states[184].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeRuleTransition{Target: states[26], FollowState: states[185]},
	}
	states[185].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[191]},
	}
	states[186].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeRuleTransition{Target: states[38], FollowState: states[187]},
	}
	states[187].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[191]},
	}
	states[188].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeRuleTransition{Target: states[36], FollowState: states[189]},
	}
	states[189].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[191]},
	}
	states[190].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[184]},
		&parser.RuntimeEpsilonTransition{Target: states[186]},
		&parser.RuntimeEpsilonTransition{Target: states[188]},
	}
	states[191].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[33]},
	}
	states[192].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[193], TokenTypeID: 13, CategoryMatches: nil},
	}
	states[193].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[194]},
	}
	states[194].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[195], TokenTypeID: 32, CategoryMatches: nil},
	}
	states[195].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[196]},
	}
	states[196].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[197], TokenTypeID: 8, CategoryMatches: nil},
		&parser.RuntimeEpsilonTransition{Target: states[199]},
	}
	states[197].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[198]},
	}
	states[198].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeRuleTransition{Target: states[38], FollowState: states[199]},
	}
	states[199].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[200]},
	}
	states[200].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[201], TokenTypeID: 14, CategoryMatches: nil},
	}
	states[201].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[37]},
	}
	states[202].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[203], TokenTypeID: 17, CategoryMatches: nil},
	}
	states[203].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[204]},
	}
	states[204].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[205], TokenTypeID: 32, CategoryMatches: nil},
	}
	states[205].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[206]},
	}
	states[206].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[207], TokenTypeID: 8, CategoryMatches: nil},
	}
	states[207].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[208]},
	}
	states[208].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeRuleTransition{Target: states[44], FollowState: states[209]},
	}
	states[209].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[210]},
	}
	states[210].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[211], TokenTypeID: 9, CategoryMatches: nil},
	}
	states[211].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[43]},
	}
	states[212].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[213], TokenTypeID: 20, CategoryMatches: nil},
	}
	states[213].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[214]},
	}
	states[214].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[215], TokenTypeID: 32, CategoryMatches: nil},
	}
	states[215].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[216]},
	}
	states[216].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[217], TokenTypeID: 9, CategoryMatches: nil},
	}
	states[217].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[228]},
	}
	states[218].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeRuleTransition{Target: states[16], FollowState: states[219]},
	}
	states[219].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[227]},
	}
	states[220].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeRuleTransition{Target: states[18], FollowState: states[221]},
	}
	states[221].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[227]},
	}
	states[222].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeRuleTransition{Target: states[2], FollowState: states[223]},
	}
	states[223].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[227]},
	}
	states[224].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeRuleTransition{Target: states[42], FollowState: states[225]},
	}
	states[225].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[227]},
	}
	states[226].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[218]},
		&parser.RuntimeEpsilonTransition{Target: states[220]},
		&parser.RuntimeEpsilonTransition{Target: states[222]},
		&parser.RuntimeEpsilonTransition{Target: states[224]},
	}
	states[227].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[230]},
	}
	states[228].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[226]},
		&parser.RuntimeEpsilonTransition{Target: states[229]},
	}
	states[229].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[1]},
	}
	states[230].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[228]},
	}
	states[231].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[232], TokenTypeID: 22, CategoryMatches: nil},
	}
	states[232].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[233]},
	}
	states[233].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[234], TokenTypeID: 32, CategoryMatches: nil},
	}
	states[234].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[235]},
	}
	states[235].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[236], TokenTypeID: 19, CategoryMatches: nil},
		&parser.RuntimeEpsilonTransition{Target: states[244]},
	}
	states[236].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[237]},
	}
	states[237].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[238], TokenTypeID: 32, CategoryMatches: nil},
	}
	states[238].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[243]},
	}
	states[239].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[240], TokenTypeID: 6, CategoryMatches: nil},
	}
	states[240].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[241]},
	}
	states[241].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[242], TokenTypeID: 32, CategoryMatches: nil},
	}
	states[242].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[245]},
	}
	states[243].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[239]},
		&parser.RuntimeEpsilonTransition{Target: states[244]},
	}
	states[244].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[246]},
	}
	states[245].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[243]},
	}
	states[246].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[247], TokenTypeID: 26, CategoryMatches: nil},
	}
	states[247].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[250]},
	}
	states[248].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeRuleTransition{Target: states[4], FollowState: states[249]},
	}
	states[249].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[252]},
	}
	states[250].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[248]},
		&parser.RuntimeEpsilonTransition{Target: states[251]},
	}
	states[251].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[253]},
	}
	states[252].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[250]},
	}
	states[253].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[254], TokenTypeID: 28, CategoryMatches: nil},
	}
	states[254].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[3]},
	}
	states[255].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[256], TokenTypeID: 32, CategoryMatches: nil},
	}
	states[256].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[257]},
	}
	states[257].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeRuleTransition{Target: states[6], FollowState: states[258]},
	}
	states[258].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[5]},
	}
	states[259].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[260], TokenTypeID: 3, CategoryMatches: nil},
	}
	states[260].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[261]},
	}
	states[261].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[262], TokenTypeID: 32, CategoryMatches: nil},
	}
	states[262].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[11]},
	}
	states[263].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[264], TokenTypeID: 32, CategoryMatches: nil},
	}
	states[264].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[13]},
	}
	states[265].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[266], TokenTypeID: 32, CategoryMatches: nil},
	}
	states[266].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[39]},
	}
	states[267].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeRuleTransition{Target: states[48], FollowState: states[268]},
	}
	states[268].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[269]},
	}
	states[269].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeRuleTransition{Target: states[48], FollowState: states[270]},
		&parser.RuntimeEpsilonTransition{Target: states[272]},
	}
	states[270].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[271]},
	}
	states[271].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[269]},
		&parser.RuntimeEpsilonTransition{Target: states[272]},
	}
	states[272].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[47]},
	}
	states[273].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeRuleTransition{Target: states[26], FollowState: states[274]},
	}
	states[274].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[284]},
	}
	states[275].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeRuleTransition{Target: states[38], FollowState: states[276]},
	}
	states[276].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[284]},
	}
	states[277].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[278], TokenTypeID: 1, CategoryMatches: nil},
	}
	states[278].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[279]},
	}
	states[279].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeRuleTransition{Target: states[44], FollowState: states[280]},
	}
	states[280].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[281]},
	}
	states[281].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[282], TokenTypeID: 2, CategoryMatches: nil},
	}
	states[282].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[284]},
	}
	states[283].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[273]},
		&parser.RuntimeEpsilonTransition{Target: states[275]},
		&parser.RuntimeEpsilonTransition{Target: states[277]},
	}
	states[284].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[291]},
	}
	states[285].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[286], TokenTypeID: 3, CategoryMatches: nil},
	}
	states[286].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[292]},
	}
	states[287].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[288], TokenTypeID: 4, CategoryMatches: nil},
	}
	states[288].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[292]},
	}
	states[289].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[290], TokenTypeID: 11, CategoryMatches: nil},
	}
	states[290].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[292]},
	}
	states[291].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[285]},
		&parser.RuntimeEpsilonTransition{Target: states[287]},
		&parser.RuntimeEpsilonTransition{Target: states[289]},
		&parser.RuntimeEpsilonTransition{Target: states[292]},
	}
	states[292].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[49]},
	}
	states[293].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[294], TokenTypeID: 13, CategoryMatches: nil},
	}
	states[294].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[295]},
	}
	states[295].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[296], TokenTypeID: 14, CategoryMatches: nil},
	}
	states[296].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[297]},
	}
	states[297].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeRuleTransition{Target: states[6], FollowState: states[298]},
	}
	states[298].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[9]},
	}
	states[299].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[300], TokenTypeID: 32, CategoryMatches: nil},
	}
	states[300].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[307]},
	}
	states[301].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[302], TokenTypeID: 5, CategoryMatches: nil},
	}
	states[302].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[308]},
	}
	states[303].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[304], TokenTypeID: 10, CategoryMatches: nil},
	}
	states[304].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[308]},
	}
	states[305].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeAtomTransition{Target: states[306], TokenTypeID: 12, CategoryMatches: nil},
	}
	states[306].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[308]},
	}
	states[307].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[301]},
		&parser.RuntimeEpsilonTransition{Target: states[303]},
		&parser.RuntimeEpsilonTransition{Target: states[305]},
	}
	states[308].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[309]},
	}
	states[309].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeRuleTransition{Target: states[30], FollowState: states[310]},
	}
	states[310].Transitions = []parser.RuntimeTransition{
		&parser.RuntimeEpsilonTransition{Target: states[29]},
	}
	decisionStates := make([]*parser.RuntimeATNState, 8)
	decisionStates[0] = states[70]
	decisionStates[1] = states[126]
	decisionStates[2] = states[152]
	decisionStates[3] = states[158]
	decisionStates[4] = states[228]
	decisionStates[5] = states[243]
	decisionStates[6] = states[250]
	decisionStates[7] = states[271]
	decisionMap := map[string]*parser.RuntimeATNState{
		"Action_Alternatives_1":                states[114],
		"Action_Group_2":                       states[106],
		"Alternatives_Group_2":                 states[148],
		"Alternatives_Group_3":                 states[152],
		"AssignableAlternatives_Group_2":       states[66],
		"AssignableAlternatives_Group_3":       states[70],
		"AssignableWithoutAlts_Alternatives_1": states[190],
		"Assignable_Alternatives_1":            states[62],
		"Assignment_Alternatives_1":            states[307],
		"CompositeAlternatives_Group_2":        states[122],
		"CompositeAlternatives_Group_3":        states[126],
		"CompositeElement_Alternatives_1":      states[283],
		"CompositeElement_Alternatives_2":      states[291],
		"CompositeGroup_Group_2":               states[269],
		"CompositeGroup_RuleCall_2":            states[271],
		"CrossRef_Group_2":                     states[196],
		"Element_Alternatives_1":               states[174],
		"Element_Alternatives_2":               states[182],
		"FieldType_Alternatives_1":             states[136],
		"Grammar_Alternatives_1":               states[228],
		"Group_Group_2":                        states[156],
		"Group_RuleCall_2":                     states[158],
		"Interface_Group_2":                    states[235],
		"Interface_Group_3":                    states[243],
		"Interface_RuleCall_4":                 states[250],
		"ParserRule_Group_2":                   states[74],
		"PrimitiveType_Alternatives_1":         states[144],
		"Token_Alternatives_1":                 states[88],
	}
	return &parser.RuntimeATN{
		States:         states,
		DecisionStates: decisionStates,
		DecisionMap:    decisionMap,
	}
}
