// Code generated by typefox.dev/fastbelt/cmd/fastbelt. DO NOT EDIT.

package grammar

import (
	"sync"
	core "typefox.dev/fastbelt"
	"typefox.dev/fastbelt/parser"
	"typefox.dev/fastbelt/util/service"
)

type CompletionParser struct {
	state *parser.ParserState
	cp    *parser.CompletionParserState
	sc    *service.Container
	atn   func() *parser.RuntimeATN
}

func NewCompletionParser(sc *service.Container) *CompletionParser {
	return &CompletionParser{
		sc:  sc,
		atn: sync.OnceValue(BuildATN),
	}
}

// Parse runs the completion parser over the given prefix tokens (typically
// the document's tokens up to the cursor) and returns the recorded
// snapshots and rule stack. The completion provider feeds that result into
// the ATN simulator.
func (p *CompletionParser) Parse(tokens []core.Token) *parser.CompletionParseResult {
	messages := service.MustGet[parser.ErrorMessageProvider](p.sc)
	recovery := service.MustGet[parser.ErrorRecoveryStrategy](p.sc)
	cp := &CompletionParser{sc: p.sc, atn: p.atn}
	cp.state = parser.NewParserState(tokens, p.atn(), recovery, messages)
	cp.cp = parser.NewCompletionParserState(cp.state)
	cp.ParseGrammar()
	return cp.cp.Result(tokens)
}

func (p *CompletionParser) ParseGrammar() {
	p.cp.EnterRule("Grammar", Grammar__Start)
	defer p.cp.ExitRule()
	{
		p.state.Consume(Keyword_grammar)
	}
	{
		p.cp.MarkAssignment("Name")
		p.state.Consume(Token_ID)
		p.cp.ClearAssignment()
	}
	{
		p.state.Consume(Keyword_Semicolon)
	}
	p.cp.RecordSnapshot(Grammar__LoopEntry)
	p.state.Sync(Grammar__LoopEntry)
	for p.state.Lookahead(GrammarLookahead0) == 0 {
		switch p.state.Lookahead(GrammarLookaheadOr0) {
		case 0:
			{
				p.cp.MarkAssignment("Rules")
				p.state.EnterRule(Grammar__Basic_1)
				p.ParseParserRule()
				p.state.ExitRule()
				p.cp.ClearAssignment()
			}
		case 1:
			{
				p.cp.MarkAssignment("Terminals")
				p.state.EnterRule(Grammar__Basic_3)
				p.ParseToken()
				p.state.ExitRule()
				p.cp.ClearAssignment()
			}
		case 2:
			{
				p.cp.MarkAssignment("TokenGroups")
				p.state.EnterRule(Grammar__Basic_5)
				p.ParseTokenGroup()
				p.state.ExitRule()
				p.cp.ClearAssignment()
			}
		case 3:
			{
				p.cp.MarkAssignment("Interfaces")
				p.state.EnterRule(Grammar__Basic_7)
				p.ParseInterface()
				p.state.ExitRule()
				p.cp.ClearAssignment()
			}
		case 4:
			{
				p.cp.MarkAssignment("Composites")
				p.state.EnterRule(Grammar__Basic_9)
				p.ParseCompositeRule()
				p.state.ExitRule()
				p.cp.ClearAssignment()
			}
		default:
			token := p.state.LA(1)
			p.state.AppendError(p.state.Messages().NoViableAlternative(token), token)
		}
		p.cp.RecordSnapshot(Grammar__LoopEntry)
		p.state.Sync(Grammar__LoopEntry)
	}
}

func (p *CompletionParser) ParseInterface() {
	p.cp.EnterRule("Interface", Interface__Start)
	defer p.cp.ExitRule()
	{
		p.state.Consume(Keyword_interface)
	}
	{
		p.cp.MarkAssignment("Name")
		p.state.Consume(Token_ID)
		p.cp.ClearAssignment()
	}
	p.cp.RecordSnapshot(Interface_extends)
	p.state.Sync(Interface_extends)
	if p.state.Lookahead(InterfaceLookahead1) == 0 {
		{
			p.state.Consume(Keyword_extends)
		}
		{
			p.cp.MarkAssignment("Extends")
			p.state.Consume(Token_ID)
			p.cp.ClearAssignment()
		}
		p.cp.RecordSnapshot(Interface__LoopEntry_0)
		p.state.Sync(Interface__LoopEntry_0)
		for p.state.Lookahead(InterfaceLookahead2) == 0 {
			{
				p.state.Consume(Keyword_Comma)
			}
			{
				p.cp.MarkAssignment("Extends")
				p.state.Consume(Token_ID)
				p.cp.ClearAssignment()
			}
			p.cp.RecordSnapshot(Interface__LoopEntry_0)
			p.state.Sync(Interface__LoopEntry_0)
		}
	}
	{
		p.state.Consume(Keyword_LeftBrace)
	}
	{
		p.cp.RecordSnapshot(Interface__LoopEntry_1)
		p.state.Sync(Interface__LoopEntry_1)
		for p.state.Lookahead(InterfaceLookahead3) == 0 {
			p.cp.MarkAssignment("Fields")
			p.state.EnterRule(Interface__Basic_2)
			p.ParseField()
			p.state.ExitRule()
			p.cp.ClearAssignment()
			p.cp.RecordSnapshot(Interface__LoopEntry_1)
			p.state.Sync(Interface__LoopEntry_1)
		}
	}
	{
		p.state.Consume(Keyword_RightBrace)
	}
}

func (p *CompletionParser) ParseField() {
	p.cp.EnterRule("Field", Field__Start)
	defer p.cp.ExitRule()
	{
		p.cp.MarkAssignment("Name")
		p.state.Consume(Token_ID)
		p.cp.ClearAssignment()
	}
	{
		p.cp.MarkAssignment("Type")
		p.state.EnterRule(Field__Basic_1)
		p.ParseFieldType()
		p.state.ExitRule()
		p.cp.ClearAssignment()
	}
}

func (p *CompletionParser) ParseFieldType() {
	p.cp.EnterRule("FieldType", FieldType__Start)
	defer p.cp.ExitRule()
	switch p.state.Lookahead(FieldTypeLookaheadOr1) {
	case 0:
		{
			p.state.EnterRule(FieldType__Basic_1)
			p.ParseSimpleType()
			p.state.ExitRule()
		}
	case 1:
		{
			p.state.EnterRule(FieldType__Basic_3)
			p.ParseReferenceType()
			p.state.ExitRule()
		}
	case 2:
		{
			p.state.EnterRule(FieldType__Basic_5)
			p.ParseArrayType()
			p.state.ExitRule()
		}
	case 3:
		{
			p.state.EnterRule(FieldType__Basic_7)
			p.ParsePrimitiveType()
			p.state.ExitRule()
		}
	default:
		token := p.state.LA(1)
		p.state.AppendError(p.state.Messages().NoViableAlternative(token), token)
	}
}

func (p *CompletionParser) ParseArrayType() {
	p.cp.EnterRule("ArrayType", ArrayType__Start)
	defer p.cp.ExitRule()
	{
		p.state.Consume(Keyword_LeftBracket)
	}
	{
		p.state.Consume(Keyword_RightBracket)
	}
	{
		p.cp.MarkAssignment("InternalType")
		p.state.EnterRule(ArrayType__Basic_1)
		p.ParseFieldType()
		p.state.ExitRule()
		p.cp.ClearAssignment()
	}
}

func (p *CompletionParser) ParseReferenceType() {
	p.cp.EnterRule("ReferenceType", ReferenceType__Start)
	defer p.cp.ExitRule()
	{
		p.state.Consume(Keyword_Asterisk)
	}
	{
		p.cp.MarkAssignment("Type")
		p.state.Consume(Token_ID)
		p.cp.ClearAssignment()
	}
}

func (p *CompletionParser) ParseSimpleType() {
	p.cp.EnterRule("SimpleType", SimpleType__Start)
	defer p.cp.ExitRule()
	{
		p.cp.MarkAssignment("Type")
		p.state.Consume(Token_ID)
		p.cp.ClearAssignment()
	}
}

func (p *CompletionParser) ParsePrimitiveType() {
	p.cp.EnterRule("PrimitiveType", PrimitiveType__Start)
	defer p.cp.ExitRule()
	{
		p.cp.MarkAssignment("Type")
		switch p.state.Lookahead(PrimitiveTypeTypeLookaheadOr2) {
		case 0:
			p.state.Consume(Keyword_string)
		case 1:
			p.state.Consume(Keyword_bool)
		case 2:
			p.state.Consume(Keyword_composite)
		}
		p.cp.ClearAssignment()
	}
}

func (p *CompletionParser) ParseParserRule() {
	p.cp.EnterRule("ParserRule", ParserRule__Start)
	defer p.cp.ExitRule()
	{
		p.cp.MarkAssignment("Name")
		p.state.Consume(Token_ID)
		p.cp.ClearAssignment()
	}
	p.cp.RecordSnapshot(ParserRule_returns)
	p.state.Sync(ParserRule_returns)
	if p.state.Lookahead(ParserRuleLookahead4) == 0 {
		{
			p.state.Consume(Keyword_returns)
		}
		{
			p.cp.MarkAssignment("ReturnType")
			p.state.Consume(Token_ID)
			p.cp.ClearAssignment()
		}
	}
	{
		p.state.Consume(Keyword_Colon)
	}
	{
		p.cp.MarkAssignment("Body")
		p.state.EnterRule(ParserRule_Semicolon)
		p.ParseAlternatives()
		p.state.ExitRule()
		p.cp.ClearAssignment()
	}
	{
		p.state.Consume(Keyword_Semicolon)
	}
}

func (p *CompletionParser) ParseToken() {
	p.cp.EnterRule("Token", Token__Start)
	defer p.cp.ExitRule()
	p.cp.RecordSnapshot(Token__Basic_2)
	p.state.Sync(Token__Basic_2)
	if p.state.Lookahead(TokenLookahead5) == 0 {
		switch p.state.Lookahead(TokenLookaheadOr3) {
		case 0:
			{
				p.cp.MarkAssignment("Type")
				p.state.Consume(Keyword_hidden)
				p.cp.ClearAssignment()
			}
		case 1:
			{
				p.cp.MarkAssignment("Type")
				p.state.Consume(Keyword_comment)
				p.cp.ClearAssignment()
			}
		default:
			token := p.state.LA(1)
			p.state.AppendError(p.state.Messages().NoViableAlternative(token), token)
		}
	}
	{
		p.state.Consume(Keyword_token)
	}
	{
		p.cp.MarkAssignment("Name")
		p.state.Consume(Token_ID)
		p.cp.ClearAssignment()
	}
	{
		p.state.Consume(Keyword_Colon)
	}
	{
		p.cp.MarkAssignment("Regexp")
		p.state.Consume(Token_RegexLiteral)
		p.cp.ClearAssignment()
	}
	{
		p.state.Consume(Keyword_Semicolon)
	}
}

func (p *CompletionParser) ParseTokenGroup() {
	p.cp.EnterRule("TokenGroup", TokenGroup__Start)
	defer p.cp.ExitRule()
	{
		p.state.Consume(Keyword_token)
	}
	{
		p.state.Consume(Keyword_group)
	}
	{
		p.cp.MarkAssignment("Name")
		p.state.Consume(Token_ID)
		p.cp.ClearAssignment()
	}
	{
		p.state.Consume(Keyword_LeftBrace)
	}
	p.cp.RecordSnapshot(TokenGroup__LoopEntry)
	p.state.Sync(TokenGroup__LoopEntry)
	for p.state.Lookahead(TokenGroupLookahead6) == 0 {
		switch p.state.Lookahead(TokenGroupLookaheadOr4) {
		case 0:
			{
				p.cp.MarkAssignment("TokenRefs")
				p.state.Consume(Token_ID)
				p.cp.ClearAssignment()
			}
		case 1:
			{
				p.state.Consume(Keyword_keywords)
			}
			{
				p.cp.MarkAssignment("Regexps")
				p.state.Consume(Token_RegexLiteral)
				p.cp.ClearAssignment()
			}
		case 2:
			{
				p.cp.MarkAssignment("Keywords")
				p.state.EnterRule(TokenGroup__Basic_3)
				p.ParseKeyword()
				p.state.ExitRule()
				p.cp.ClearAssignment()
			}
		default:
			token := p.state.LA(1)
			p.state.AppendError(p.state.Messages().NoViableAlternative(token), token)
		}
		p.cp.RecordSnapshot(TokenGroup__LoopEntry)
		p.state.Sync(TokenGroup__LoopEntry)
	}
	{
		p.state.Consume(Keyword_RightBrace)
	}
}

func (p *CompletionParser) ParseAlternatives() {
	p.cp.EnterRule("Alternatives", Alternatives__Start)
	defer p.cp.ExitRule()
	{
		p.state.EnterRule(Alternatives_Pipe)
		p.ParseGroup()
		p.state.ExitRule()
	}
	p.cp.RecordSnapshot(Alternatives_Pipe)
	p.state.Sync(Alternatives_Pipe)
	if p.state.Lookahead(AlternativesLookahead7) == 0 {
		for ok := true; ok; ok = p.state.Lookahead(AlternativesLookahead8) == 0 {
			{
				p.state.Consume(Keyword_Pipe)
			}
			{
				p.cp.MarkAssignment("Alts")
				p.state.EnterRule(Alternatives__Basic_2)
				p.ParseGroup()
				p.state.ExitRule()
				p.cp.ClearAssignment()
			}
			p.cp.RecordSnapshot(Alternatives__LoopBack)
			p.state.Sync(Alternatives__LoopBack)
		}
	}
}

func (p *CompletionParser) ParseGroup() {
	p.cp.EnterRule("Group", Group__Start)
	defer p.cp.ExitRule()
	{
		p.state.EnterRule(Group__Basic_1)
		p.ParseElement()
		p.state.ExitRule()
	}
	p.cp.RecordSnapshot(Group__Basic_1)
	p.state.Sync(Group__Basic_1)
	if p.state.Lookahead(GroupLookahead9) == 0 {
		{
			for ok := true; ok; ok = p.state.Lookahead(GroupLookahead10) == 0 {
				p.cp.MarkAssignment("Elements")
				p.state.EnterRule(Group__Basic_2)
				p.ParseElement()
				p.state.ExitRule()
				p.cp.ClearAssignment()
				p.cp.RecordSnapshot(Group__LoopBack)
				p.state.Sync(Group__LoopBack)
			}
		}
	}
}

func (p *CompletionParser) ParseElement() {
	p.cp.EnterRule("Element", Element__Start)
	defer p.cp.ExitRule()
	switch p.state.Lookahead(ElementLookaheadOr5) {
	case 0:
		{
			p.state.EnterRule(Element__Basic_1)
			p.ParseKeyword()
			p.state.ExitRule()
		}
	case 1:
		{
			p.state.EnterRule(Element__Basic_3)
			p.ParseAssignment()
			p.state.ExitRule()
		}
	case 2:
		{
			p.state.EnterRule(Element__Basic_5)
			p.ParseRuleCall()
			p.state.ExitRule()
		}
	case 3:
		{
			p.state.EnterRule(Element__Basic_7)
			p.ParseAction()
			p.state.ExitRule()
		}
	case 4:
		{
			p.state.Consume(Keyword_LeftParen)
		}
		{
			p.state.EnterRule(Element_RightParen)
			p.ParseAlternatives()
			p.state.ExitRule()
		}
		{
			p.state.Consume(Keyword_RightParen)
		}
	default:
		token := p.state.LA(1)
		p.state.AppendError(p.state.Messages().NoViableAlternative(token), token)
	}
	{
		p.cp.RecordSnapshot(Element__Basic_14)
		p.state.Sync(Element__Basic_14)
		if p.state.Lookahead(ElementLookahead11) == 0 {
			p.cp.MarkAssignment("Cardinality")
			switch p.state.Lookahead(ElementCardinalityLookaheadOr6) {
			case 0:
				p.state.Consume(Keyword_Asterisk)
			case 1:
				p.state.Consume(Keyword_Plus)
			case 2:
				p.state.Consume(Keyword_Question)
			}
			p.cp.ClearAssignment()
		}
	}
}

func (p *CompletionParser) ParseKeyword() {
	p.cp.EnterRule("Keyword", Keyword__Start)
	defer p.cp.ExitRule()
	{
		p.cp.MarkAssignment("Value")
		p.state.Consume(Token_StringLiteral)
		p.cp.ClearAssignment()
	}
}

func (p *CompletionParser) ParseAssignment() {
	p.cp.EnterRule("Assignment", Assignment__Start)
	defer p.cp.ExitRule()
	{
		p.cp.MarkAssignment("Property")
		p.state.Consume(Token_ID)
		p.cp.ClearAssignment()
	}
	{
		p.cp.MarkAssignment("Operator")
		switch p.state.Lookahead(AssignmentOperatorLookaheadOr7) {
		case 0:
			p.state.Consume(Keyword_PlusEquals)
		case 1:
			p.state.Consume(Keyword_Equals)
		case 2:
			p.state.Consume(Keyword_QuestionEquals)
		}
		p.cp.ClearAssignment()
	}
	{
		p.cp.MarkAssignment("Value")
		p.state.EnterRule(Assignment__Basic_5)
		p.ParseAssignable()
		p.state.ExitRule()
		p.cp.ClearAssignment()
	}
}

func (p *CompletionParser) ParseAssignable() {
	p.cp.EnterRule("Assignable", Assignable__Start)
	defer p.cp.ExitRule()
	switch p.state.Lookahead(AssignableLookaheadOr8) {
	case 0:
		{
			p.state.EnterRule(Assignable__Basic_1)
			p.ParseKeyword()
			p.state.ExitRule()
		}
	case 1:
		{
			p.state.EnterRule(Assignable__Basic_3)
			p.ParseRuleCall()
			p.state.ExitRule()
		}
	case 2:
		{
			p.state.EnterRule(Assignable__Basic_5)
			p.ParseCrossRef()
			p.state.ExitRule()
		}
	case 3:
		{
			p.state.Consume(Keyword_LeftParen)
		}
		{
			p.state.EnterRule(Assignable_RightParen)
			p.ParseAssignableAlternatives()
			p.state.ExitRule()
		}
		{
			p.state.Consume(Keyword_RightParen)
		}
	default:
		token := p.state.LA(1)
		p.state.AppendError(p.state.Messages().NoViableAlternative(token), token)
	}
}

func (p *CompletionParser) ParseAssignableWithoutAlts() {
	p.cp.EnterRule("AssignableWithoutAlts", AssignableWithoutAlts__Start)
	defer p.cp.ExitRule()
	switch p.state.Lookahead(AssignableWithoutAltsLookaheadOr9) {
	case 0:
		{
			p.state.EnterRule(AssignableWithoutAlts__Basic_1)
			p.ParseKeyword()
			p.state.ExitRule()
		}
	case 1:
		{
			p.state.EnterRule(AssignableWithoutAlts__Basic_3)
			p.ParseRuleCall()
			p.state.ExitRule()
		}
	case 2:
		{
			p.state.EnterRule(AssignableWithoutAlts__Basic_5)
			p.ParseCrossRef()
			p.state.ExitRule()
		}
	default:
		token := p.state.LA(1)
		p.state.AppendError(p.state.Messages().NoViableAlternative(token), token)
	}
}

func (p *CompletionParser) ParseAssignableAlternatives() {
	p.cp.EnterRule("AssignableAlternatives", AssignableAlternatives__Start)
	defer p.cp.ExitRule()
	{
		p.state.EnterRule(AssignableAlternatives_Pipe)
		p.ParseAssignableWithoutAlts()
		p.state.ExitRule()
	}
	p.cp.RecordSnapshot(AssignableAlternatives_Pipe)
	p.state.Sync(AssignableAlternatives_Pipe)
	if p.state.Lookahead(AssignableAlternativesLookahead12) == 0 {
		for ok := true; ok; ok = p.state.Lookahead(AssignableAlternativesLookahead13) == 0 {
			{
				p.state.Consume(Keyword_Pipe)
			}
			{
				p.cp.MarkAssignment("Alts")
				p.state.EnterRule(AssignableAlternatives__Basic_2)
				p.ParseAssignableWithoutAlts()
				p.state.ExitRule()
				p.cp.ClearAssignment()
			}
			p.cp.RecordSnapshot(AssignableAlternatives__LoopBack)
			p.state.Sync(AssignableAlternatives__LoopBack)
		}
	}
}

func (p *CompletionParser) ParseCrossRef() {
	p.cp.EnterRule("CrossRef", CrossRef__Start)
	defer p.cp.ExitRule()
	{
		p.state.Consume(Keyword_LeftBracket)
	}
	{
		p.cp.MarkAssignment("Type")
		p.state.Consume(Token_ID)
		p.cp.ClearAssignment()
	}
	p.cp.RecordSnapshot(CrossRef_Colon)
	p.state.Sync(CrossRef_Colon)
	if p.state.Lookahead(CrossRefLookahead14) == 0 {
		{
			p.state.Consume(Keyword_Colon)
		}
		{
			p.cp.MarkAssignment("Rule")
			p.state.EnterRule(CrossRef__Basic_1)
			p.ParseRuleCall()
			p.state.ExitRule()
			p.cp.ClearAssignment()
		}
	}
	{
		p.state.Consume(Keyword_RightBracket)
	}
}

func (p *CompletionParser) ParseRuleCall() {
	p.cp.EnterRule("RuleCall", RuleCall__Start)
	defer p.cp.ExitRule()
	{
		p.cp.MarkAssignment("Rule")
		p.state.Consume(Token_ID)
		p.cp.ClearAssignment()
	}
}

func (p *CompletionParser) ParseAction() {
	p.cp.EnterRule("Action", Action__Start)
	defer p.cp.ExitRule()
	{
		p.state.Consume(Keyword_LeftBrace)
	}
	{
		p.cp.MarkAssignment("Type")
		p.state.Consume(Token_ID)
		p.cp.ClearAssignment()
	}
	p.cp.RecordSnapshot(Action_Dot)
	p.state.Sync(Action_Dot)
	if p.state.Lookahead(ActionLookahead15) == 0 {
		{
			p.state.Consume(Keyword_Dot)
		}
		{
			p.cp.MarkAssignment("Property")
			p.state.Consume(Token_ID)
			p.cp.ClearAssignment()
		}
		{
			p.cp.MarkAssignment("Operator")
			switch p.state.Lookahead(ActionOperatorLookaheadOr10) {
			case 0:
				p.state.Consume(Keyword_PlusEquals)
			case 1:
				p.state.Consume(Keyword_Equals)
			}
			p.cp.ClearAssignment()
		}
		{
			p.state.Consume(Keyword_current)
		}
	}
	{
		p.state.Consume(Keyword_RightBrace)
	}
}

func (p *CompletionParser) ParseCompositeRule() {
	p.cp.EnterRule("CompositeRule", CompositeRule__Start)
	defer p.cp.ExitRule()
	{
		p.state.Consume(Keyword_composite)
	}
	{
		p.cp.MarkAssignment("Name")
		p.state.Consume(Token_ID)
		p.cp.ClearAssignment()
	}
	{
		p.state.Consume(Keyword_Colon)
	}
	{
		p.cp.MarkAssignment("Body")
		p.state.EnterRule(CompositeRule_Semicolon)
		p.ParseCompositeAlternatives()
		p.state.ExitRule()
		p.cp.ClearAssignment()
	}
	{
		p.state.Consume(Keyword_Semicolon)
	}
}

func (p *CompletionParser) ParseCompositeAlternatives() {
	p.cp.EnterRule("CompositeAlternatives", CompositeAlternatives__Start)
	defer p.cp.ExitRule()
	{
		p.state.EnterRule(CompositeAlternatives_Pipe)
		p.ParseCompositeGroup()
		p.state.ExitRule()
	}
	p.cp.RecordSnapshot(CompositeAlternatives_Pipe)
	p.state.Sync(CompositeAlternatives_Pipe)
	if p.state.Lookahead(CompositeAlternativesLookahead16) == 0 {
		for ok := true; ok; ok = p.state.Lookahead(CompositeAlternativesLookahead17) == 0 {
			{
				p.state.Consume(Keyword_Pipe)
			}
			{
				p.cp.MarkAssignment("Alts")
				p.state.EnterRule(CompositeAlternatives__Basic_2)
				p.ParseCompositeGroup()
				p.state.ExitRule()
				p.cp.ClearAssignment()
			}
			p.cp.RecordSnapshot(CompositeAlternatives__LoopBack)
			p.state.Sync(CompositeAlternatives__LoopBack)
		}
	}
}

func (p *CompletionParser) ParseCompositeGroup() {
	p.cp.EnterRule("CompositeGroup", CompositeGroup__Start)
	defer p.cp.ExitRule()
	{
		p.state.EnterRule(CompositeGroup__Basic_1)
		p.ParseCompositeElement()
		p.state.ExitRule()
	}
	p.cp.RecordSnapshot(CompositeGroup__Basic_1)
	p.state.Sync(CompositeGroup__Basic_1)
	if p.state.Lookahead(CompositeGroupLookahead18) == 0 {
		{
			for ok := true; ok; ok = p.state.Lookahead(CompositeGroupLookahead19) == 0 {
				p.cp.MarkAssignment("Elements")
				p.state.EnterRule(CompositeGroup__Basic_2)
				p.ParseCompositeElement()
				p.state.ExitRule()
				p.cp.ClearAssignment()
				p.cp.RecordSnapshot(CompositeGroup__LoopBack)
				p.state.Sync(CompositeGroup__LoopBack)
			}
		}
	}
}

func (p *CompletionParser) ParseCompositeElement() {
	p.cp.EnterRule("CompositeElement", CompositeElement__Start)
	defer p.cp.ExitRule()
	switch p.state.Lookahead(CompositeElementLookaheadOr11) {
	case 0:
		{
			p.state.EnterRule(CompositeElement__Basic_1)
			p.ParseKeyword()
			p.state.ExitRule()
		}
	case 1:
		{
			p.state.EnterRule(CompositeElement__Basic_3)
			p.ParseRuleCall()
			p.state.ExitRule()
		}
	case 2:
		{
			p.state.Consume(Keyword_LeftParen)
		}
		{
			p.state.EnterRule(CompositeElement_RightParen)
			p.ParseCompositeAlternatives()
			p.state.ExitRule()
		}
		{
			p.state.Consume(Keyword_RightParen)
		}
	default:
		token := p.state.LA(1)
		p.state.AppendError(p.state.Messages().NoViableAlternative(token), token)
	}
	{
		p.cp.RecordSnapshot(CompositeElement__Basic_10)
		p.state.Sync(CompositeElement__Basic_10)
		if p.state.Lookahead(CompositeElementLookahead20) == 0 {
			p.cp.MarkAssignment("Cardinality")
			switch p.state.Lookahead(CompositeElementCardinalityLookaheadOr12) {
			case 0:
				p.state.Consume(Keyword_Asterisk)
			case 1:
				p.state.Consume(Keyword_Plus)
			case 2:
				p.state.Consume(Keyword_Question)
			}
			p.cp.ClearAssignment()
		}
	}
}
