// Code generated by typefox.dev/fastbelt/cmd/fastbelt. DO NOT EDIT.

package grammar

import (
	"sync"
	core "typefox.dev/fastbelt"
	"typefox.dev/fastbelt/parser"
	"typefox.dev/fastbelt/util/service"
)

type CompletionParser struct {
	state *parser.ParserState
	cp    *parser.CompletionParserState
	sc    *service.Container
	atn   func() *parser.RuntimeATN
}

func NewCompletionParser(sc *service.Container) *CompletionParser {
	return &CompletionParser{
		sc:  sc,
		atn: sync.OnceValue(BuildATN),
	}
}

// Parse runs the completion parser over the given prefix tokens (typically
// the document's tokens up to the cursor) and returns the recorded
// snapshots and rule stack. The completion provider feeds that result into
// the ATN simulator.
func (p *CompletionParser) Parse(tokens []core.Token) *parser.CompletionParseResult {
	messages := service.MustGet[parser.ErrorMessageProvider](p.sc)
	recovery := service.MustGet[parser.ErrorRecoveryStrategy](p.sc)
	cp := &CompletionParser{sc: p.sc, atn: p.atn}
	cp.state = parser.NewParserState(tokens, p.atn(), recovery, messages)
	cp.cp = parser.NewCompletionParserState(cp.state)
	cp.ParseGrammar()
	return cp.cp.Result(tokens)
}

func (p *CompletionParser) ParseGrammar() {
	p.cp.EnterRule("Grammar", 0)
	defer p.cp.ExitRule()
	{
		token := p.state.Consume(Keyword_grammar)
		_ = token
	}
	{
		p.cp.MarkAssignment("Name")
		token := p.state.Consume(Token_ID)
		_ = token
		p.cp.ClearAssignment()
	}
	{
		token := p.state.Consume(Keyword_Semicolon)
		_ = token
	}
	p.cp.RecordSnapshot(67)
	p.state.Sync(67)
	for p.state.Lookahead(GrammarLookahead0) == 0 {
		switch p.state.Lookahead(GrammarLookaheadOr0) {
		case 0:
			{
				p.cp.MarkAssignment("Rules")
				p.state.EnterRule(56)
				p.ParseParserRule()
				p.state.ExitRule()
				p.cp.ClearAssignment()
			}
		case 1:
			{
				p.cp.MarkAssignment("Terminals")
				p.state.EnterRule(58)
				p.ParseToken()
				p.state.ExitRule()
				p.cp.ClearAssignment()
			}
		case 2:
			{
				p.cp.MarkAssignment("TokenGroups")
				p.state.EnterRule(60)
				p.ParseTokenGroup()
				p.state.ExitRule()
				p.cp.ClearAssignment()
			}
		case 3:
			{
				p.cp.MarkAssignment("Interfaces")
				p.state.EnterRule(62)
				p.ParseInterface()
				p.state.ExitRule()
				p.cp.ClearAssignment()
			}
		case 4:
			{
				p.cp.MarkAssignment("Composites")
				p.state.EnterRule(64)
				p.ParseCompositeRule()
				p.state.ExitRule()
				p.cp.ClearAssignment()
			}
		default:
			token := p.state.LA(1)
			p.state.AppendError(p.state.Messages().NoViableAlternative(token), token)
		}
		p.cp.RecordSnapshot(67)
		p.state.Sync(67)
	}
}

func (p *CompletionParser) ParseInterface() {
	p.cp.EnterRule("Interface", 2)
	defer p.cp.ExitRule()
	{
		token := p.state.Consume(Keyword_interface)
		_ = token
	}
	{
		p.cp.MarkAssignment("Name")
		token := p.state.Consume(Token_ID)
		_ = token
		p.cp.ClearAssignment()
	}
	p.cp.RecordSnapshot(72)
	p.state.Sync(72)
	if p.state.Lookahead(InterfaceLookahead1) == 0 {
		{
			token := p.state.Consume(Keyword_extends)
			_ = token
		}
		{
			p.cp.MarkAssignment("Extends")
			token := p.state.Consume(Token_ID)
			_ = token
			p.cp.ClearAssignment()
		}
		p.cp.RecordSnapshot(77)
		p.state.Sync(77)
		for p.state.Lookahead(InterfaceLookahead2) == 0 {
			{
				token := p.state.Consume(Keyword_Comma)
				_ = token
			}
			{
				p.cp.MarkAssignment("Extends")
				token := p.state.Consume(Token_ID)
				_ = token
				p.cp.ClearAssignment()
			}
			p.cp.RecordSnapshot(77)
			p.state.Sync(77)
		}
	}
	{
		token := p.state.Consume(Keyword_LeftBrace)
		_ = token
	}
	{
		p.cp.RecordSnapshot(83)
		p.state.Sync(83)
		for p.state.Lookahead(InterfaceLookahead3) == 0 {
			p.cp.MarkAssignment("Fields")
			p.state.EnterRule(82)
			p.ParseField()
			p.state.ExitRule()
			p.cp.ClearAssignment()
			p.cp.RecordSnapshot(83)
			p.state.Sync(83)
		}
	}
	{
		token := p.state.Consume(Keyword_RightBrace)
		_ = token
	}
}

func (p *CompletionParser) ParseField() {
	p.cp.EnterRule("Field", 4)
	defer p.cp.ExitRule()
	{
		p.cp.MarkAssignment("Name")
		token := p.state.Consume(Token_ID)
		_ = token
		p.cp.ClearAssignment()
	}
	{
		p.cp.MarkAssignment("Type")
		p.state.EnterRule(90)
		p.ParseFieldType()
		p.state.ExitRule()
		p.cp.ClearAssignment()
	}
}

func (p *CompletionParser) ParseFieldType() {
	p.cp.EnterRule("FieldType", 6)
	defer p.cp.ExitRule()
	switch p.state.Lookahead(FieldTypeLookaheadOr1) {
	case 0:
		{
			p.state.EnterRule(92)
			p.ParseSimpleType()
			p.state.ExitRule()
		}
	case 1:
		{
			p.state.EnterRule(94)
			p.ParseReferenceType()
			p.state.ExitRule()
		}
	case 2:
		{
			p.state.EnterRule(96)
			p.ParseArrayType()
			p.state.ExitRule()
		}
	case 3:
		{
			p.state.EnterRule(98)
			p.ParsePrimitiveType()
			p.state.ExitRule()
		}
	default:
		token := p.state.LA(1)
		p.state.AppendError(p.state.Messages().NoViableAlternative(token), token)
	}
}

func (p *CompletionParser) ParseArrayType() {
	p.cp.EnterRule("ArrayType", 8)
	defer p.cp.ExitRule()
	{
		token := p.state.Consume(Keyword_LeftBracket)
		_ = token
	}
	{
		token := p.state.Consume(Keyword_RightBracket)
		_ = token
	}
	{
		p.cp.MarkAssignment("InternalType")
		p.state.EnterRule(104)
		p.ParseFieldType()
		p.state.ExitRule()
		p.cp.ClearAssignment()
	}
}

func (p *CompletionParser) ParseReferenceType() {
	p.cp.EnterRule("ReferenceType", 10)
	defer p.cp.ExitRule()
	{
		token := p.state.Consume(Keyword_Asterisk)
		_ = token
	}
	{
		p.cp.MarkAssignment("Type")
		token := p.state.Consume(Token_ID)
		_ = token
		p.cp.ClearAssignment()
	}
}

func (p *CompletionParser) ParseSimpleType() {
	p.cp.EnterRule("SimpleType", 12)
	defer p.cp.ExitRule()
	{
		p.cp.MarkAssignment("Type")
		token := p.state.Consume(Token_ID)
		_ = token
		p.cp.ClearAssignment()
	}
}

func (p *CompletionParser) ParsePrimitiveType() {
	p.cp.EnterRule("PrimitiveType", 14)
	defer p.cp.ExitRule()
	{
		p.cp.MarkAssignment("Type")
		switch p.state.Lookahead(PrimitiveTypeTypeLookaheadOr2) {
		case 0:
			token := p.state.Consume(Keyword_string)
			_ = token
		case 1:
			token := p.state.Consume(Keyword_bool)
			_ = token
		case 2:
			token := p.state.Consume(Keyword_composite)
			_ = token
		}
		p.cp.ClearAssignment()
	}
}

func (p *CompletionParser) ParseParserRule() {
	p.cp.EnterRule("ParserRule", 16)
	defer p.cp.ExitRule()
	{
		p.cp.MarkAssignment("Name")
		token := p.state.Consume(Token_ID)
		_ = token
		p.cp.ClearAssignment()
	}
	p.cp.RecordSnapshot(119)
	p.state.Sync(119)
	if p.state.Lookahead(ParserRuleLookahead4) == 0 {
		{
			token := p.state.Consume(Keyword_returns)
			_ = token
		}
		{
			p.cp.MarkAssignment("ReturnType")
			token := p.state.Consume(Token_ID)
			_ = token
			p.cp.ClearAssignment()
		}
	}
	{
		token := p.state.Consume(Keyword_Colon)
		_ = token
	}
	{
		p.cp.MarkAssignment("Body")
		p.state.EnterRule(124)
		p.ParseAlternatives()
		p.state.ExitRule()
		p.cp.ClearAssignment()
	}
	{
		token := p.state.Consume(Keyword_Semicolon)
		_ = token
	}
}

func (p *CompletionParser) ParseToken() {
	p.cp.EnterRule("Token", 18)
	defer p.cp.ExitRule()
	p.cp.RecordSnapshot(130)
	p.state.Sync(130)
	if p.state.Lookahead(TokenLookahead5) == 0 {
		switch p.state.Lookahead(TokenLookaheadOr3) {
		case 0:
			{
				p.cp.MarkAssignment("Type")
				token := p.state.Consume(Keyword_hidden)
				_ = token
				p.cp.ClearAssignment()
			}
		case 1:
			{
				p.cp.MarkAssignment("Type")
				token := p.state.Consume(Keyword_comment)
				_ = token
				p.cp.ClearAssignment()
			}
		default:
			token := p.state.LA(1)
			p.state.AppendError(p.state.Messages().NoViableAlternative(token), token)
		}
	}
	{
		token := p.state.Consume(Keyword_token)
		_ = token
	}
	{
		p.cp.MarkAssignment("Name")
		token := p.state.Consume(Token_ID)
		_ = token
		p.cp.ClearAssignment()
	}
	{
		token := p.state.Consume(Keyword_Colon)
		_ = token
	}
	{
		p.cp.MarkAssignment("Regexp")
		token := p.state.Consume(Token_RegexLiteral)
		_ = token
		p.cp.ClearAssignment()
	}
	{
		token := p.state.Consume(Keyword_Semicolon)
		_ = token
	}
}

func (p *CompletionParser) ParseTokenGroup() {
	p.cp.EnterRule("TokenGroup", 20)
	defer p.cp.ExitRule()
	{
		token := p.state.Consume(Keyword_token)
		_ = token
	}
	{
		token := p.state.Consume(Keyword_group)
		_ = token
	}
	{
		p.cp.MarkAssignment("Name")
		token := p.state.Consume(Token_ID)
		_ = token
		p.cp.ClearAssignment()
	}
	{
		token := p.state.Consume(Keyword_LeftBrace)
		_ = token
	}
	p.cp.RecordSnapshot(150)
	p.state.Sync(150)
	for p.state.Lookahead(TokenGroupLookahead6) == 0 {
		switch p.state.Lookahead(TokenGroupLookaheadOr4) {
		case 0:
			{
				p.cp.MarkAssignment("TokenRefs")
				token := p.state.Consume(Token_ID)
				_ = token
				p.cp.ClearAssignment()
			}
		case 1:
			{
				p.cp.MarkAssignment("Regexps")
				token := p.state.Consume(Token_RegexLiteral)
				_ = token
				p.cp.ClearAssignment()
			}
		case 2:
			{
				p.cp.MarkAssignment("Keywords")
				token := p.state.Consume(Token_StringLiteral)
				_ = token
				p.cp.ClearAssignment()
			}
		default:
			token := p.state.LA(1)
			p.state.AppendError(p.state.Messages().NoViableAlternative(token), token)
		}
		p.cp.RecordSnapshot(150)
		p.state.Sync(150)
	}
	{
		token := p.state.Consume(Keyword_RightBrace)
		_ = token
	}
}

func (p *CompletionParser) ParseAlternatives() {
	p.cp.EnterRule("Alternatives", 22)
	defer p.cp.ExitRule()
	{
		p.state.EnterRule(156)
		p.ParseGroup()
		p.state.ExitRule()
	}
	p.cp.RecordSnapshot(156)
	p.state.Sync(156)
	if p.state.Lookahead(AlternativesLookahead7) == 0 {
		for ok := true; ok; ok = p.state.Lookahead(AlternativesLookahead8) == 0 {
			{
				token := p.state.Consume(Keyword_Pipe)
				_ = token
			}
			{
				p.cp.MarkAssignment("Alts")
				p.state.EnterRule(158)
				p.ParseGroup()
				p.state.ExitRule()
				p.cp.ClearAssignment()
			}
			p.cp.RecordSnapshot(159)
			p.state.Sync(159)
		}
	}
}

func (p *CompletionParser) ParseGroup() {
	p.cp.EnterRule("Group", 24)
	defer p.cp.ExitRule()
	{
		p.state.EnterRule(162)
		p.ParseElement()
		p.state.ExitRule()
	}
	p.cp.RecordSnapshot(162)
	p.state.Sync(162)
	if p.state.Lookahead(GroupLookahead9) == 0 {
		{
			for ok := true; ok; ok = p.state.Lookahead(GroupLookahead10) == 0 {
				p.cp.MarkAssignment("Elements")
				p.state.EnterRule(163)
				p.ParseElement()
				p.state.ExitRule()
				p.cp.ClearAssignment()
				p.cp.RecordSnapshot(164)
				p.state.Sync(164)
			}
		}
	}
}

func (p *CompletionParser) ParseElement() {
	p.cp.EnterRule("Element", 26)
	defer p.cp.ExitRule()
	switch p.state.Lookahead(ElementLookaheadOr5) {
	case 0:
		{
			p.state.EnterRule(167)
			p.ParseKeyword()
			p.state.ExitRule()
		}
	case 1:
		{
			p.state.EnterRule(169)
			p.ParseAssignment()
			p.state.ExitRule()
		}
	case 2:
		{
			p.state.EnterRule(171)
			p.ParseRuleCall()
			p.state.ExitRule()
		}
	case 3:
		{
			p.state.EnterRule(173)
			p.ParseAction()
			p.state.ExitRule()
		}
	case 4:
		{
			token := p.state.Consume(Keyword_LeftParen)
			_ = token
		}
		{
			p.state.EnterRule(176)
			p.ParseAlternatives()
			p.state.ExitRule()
		}
		{
			token := p.state.Consume(Keyword_RightParen)
			_ = token
		}
	default:
		token := p.state.LA(1)
		p.state.AppendError(p.state.Messages().NoViableAlternative(token), token)
	}
	{
		p.cp.RecordSnapshot(186)
		p.state.Sync(186)
		if p.state.Lookahead(ElementLookahead11) == 0 {
			p.cp.MarkAssignment("Cardinality")
			switch p.state.Lookahead(ElementCardinalityLookaheadOr6) {
			case 0:
				token := p.state.Consume(Keyword_Asterisk)
				_ = token
			case 1:
				token := p.state.Consume(Keyword_Plus)
				_ = token
			case 2:
				token := p.state.Consume(Keyword_Question)
				_ = token
			}
			p.cp.ClearAssignment()
		}
	}
}

func (p *CompletionParser) ParseKeyword() {
	p.cp.EnterRule("Keyword", 28)
	defer p.cp.ExitRule()
	{
		p.cp.MarkAssignment("Value")
		token := p.state.Consume(Token_StringLiteral)
		_ = token
		p.cp.ClearAssignment()
	}
}

func (p *CompletionParser) ParseAssignment() {
	p.cp.EnterRule("Assignment", 30)
	defer p.cp.ExitRule()
	{
		p.cp.MarkAssignment("Property")
		token := p.state.Consume(Token_ID)
		_ = token
		p.cp.ClearAssignment()
	}
	{
		p.cp.MarkAssignment("Operator")
		switch p.state.Lookahead(AssignmentOperatorLookaheadOr7) {
		case 0:
			token := p.state.Consume(Keyword_PlusEquals)
			_ = token
		case 1:
			token := p.state.Consume(Keyword_Equals)
			_ = token
		case 2:
			token := p.state.Consume(Keyword_QuestionEquals)
			_ = token
		}
		p.cp.ClearAssignment()
	}
	{
		p.cp.MarkAssignment("Value")
		p.state.EnterRule(200)
		p.ParseAssignable()
		p.state.ExitRule()
		p.cp.ClearAssignment()
	}
}

func (p *CompletionParser) ParseAssignable() {
	p.cp.EnterRule("Assignable", 32)
	defer p.cp.ExitRule()
	switch p.state.Lookahead(AssignableLookaheadOr8) {
	case 0:
		{
			p.state.EnterRule(202)
			p.ParseKeyword()
			p.state.ExitRule()
		}
	case 1:
		{
			p.state.EnterRule(204)
			p.ParseRuleCall()
			p.state.ExitRule()
		}
	case 2:
		{
			p.state.EnterRule(206)
			p.ParseCrossRef()
			p.state.ExitRule()
		}
	case 3:
		{
			token := p.state.Consume(Keyword_LeftParen)
			_ = token
		}
		{
			p.state.EnterRule(209)
			p.ParseAssignableAlternatives()
			p.state.ExitRule()
		}
		{
			token := p.state.Consume(Keyword_RightParen)
			_ = token
		}
	default:
		token := p.state.LA(1)
		p.state.AppendError(p.state.Messages().NoViableAlternative(token), token)
	}
}

func (p *CompletionParser) ParseAssignableWithoutAlts() {
	p.cp.EnterRule("AssignableWithoutAlts", 34)
	defer p.cp.ExitRule()
	switch p.state.Lookahead(AssignableWithoutAltsLookaheadOr9) {
	case 0:
		{
			p.state.EnterRule(214)
			p.ParseKeyword()
			p.state.ExitRule()
		}
	case 1:
		{
			p.state.EnterRule(216)
			p.ParseRuleCall()
			p.state.ExitRule()
		}
	case 2:
		{
			p.state.EnterRule(218)
			p.ParseCrossRef()
			p.state.ExitRule()
		}
	default:
		token := p.state.LA(1)
		p.state.AppendError(p.state.Messages().NoViableAlternative(token), token)
	}
}

func (p *CompletionParser) ParseAssignableAlternatives() {
	p.cp.EnterRule("AssignableAlternatives", 36)
	defer p.cp.ExitRule()
	{
		p.state.EnterRule(222)
		p.ParseAssignableWithoutAlts()
		p.state.ExitRule()
	}
	p.cp.RecordSnapshot(222)
	p.state.Sync(222)
	if p.state.Lookahead(AssignableAlternativesLookahead12) == 0 {
		for ok := true; ok; ok = p.state.Lookahead(AssignableAlternativesLookahead13) == 0 {
			{
				token := p.state.Consume(Keyword_Pipe)
				_ = token
			}
			{
				p.cp.MarkAssignment("Alts")
				p.state.EnterRule(224)
				p.ParseAssignableWithoutAlts()
				p.state.ExitRule()
				p.cp.ClearAssignment()
			}
			p.cp.RecordSnapshot(225)
			p.state.Sync(225)
		}
	}
}

func (p *CompletionParser) ParseCrossRef() {
	p.cp.EnterRule("CrossRef", 38)
	defer p.cp.ExitRule()
	{
		token := p.state.Consume(Keyword_LeftBracket)
		_ = token
	}
	{
		p.cp.MarkAssignment("Type")
		token := p.state.Consume(Token_ID)
		_ = token
		p.cp.ClearAssignment()
	}
	p.cp.RecordSnapshot(229)
	p.state.Sync(229)
	if p.state.Lookahead(CrossRefLookahead14) == 0 {
		{
			token := p.state.Consume(Keyword_Colon)
			_ = token
		}
		{
			p.cp.MarkAssignment("Rule")
			p.state.EnterRule(231)
			p.ParseRuleCall()
			p.state.ExitRule()
			p.cp.ClearAssignment()
		}
	}
	{
		token := p.state.Consume(Keyword_RightBracket)
		_ = token
	}
}

func (p *CompletionParser) ParseRuleCall() {
	p.cp.EnterRule("RuleCall", 40)
	defer p.cp.ExitRule()
	{
		p.cp.MarkAssignment("Rule")
		token := p.state.Consume(Token_ID)
		_ = token
		p.cp.ClearAssignment()
	}
}

func (p *CompletionParser) ParseAction() {
	p.cp.EnterRule("Action", 42)
	defer p.cp.ExitRule()
	{
		token := p.state.Consume(Keyword_LeftBrace)
		_ = token
	}
	{
		p.cp.MarkAssignment("Type")
		token := p.state.Consume(Token_ID)
		_ = token
		p.cp.ClearAssignment()
	}
	p.cp.RecordSnapshot(238)
	p.state.Sync(238)
	if p.state.Lookahead(ActionLookahead15) == 0 {
		{
			token := p.state.Consume(Keyword_Dot)
			_ = token
		}
		{
			p.cp.MarkAssignment("Property")
			token := p.state.Consume(Token_ID)
			_ = token
			p.cp.ClearAssignment()
		}
		{
			p.cp.MarkAssignment("Operator")
			switch p.state.Lookahead(ActionOperatorLookaheadOr10) {
			case 0:
				token := p.state.Consume(Keyword_PlusEquals)
				_ = token
			case 1:
				token := p.state.Consume(Keyword_Equals)
				_ = token
			}
			p.cp.ClearAssignment()
		}
		{
			token := p.state.Consume(Keyword_current)
			_ = token
		}
	}
	{
		token := p.state.Consume(Keyword_RightBrace)
		_ = token
	}
}

func (p *CompletionParser) ParseCompositeRule() {
	p.cp.EnterRule("CompositeRule", 44)
	defer p.cp.ExitRule()
	{
		token := p.state.Consume(Keyword_composite)
		_ = token
	}
	{
		p.cp.MarkAssignment("Name")
		token := p.state.Consume(Token_ID)
		_ = token
		p.cp.ClearAssignment()
	}
	{
		token := p.state.Consume(Keyword_Colon)
		_ = token
	}
	{
		p.cp.MarkAssignment("Body")
		p.state.EnterRule(254)
		p.ParseCompositeAlternatives()
		p.state.ExitRule()
		p.cp.ClearAssignment()
	}
	{
		token := p.state.Consume(Keyword_Semicolon)
		_ = token
	}
}

func (p *CompletionParser) ParseCompositeAlternatives() {
	p.cp.EnterRule("CompositeAlternatives", 46)
	defer p.cp.ExitRule()
	{
		p.state.EnterRule(257)
		p.ParseCompositeGroup()
		p.state.ExitRule()
	}
	p.cp.RecordSnapshot(257)
	p.state.Sync(257)
	if p.state.Lookahead(CompositeAlternativesLookahead16) == 0 {
		for ok := true; ok; ok = p.state.Lookahead(CompositeAlternativesLookahead17) == 0 {
			{
				token := p.state.Consume(Keyword_Pipe)
				_ = token
			}
			{
				p.cp.MarkAssignment("Alts")
				p.state.EnterRule(259)
				p.ParseCompositeGroup()
				p.state.ExitRule()
				p.cp.ClearAssignment()
			}
			p.cp.RecordSnapshot(260)
			p.state.Sync(260)
		}
	}
}

func (p *CompletionParser) ParseCompositeGroup() {
	p.cp.EnterRule("CompositeGroup", 48)
	defer p.cp.ExitRule()
	{
		p.state.EnterRule(263)
		p.ParseCompositeElement()
		p.state.ExitRule()
	}
	p.cp.RecordSnapshot(263)
	p.state.Sync(263)
	if p.state.Lookahead(CompositeGroupLookahead18) == 0 {
		{
			for ok := true; ok; ok = p.state.Lookahead(CompositeGroupLookahead19) == 0 {
				p.cp.MarkAssignment("Elements")
				p.state.EnterRule(264)
				p.ParseCompositeElement()
				p.state.ExitRule()
				p.cp.ClearAssignment()
				p.cp.RecordSnapshot(265)
				p.state.Sync(265)
			}
		}
	}
}

func (p *CompletionParser) ParseCompositeElement() {
	p.cp.EnterRule("CompositeElement", 50)
	defer p.cp.ExitRule()
	switch p.state.Lookahead(CompositeElementLookaheadOr11) {
	case 0:
		{
			p.state.EnterRule(268)
			p.ParseKeyword()
			p.state.ExitRule()
		}
	case 1:
		{
			p.state.EnterRule(270)
			p.ParseRuleCall()
			p.state.ExitRule()
		}
	case 2:
		{
			token := p.state.Consume(Keyword_LeftParen)
			_ = token
		}
		{
			p.state.EnterRule(273)
			p.ParseCompositeAlternatives()
			p.state.ExitRule()
		}
		{
			token := p.state.Consume(Keyword_RightParen)
			_ = token
		}
	default:
		token := p.state.LA(1)
		p.state.AppendError(p.state.Messages().NoViableAlternative(token), token)
	}
	{
		p.cp.RecordSnapshot(283)
		p.state.Sync(283)
		if p.state.Lookahead(CompositeElementLookahead20) == 0 {
			p.cp.MarkAssignment("Cardinality")
			switch p.state.Lookahead(CompositeElementCardinalityLookaheadOr12) {
			case 0:
				token := p.state.Consume(Keyword_Asterisk)
				_ = token
			case 1:
				token := p.state.Consume(Keyword_Plus)
				_ = token
			case 2:
				token := p.state.Consume(Keyword_Question)
				_ = token
			}
			p.cp.ClearAssignment()
		}
	}
}
