// Code generated by typefox.dev/fastbelt/cmd/fastbelt. DO NOT EDIT.

package grammar

import (
	"encoding/json"
	"fmt"
	"reflect"

	core "typefox.dev/fastbelt"
)

func newToken(tokenType *core.TokenType, view string) *core.Token {
	token := core.NewToken(tokenType, view, 0, 0, 0, 0, 0, 0)
	return &token
}

func (i *GrammarImpl) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		T__         string          `json:"$type"`
		Name        string          `json:"name,omitempty"`
		Rules       []ParserRule    `json:"rules,omitempty"`
		Composites  []CompositeRule `json:"composites,omitempty"`
		Terminals   []Token         `json:"terminals,omitempty"`
		TokenGroups []TokenGroup    `json:"tokenGroups,omitempty"`
		Interfaces  []Interface     `json:"interfaces,omitempty"`
	}{
		T__:         "Grammar",
		Name:        i.Name(),
		Rules:       i.Rules(),
		Composites:  i.Composites(),
		Terminals:   i.Terminals(),
		TokenGroups: i.TokenGroups(),
		Interfaces:  i.Interfaces(),
	})
}

func (i *InterfaceImpl) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		T__     string                       `json:"$type"`
		Name    string                       `json:"name,omitempty"`
		Extends []*core.Reference[Interface] `json:"extends,omitempty"`
		Fields  []Field                      `json:"fields,omitempty"`
	}{
		T__:     "Interface",
		Name:    i.Name(),
		Extends: i.Extends(),
		Fields:  i.Fields(),
	})
}

func (i *FieldImpl) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		T__  string    `json:"$type"`
		Name string    `json:"name,omitempty"`
		Type FieldType `json:"type,omitempty"`
	}{
		T__:  "Field",
		Name: i.Name(),
		Type: i.Type(),
	})
}

func (i *FieldTypeImpl) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		T__ string `json:"$type"`
	}{
		T__: "FieldType",
	})
}

func (i *ArrayTypeImpl) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		T__          string    `json:"$type"`
		InternalType FieldType `json:"internalType,omitempty"`
	}{
		T__:          "ArrayType",
		InternalType: i.InternalType(),
	})
}

func (i *ReferenceTypeImpl) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		T__  string                     `json:"$type"`
		Type *core.Reference[Interface] `json:"type,omitempty"`
	}{
		T__:  "ReferenceType",
		Type: i.Type(),
	})
}

func (i *SimpleTypeImpl) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		T__  string                     `json:"$type"`
		Type *core.Reference[Interface] `json:"type,omitempty"`
	}{
		T__:  "SimpleType",
		Type: i.Type(),
	})
}

func (i *PrimitiveTypeImpl) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		T__  string `json:"$type"`
		Type string `json:"type,omitempty"`
	}{
		T__:  "PrimitiveType",
		Type: i.Type(),
	})
}

func (i *AbstractRuleImpl) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		T__  string `json:"$type"`
		Name string `json:"name,omitempty"`
	}{
		T__:  "AbstractRule",
		Name: i.Name(),
	})
}

func (i *AbstractRuleWithBodyImpl) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		T__  string  `json:"$type"`
		Name string  `json:"name,omitempty"`
		Body Element `json:"body,omitempty"`
	}{
		T__:  "AbstractRuleWithBody",
		Name: i.Name(),
		Body: i.Body(),
	})
}

func (i *AbstractTokenRuleImpl) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		T__  string `json:"$type"`
		Name string `json:"name,omitempty"`
	}{
		T__:  "AbstractTokenRule",
		Name: i.Name(),
	})
}

func (i *ParserRuleImpl) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		T__        string                     `json:"$type"`
		Name       string                     `json:"name,omitempty"`
		Body       Element                    `json:"body,omitempty"`
		Entry      bool                       `json:"entry,omitempty"`
		ReturnType *core.Reference[Interface] `json:"returnType,omitempty"`
	}{
		T__:        "ParserRule",
		Name:       i.Name(),
		Body:       i.Body(),
		Entry:      i.IsEntry(),
		ReturnType: i.ReturnType(),
	})
}

func (i *TokenImpl) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		T__    string `json:"$type"`
		Name   string `json:"name,omitempty"`
		Type   string `json:"type,omitempty"`
		Regexp string `json:"regexp,omitempty"`
	}{
		T__:    "Token",
		Name:   i.Name(),
		Type:   i.Type(),
		Regexp: i.Regexp(),
	})
}

func (i *TokenGroupImpl) MarshalJSON() ([]byte, error) {
	regexps := make([]string, len(i.Regexps()))
	for j, item := range i.Regexps() {
		regexps[j] = item.String()
	}
	return json.Marshal(struct {
		T__       string                               `json:"$type"`
		Name      string                               `json:"name,omitempty"`
		TokenRefs []*core.Reference[AbstractTokenRule] `json:"tokenRefs,omitempty"`
		Regexps   []string                             `json:"regexps,omitempty"`
		Keywords  []Keyword                            `json:"keywords,omitempty"`
	}{
		T__:       "TokenGroup",
		Name:      i.Name(),
		TokenRefs: i.TokenRefs(),
		Regexps:   regexps,
		Keywords:  i.Keywords(),
	})
}

func (i *ElementImpl) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		T__         string `json:"$type"`
		Cardinality string `json:"cardinality,omitempty"`
	}{
		T__:         "Element",
		Cardinality: i.Cardinality(),
	})
}

func (i *AlternativesImpl) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		T__         string    `json:"$type"`
		Cardinality string    `json:"cardinality,omitempty"`
		Alts        []Element `json:"alts,omitempty"`
	}{
		T__:         "Alternatives",
		Cardinality: i.Cardinality(),
		Alts:        i.Alts(),
	})
}

func (i *GroupImpl) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		T__         string    `json:"$type"`
		Cardinality string    `json:"cardinality,omitempty"`
		Elements    []Element `json:"elements,omitempty"`
	}{
		T__:         "Group",
		Cardinality: i.Cardinality(),
		Elements:    i.Elements(),
	})
}

func (i *KeywordImpl) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		T__         string `json:"$type"`
		Cardinality string `json:"cardinality,omitempty"`
		Value       string `json:"value,omitempty"`
	}{
		T__:         "Keyword",
		Cardinality: i.Cardinality(),
		Value:       i.Value(),
	})
}

func (i *AssignmentImpl) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		T__         string                 `json:"$type"`
		Cardinality string                 `json:"cardinality,omitempty"`
		Property    *core.Reference[Field] `json:"property,omitempty"`
		Operator    string                 `json:"operator,omitempty"`
		Value       Assignable             `json:"value,omitempty"`
	}{
		T__:         "Assignment",
		Cardinality: i.Cardinality(),
		Property:    i.Property(),
		Operator:    i.Operator(),
		Value:       i.Value(),
	})
}

func (i *AssignableImpl) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		T__         string `json:"$type"`
		Cardinality string `json:"cardinality,omitempty"`
	}{
		T__:         "Assignable",
		Cardinality: i.Cardinality(),
	})
}

func (i *CrossRefImpl) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		T__         string                     `json:"$type"`
		Cardinality string                     `json:"cardinality,omitempty"`
		Type        *core.Reference[Interface] `json:"type,omitempty"`
		Rule        RuleCall                   `json:"rule,omitempty"`
	}{
		T__:         "CrossRef",
		Cardinality: i.Cardinality(),
		Type:        i.Type(),
		Rule:        i.Rule(),
	})
}

func (i *RuleCallImpl) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		T__         string                        `json:"$type"`
		Cardinality string                        `json:"cardinality,omitempty"`
		Rule        *core.Reference[AbstractRule] `json:"rule,omitempty"`
	}{
		T__:         "RuleCall",
		Cardinality: i.Cardinality(),
		Rule:        i.Rule(),
	})
}

func (i *ActionImpl) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		T__         string                     `json:"$type"`
		Cardinality string                     `json:"cardinality,omitempty"`
		Type        *core.Reference[Interface] `json:"type,omitempty"`
		Operator    string                     `json:"operator,omitempty"`
		Property    *core.Reference[Field]     `json:"property,omitempty"`
	}{
		T__:         "Action",
		Cardinality: i.Cardinality(),
		Type:        i.Type(),
		Operator:    i.Operator(),
		Property:    i.Property(),
	})
}

func (i *CompositeRuleImpl) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		T__  string  `json:"$type"`
		Name string  `json:"name,omitempty"`
		Body Element `json:"body,omitempty"`
	}{
		T__:  "CompositeRule",
		Name: i.Name(),
		Body: i.Body(),
	})
}

func (i *GrammarImpl) UnmarshalJSON(data []byte) error {
	aux := &struct {
		T__         string            `json:"$type"`
		Name        string            `json:"name"`
		Rules       []json.RawMessage `json:"rules"`
		Composites  []json.RawMessage `json:"composites"`
		Terminals   []json.RawMessage `json:"terminals"`
		TokenGroups []json.RawMessage `json:"tokenGroups"`
		Interfaces  []json.RawMessage `json:"interfaces"`
	}{}
	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	i.SetName(newToken(Token_ID, aux.Name))
	i.rules = []ParserRule{}
	for _, item := range aux.Rules {
		node, err := Unmarshal[ParserRule](item)
		if err != nil {
			return err
		}
		i.SetRulesItem(node)
	}
	i.composites = []CompositeRule{}
	for _, item := range aux.Composites {
		node, err := Unmarshal[CompositeRule](item)
		if err != nil {
			return err
		}
		i.SetCompositesItem(node)
	}
	i.terminals = []Token{}
	for _, item := range aux.Terminals {
		node, err := Unmarshal[Token](item)
		if err != nil {
			return err
		}
		i.SetTerminalsItem(node)
	}
	i.tokenGroups = []TokenGroup{}
	for _, item := range aux.TokenGroups {
		node, err := Unmarshal[TokenGroup](item)
		if err != nil {
			return err
		}
		i.SetTokenGroupsItem(node)
	}
	i.interfaces = []Interface{}
	for _, item := range aux.Interfaces {
		node, err := Unmarshal[Interface](item)
		if err != nil {
			return err
		}
		i.SetInterfacesItem(node)
	}
	return nil
}

func (i *InterfaceImpl) UnmarshalJSON(data []byte) error {
	aux := &struct {
		T__     string            `json:"$type"`
		Name    string            `json:"name"`
		Extends []json.RawMessage `json:"extends"`
		Fields  []json.RawMessage `json:"fields"`
	}{}
	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	i.SetName(newToken(Token_ID, aux.Name))
	i.extends = []*core.Reference[Interface]{}
	for _, item := range aux.Extends {
		node := core.NewReference[Interface](i, nil, nil)
		if err := node.UnmarshalJSON(item); err != nil {
			return err
		}
		i.SetExtendsItem(node)
	}
	i.fields = []Field{}
	for _, item := range aux.Fields {
		node, err := Unmarshal[Field](item)
		if err != nil {
			return err
		}
		i.SetFieldsItem(node)
	}
	return nil
}

func (i *FieldImpl) UnmarshalJSON(data []byte) error {
	aux := &struct {
		T__  string          `json:"$type"`
		Name string          `json:"name"`
		Type json.RawMessage `json:"type"`
	}{}
	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	i.SetName(newToken(Token_ID, aux.Name))
	if aux.Type != nil {
		_Type, err := Unmarshal[FieldType](aux.Type)
		if err != nil {
			return err
		}
		i.SetType(_Type)
	}
	return nil
}

func (i *FieldTypeImpl) UnmarshalJSON(data []byte) error {
	return nil
}

func (i *ArrayTypeImpl) UnmarshalJSON(data []byte) error {
	aux := &struct {
		T__          string          `json:"$type"`
		InternalType json.RawMessage `json:"internalType"`
	}{}
	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	if aux.InternalType != nil {
		internalType, err := Unmarshal[FieldType](aux.InternalType)
		if err != nil {
			return err
		}
		i.SetInternalType(internalType)
	}
	return nil
}

func (i *ReferenceTypeImpl) UnmarshalJSON(data []byte) error {
	aux := &struct {
		T__  string          `json:"$type"`
		Type json.RawMessage `json:"type"`
	}{}
	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	if aux.Type != nil {
		_Type := core.NewReference[Interface](i, nil, nil)
		if err := _Type.UnmarshalJSON(aux.Type); err != nil {
			return err
		}
		i.SetType(_Type)
	}
	return nil
}

func (i *SimpleTypeImpl) UnmarshalJSON(data []byte) error {
	aux := &struct {
		T__  string          `json:"$type"`
		Type json.RawMessage `json:"type"`
	}{}
	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	if aux.Type != nil {
		_Type := core.NewReference[Interface](i, nil, nil)
		if err := _Type.UnmarshalJSON(aux.Type); err != nil {
			return err
		}
		i.SetType(_Type)
	}
	return nil
}

func (i *PrimitiveTypeImpl) UnmarshalJSON(data []byte) error {
	aux := &struct {
		T__  string `json:"$type"`
		Type string `json:"type"`
	}{}
	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	i.SetType(newToken(Token_ID, aux.Type))
	return nil
}

func (i *AbstractRuleImpl) UnmarshalJSON(data []byte) error {
	aux := &struct {
		T__  string `json:"$type"`
		Name string `json:"name"`
	}{}
	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	i.SetName(newToken(Token_ID, aux.Name))
	return nil
}

func (i *AbstractRuleWithBodyImpl) UnmarshalJSON(data []byte) error {
	aux := &struct {
		T__  string          `json:"$type"`
		Name string          `json:"name"`
		Body json.RawMessage `json:"body"`
	}{}
	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	i.SetName(newToken(Token_ID, aux.Name))
	if aux.Body != nil {
		body, err := Unmarshal[Element](aux.Body)
		if err != nil {
			return err
		}
		i.SetBody(body)
	}
	return nil
}

func (i *AbstractTokenRuleImpl) UnmarshalJSON(data []byte) error {
	aux := &struct {
		T__  string `json:"$type"`
		Name string `json:"name"`
	}{}
	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	i.SetName(newToken(Token_ID, aux.Name))
	return nil
}

func (i *ParserRuleImpl) UnmarshalJSON(data []byte) error {
	aux := &struct {
		T__        string          `json:"$type"`
		Name       string          `json:"name"`
		Body       json.RawMessage `json:"body"`
		Entry      bool            `json:"entry"`
		ReturnType json.RawMessage `json:"returnType"`
	}{}
	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	i.SetName(newToken(Token_ID, aux.Name))
	if aux.Body != nil {
		body, err := Unmarshal[Element](aux.Body)
		if err != nil {
			return err
		}
		i.SetBody(body)
	}
	if aux.Entry {
		i.SetEntry(newToken(Token_ID, ""))
	}
	if aux.ReturnType != nil {
		returnType := core.NewReference[Interface](i, nil, nil)
		if err := returnType.UnmarshalJSON(aux.ReturnType); err != nil {
			return err
		}
		i.SetReturnType(returnType)
	}
	return nil
}

func (i *TokenImpl) UnmarshalJSON(data []byte) error {
	aux := &struct {
		T__    string `json:"$type"`
		Name   string `json:"name"`
		Type   string `json:"type"`
		Regexp string `json:"regexp"`
	}{}
	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	i.SetName(newToken(Token_ID, aux.Name))
	i.SetType(newToken(Token_ID, aux.Type))
	i.SetRegexp(newToken(Token_ID, aux.Regexp))
	return nil
}

func (i *TokenGroupImpl) UnmarshalJSON(data []byte) error {
	aux := &struct {
		T__       string            `json:"$type"`
		Name      string            `json:"name"`
		TokenRefs []json.RawMessage `json:"tokenRefs"`
		Regexps   []string          `json:"regexps"`
		Keywords  []json.RawMessage `json:"keywords"`
	}{}
	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	i.SetName(newToken(Token_ID, aux.Name))
	i.tokenRefs = []*core.Reference[AbstractTokenRule]{}
	for _, item := range aux.TokenRefs {
		node := core.NewReference[AbstractTokenRule](i, nil, nil)
		if err := node.UnmarshalJSON(item); err != nil {
			return err
		}
		i.SetTokenRefsItem(node)
	}
	i.regexps = []*core.Token{}
	for _, item := range aux.Regexps {
		i.SetRegexpsItem(newToken(Token_ID, item))
	}
	i.keywords = []Keyword{}
	for _, item := range aux.Keywords {
		node, err := Unmarshal[Keyword](item)
		if err != nil {
			return err
		}
		i.SetKeywordsItem(node)
	}
	return nil
}

func (i *ElementImpl) UnmarshalJSON(data []byte) error {
	aux := &struct {
		T__         string `json:"$type"`
		Cardinality string `json:"cardinality"`
	}{}
	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	i.SetCardinality(newToken(Token_ID, aux.Cardinality))
	return nil
}

func (i *AlternativesImpl) UnmarshalJSON(data []byte) error {
	aux := &struct {
		T__         string            `json:"$type"`
		Cardinality string            `json:"cardinality"`
		Alts        []json.RawMessage `json:"alts"`
	}{}
	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	i.SetCardinality(newToken(Token_ID, aux.Cardinality))
	i.alts = []Element{}
	for _, item := range aux.Alts {
		node, err := Unmarshal[Element](item)
		if err != nil {
			return err
		}
		i.SetAltsItem(node)
	}
	return nil
}

func (i *GroupImpl) UnmarshalJSON(data []byte) error {
	aux := &struct {
		T__         string            `json:"$type"`
		Cardinality string            `json:"cardinality"`
		Elements    []json.RawMessage `json:"elements"`
	}{}
	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	i.SetCardinality(newToken(Token_ID, aux.Cardinality))
	i.elements = []Element{}
	for _, item := range aux.Elements {
		node, err := Unmarshal[Element](item)
		if err != nil {
			return err
		}
		i.SetElementsItem(node)
	}
	return nil
}

func (i *KeywordImpl) UnmarshalJSON(data []byte) error {
	aux := &struct {
		T__         string `json:"$type"`
		Cardinality string `json:"cardinality"`
		Value       string `json:"value"`
	}{}
	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	i.SetCardinality(newToken(Token_ID, aux.Cardinality))
	i.SetValue(newToken(Token_ID, aux.Value))
	return nil
}

func (i *AssignmentImpl) UnmarshalJSON(data []byte) error {
	aux := &struct {
		T__         string          `json:"$type"`
		Cardinality string          `json:"cardinality"`
		Property    json.RawMessage `json:"property"`
		Operator    string          `json:"operator"`
		Value       json.RawMessage `json:"value"`
	}{}
	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	i.SetCardinality(newToken(Token_ID, aux.Cardinality))
	if aux.Property != nil {
		property := core.NewReference[Field](i, nil, nil)
		if err := property.UnmarshalJSON(aux.Property); err != nil {
			return err
		}
		i.SetProperty(property)
	}
	i.SetOperator(newToken(Token_ID, aux.Operator))
	if aux.Value != nil {
		value, err := Unmarshal[Assignable](aux.Value)
		if err != nil {
			return err
		}
		i.SetValue(value)
	}
	return nil
}

func (i *AssignableImpl) UnmarshalJSON(data []byte) error {
	aux := &struct {
		T__         string `json:"$type"`
		Cardinality string `json:"cardinality"`
	}{}
	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	i.SetCardinality(newToken(Token_ID, aux.Cardinality))
	return nil
}

func (i *CrossRefImpl) UnmarshalJSON(data []byte) error {
	aux := &struct {
		T__         string          `json:"$type"`
		Cardinality string          `json:"cardinality"`
		Type        json.RawMessage `json:"type"`
		Rule        json.RawMessage `json:"rule"`
	}{}
	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	i.SetCardinality(newToken(Token_ID, aux.Cardinality))
	if aux.Type != nil {
		_Type := core.NewReference[Interface](i, nil, nil)
		if err := _Type.UnmarshalJSON(aux.Type); err != nil {
			return err
		}
		i.SetType(_Type)
	}
	if aux.Rule != nil {
		rule, err := Unmarshal[RuleCall](aux.Rule)
		if err != nil {
			return err
		}
		i.SetRule(rule)
	}
	return nil
}

func (i *RuleCallImpl) UnmarshalJSON(data []byte) error {
	aux := &struct {
		T__         string          `json:"$type"`
		Cardinality string          `json:"cardinality"`
		Rule        json.RawMessage `json:"rule"`
	}{}
	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	i.SetCardinality(newToken(Token_ID, aux.Cardinality))
	if aux.Rule != nil {
		rule := core.NewReference[AbstractRule](i, nil, nil)
		if err := rule.UnmarshalJSON(aux.Rule); err != nil {
			return err
		}
		i.SetRule(rule)
	}
	return nil
}

func (i *ActionImpl) UnmarshalJSON(data []byte) error {
	aux := &struct {
		T__         string          `json:"$type"`
		Cardinality string          `json:"cardinality"`
		Type        json.RawMessage `json:"type"`
		Operator    string          `json:"operator"`
		Property    json.RawMessage `json:"property"`
	}{}
	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	i.SetCardinality(newToken(Token_ID, aux.Cardinality))
	if aux.Type != nil {
		_Type := core.NewReference[Interface](i, nil, nil)
		if err := _Type.UnmarshalJSON(aux.Type); err != nil {
			return err
		}
		i.SetType(_Type)
	}
	i.SetOperator(newToken(Token_ID, aux.Operator))
	if aux.Property != nil {
		property := core.NewReference[Field](i, nil, nil)
		if err := property.UnmarshalJSON(aux.Property); err != nil {
			return err
		}
		i.SetProperty(property)
	}
	return nil
}

func (i *CompositeRuleImpl) UnmarshalJSON(data []byte) error {
	aux := &struct {
		T__  string          `json:"$type"`
		Name string          `json:"name"`
		Body json.RawMessage `json:"body"`
	}{}
	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	i.SetName(newToken(Token_ID, aux.Name))
	if aux.Body != nil {
		body, err := Unmarshal[Element](aux.Body)
		if err != nil {
			return err
		}
		i.SetBody(body)
	}
	return nil
}

// Unmarshal decodes data into an instance of type T by reading the "$type" field,
// selecting a corresponding factory, creating an instance, and unmarshaling its content.
func Unmarshal[T core.AstNode](data []byte) (T, error) {
	node := &struct {
		Type string `json:"$type"`
	}{}
	if err := json.Unmarshal(data, node); err != nil {
		var zero T
		return zero, fmt.Errorf("unmarshal: %w", err)
	}
	factory, ok := FastbeltSyntheticFactories[node.Type]
	if !ok {
		var zero T
		return zero, fmt.Errorf("unmarshal: unknown type %q", node.Type)
	}
	instance := factory()
	asT, ok := instance.(T)
	if !ok {
		var zero T
		return zero, fmt.Errorf("unmarshal: %T is not convertible to type %s", instance, reflect.TypeFor[T]())
	}
	if unmarshaler, ok := instance.(json.Unmarshaler); ok {
		if err := unmarshaler.UnmarshalJSON(data); err != nil {
			var zero T
			return zero, fmt.Errorf("unmarshal %s: %w", node.Type, err)
		}
	} else {
		var zero T
		return zero, fmt.Errorf("unmarshal: %T is not convertible to type json.Unmarshaler", instance)
	}
	return asT, nil
}
