// Code generated by typefox.dev/fastbelt/cmd/fastbelt. DO NOT EDIT.

package grammar

import (
	core "typefox.dev/fastbelt"
	"typefox.dev/fastbelt/parser"
)

const (
	DecisionCompositeGroupElementsLoop = 34
	DecisionCompositeGroupOptional     = 35
	DecisionElementAlternatives        = 20
	DecisionGrammarAlternatives        = 1
	DecisionGroupElementsLoop          = 18
	DecisionGroupOptional              = 19
)

var ActionOperatorAlternatives = parser.LL1Lookahead{
	Types:  []*core.TokenType{Keyword_PlusEquals, Keyword_Equals},
	Lookup: []int{5: 1, 10: 2},
}

var AssignableAlternatives = parser.LL1Lookahead{
	Types:  []*core.TokenType{Token_StringLiteral, Token_ID, Keyword_LeftBracket, Keyword_LeftParen},
	Lookup: []int{1: 4, 13: 3, 34: 1, 35: 2},
}

var AssignableWithoutAltsAlternatives = parser.LL1Lookahead{
	Types:  []*core.TokenType{Token_StringLiteral, Token_ID, Keyword_LeftBracket},
	Lookup: []int{13: 3, 34: 1, 35: 2},
}

var AssignmentOperatorAlternatives = parser.LL1Lookahead{
	Types:  []*core.TokenType{Keyword_PlusEquals, Keyword_Equals, Keyword_QuestionEquals},
	Lookup: []int{5: 1, 10: 2, 12: 3},
}

var CompositeElementAlternatives = parser.LL1Lookahead{
	Types:  []*core.TokenType{Token_StringLiteral, Token_ID, Keyword_LeftParen},
	Lookup: []int{1: 3, 34: 1, 35: 2},
}

var CompositeElementCardinalityAlternatives = parser.LL1Lookahead{
	Types:  []*core.TokenType{Keyword_Asterisk, Keyword_Plus, Keyword_Question},
	Lookup: []int{3: 1, 4: 2, 11: 3},
}

var ElementCardinalityAlternatives = parser.LL1Lookahead{
	Types:  []*core.TokenType{Keyword_Asterisk, Keyword_Plus, Keyword_Question},
	Lookup: []int{3: 1, 4: 2, 11: 3},
}

var FieldTypeAlternatives = parser.LL1Lookahead{
	Types:  []*core.TokenType{Token_ID, Keyword_Asterisk, Keyword_LeftBracket, Keyword_bool, Keyword_composite, Keyword_string},
	Lookup: []int{3: 2, 13: 3, 15: 4, 17: 4, 27: 4, 35: 1},
}

var GrammarLoop = parser.LL1Lookahead{
	Types:  []*core.TokenType{Keyword_comment, Keyword_composite, Keyword_entry, Keyword_hidden, Keyword_interface, Keyword_token, Token_ID},
	Lookup: []int{16: 1, 17: 1, 19: 1, 23: 1, 24: 1, 28: 1, 35: 1},
}

var PrimitiveTypeTypeAlternatives = parser.LL1Lookahead{
	Types:  []*core.TokenType{Keyword_string, Keyword_bool, Keyword_composite},
	Lookup: []int{15: 2, 17: 3, 27: 1},
}

var TokenAlternatives = parser.LL1Lookahead{
	Types:  []*core.TokenType{Keyword_hidden, Keyword_comment},
	Lookup: []int{16: 2, 23: 1},
}

var TokenGroupAlternatives = parser.LL1Lookahead{
	Types:  []*core.TokenType{Token_ID, Keyword_keywords, Token_StringLiteral},
	Lookup: []int{25: 2, 34: 3, 35: 1},
}

// FastbeltParserLookahead abstracts every lookahead/prediction decision performed by
// the generated parser. Each method corresponds to a single decision point;
// implementations may override individual decisions while delegating the rest
// to DefaultFastbeltParserLookahead.
type FastbeltParserLookahead interface {
	parser.ParserLookahead

	ActionOperatorAlternatives(state *parser.ParserState) (int, *parser.PredictionFailure)
	ActionOptional(state *parser.ParserState) bool
	AlternativesLoop(state *parser.ParserState) bool
	AlternativesOptional(state *parser.ParserState) bool
	AssignableAlternatives(state *parser.ParserState) (int, *parser.PredictionFailure)
	AssignableAlternativesLoop(state *parser.ParserState) bool
	AssignableAlternativesOptional(state *parser.ParserState) bool
	AssignableWithoutAltsAlternatives(state *parser.ParserState) (int, *parser.PredictionFailure)
	AssignmentOperatorAlternatives(state *parser.ParserState) (int, *parser.PredictionFailure)
	CompositeAlternativesLoop(state *parser.ParserState) bool
	CompositeAlternativesOptional(state *parser.ParserState) bool
	CompositeElementAlternatives(state *parser.ParserState) (int, *parser.PredictionFailure)
	CompositeElementCardinalityAlternatives(state *parser.ParserState) (int, *parser.PredictionFailure)
	CompositeGroupElementsLoop(state *parser.ParserState) bool
	CompositeGroupOptional(state *parser.ParserState) bool
	CompositeRuleSemicolonOptional(state *parser.ParserState) bool
	CrossRefOptional(state *parser.ParserState) bool
	ElementAlternatives(state *parser.ParserState) (int, *parser.PredictionFailure)
	ElementCardinalityAlternatives(state *parser.ParserState) (int, *parser.PredictionFailure)
	FieldTypeAlternatives(state *parser.ParserState) (int, *parser.PredictionFailure)
	GrammarAlternatives(state *parser.ParserState) (int, *parser.PredictionFailure)
	GrammarLoop(state *parser.ParserState) bool
	GrammarSemicolonOptional(state *parser.ParserState) bool
	GroupElementsLoop(state *parser.ParserState) bool
	GroupOptional(state *parser.ParserState) bool
	InterfaceFieldsLoop(state *parser.ParserState) bool
	InterfaceLoop(state *parser.ParserState) bool
	InterfaceOptional(state *parser.ParserState) bool
	ParserRuleEntryOptional(state *parser.ParserState) bool
	ParserRuleOptional(state *parser.ParserState) bool
	ParserRuleSemicolonOptional(state *parser.ParserState) bool
	PrimitiveTypeTypeAlternatives(state *parser.ParserState) (int, *parser.PredictionFailure)
	TokenAlternatives(state *parser.ParserState) (int, *parser.PredictionFailure)
	TokenGroupAlternatives(state *parser.ParserState) (int, *parser.PredictionFailure)
	TokenSemicolonOptional(state *parser.ParserState) bool
}

// DefaultFastbeltParserLookahead resolves every decision with the parser state's built-in
// static LL(1) and adaptive ALL(*) prediction.
type DefaultFastbeltParserLookahead struct {
	parser.DefaultParserLookahead
}

func NewDefaultFastbeltParserLookahead() FastbeltParserLookahead {
	return &DefaultFastbeltParserLookahead{}
}

func (l *DefaultFastbeltParserLookahead) ActionOperatorAlternatives(state *parser.ParserState) (int, *parser.PredictionFailure) {
	return state.Lookahead(ActionOperatorAlternatives)
}

func (l *DefaultFastbeltParserLookahead) ActionOptional(state *parser.ParserState) bool {
	return state.LA(1).Type == Keyword_Dot
}

func (l *DefaultFastbeltParserLookahead) AlternativesLoop(state *parser.ParserState) bool {
	return state.LA(1).Type == Keyword_Pipe
}

func (l *DefaultFastbeltParserLookahead) AlternativesOptional(state *parser.ParserState) bool {
	return state.LA(1).Type == Keyword_Pipe
}

func (l *DefaultFastbeltParserLookahead) AssignableAlternatives(state *parser.ParserState) (int, *parser.PredictionFailure) {
	return state.Lookahead(AssignableAlternatives)
}

func (l *DefaultFastbeltParserLookahead) AssignableAlternativesLoop(state *parser.ParserState) bool {
	return state.LA(1).Type == Keyword_Pipe
}

func (l *DefaultFastbeltParserLookahead) AssignableAlternativesOptional(state *parser.ParserState) bool {
	return state.LA(1).Type == Keyword_Pipe
}

func (l *DefaultFastbeltParserLookahead) AssignableWithoutAltsAlternatives(state *parser.ParserState) (int, *parser.PredictionFailure) {
	return state.Lookahead(AssignableWithoutAltsAlternatives)
}

func (l *DefaultFastbeltParserLookahead) AssignmentOperatorAlternatives(state *parser.ParserState) (int, *parser.PredictionFailure) {
	return state.Lookahead(AssignmentOperatorAlternatives)
}

func (l *DefaultFastbeltParserLookahead) CompositeAlternativesLoop(state *parser.ParserState) bool {
	return state.LA(1).Type == Keyword_Pipe
}

func (l *DefaultFastbeltParserLookahead) CompositeAlternativesOptional(state *parser.ParserState) bool {
	return state.LA(1).Type == Keyword_Pipe
}

func (l *DefaultFastbeltParserLookahead) CompositeElementAlternatives(state *parser.ParserState) (int, *parser.PredictionFailure) {
	return state.Lookahead(CompositeElementAlternatives)
}

func (l *DefaultFastbeltParserLookahead) CompositeElementCardinalityAlternatives(state *parser.ParserState) (int, *parser.PredictionFailure) {
	return state.Lookahead(CompositeElementCardinalityAlternatives)
}

func (l *DefaultFastbeltParserLookahead) CompositeGroupElementsLoop(state *parser.ParserState) bool {
	prediction, _ := state.AdaptivePredict(DecisionCompositeGroupElementsLoop, l.PredictionMode())
	return prediction == 0
}

func (l *DefaultFastbeltParserLookahead) CompositeGroupOptional(state *parser.ParserState) bool {
	prediction, _ := state.AdaptivePredict(DecisionCompositeGroupOptional, l.PredictionMode())
	return prediction == 0
}

func (l *DefaultFastbeltParserLookahead) CompositeRuleSemicolonOptional(state *parser.ParserState) bool {
	return state.LA(1).Type == Keyword_Semicolon
}

func (l *DefaultFastbeltParserLookahead) CrossRefOptional(state *parser.ParserState) bool {
	return state.LA(1).Type == Keyword_Colon
}

func (l *DefaultFastbeltParserLookahead) ElementAlternatives(state *parser.ParserState) (int, *parser.PredictionFailure) {
	return state.AdaptivePredict(DecisionElementAlternatives, l.PredictionMode())
}

func (l *DefaultFastbeltParserLookahead) ElementCardinalityAlternatives(state *parser.ParserState) (int, *parser.PredictionFailure) {
	return state.Lookahead(ElementCardinalityAlternatives)
}

func (l *DefaultFastbeltParserLookahead) FieldTypeAlternatives(state *parser.ParserState) (int, *parser.PredictionFailure) {
	return state.Lookahead(FieldTypeAlternatives)
}

func (l *DefaultFastbeltParserLookahead) GrammarAlternatives(state *parser.ParserState) (int, *parser.PredictionFailure) {
	return state.AdaptivePredict(DecisionGrammarAlternatives, l.PredictionMode())
}

func (l *DefaultFastbeltParserLookahead) GrammarLoop(state *parser.ParserState) bool {
	prediction, _ := state.Lookahead(GrammarLoop)
	return prediction == 0
}

func (l *DefaultFastbeltParserLookahead) GrammarSemicolonOptional(state *parser.ParserState) bool {
	return state.LA(1).Type == Keyword_Semicolon
}

func (l *DefaultFastbeltParserLookahead) GroupElementsLoop(state *parser.ParserState) bool {
	prediction, _ := state.AdaptivePredict(DecisionGroupElementsLoop, l.PredictionMode())
	return prediction == 0
}

func (l *DefaultFastbeltParserLookahead) GroupOptional(state *parser.ParserState) bool {
	prediction, _ := state.AdaptivePredict(DecisionGroupOptional, l.PredictionMode())
	return prediction == 0
}

func (l *DefaultFastbeltParserLookahead) InterfaceFieldsLoop(state *parser.ParserState) bool {
	return state.LA(1).Type == Token_ID
}

func (l *DefaultFastbeltParserLookahead) InterfaceLoop(state *parser.ParserState) bool {
	return state.LA(1).Type == Keyword_Comma
}

func (l *DefaultFastbeltParserLookahead) InterfaceOptional(state *parser.ParserState) bool {
	return state.LA(1).Type == Keyword_extends
}

func (l *DefaultFastbeltParserLookahead) ParserRuleEntryOptional(state *parser.ParserState) bool {
	return state.LA(1).Type == Keyword_entry
}

func (l *DefaultFastbeltParserLookahead) ParserRuleOptional(state *parser.ParserState) bool {
	return state.LA(1).Type == Keyword_returns
}

func (l *DefaultFastbeltParserLookahead) ParserRuleSemicolonOptional(state *parser.ParserState) bool {
	return state.LA(1).Type == Keyword_Semicolon
}

func (l *DefaultFastbeltParserLookahead) PrimitiveTypeTypeAlternatives(state *parser.ParserState) (int, *parser.PredictionFailure) {
	return state.Lookahead(PrimitiveTypeTypeAlternatives)
}

func (l *DefaultFastbeltParserLookahead) TokenAlternatives(state *parser.ParserState) (int, *parser.PredictionFailure) {
	return state.Lookahead(TokenAlternatives)
}

func (l *DefaultFastbeltParserLookahead) TokenGroupAlternatives(state *parser.ParserState) (int, *parser.PredictionFailure) {
	return state.Lookahead(TokenGroupAlternatives)
}

func (l *DefaultFastbeltParserLookahead) TokenSemicolonOptional(state *parser.ParserState) bool {
	return state.LA(1).Type == Keyword_Semicolon
}
