// Code generated by typefox.dev/fastbelt/cmd/fastbelt. DO NOT EDIT.

package grammar

import (
	core "typefox.dev/fastbelt"
	"typefox.dev/fastbelt/lexer"
	"typefox.dev/fastbelt/parser"
	"typefox.dev/fastbelt/util/service"
)

// SetupGeneratedServices sets up the generated services for this grammar.
// If any service is already set, it's not overwritten.
func SetupGeneratedServices(sc *service.Container) {
	if !service.Has[FastbeltScopeProvider](sc) {
		service.MustPut(sc, NewDefaultFastbeltScopeProvider(sc))
	}
	if !service.Has[FastbeltReferenceLinker](sc) {
		service.MustPut(sc, NewDefaultFastbeltReferenceLinker(sc))
	}
	if !service.Has[FastbeltReferencesConstructor](sc) {
		service.MustPut(sc, NewDefaultFastbeltReferencesConstructor(sc))
	}
	if !service.Has[lexer.Lexer](sc) {
		service.MustPut[lexer.Lexer](sc, NewLexer())
	}
	if !service.Has[parser.Parser](sc) {
		service.MustPut[parser.Parser](sc, NewParser(sc))
	}
	if !service.Has[core.SymbolContainers](sc) {
		service.MustPut[core.SymbolContainers](sc, NewSymbolContainers())
	}
}
