// Code generated by typefox.dev/fastbelt/cmd/fastbelt. DO NOT EDIT.

package completion

import (
	"encoding/json"

	core "typefox.dev/fastbelt"
)

func (i *ObjData) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		T__ string `json:"$type"`
	}{
		T__: "Obj",
	})
}

func (i *RootData) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		T__     string `json:"$type"`
		Objects []Obj  `json:"objects"`
	}{
		T__:     "Root",
		Objects: i.Objects(),
	})
}

func (i *DeclareData) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		T__      string    `json:"$type"`
		Name     string    `json:"name"`
		Children []Declare `json:"children"`
	}{
		T__:      "Declare",
		Name:     i.Name(),
		Children: i.Children(),
	})
}

func (i *EData) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		T__ string                   `json:"$type"`
		Ref *core.Reference[Declare] `json:"ref"`
	}{
		T__: "E",
		Ref: i.Ref(),
	})
}

func (i *FData) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		T__   string  `json:"$type"`
		Items []FItem `json:"items"`
	}{
		T__:   "F",
		Items: i.Items(),
	})
}

func (i *FItemData) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		T__ string                   `json:"$type"`
		Ref *core.Reference[Declare] `json:"ref"`
	}{
		T__: "FItem",
		Ref: i.Ref(),
	})
}

func (i *GData) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		T__ string                   `json:"$type"`
		Ref *core.Reference[Declare] `json:"ref"`
	}{
		T__: "G",
		Ref: i.Ref(),
	})
}

func (i *HData) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		T__    string     `json:"$type"`
		Member MemberCall `json:"member"`
	}{
		T__:    "H",
		Member: i.Member(),
	})
}

func (i *MemberCallData) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		T__      string                   `json:"$type"`
		Ref      *core.Reference[Declare] `json:"ref"`
		Previous MemberCall               `json:"previous"`
	}{
		T__:      "MemberCall",
		Ref:      i.Ref(),
		Previous: i.Previous(),
	})
}

func (i *JData) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		T__ string                   `json:"$type"`
		Ref *core.Reference[Declare] `json:"ref"`
	}{
		T__: "J",
		Ref: i.Ref(),
	})
}

func (i *KData) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		T__  string                   `json:"$type"`
		Ref1 *core.Reference[Declare] `json:"ref1"`
		Ref2 *core.Reference[Declare] `json:"ref2"`
	}{
		T__:  "K",
		Ref1: i.Ref1(),
		Ref2: i.Ref2(),
	})
}

func (i *ObjData) UnmarshalJSON(data []byte) error {
	aux := &struct {
		T__ string `json:"$type"`
	}{}
	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	return nil
}

func (i *RootData) UnmarshalJSON(data []byte) error {
	aux := &struct {
		T__     string     `json:"$type"`
		Objects []*ObjImpl `json:"objects"`
	}{}
	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	i.objects = []Obj{}
	for _, item := range aux.Objects {
		i.SetObjectsItem(item)
	}
	return nil
}

func (i *DeclareData) UnmarshalJSON(data []byte) error {
	aux := &struct {
		T__      string         `json:"$type"`
		Name     string         `json:"name"`
		Children []*DeclareImpl `json:"children"`
	}{}
	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	var cn core.CompositeNode
	cn = core.NewCompositeNode()
	cn.SetToken(&core.Token{Image: aux.Name})
	i.SetName(cn)
	i.children = []Declare{}
	for _, item := range aux.Children {
		i.SetChildrenItem(item)
	}
	return nil
}

func (i *EData) UnmarshalJSON(data []byte) error {
	aux := &struct {
		T__ string                   `json:"$type"`
		Ref *core.Reference[Declare] `json:"ref"`
	}{}
	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	i.SetRef(aux.Ref)
	return nil
}

func (i *FData) UnmarshalJSON(data []byte) error {
	aux := &struct {
		T__   string       `json:"$type"`
		Items []*FItemImpl `json:"items"`
	}{}
	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	i.items = []FItem{}
	for _, item := range aux.Items {
		i.SetItemsItem(item)
	}
	return nil
}

func (i *FItemData) UnmarshalJSON(data []byte) error {
	aux := &struct {
		T__ string                   `json:"$type"`
		Ref *core.Reference[Declare] `json:"ref"`
	}{}
	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	i.SetRef(aux.Ref)
	return nil
}

func (i *GData) UnmarshalJSON(data []byte) error {
	aux := &struct {
		T__ string                   `json:"$type"`
		Ref *core.Reference[Declare] `json:"ref"`
	}{}
	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	i.SetRef(aux.Ref)
	return nil
}

func (i *HData) UnmarshalJSON(data []byte) error {
	aux := &struct {
		T__    string          `json:"$type"`
		Member *MemberCallImpl `json:"member"`
	}{}
	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	i.SetMember(aux.Member)
	return nil
}

func (i *MemberCallData) UnmarshalJSON(data []byte) error {
	aux := &struct {
		T__      string                   `json:"$type"`
		Ref      *core.Reference[Declare] `json:"ref"`
		Previous *MemberCallImpl          `json:"previous"`
	}{}
	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	i.SetRef(aux.Ref)
	i.SetPrevious(aux.Previous)
	return nil
}

func (i *JData) UnmarshalJSON(data []byte) error {
	aux := &struct {
		T__ string                   `json:"$type"`
		Ref *core.Reference[Declare] `json:"ref"`
	}{}
	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	i.SetRef(aux.Ref)
	return nil
}

func (i *KData) UnmarshalJSON(data []byte) error {
	aux := &struct {
		T__  string                   `json:"$type"`
		Ref1 *core.Reference[Declare] `json:"ref1"`
		Ref2 *core.Reference[Declare] `json:"ref2"`
	}{}
	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	i.SetRef1(aux.Ref1)
	i.SetRef2(aux.Ref2)
	return nil
}
