// Code generated by typefox.dev/fastbelt/cmd/fastbelt. DO NOT EDIT.

package completion

import (
	"strings"
	core "typefox.dev/fastbelt"
	"typefox.dev/fastbelt/lexer"
	"unicode/utf8"
)

const Keyword_Dot_Idx = 1

var Keyword_Dot = core.NewTokenType(
	Keyword_Dot_Idx,
	".",
	".",
	core.TokenKindKeyword,
	func(text string, offset int) int {
		if strings.HasPrefix(text[offset:], ".") {
			return 1
		}
		return 0
	},
	[]rune{'.'},
)

const Keyword_a_Idx = 2

var Keyword_a = core.NewTokenType(
	Keyword_a_Idx,
	"a",
	"a",
	core.TokenKindKeyword,
	func(text string, offset int) int {
		if strings.HasPrefix(text[offset:], "a") {
			return 1
		}
		return 0
	},
	[]rune{'a'},
)

const Keyword_and_Idx = 3

var Keyword_and = core.NewTokenType(
	Keyword_and_Idx,
	"and",
	"and",
	core.TokenKindKeyword,
	func(text string, offset int) int {
		if strings.HasPrefix(text[offset:], "and") {
			return 3
		}
		return 0
	},
	[]rune{'a'},
)

const Keyword_b_Idx = 4

var Keyword_b = core.NewTokenType(
	Keyword_b_Idx,
	"b",
	"b",
	core.TokenKindKeyword,
	func(text string, offset int) int {
		if strings.HasPrefix(text[offset:], "b") {
			return 1
		}
		return 0
	},
	[]rune{'b'},
)

const Keyword_c_Idx = 5

var Keyword_c = core.NewTokenType(
	Keyword_c_Idx,
	"c",
	"c",
	core.TokenKindKeyword,
	func(text string, offset int) int {
		if strings.HasPrefix(text[offset:], "c") {
			return 1
		}
		return 0
	},
	[]rune{'c'},
)

const Keyword_common_Idx = 6

var Keyword_common = core.NewTokenType(
	Keyword_common_Idx,
	"common",
	"common",
	core.TokenKindKeyword,
	func(text string, offset int) int {
		if strings.HasPrefix(text[offset:], "common") {
			return 6
		}
		return 0
	},
	[]rune{'c'},
)

const Keyword_d_Idx = 7

var Keyword_d = core.NewTokenType(
	Keyword_d_Idx,
	"d",
	"d",
	core.TokenKindKeyword,
	func(text string, offset int) int {
		if strings.HasPrefix(text[offset:], "d") {
			return 1
		}
		return 0
	},
	[]rune{'d'},
)

const Keyword_declare_Idx = 8

var Keyword_declare = core.NewTokenType(
	Keyword_declare_Idx,
	"declare",
	"declare",
	core.TokenKindKeyword,
	func(text string, offset int) int {
		if strings.HasPrefix(text[offset:], "declare") {
			return 7
		}
		return 0
	},
	[]rune{'d'},
)

const Keyword_e_Idx = 9

var Keyword_e = core.NewTokenType(
	Keyword_e_Idx,
	"e",
	"e",
	core.TokenKindKeyword,
	func(text string, offset int) int {
		if strings.HasPrefix(text[offset:], "e") {
			return 1
		}
		return 0
	},
	[]rune{'e'},
)

const Keyword_end_Idx = 10

var Keyword_end = core.NewTokenType(
	Keyword_end_Idx,
	"end",
	"end",
	core.TokenKindKeyword,
	func(text string, offset int) int {
		if strings.HasPrefix(text[offset:], "end") {
			return 3
		}
		return 0
	},
	[]rune{'e'},
)

const Keyword_f_Idx = 11

var Keyword_f = core.NewTokenType(
	Keyword_f_Idx,
	"f",
	"f",
	core.TokenKindKeyword,
	func(text string, offset int) int {
		if strings.HasPrefix(text[offset:], "f") {
			return 1
		}
		return 0
	},
	[]rune{'f'},
)

const Keyword_first_Idx = 12

var Keyword_first = core.NewTokenType(
	Keyword_first_Idx,
	"first",
	"first",
	core.TokenKindKeyword,
	func(text string, offset int) int {
		if strings.HasPrefix(text[offset:], "first") {
			return 5
		}
		return 0
	},
	[]rune{'f'},
)

const Keyword_g_Idx = 13

var Keyword_g = core.NewTokenType(
	Keyword_g_Idx,
	"g",
	"g",
	core.TokenKindKeyword,
	func(text string, offset int) int {
		if strings.HasPrefix(text[offset:], "g") {
			return 1
		}
		return 0
	},
	[]rune{'g'},
)

const Keyword_h_Idx = 14

var Keyword_h = core.NewTokenType(
	Keyword_h_Idx,
	"h",
	"h",
	core.TokenKindKeyword,
	func(text string, offset int) int {
		if strings.HasPrefix(text[offset:], "h") {
			return 1
		}
		return 0
	},
	[]rune{'h'},
)

const Keyword_i_Idx = 15

var Keyword_i = core.NewTokenType(
	Keyword_i_Idx,
	"i",
	"i",
	core.TokenKindKeyword,
	func(text string, offset int) int {
		if strings.HasPrefix(text[offset:], "i") {
			return 1
		}
		return 0
	},
	[]rune{'i'},
)

const Keyword_j_Idx = 16

var Keyword_j = core.NewTokenType(
	Keyword_j_Idx,
	"j",
	"j",
	core.TokenKindKeyword,
	func(text string, offset int) int {
		if strings.HasPrefix(text[offset:], "j") {
			return 1
		}
		return 0
	},
	[]rune{'j'},
)

const Keyword_k_Idx = 17

var Keyword_k = core.NewTokenType(
	Keyword_k_Idx,
	"k",
	"k",
	core.TokenKindKeyword,
	func(text string, offset int) int {
		if strings.HasPrefix(text[offset:], "k") {
			return 1
		}
		return 0
	},
	[]rune{'k'},
)

const Keyword_l_Idx = 18

var Keyword_l = core.NewTokenType(
	Keyword_l_Idx,
	"l",
	"l",
	core.TokenKindKeyword,
	func(text string, offset int) int {
		if strings.HasPrefix(text[offset:], "l") {
			return 1
		}
		return 0
	},
	[]rune{'l'},
)

const Keyword_long_Idx = 19

var Keyword_long = core.NewTokenType(
	Keyword_long_Idx,
	"long",
	"long",
	core.TokenKindKeyword,
	func(text string, offset int) int {
		if strings.HasPrefix(text[offset:], "long") {
			return 4
		}
		return 0
	},
	[]rune{'l'},
)

const Keyword_m_Idx = 20

var Keyword_m = core.NewTokenType(
	Keyword_m_Idx,
	"m",
	"m",
	core.TokenKindKeyword,
	func(text string, offset int) int {
		if strings.HasPrefix(text[offset:], "m") {
			return 1
		}
		return 0
	},
	[]rune{'m'},
)

const Keyword_n_Idx = 21

var Keyword_n = core.NewTokenType(
	Keyword_n_Idx,
	"n",
	"n",
	core.TokenKindKeyword,
	func(text string, offset int) int {
		if strings.HasPrefix(text[offset:], "n") {
			return 1
		}
		return 0
	},
	[]rune{'n'},
)

const Keyword_o_Idx = 22

var Keyword_o = core.NewTokenType(
	Keyword_o_Idx,
	"o",
	"o",
	core.TokenKindKeyword,
	func(text string, offset int) int {
		if strings.HasPrefix(text[offset:], "o") {
			return 1
		}
		return 0
	},
	[]rune{'o'},
)

const Keyword_optional_Idx = 23

var Keyword_optional = core.NewTokenType(
	Keyword_optional_Idx,
	"optional",
	"optional",
	core.TokenKindKeyword,
	func(text string, offset int) int {
		if strings.HasPrefix(text[offset:], "optional") {
			return 8
		}
		return 0
	},
	[]rune{'o'},
)

const Keyword_second_Idx = 24

var Keyword_second = core.NewTokenType(
	Keyword_second_Idx,
	"second",
	"second",
	core.TokenKindKeyword,
	func(text string, offset int) int {
		if strings.HasPrefix(text[offset:], "second") {
			return 6
		}
		return 0
	},
	[]rune{'s'},
)

const Keyword_self_Idx = 25

var Keyword_self = core.NewTokenType(
	Keyword_self_Idx,
	"self",
	"self",
	core.TokenKindKeyword,
	func(text string, offset int) int {
		if strings.HasPrefix(text[offset:], "self") {
			return 4
		}
		return 0
	},
	[]rune{'s'},
)

const Keyword_then_Idx = 26

var Keyword_then = core.NewTokenType(
	Keyword_then_Idx,
	"then",
	"then",
	core.TokenKindKeyword,
	func(text string, offset int) int {
		if strings.HasPrefix(text[offset:], "then") {
			return 4
		}
		return 0
	},
	[]rune{'t'},
)

const Keyword_x_Idx = 27

var Keyword_x = core.NewTokenType(
	Keyword_x_Idx,
	"x",
	"x",
	core.TokenKindKeyword,
	func(text string, offset int) int {
		if strings.HasPrefix(text[offset:], "x") {
			return 1
		}
		return 0
	},
	[]rune{'x'},
)

const Keyword_y_Idx = 28

var Keyword_y = core.NewTokenType(
	Keyword_y_Idx,
	"y",
	"y",
	core.TokenKindKeyword,
	func(text string, offset int) int {
		if strings.HasPrefix(text[offset:], "y") {
			return 1
		}
		return 0
	},
	[]rune{'y'},
)

const Keyword_LeftBrace_Idx = 29

var Keyword_LeftBrace = core.NewTokenType(
	Keyword_LeftBrace_Idx,
	"{",
	"{",
	core.TokenKindKeyword,
	func(text string, offset int) int {
		if strings.HasPrefix(text[offset:], "{") {
			return 1
		}
		return 0
	},
	[]rune{'{'},
)

const Keyword_RightBrace_Idx = 30

var Keyword_RightBrace = core.NewTokenType(
	Keyword_RightBrace_Idx,
	"}",
	"}",
	core.TokenKindKeyword,
	func(text string, offset int) int {
		if strings.HasPrefix(text[offset:], "}") {
			return 1
		}
		return 0
	},
	[]rune{'}'},
)

const Token_DECLARE_Idx = Keyword_declare_Idx

var Token_DECLARE = Keyword_declare

const Token_FIRST_Idx = Keyword_first_Idx

var Token_FIRST = Keyword_first

const Token_SECOND_Idx = Keyword_second_Idx

var Token_SECOND = Keyword_second

const Token_LONG_Idx = Keyword_long_Idx

var Token_LONG = Keyword_long

const Token_SELF_Idx = Keyword_self_Idx

var Token_SELF = Keyword_self

const Token_COMMON_Idx = Keyword_common_Idx

var Token_COMMON = Keyword_common

const Token_THEN_Idx = Keyword_then_Idx

var Token_THEN = Keyword_then

const Token_LBRACE_Idx = Keyword_LeftBrace_Idx

var Token_LBRACE = Keyword_LeftBrace

const Token_RBRACE_Idx = Keyword_RightBrace_Idx

var Token_RBRACE = Keyword_RightBrace

const Token_DOT_Idx = Keyword_Dot_Idx

var Token_DOT = Keyword_Dot

const Token_OPTIONAL_Idx = Keyword_optional_Idx

var Token_OPTIONAL = Keyword_optional

const Token_AND_Idx = Keyword_and_Idx

var Token_AND = Keyword_and

const Token_END_Idx = Keyword_end_Idx

var Token_END = Keyword_end

const Token_WS_Idx = 31

var Token_WS = core.NewTokenType(
	Token_WS_Idx,
	"WS",
	"WS",
	core.TokenKindToken,
	func(s string, offset int) int {
		input := s[offset:]
		length := len(input)
		state := 0
		acceptedIndex := 0
		index := 0
	loop:
		for index < length {
			r, runeSize := utf8.DecodeRuneInString(input[index:])
			switch state {
			case 0:
				nextState := -1
				next := Token_WS_Next[0]
				lookup := Token_WS_Lookup[0]
				for i, lowHigh := range lookup {
					if rune(lowHigh&0xFFFFFFFF) <= r && r <= rune(lowHigh>>32) {
						nextState = next[i]
						break
					}
				}
				if nextState > -1 {
					state = nextState
				} else {
					break loop
				}
			case 1:
				nextState := -1
				next := Token_WS_Next[1]
				lookup := Token_WS_Lookup[1]
				for i, lowHigh := range lookup {
					if rune(lowHigh&0xFFFFFFFF) <= r && r <= rune(lowHigh>>32) {
						nextState = next[i]
						break
					}
				}
				if nextState > -1 {
					state = nextState
				} else {
					break loop
				}
			default:
				break loop
			}
			index += runeSize
			if Token_WS_Accepting[state] {
				acceptedIndex = index
			}
		}
		return acceptedIndex
	},
	[]rune{'\u0009', '\u000A', '\u000D', ' '},
)
var Token_WS_Lookup = [][]int64{
	{0x0000000A00000009, 0x0000000D0000000D, 0x0000002000000020},
	{0x0000000A00000009, 0x0000000D0000000D, 0x0000002000000020},
}
var Token_WS_Next = [][]int{
	{1, 1, 1},
	{1, 1, 1},
}
var Token_WS_Accepting = [2]bool{
	1: true,
}

const Token_ID_Idx = 32

var Token_ID = core.NewTokenType(
	Token_ID_Idx,
	"ID",
	"ID",
	core.TokenKindToken,
	func(s string, offset int) int {
		input := s[offset:]
		length := len(input)
		state := 0
		acceptedIndex := 0
		index := 0
	loop:
		for index < length {
			r, runeSize := utf8.DecodeRuneInString(input[index:])
			switch state {
			case 0:
				nextState := -1
				next := Token_ID_Next[0]
				lookup := Token_ID_Lookup[0]
				for i, lowHigh := range lookup {
					if rune(lowHigh&0xFFFFFFFF) <= r && r <= rune(lowHigh>>32) {
						nextState = next[i]
						break
					}
				}
				if nextState > -1 {
					state = nextState
				} else {
					break loop
				}
			case 1:
				nextState := -1
				next := Token_ID_Next[1]
				lookup := Token_ID_Lookup[1]
				for i, lowHigh := range lookup {
					if rune(lowHigh&0xFFFFFFFF) <= r && r <= rune(lowHigh>>32) {
						nextState = next[i]
						break
					}
				}
				if nextState > -1 {
					state = nextState
				} else {
					break loop
				}
			default:
				break loop
			}
			index += runeSize
			if Token_ID_Accepting[state] {
				acceptedIndex = index
			}
		}
		return acceptedIndex
	},
	[]rune{'0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'},
)
var Token_ID_Lookup = [][]int64{
	{0x0000003900000030, 0x0000005A00000041, 0x0000005F0000005F, 0x0000007A00000061},
	{0x0000003900000030, 0x0000005A00000041, 0x0000005F0000005F, 0x0000007A00000061},
}
var Token_ID_Next = [][]int{
	{1, 1, 1, 1},
	{1, 1, 1, 1},
}
var Token_ID_Accepting = [2]bool{
	1: true,
}

const TokenGroup_SomeTokenGroup_Idx = 33

var TokenGroup_SomeTokenGroup = core.NewTokenGroup(
	TokenGroup_SomeTokenGroup_Idx,
	"SomeTokenGroup",
	"SomeTokenGroup",
	[]*core.TokenType{
		Keyword_a,
		Keyword_b,
		Token_ID,
	},
)

const (
	TokenMode_default = 0
)

func NewLexer() lexer.Lexer {
	modes := make([]*lexer.TokenMode, 1, 1)
	modes[TokenMode_default] = lexer.NewTokenMode("default",
		lexer.UseTokenType(Keyword_a),
		lexer.UseTokenType(Keyword_b),
		lexer.UseTokenType(Keyword_c),
		lexer.UseTokenType(Keyword_d),
		lexer.UseTokenType(Keyword_e),
		lexer.UseTokenType(Keyword_f),
		lexer.UseTokenType(Keyword_g),
		lexer.UseTokenType(Keyword_h),
		lexer.UseTokenType(Keyword_i),
		lexer.UseTokenType(Keyword_j),
		lexer.UseTokenType(Keyword_k),
		lexer.UseTokenType(Keyword_l),
		lexer.UseTokenType(Keyword_m),
		lexer.UseTokenType(Keyword_n),
		lexer.UseTokenType(Keyword_o),
		lexer.UseTokenType(Keyword_x),
		lexer.UseTokenType(Keyword_y),
		lexer.UseTokenType(Token_DECLARE),
		lexer.UseTokenType(Token_FIRST),
		lexer.UseTokenType(Token_SECOND),
		lexer.UseTokenType(Token_LONG),
		lexer.UseTokenType(Token_SELF),
		lexer.UseTokenType(Token_COMMON),
		lexer.UseTokenType(Token_THEN),
		lexer.UseTokenType(Token_LBRACE),
		lexer.UseTokenType(Token_RBRACE),
		lexer.UseTokenType(Token_DOT),
		lexer.UseTokenType(Token_OPTIONAL),
		lexer.UseTokenType(Token_AND),
		lexer.UseTokenType(Token_ID),
		lexer.UseTokenType(Token_END),
		lexer.UseTokenType(Token_WS).WithGroup(core.SkippedGroup),
	)
	return lexer.NewDefaultLexer(TokenMode_default, modes...)
}
