// Code generated by typefox.dev/fastbelt/cmd/fastbelt. DO NOT EDIT.

package completion

import (
	core "typefox.dev/fastbelt"
	"typefox.dev/fastbelt/parser"
	"typefox.dev/fastbelt/util/service"
)

type Parser struct {
	state                 *parser.ParserState
	sc                    *service.Container
	referencesConstructor CompletionReferencesConstructor
	lookahead             CompletionParserLookahead
}

func (p *Parser) Parse(document *core.Document) *parser.ParseResult {
	recovery := service.MustGet[parser.ErrorRecoveryStrategy](p.sc)
	messages := service.MustGet[parser.ErrorMessageProvider](p.sc)
	referencesConstructor := service.MustGet[CompletionReferencesConstructor](p.sc)
	lookahead := service.MustGet[CompletionParserLookahead](p.sc)
	cp := &Parser{sc: p.sc, referencesConstructor: referencesConstructor, lookahead: lookahead, state: parser.NewParserState(document.Tokens, ATN(), recovery, messages)}
	result := cp.ParseRoot()
	cp.state.ExpectEndOfInput()
	return &parser.ParseResult{Node: result, Errors: cp.state.Errors()}
}

func NewParser(sc *service.Container) *Parser {
	return &Parser{
		sc: sc,
	}
}

func (p *Parser) ParseRoot() Root {
	current := NewRoot()
	current.SetTextRangeStart(p.state.LA(1).Range.Start)
	{
		{
			p.state.Sync(Root__LoopEntry)
		loop0:
			for {
				switch prediction, _ := p.lookahead.RootObjectsAlternatives(p.state); prediction {
				case 0:
					p.state.EnterRule(Root__Basic_1)
					result := p.ParseDeclare()
					p.state.ExitRule()
					if result != nil {
						current.SetObjectsItem(result)
					}
				case 1:
					p.state.EnterRule(Root__Basic_3)
					result := p.ParseSeq()
					p.state.ExitRule()
					if result != nil {
						current.SetObjectsItem(result)
					}
				case 2:
					p.state.EnterRule(Root__Basic_5)
					result := p.ParseAlt()
					p.state.ExitRule()
					if result != nil {
						current.SetObjectsItem(result)
					}
				case 3:
					p.state.EnterRule(Root__Basic_7)
					result := p.ParsePrefix()
					p.state.ExitRule()
					if result != nil {
						current.SetObjectsItem(result)
					}
				case 4:
					p.state.EnterRule(Root__Basic_9)
					result := p.ParseCall()
					p.state.ExitRule()
					if result != nil {
						current.SetObjectsItem(result)
					}
				case 5:
					p.state.EnterRule(Root__Basic_11)
					result := p.ParseRefFQN()
					p.state.ExitRule()
					if result != nil {
						current.SetObjectsItem(result)
					}
				case 6:
					p.state.EnterRule(Root__Basic_13)
					result := p.ParseRefList()
					p.state.ExitRule()
					if result != nil {
						current.SetObjectsItem(result)
					}
				case 7:
					p.state.EnterRule(Root__Basic_15)
					result := p.ParseRefID()
					p.state.ExitRule()
					if result != nil {
						current.SetObjectsItem(result)
					}
				case 8:
					p.state.EnterRule(Root__Basic_17)
					result := p.ParseMember()
					p.state.ExitRule()
					if result != nil {
						current.SetObjectsItem(result)
					}
				case 9:
					p.state.EnterRule(Root__Basic_19)
					result := p.ParseMemberNoDot()
					p.state.ExitRule()
					if result != nil {
						current.SetObjectsItem(result)
					}
				case 10:
					p.state.EnterRule(Root__Basic_21)
					result := p.ParseRefOrKeyword()
					p.state.ExitRule()
					if result != nil {
						current.SetObjectsItem(result)
					}
				case 11:
					p.state.EnterRule(Root__Basic_23)
					result := p.ParseDedup()
					p.state.ExitRule()
					if result != nil {
						current.SetObjectsItem(result)
					}
				case 12:
					p.state.EnterRule(Root__Basic_25)
					result := p.ParseOpt()
					p.state.ExitRule()
					if result != nil {
						current.SetObjectsItem(result)
					}
				case 13:
					p.state.EnterRule(Root__Basic_27)
					result := p.ParseGroup()
					p.state.ExitRule()
					if result != nil {
						current.SetObjectsItem(result)
					}
				case 14:
					p.state.EnterRule(Root__Basic_29)
					result := p.ParseRefGroup()
					p.state.ExitRule()
					if result != nil {
						current.SetObjectsItem(result)
					}
				case 15:
					p.state.EnterRule(Root__Basic_31)
					result := p.ParseRefAction()
					p.state.ExitRule()
					if result != nil {
						current.SetObjectsItem(result)
					}
				case 16:
					p.state.EnterRule(Root__Basic_33)
					result := p.ParseScope()
					p.state.ExitRule()
					if result != nil {
						current.SetObjectsItem(result)
					}
				case 17:
					p.state.EnterRule(Root__Basic_35)
					result := p.ParseLoop()
					p.state.ExitRule()
					if result != nil {
						current.SetObjectsItem(result)
					}
				case 18:
					p.state.EnterRule(Root__Basic_37)
					result := p.ParseChain()
					p.state.ExitRule()
					if result != nil {
						current.SetObjectsItem(result)
					}
				case 19:
					p.state.EnterRule(Root__Basic_39)
					result := p.ParseInfix()
					p.state.ExitRule()
					if result != nil {
						current.SetObjectsItem(result)
					}
				case 20:
					p.state.EnterRule(Root__Basic_41)
					result := p.ParseWrap()
					p.state.ExitRule()
					if result != nil {
						current.SetObjectsItem(result)
					}
				case 21:
					p.state.EnterRule(Root__Basic_43)
					result := p.ParseShadow()
					p.state.ExitRule()
					if result != nil {
						current.SetObjectsItem(result)
					}
				case 22:
					p.state.EnterRule(Root__Basic_45)
					result := p.ParseNest()
					p.state.ExitRule()
					if result != nil {
						current.SetObjectsItem(result)
					}
				case 23:
					p.state.EnterRule(Root__Basic_47)
					result := p.ParseAmbig()
					p.state.ExitRule()
					if result != nil {
						current.SetObjectsItem(result)
					}
				case 24:
					p.state.EnterRule(Root__Basic_49)
					result := p.ParseRetype()
					p.state.ExitRule()
					if result != nil {
						current.SetObjectsItem(result)
					}
				default:
					break loop0
				}
				p.state.Sync(Root__LoopEntry)
			}
		}
	}
	current.SetTextRangeEnd(p.state.LA(0).Range.End)
	return current
}

func (p *Parser) ParseDeclare() Declare {
	current := NewDeclare()
	current.SetTextRangeStart(p.state.LA(1).Range.Start)
	{
		{
			token := p.state.Consume(Token_DECLARE)
			core.AssignToken(current, token, Declare_DECLARE)
		}
		{
			result := core.NewCompositeNode()
			result.SetTextRangeStart(p.state.LA(1).Range.Start)
			p.state.EnterRule(Declare__Basic_4)
			p.ParseFQN(result)
			p.state.ExitRule()
			result.SetTextRangeEnd(p.state.LA(0).Range.End)
			if result != nil {
				current.SetName(result)
			}
		}
		p.state.Sync(Declare__Basic_4)
		if p.lookahead.DeclareOptional(p.state) {
			{
				token := p.state.Consume(Token_LBRACE)
				core.AssignToken(current, token, Declare_LBRACE)
			}
			{
				p.state.Sync(Declare__LoopEntry)
				for p.lookahead.DeclareChildrenLoop(p.state) {
					p.state.EnterRule(Declare__Basic_2)
					result := p.ParseDeclare()
					p.state.ExitRule()
					if result != nil {
						current.SetChildrenItem(result)
					}
					p.state.Sync(Declare__LoopEntry)
				}
			}
			{
				token := p.state.Consume(Token_RBRACE)
				core.AssignToken(current, token, Declare_RBRACE)
			}
		}
	}
	current.SetTextRangeEnd(p.state.LA(0).Range.End)
	return current
}

func (p *Parser) ParseSeq() Obj {
	current := NewObj()
	current.SetTextRangeStart(p.state.LA(1).Range.Start)
	{
		{
			token := p.state.Consume(Keyword_seq)
			core.AssignToken(current, token, Seq_seq)
		}
		{
			token := p.state.Consume(Token_FIRST)
			core.AssignToken(current, token, Seq_FIRST)
		}
	}
	current.SetTextRangeEnd(p.state.LA(0).Range.End)
	return current
}

func (p *Parser) ParseAlt() Obj {
	current := NewObj()
	current.SetTextRangeStart(p.state.LA(1).Range.Start)
	{
		{
			token := p.state.Consume(Keyword_alt)
			core.AssignToken(current, token, Alt_alt)
		}
		switch prediction, failure := p.lookahead.AltAlternatives(p.state); prediction {
		case 0:
			{
				token := p.state.Consume(Token_FIRST)
				core.AssignToken(current, token, Alt_FIRST)
			}
		case 1:
			{
				token := p.state.Consume(Token_SECOND)
				core.AssignToken(current, token, Alt_SECOND)
			}
		default:
			p.state.AppendError(p.state.Messages().NoViableAlternative(failure), failure.Token)
		}
	}
	current.SetTextRangeEnd(p.state.LA(0).Range.End)
	return current
}

func (p *Parser) ParsePrefix() Obj {
	current := NewObj()
	current.SetTextRangeStart(p.state.LA(1).Range.Start)
	{
		{
			token := p.state.Consume(Keyword_prefix)
			core.AssignToken(current, token, Prefix_prefix)
		}
		switch prediction, failure := p.lookahead.PrefixAlternatives(p.state); prediction {
		case 0:
			{
				token := p.state.Consume(Token_COMMON)
				core.AssignToken(current, token, Prefix_COMMON_0)
			}
			{
				token := p.state.Consume(Token_FIRST)
				core.AssignToken(current, token, Prefix_FIRST)
			}
		case 1:
			{
				token := p.state.Consume(Token_COMMON)
				core.AssignToken(current, token, Prefix_COMMON_1)
			}
			{
				token := p.state.Consume(Token_SECOND)
				core.AssignToken(current, token, Prefix_SECOND)
			}
		default:
			p.state.AppendError(p.state.Messages().NoViableAlternative(failure), failure.Token)
		}
	}
	current.SetTextRangeEnd(p.state.LA(0).Range.End)
	return current
}

func (p *Parser) ParseCall() Obj {
	current := NewObj()
	current.SetTextRangeStart(p.state.LA(1).Range.Start)
	{
		{
			token := p.state.Consume(Keyword_call)
			core.AssignToken(current, token, Call_call)
		}
		switch prediction, failure := p.lookahead.CallAlternatives(p.state); prediction {
		case 0:
			{
				p.state.EnterRule(Call__Basic_1)
				result := p.ParseCallLong()
				p.state.ExitRule()
				core.MergeTokens(result, current.Tokens())
				current = result
			}
		case 1:
			{
				p.state.EnterRule(Call__Basic_3)
				result := p.ParseCallShort()
				p.state.ExitRule()
				core.MergeTokens(result, current.Tokens())
				current = result
			}
		default:
			p.state.AppendError(p.state.Messages().NoViableAlternative(failure), failure.Token)
		}
	}
	current.SetTextRangeEnd(p.state.LA(0).Range.End)
	return current
}

func (p *Parser) ParseCallLong() Obj {
	current := NewObj()
	current.SetTextRangeStart(p.state.LA(1).Range.Start)
	{
		{
			token := p.state.Consume(Token_COMMON)
			core.AssignToken(current, token, CallLong_COMMON)
		}
		{
			token := p.state.Consume(Token_THEN)
			core.AssignToken(current, token, CallLong_THEN)
		}
		{
			token := p.state.Consume(Token_LONG)
			core.AssignToken(current, token, CallLong_LONG)
		}
	}
	current.SetTextRangeEnd(p.state.LA(0).Range.End)
	return current
}

func (p *Parser) ParseCallShort() Obj {
	current := NewObj()
	current.SetTextRangeStart(p.state.LA(1).Range.Start)
	{
		{
			token := p.state.Consume(Token_COMMON)
			core.AssignToken(current, token, CallShort_COMMON)
		}
	}
	current.SetTextRangeEnd(p.state.LA(0).Range.End)
	return current
}

func (p *Parser) ParseRefFQN() RefFQN {
	current := NewRefFQN()
	current.SetTextRangeStart(p.state.LA(1).Range.Start)
	{
		{
			token := p.state.Consume(Keyword_fqn)
			core.AssignToken(current, token, RefFQN_fqn)
		}
		{
			result := core.NewCompositeNode()
			result.SetTextRangeStart(p.state.LA(1).Range.Start)
			p.state.EnterRule(RefFQN__Basic_1)
			p.ParseFQN(result)
			p.state.ExitRule()
			result.SetTextRangeEnd(p.state.LA(0).Range.End)
			if result != nil {
				current.SetRef(p.referencesConstructor.RefFQNRef(current, result))
			}
		}
	}
	current.SetTextRangeEnd(p.state.LA(0).Range.End)
	return current
}

func (p *Parser) ParseRefList() RefList {
	current := NewRefList()
	current.SetTextRangeStart(p.state.LA(1).Range.Start)
	{
		{
			token := p.state.Consume(Keyword_list)
			core.AssignToken(current, token, RefList_list)
		}
		{
			for ok := true; ok; ok = p.lookahead.RefListItemsLoop(p.state) {
				p.state.EnterRule(RefList__Basic_1)
				result := p.ParseRefListItem()
				p.state.ExitRule()
				if result != nil {
					current.SetItemsItem(result)
				}
				p.state.Sync(RefList__LoopBack)
			}
		}
	}
	current.SetTextRangeEnd(p.state.LA(0).Range.End)
	return current
}

func (p *Parser) ParseRefListItem() RefListItem {
	current := NewRefListItem()
	current.SetTextRangeStart(p.state.LA(1).Range.Start)
	{
		{
			result := core.NewCompositeNode()
			result.SetTextRangeStart(p.state.LA(1).Range.Start)
			p.state.EnterRule(RefListItem__Basic_1)
			p.ParseFQN(result)
			p.state.ExitRule()
			result.SetTextRangeEnd(p.state.LA(0).Range.End)
			if result != nil {
				current.SetRef(p.referencesConstructor.RefListItemRef(current, result))
			}
		}
	}
	current.SetTextRangeEnd(p.state.LA(0).Range.End)
	return current
}

func (p *Parser) ParseRefID() RefID {
	current := NewRefID()
	current.SetTextRangeStart(p.state.LA(1).Range.Start)
	{
		{
			token := p.state.Consume(Keyword_ref)
			core.AssignToken(current, token, RefID_ref)
		}
		{
			token := p.state.Consume(Token_ID)
			core.AssignToken(current, token, RefID_Ref_ID)
			if token != nil {
				current.SetRef(p.referencesConstructor.RefIDRef(current, token))
			}
		}
	}
	current.SetTextRangeEnd(p.state.LA(0).Range.End)
	return current
}

func (p *Parser) ParseMember() Member {
	current := NewMember()
	current.SetTextRangeStart(p.state.LA(1).Range.Start)
	{
		{
			token := p.state.Consume(Keyword_member)
			core.AssignToken(current, token, Member_member)
		}
		{
			p.state.EnterRule(Member__Basic_1)
			result := p.ParseMemberCall()
			p.state.ExitRule()
			if result != nil {
				current.SetCall(result)
			}
		}
	}
	current.SetTextRangeEnd(p.state.LA(0).Range.End)
	return current
}

func (p *Parser) ParseMemberNoDot() Member {
	current := NewMember()
	current.SetTextRangeStart(p.state.LA(1).Range.Start)
	{
		{
			token := p.state.Consume(Keyword_nodot)
			core.AssignToken(current, token, MemberNoDot_nodot)
		}
		{
			p.state.EnterRule(MemberNoDot__Basic_1)
			result := p.ParseMemberCallNoDot()
			p.state.ExitRule()
			if result != nil {
				current.SetCall(result)
			}
		}
	}
	current.SetTextRangeEnd(p.state.LA(0).Range.End)
	return current
}

func (p *Parser) ParseMemberCall() MemberCall {
	current := NewMemberCall()
	current.SetTextRangeStart(p.state.LA(1).Range.Start)
	{
		{
			token := p.state.Consume(Token_ID)
			core.AssignToken(current, token, MemberCall_Ref_ID_0)
			if token != nil {
				current.SetRef(p.referencesConstructor.MemberCallRef(current, token))
			}
		}
		p.state.Sync(MemberCall__LoopEntry)
		for p.lookahead.MemberCallLoop(p.state) {
			{
				result := NewMemberCall()
				result.SetTextRange(current.TextRange())
				result.SetPrevious(current)
				current.SetTextRangeEnd(p.state.LA(0).Range.End)
				current = result
			}
			current := current.(MemberCall)
			{
				token := p.state.Consume(Token_DOT)
				core.AssignToken(current, token, MemberCall_DOT)
			}
			{
				token := p.state.Consume(Token_ID)
				core.AssignToken(current, token, MemberCall_Ref_ID_1)
				if token != nil {
					current.SetRef(p.referencesConstructor.MemberCallRef(current, token))
				}
			}
			p.state.Sync(MemberCall__LoopEntry)
		}
	}
	current.SetTextRangeEnd(p.state.LA(0).Range.End)
	return current
}

func (p *Parser) ParseMemberCallNoDot() MemberCall {
	current := NewMemberCall()
	current.SetTextRangeStart(p.state.LA(1).Range.Start)
	{
		{
			token := p.state.Consume(Token_ID)
			core.AssignToken(current, token, MemberCallNoDot_Ref_ID_0)
			if token != nil {
				current.SetRef(p.referencesConstructor.MemberCallRef(current, token))
			}
		}
		p.state.Sync(MemberCallNoDot__LoopEntry)
		for p.lookahead.MemberCallNoDotLoop(p.state) {
			{
				result := NewMemberCall()
				result.SetTextRange(current.TextRange())
				result.SetPrevious(current)
				current.SetTextRangeEnd(p.state.LA(0).Range.End)
				current = result
			}
			current := current.(MemberCall)
			{
				token := p.state.Consume(Token_ID)
				core.AssignToken(current, token, MemberCallNoDot_Ref_ID_1)
				if token != nil {
					current.SetRef(p.referencesConstructor.MemberCallRef(current, token))
				}
			}
			p.state.Sync(MemberCallNoDot__LoopEntry)
		}
	}
	current.SetTextRangeEnd(p.state.LA(0).Range.End)
	return current
}

func (p *Parser) ParseRefOrKeyword() RefOrKeyword {
	current := NewRefOrKeyword()
	current.SetTextRangeStart(p.state.LA(1).Range.Start)
	{
		{
			token := p.state.Consume(Keyword_choice)
			core.AssignToken(current, token, RefOrKeyword_choice)
		}
		switch prediction, failure := p.lookahead.RefOrKeywordAlternatives(p.state); prediction {
		case 0:
			{
				token := p.state.Consume(Token_ID)
				core.AssignToken(current, token, RefOrKeyword_Ref_ID)
				if token != nil {
					current.SetRef(p.referencesConstructor.RefOrKeywordRef(current, token))
				}
			}
		case 1:
			{
				token := p.state.Consume(Token_SELF)
				core.AssignToken(current, token, RefOrKeyword_SELF)
			}
		default:
			p.state.AppendError(p.state.Messages().NoViableAlternative(failure), failure.Token)
		}
	}
	current.SetTextRangeEnd(p.state.LA(0).Range.End)
	return current
}

func (p *Parser) ParseDedup() Dedup {
	current := NewDedup()
	current.SetTextRangeStart(p.state.LA(1).Range.Start)
	{
		{
			token := p.state.Consume(Keyword_dedup)
			core.AssignToken(current, token, Dedup_dedup)
		}
		switch prediction, failure := p.lookahead.DedupAlternatives(p.state); prediction {
		case 0:
			{
				token := p.state.Consume(Token_ID)
				core.AssignToken(current, token, Dedup_Ref1_ID)
				if token != nil {
					current.SetRef1(p.referencesConstructor.DedupRef1(current, token))
				}
			}
			{
				token := p.state.Consume(Keyword_x)
				core.AssignToken(current, token, Dedup_x)
			}
		case 1:
			{
				token := p.state.Consume(Token_ID)
				core.AssignToken(current, token, Dedup_Ref2_ID)
				if token != nil {
					current.SetRef2(p.referencesConstructor.DedupRef2(current, token))
				}
			}
			{
				token := p.state.Consume(Keyword_y)
				core.AssignToken(current, token, Dedup_y)
			}
		default:
			p.state.AppendError(p.state.Messages().NoViableAlternative(failure), failure.Token)
		}
	}
	current.SetTextRangeEnd(p.state.LA(0).Range.End)
	return current
}

func (p *Parser) ParseOpt() Obj {
	current := NewObj()
	current.SetTextRangeStart(p.state.LA(1).Range.Start)
	{
		{
			token := p.state.Consume(Keyword_opt)
			core.AssignToken(current, token, Opt_opt)
		}
		p.state.Sync(Opt__Basic_1)
		if p.lookahead.OptOptional(p.state) {
			{
				token := p.state.Consume(Token_OPTIONAL)
				core.AssignToken(current, token, Opt_OPTIONAL)
			}
			{
				token := p.state.Consume(Token_AND)
				core.AssignToken(current, token, Opt_AND)
			}
		}
		{
			token := p.state.Consume(Token_THEN)
			core.AssignToken(current, token, Opt_THEN)
		}
		{
			token := p.state.Consume(Token_END)
			core.AssignToken(current, token, Opt_END)
		}
	}
	current.SetTextRangeEnd(p.state.LA(0).Range.End)
	return current
}

func (p *Parser) ParseGroup() Obj {
	current := NewObj()
	current.SetTextRangeStart(p.state.LA(1).Range.Start)
	{
		{
			token := p.state.Consume(Keyword_group)
			core.AssignToken(current, token, Group_group)
		}
		{
			token := p.state.Consume(TokenGroup_SomeTokenGroup)
			core.AssignToken(current, token, Group_SomeTokenGroup)
		}
	}
	current.SetTextRangeEnd(p.state.LA(0).Range.End)
	return current
}

func (p *Parser) ParseRefGroup() RefGroup {
	current := NewRefGroup()
	current.SetTextRangeStart(p.state.LA(1).Range.Start)
	{
		{
			token := p.state.Consume(Keyword_refgroup)
			core.AssignToken(current, token, RefGroup_refgroup)
		}
		{
			token := p.state.Consume(TokenGroup_SomeTokenGroup)
			core.AssignToken(current, token, RefGroup_Ref_SomeTokenGroup)
			if token != nil {
				current.SetRef(p.referencesConstructor.RefGroupRef(current, token))
			}
		}
	}
	current.SetTextRangeEnd(p.state.LA(0).Range.End)
	return current
}

func (p *Parser) ParseRefAction() Obj {
	startPos := p.state.LA(1).Range.Start
	var current Obj
	{
		{
			result := NewRefAction()
			result.SetTextRangeStart(startPos)
			current = result
		}
		current := current.(RefAction)
		{
			token := p.state.Consume(Keyword_action)
			core.AssignToken(current, token, RefAction_action)
		}
		{
			token := p.state.Consume(Token_ID)
			core.AssignToken(current, token, RefAction_Ref_ID)
			if token != nil {
				current.SetRef(p.referencesConstructor.RefActionRef(current, token))
			}
		}
	}
	current.SetTextRangeEnd(p.state.LA(0).Range.End)
	return current
}

func (p *Parser) ParseScope() Scope {
	current := NewScope()
	current.SetTextRangeStart(p.state.LA(1).Range.Start)
	{
		{
			token := p.state.Consume(Keyword_scope)
			core.AssignToken(current, token, Scope_scope)
		}
		{
			token := p.state.Consume(Token_LBRACE)
			core.AssignToken(current, token, Scope_LBRACE)
		}
		{
			p.state.Sync(Scope__LoopEntry_0)
			for p.lookahead.ScopeLocalsLoop(p.state) {
				p.state.EnterRule(Scope__Basic_1)
				result := p.ParseDeclare()
				p.state.ExitRule()
				if result != nil {
					current.SetLocalsItem(result)
				}
				p.state.Sync(Scope__LoopEntry_0)
			}
		}
		{
			token := p.state.Consume(Keyword_use)
			core.AssignToken(current, token, Scope_use)
		}
		{
			p.state.EnterRule(Scope__LoopEntry_1)
			result := p.ParseRefItem()
			p.state.ExitRule()
			if result != nil {
				current.SetItem(result)
			}
		}
		p.state.Sync(Scope__LoopEntry_1)
		for p.lookahead.ScopeLoop(p.state) {
			{
				token := p.state.Consume(Token_AND)
				core.AssignToken(current, token, Scope_AND)
			}
			{
				p.state.EnterRule(Scope__Basic_4)
				result := p.ParseRefItem()
				p.state.ExitRule()
				if result != nil {
					current.SetOthersItem(result)
				}
			}
			p.state.Sync(Scope__LoopEntry_1)
		}
		{
			token := p.state.Consume(Token_RBRACE)
			core.AssignToken(current, token, Scope_RBRACE)
		}
	}
	current.SetTextRangeEnd(p.state.LA(0).Range.End)
	return current
}

func (p *Parser) ParseRefItem() RefItem {
	current := NewRefItem()
	current.SetTextRangeStart(p.state.LA(1).Range.Start)
	{
		{
			token := p.state.Consume(Token_ID)
			core.AssignToken(current, token, RefItem_Ref_ID)
			if token != nil {
				current.SetRef(p.referencesConstructor.RefItemRef(current, token))
			}
		}
	}
	current.SetTextRangeEnd(p.state.LA(0).Range.End)
	return current
}

func (p *Parser) ParseLoop() Loop {
	current := NewLoop()
	current.SetTextRangeStart(p.state.LA(1).Range.Start)
	{
		{
			token := p.state.Consume(Keyword_loop)
			core.AssignToken(current, token, Loop_loop)
		}
		{
			token := p.state.Consume(Token_LBRACE)
			core.AssignToken(current, token, Loop_LBRACE)
		}
		p.state.Sync(Loop__LoopEntry)
	loop1:
		for {
			switch prediction, _ := p.lookahead.LoopAlternatives(p.state); prediction {
			case 0:
				{
					p.state.EnterRule(Loop__Basic_1)
					result := p.ParseDeclare()
					p.state.ExitRule()
					if result != nil {
						current.SetLocalsItem(result)
					}
				}
			case 1:
				{
					p.state.EnterRule(Loop__Basic_3)
					result := p.ParseRefItem()
					p.state.ExitRule()
					if result != nil {
						current.SetItemsItem(result)
					}
				}
			case 2:
				{
					p.state.EnterRule(Loop__Basic_5)
					result := p.ParseLoop()
					p.state.ExitRule()
					if result != nil {
						current.SetNestedItem(result)
					}
				}
			default:
				break loop1
			}
			p.state.Sync(Loop__LoopEntry)
		}
		{
			token := p.state.Consume(Token_RBRACE)
			core.AssignToken(current, token, Loop_RBRACE)
		}
	}
	current.SetTextRangeEnd(p.state.LA(0).Range.End)
	return current
}

func (p *Parser) ParseChain() Chain {
	current := NewChain()
	current.SetTextRangeStart(p.state.LA(1).Range.Start)
	{
		{
			token := p.state.Consume(Keyword_chain)
			core.AssignToken(current, token, Chain_chain)
		}
		{
			token := p.state.Consume(Token_LBRACE)
			core.AssignToken(current, token, Chain_LBRACE)
		}
		{
			p.state.Sync(Chain__LoopEntry)
			for p.lookahead.ChainItemsLoop(p.state) {
				p.state.EnterRule(Chain__Basic_1)
				result := p.ParseChainItem()
				p.state.ExitRule()
				if result != nil {
					current.SetItemsItem(result)
				}
				p.state.Sync(Chain__LoopEntry)
			}
		}
		{
			token := p.state.Consume(Token_RBRACE)
			core.AssignToken(current, token, Chain_RBRACE)
		}
	}
	current.SetTextRangeEnd(p.state.LA(0).Range.End)
	return current
}

func (p *Parser) ParseChainItem() ChainItem {
	current := NewChainItem()
	current.SetTextRangeStart(p.state.LA(1).Range.Start)
	{
		{
			token := p.state.Consume(Token_ID)
			core.AssignToken(current, token, ChainItem_Ref_ID_0)
			if token != nil {
				current.SetRef(p.referencesConstructor.ChainItemRef(current, token))
			}
		}
		p.state.Sync(ChainItem__LoopEntry)
		for p.lookahead.ChainItemLoop(p.state) {
			{
				result := NewChainItem()
				result.SetTextRange(current.TextRange())
				result.SetPrevious(current)
				current.SetTextRangeEnd(p.state.LA(0).Range.End)
				current = result
			}
			current := current.(ChainItem)
			{
				token := p.state.Consume(Token_AND)
				core.AssignToken(current, token, ChainItem_AND)
			}
			{
				token := p.state.Consume(Token_ID)
				core.AssignToken(current, token, ChainItem_Ref_ID_1)
				if token != nil {
					current.SetRef(p.referencesConstructor.ChainItemRef(current, token))
				}
			}
			p.state.Sync(ChainItem__LoopEntry)
		}
	}
	current.SetTextRangeEnd(p.state.LA(0).Range.End)
	return current
}

func (p *Parser) ParseInfix() Infix {
	current := NewInfix()
	current.SetTextRangeStart(p.state.LA(1).Range.Start)
	{
		{
			token := p.state.Consume(Keyword_infix)
			core.AssignToken(current, token, Infix_infix)
		}
		{
			token := p.state.Consume(Token_LBRACE)
			core.AssignToken(current, token, Infix_LBRACE)
		}
		{
			p.state.Sync(Infix__LoopEntry)
			for p.lookahead.InfixItemsLoop(p.state) {
				p.state.EnterRule(Infix__Basic_1)
				result := p.ParseBinary()
				p.state.ExitRule()
				if result != nil {
					current.SetItemsItem(result)
				}
				p.state.Sync(Infix__LoopEntry)
			}
		}
		{
			token := p.state.Consume(Token_RBRACE)
			core.AssignToken(current, token, Infix_RBRACE)
		}
	}
	current.SetTextRangeEnd(p.state.LA(0).Range.End)
	return current
}

func (p *Parser) ParsePrimary() Expr {
	startPos := p.state.LA(1).Range.Start
	var current Expr
	{
		{
			result := NewOperand()
			result.SetTextRangeStart(startPos)
			current = result
		}
		current := current.(Operand)
		{
			token := p.state.Consume(Token_ID)
			core.AssignToken(current, token, Primary_Ref_ID)
			if token != nil {
				current.SetRef(p.referencesConstructor.OperandRef(current, token))
			}
		}
	}
	current.SetTextRangeEnd(p.state.LA(0).Range.End)
	return current
}

func (p *Parser) ParseWrap() Wrap {
	current := NewWrap()
	current.SetTextRangeStart(p.state.LA(1).Range.Start)
	{
		{
			token := p.state.Consume(Keyword_wrap)
			core.AssignToken(current, token, Wrap_wrap)
		}
		{
			token := p.state.Consume(Token_LBRACE)
			core.AssignToken(current, token, Wrap_LBRACE)
		}
		{
			p.state.EnterRule(Wrap_RBRACE)
			result := p.ParseWrapGroup()
			p.state.ExitRule()
			if result != nil {
				current.SetItem(result)
			}
		}
		{
			token := p.state.Consume(Token_RBRACE)
			core.AssignToken(current, token, Wrap_RBRACE)
		}
	}
	current.SetTextRangeEnd(p.state.LA(0).Range.End)
	return current
}

func (p *Parser) ParseWrapGroup() WrapItem {
	var current WrapItem
	{
		{
			p.state.EnterRule(WrapGroup__Basic_3)
			result := p.ParseWrapElement()
			p.state.ExitRule()
			current = result
		}
		p.state.Sync(WrapGroup__Basic_3)
		if p.lookahead.WrapGroupOptional(p.state) {
			{
				result := NewWrapGroup()
				result.SetTextRange(current.TextRange())
				result.SetElementsItem(current)
				current.SetTextRangeEnd(p.state.LA(0).Range.End)
				current = result
			}
			current := current.(WrapGroup)
			{
				for ok := true; ok; ok = p.lookahead.WrapGroupElementsLoop(p.state) {
					p.state.EnterRule(WrapGroup__Basic_2)
					result := p.ParseWrapElement()
					p.state.ExitRule()
					if result != nil {
						current.SetElementsItem(result)
					}
					p.state.Sync(WrapGroup__LoopBack)
				}
			}
		}
	}
	current.SetTextRangeEnd(p.state.LA(0).Range.End)
	return current
}

func (p *Parser) ParseWrapElement() WrapItem {
	startPos := p.state.LA(1).Range.Start
	var current WrapItem
	{
		switch prediction, failure := p.lookahead.WrapElementAlternatives(p.state); prediction {
		case 0:
			{
				result := NewWrapRef()
				result.SetTextRangeStart(startPos)
				current = result
			}
			current := current.(WrapRef)
			{
				token := p.state.Consume(Token_ID)
				core.AssignToken(current, token, WrapElement_Ref_ID)
				if token != nil {
					current.SetRef(p.referencesConstructor.WrapRefRef(current, token))
				}
			}
		case 1:
			{
				current = NewWrapItem()
				current.SetTextRangeStart(startPos)
				token := p.state.Consume(Token_LBRACE)
				core.AssignToken(current, token, WrapElement_LBRACE)
			}
			{
				p.state.EnterRule(WrapElement_RBRACE)
				result := p.ParseWrapGroup()
				p.state.ExitRule()
				core.MergeTokens(result, current.Tokens())
				current = result
			}
			{
				token := p.state.Consume(Token_RBRACE)
				core.AssignToken(current, token, WrapElement_RBRACE)
			}
		default:
			p.state.AppendError(p.state.Messages().NoViableAlternative(failure), failure.Token)
		}
		if current == nil {
			current = NewWrapItem()
			current.SetTextRangeStart(startPos)
		}
	}
	current.SetTextRangeEnd(p.state.LA(0).Range.End)
	return current
}

func (p *Parser) ParseShadow() Shadow {
	current := NewShadow()
	current.SetTextRangeStart(p.state.LA(1).Range.Start)
	{
		{
			token := p.state.Consume(Keyword_shadow)
			core.AssignToken(current, token, Shadow_shadow)
		}
		{
			p.state.EnterRule(Shadow__LoopEntry)
			result := p.ParseBinary()
			p.state.ExitRule()
			if result != nil {
				current.SetRight(result)
			}
		}
		{
			p.state.Sync(Shadow__LoopEntry)
			for p.lookahead.ShadowItemsLoop(p.state) {
				p.state.EnterRule(Shadow__Basic_2)
				result := p.ParseRefItem()
				p.state.ExitRule()
				if result != nil {
					current.SetItemsItem(result)
				}
				p.state.Sync(Shadow__LoopEntry)
			}
		}
	}
	current.SetTextRangeEnd(p.state.LA(0).Range.End)
	return current
}

func (p *Parser) ParseNest() Nest {
	current := NewNest()
	current.SetTextRangeStart(p.state.LA(1).Range.Start)
	{
		{
			token := p.state.Consume(Keyword_nest)
			core.AssignToken(current, token, Nest_nest)
		}
		{
			token := p.state.Consume(Token_LBRACE)
			core.AssignToken(current, token, Nest_LBRACE)
		}
		p.state.Sync(Nest__LoopEntry)
	loop2:
		for {
			switch prediction, _ := p.lookahead.NestAlternatives(p.state); prediction {
			case 0:
				{
					p.state.EnterRule(Nest__Basic_1)
					result := p.ParseDeclare()
					p.state.ExitRule()
					if result != nil {
						current.SetLocalsItem(result)
					}
				}
			case 1:
				{
					token := p.state.Consume(Token_ID)
					core.AssignToken(current, token, Nest_Ref_ID)
					if token != nil {
						current.SetRef(p.referencesConstructor.NestRef(current, token))
					}
				}
			case 2:
				{
					p.state.EnterRule(Nest__Basic_4)
					result := p.ParseNest()
					p.state.ExitRule()
					if result != nil {
						current.SetChildrenItem(result)
					}
				}
			default:
				break loop2
			}
			p.state.Sync(Nest__LoopEntry)
		}
		{
			token := p.state.Consume(Token_RBRACE)
			core.AssignToken(current, token, Nest_RBRACE)
		}
	}
	current.SetTextRangeEnd(p.state.LA(0).Range.End)
	return current
}

func (p *Parser) ParseAmbig() Ambig {
	current := NewAmbig()
	current.SetTextRangeStart(p.state.LA(1).Range.Start)
	{
		{
			token := p.state.Consume(Keyword_ambig)
			core.AssignToken(current, token, Ambig_ambig)
		}
		switch prediction, failure := p.lookahead.AmbigAlternatives(p.state); prediction {
		case 0:
			{
				p.state.EnterRule(Ambig__Basic_1)
				result := p.ParseAmbigName()
				p.state.ExitRule()
				if result != nil {
					current.SetName(result)
				}
			}
		case 1:
			{
				p.state.EnterRule(Ambig__Basic_3)
				result := p.ParseAmbigRefs()
				p.state.ExitRule()
				if result != nil {
					current.SetRefs(result)
				}
			}
		default:
			p.state.AppendError(p.state.Messages().NoViableAlternative(failure), failure.Token)
		}
	}
	current.SetTextRangeEnd(p.state.LA(0).Range.End)
	return current
}

func (p *Parser) ParseAmbigName() AmbigName {
	current := NewAmbigName()
	current.SetTextRangeStart(p.state.LA(1).Range.Start)
	{
		{
			token := p.state.Consume(Token_ID)
			core.AssignToken(current, token, AmbigName_Name_ID)
			if token != nil {
				current.SetName(token)
			}
		}
		{
			token := p.state.Consume(Token_ID)
			core.AssignToken(current, token, AmbigName_Ref_ID)
			if token != nil {
				current.SetRef(p.referencesConstructor.AmbigNameRef(current, token))
			}
		}
		{
			token := p.state.Consume(Token_FIRST)
			core.AssignToken(current, token, AmbigName_FIRST)
		}
	}
	current.SetTextRangeEnd(p.state.LA(0).Range.End)
	return current
}

func (p *Parser) ParseAmbigRefs() AmbigRefs {
	current := NewAmbigRefs()
	current.SetTextRangeStart(p.state.LA(1).Range.Start)
	{
		{
			token := p.state.Consume(Token_ID)
			core.AssignToken(current, token, AmbigRefs_Ref1_ID)
			if token != nil {
				current.SetRef1(p.referencesConstructor.AmbigRefsRef1(current, token))
			}
		}
		{
			token := p.state.Consume(Token_ID)
			core.AssignToken(current, token, AmbigRefs_Ref_ID)
			if token != nil {
				current.SetRef(p.referencesConstructor.AmbigRefsRef(current, token))
			}
		}
		{
			token := p.state.Consume(Token_SECOND)
			core.AssignToken(current, token, AmbigRefs_SECOND)
		}
	}
	current.SetTextRangeEnd(p.state.LA(0).Range.End)
	return current
}

func (p *Parser) ParseRetype() Retype {
	current := NewRetype()
	current.SetTextRangeStart(p.state.LA(1).Range.Start)
	{
		{
			token := p.state.Consume(Keyword_retype)
			core.AssignToken(current, token, Retype_retype)
		}
		{
			token := p.state.Consume(Token_LBRACE)
			core.AssignToken(current, token, Retype_LBRACE)
		}
		{
			p.state.Sync(Retype__LoopEntry)
			for p.lookahead.RetypeItemsLoop(p.state) {
				p.state.EnterRule(Retype__Basic_1)
				result := p.ParseRetypeItem()
				p.state.ExitRule()
				if result != nil {
					current.SetItemsItem(result)
				}
				p.state.Sync(Retype__LoopEntry)
			}
		}
		{
			token := p.state.Consume(Token_RBRACE)
			core.AssignToken(current, token, Retype_RBRACE)
		}
	}
	current.SetTextRangeEnd(p.state.LA(0).Range.End)
	return current
}

func (p *Parser) ParseRetypeItem() RetypeItem {
	startPos := p.state.LA(1).Range.Start
	var current RetypeItem
	{
		{
			result := NewRetypeWrapper()
			result.SetTextRangeStart(startPos)
			current = result
		}
		current := current.(RetypeWrapper)
		{
			p.state.EnterRule(RetypeItem__Basic_1)
			result := p.ParseRefItem()
			p.state.ExitRule()
			if result != nil {
				current.SetInner(result)
			}
		}
	}
	current.SetTextRangeEnd(p.state.LA(0).Range.End)
	return current
}

func (p *Parser) ParseFQN(current core.CompositeNode) {
	{
		token := p.state.Consume(Token_ID)
		core.AssignToken(current, token, FQN_ID_0)
	}
	p.state.Sync(FQN__LoopEntry)
	for p.lookahead.FQNLoop(p.state) {
		{
			token := p.state.Consume(Token_DOT)
			core.AssignToken(current, token, FQN_DOT)
		}
		{
			token := p.state.Consume(Token_ID)
			core.AssignToken(current, token, FQN_ID_1)
		}
		p.state.Sync(FQN__LoopEntry)
	}
}

var BinaryPrecedence = map[int]parser.InfixPrecedence{
	Keyword_times_Idx: {Level: 0},
	Keyword_plus_Idx:  {Level: 1},
}

func (p *Parser) ParseBinary() Expr {
	var parts []Expr
	var operators []*core.Token
	{
		p.state.EnterRule(Binary__LoopEntry)
		result := p.ParsePrimary()
		p.state.ExitRule()
		parts = append(parts, result)
	}
	p.state.Sync(Binary__LoopEntry)
	for p.lookahead.BinaryLoop(p.state) {
		if token := p.state.Consume(TokenGroup_BinaryOperator); token != nil {
			operators = append(operators, token)
		}
		{
			p.state.EnterRule(Binary__Basic_2)
			result := p.ParsePrimary()
			p.state.ExitRule()
			parts = append(parts, result)
		}
		p.state.Sync(Binary__LoopEntry)
	}
	if len(parts) == 1 {
		// A lone operand is returned unchanged; no binary node is created.
		return parts[0]
	}
	return parser.BuildInfixTree(parts, operators, BinaryPrecedence, func(left Expr, operator *core.Token, right Expr) Expr {
		result := NewBinary()
		if left != nil {
			result.SetLeft(left)
			result.SetTextRangeStart(left.TextRange().Start)
		}
		if operator != nil {
			core.AssignToken(result, operator, Binary_BinaryOperator)
			result.SetOperator(operator)
			result.SetTextRangeEnd(operator.Range.End)
		}
		if right != nil {
			result.SetRight(right)
			result.SetTextRangeEnd(right.TextRange().End)
		}
		return result
	})
}
