// Code generated by fastbelt. DO NOT EDIT.

package token_groups

import (
	"sync"
	"typefox.dev/fastbelt/parser"
)

const (
	StateNumber__Model__Start = iota
	StateNumber__Model__Stop
	StateNumber__A__Start
	StateNumber__A__Stop
	StateNumber__B__Start
	StateNumber__B__Stop
	StateNumber__C__Start
	StateNumber__C__Stop
	StateNumber__D__Start
	StateNumber__D__Stop
	StateNumber__E__Start
	StateNumber__E__Stop
	StateNumber__F__Start
	StateNumber__F__Stop
	StateNumber__G__Start
	StateNumber__G__Stop
	StateNumber__Model__Basic_0
	StateNumber__Model__Basic_1
	StateNumber__Model__Basic_2
	StateNumber__Model__Basic_3
	StateNumber__Model__Basic_4
	StateNumber__Model__Basic_5
	StateNumber__Model__Basic_6
	StateNumber__Model__Basic_7
	StateNumber__Model__Basic_8
	StateNumber__Model__Basic_9
	StateNumber__Model__Basic_10
	StateNumber__Model__Basic_11
	StateNumber__Model__Basic_12
	StateNumber__Model__Basic_13
	StateNumber__Model__Basic_14
	StateNumber__Model__BlockEnd
	StateNumber__A_LETTER_A
	StateNumber__A__Basic_0
	StateNumber__A__Basic_1
	StateNumber__B_LETTER_B
	StateNumber__B__Basic_0
	StateNumber__B__Basic_1
	StateNumber__B_Value_LETTER_B
	StateNumber__B__Basic_2
	StateNumber__B__Basic_3
	StateNumber__B__BlockEnd
	StateNumber__C_LETTER_C
	StateNumber__C__Basic_0
	StateNumber__C__Basic_1
	StateNumber__D_LETTER_D
	StateNumber__D__Basic_0
	StateNumber__D__Basic_1
	StateNumber__D__Basic_2
	StateNumber__E_LETTER_E
	StateNumber__E__Basic_0
	StateNumber__E__Basic_1
	StateNumber__E__Basic_2
	StateNumber__F_LETTER_F
	StateNumber__F__Basic_0
	StateNumber__F__Basic_1
	StateNumber__G_LETTER_G
	StateNumber__G__Basic_0
	StateNumber__G_Value_LETTER_A
	StateNumber__G__Basic_1
	StateNumber__G__Basic_2
	StateNumber__G_Value_LETTER_B
	StateNumber__G__Basic_3
	StateNumber__G__Basic_4
	StateNumber__G__BlockEnd
)

var once sync.Once
var atn *parser.RuntimeATN

func ATN() *parser.RuntimeATN {
	once.Do(func() {
		atn = BuildATN()
	})
	return atn
}
func BuildATN() *parser.RuntimeATN {
	states := make([]*parser.RuntimeATNState, 65)
	states[StateNumber__Model__Start] = parser.NewATNState(StateNumber__Model__Start, parser.ATNRuleStart, true)
	states[StateNumber__Model__Stop] = parser.NewATNState(StateNumber__Model__Stop, parser.ATNRuleStop, false)
	states[StateNumber__A__Start] = parser.NewATNState(StateNumber__A__Start, parser.ATNRuleStart, true)
	states[StateNumber__A__Stop] = parser.NewATNState(StateNumber__A__Stop, parser.ATNRuleStop, false)
	states[StateNumber__B__Start] = parser.NewATNState(StateNumber__B__Start, parser.ATNRuleStart, true)
	states[StateNumber__B__Stop] = parser.NewATNState(StateNumber__B__Stop, parser.ATNRuleStop, false)
	states[StateNumber__C__Start] = parser.NewATNState(StateNumber__C__Start, parser.ATNRuleStart, true)
	states[StateNumber__C__Stop] = parser.NewATNState(StateNumber__C__Stop, parser.ATNRuleStop, false)
	states[StateNumber__D__Start] = parser.NewATNState(StateNumber__D__Start, parser.ATNRuleStart, true)
	states[StateNumber__D__Stop] = parser.NewATNState(StateNumber__D__Stop, parser.ATNRuleStop, false)
	states[StateNumber__E__Start] = parser.NewATNState(StateNumber__E__Start, parser.ATNRuleStart, true)
	states[StateNumber__E__Stop] = parser.NewATNState(StateNumber__E__Stop, parser.ATNRuleStop, false)
	states[StateNumber__F__Start] = parser.NewATNState(StateNumber__F__Start, parser.ATNRuleStart, true)
	states[StateNumber__F__Stop] = parser.NewATNState(StateNumber__F__Stop, parser.ATNRuleStop, false)
	states[StateNumber__G__Start] = parser.NewATNState(StateNumber__G__Start, parser.ATNRuleStart, true)
	states[StateNumber__G__Stop] = parser.NewATNState(StateNumber__G__Stop, parser.ATNRuleStop, false)
	states[StateNumber__Model__Basic_0] = parser.NewATNState(StateNumber__Model__Basic_0, parser.ATNBasic, true)
	states[StateNumber__Model__Basic_1] = parser.NewATNState(StateNumber__Model__Basic_1, parser.ATNBasic, true)
	states[StateNumber__Model__Basic_2] = parser.NewATNState(StateNumber__Model__Basic_2, parser.ATNBasic, true)
	states[StateNumber__Model__Basic_3] = parser.NewATNState(StateNumber__Model__Basic_3, parser.ATNBasic, true)
	states[StateNumber__Model__Basic_4] = parser.NewATNState(StateNumber__Model__Basic_4, parser.ATNBasic, true)
	states[StateNumber__Model__Basic_5] = parser.NewATNState(StateNumber__Model__Basic_5, parser.ATNBasic, true)
	states[StateNumber__Model__Basic_6] = parser.NewATNState(StateNumber__Model__Basic_6, parser.ATNBasic, true)
	states[StateNumber__Model__Basic_7] = parser.NewATNState(StateNumber__Model__Basic_7, parser.ATNBasic, true)
	states[StateNumber__Model__Basic_8] = parser.NewATNState(StateNumber__Model__Basic_8, parser.ATNBasic, true)
	states[StateNumber__Model__Basic_9] = parser.NewATNState(StateNumber__Model__Basic_9, parser.ATNBasic, true)
	states[StateNumber__Model__Basic_10] = parser.NewATNState(StateNumber__Model__Basic_10, parser.ATNBasic, true)
	states[StateNumber__Model__Basic_11] = parser.NewATNState(StateNumber__Model__Basic_11, parser.ATNBasic, true)
	states[StateNumber__Model__Basic_12] = parser.NewATNState(StateNumber__Model__Basic_12, parser.ATNBasic, true)
	states[StateNumber__Model__Basic_13] = parser.NewATNState(StateNumber__Model__Basic_13, parser.ATNBasic, true)
	states[StateNumber__Model__Basic_14] = parser.NewATNState(StateNumber__Model__Basic_14, parser.ATNBasic, true).SetDecision(0)
	states[StateNumber__Model__BlockEnd] = parser.NewATNState(StateNumber__Model__BlockEnd, parser.ATNBlockEnd, true)
	states[StateNumber__A_LETTER_A] = parser.NewATNState(StateNumber__A_LETTER_A, parser.ATNBasic, false)
	states[StateNumber__A__Basic_0] = parser.NewATNState(StateNumber__A__Basic_0, parser.ATNBasic, false)
	states[StateNumber__A__Basic_1] = parser.NewATNState(StateNumber__A__Basic_1, parser.ATNBasic, true)
	states[StateNumber__B_LETTER_B] = parser.NewATNState(StateNumber__B_LETTER_B, parser.ATNBasic, false)
	states[StateNumber__B__Basic_0] = parser.NewATNState(StateNumber__B__Basic_0, parser.ATNBasic, false)
	states[StateNumber__B__Basic_1] = parser.NewATNState(StateNumber__B__Basic_1, parser.ATNBasic, true)
	states[StateNumber__B_Value_LETTER_B] = parser.NewATNState(StateNumber__B_Value_LETTER_B, parser.ATNBasic, false)
	states[StateNumber__B__Basic_2] = parser.NewATNState(StateNumber__B__Basic_2, parser.ATNBasic, true)
	states[StateNumber__B__Basic_3] = parser.NewATNState(StateNumber__B__Basic_3, parser.ATNBasic, true).SetDecision(1)
	states[StateNumber__B__BlockEnd] = parser.NewATNState(StateNumber__B__BlockEnd, parser.ATNBlockEnd, true)
	states[StateNumber__C_LETTER_C] = parser.NewATNState(StateNumber__C_LETTER_C, parser.ATNBasic, false)
	states[StateNumber__C__Basic_0] = parser.NewATNState(StateNumber__C__Basic_0, parser.ATNBasic, false)
	states[StateNumber__C__Basic_1] = parser.NewATNState(StateNumber__C__Basic_1, parser.ATNBasic, true)
	states[StateNumber__D_LETTER_D] = parser.NewATNState(StateNumber__D_LETTER_D, parser.ATNBasic, false)
	states[StateNumber__D__Basic_0] = parser.NewATNState(StateNumber__D__Basic_0, parser.ATNBasic, false)
	states[StateNumber__D__Basic_1] = parser.NewATNState(StateNumber__D__Basic_1, parser.ATNBasic, true)
	states[StateNumber__D__Basic_2] = parser.NewATNState(StateNumber__D__Basic_2, parser.ATNBasic, true).SetDecision(2)
	states[StateNumber__E_LETTER_E] = parser.NewATNState(StateNumber__E_LETTER_E, parser.ATNBasic, false)
	states[StateNumber__E__Basic_0] = parser.NewATNState(StateNumber__E__Basic_0, parser.ATNBasic, false)
	states[StateNumber__E__Basic_1] = parser.NewATNState(StateNumber__E__Basic_1, parser.ATNBasic, false)
	states[StateNumber__E__Basic_2] = parser.NewATNState(StateNumber__E__Basic_2, parser.ATNBasic, true)
	states[StateNumber__F_LETTER_F] = parser.NewATNState(StateNumber__F_LETTER_F, parser.ATNBasic, false)
	states[StateNumber__F__Basic_0] = parser.NewATNState(StateNumber__F__Basic_0, parser.ATNBasic, false)
	states[StateNumber__F__Basic_1] = parser.NewATNState(StateNumber__F__Basic_1, parser.ATNBasic, true)
	states[StateNumber__G_LETTER_G] = parser.NewATNState(StateNumber__G_LETTER_G, parser.ATNBasic, false)
	states[StateNumber__G__Basic_0] = parser.NewATNState(StateNumber__G__Basic_0, parser.ATNBasic, false)
	states[StateNumber__G_Value_LETTER_A] = parser.NewATNState(StateNumber__G_Value_LETTER_A, parser.ATNBasic, false)
	states[StateNumber__G__Basic_1] = parser.NewATNState(StateNumber__G__Basic_1, parser.ATNBasic, true)
	states[StateNumber__G__Basic_2] = parser.NewATNState(StateNumber__G__Basic_2, parser.ATNBasic, false)
	states[StateNumber__G_Value_LETTER_B] = parser.NewATNState(StateNumber__G_Value_LETTER_B, parser.ATNBasic, false)
	states[StateNumber__G__Basic_3] = parser.NewATNState(StateNumber__G__Basic_3, parser.ATNBasic, true)
	states[StateNumber__G__Basic_4] = parser.NewATNState(StateNumber__G__Basic_4, parser.ATNBasic, true).SetDecision(3)
	states[StateNumber__G__BlockEnd] = parser.NewATNState(StateNumber__G__BlockEnd, parser.ATNBlockEnd, true)
	states[StateNumber__Model__Start].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Model__Basic_14]),
	)
	states[StateNumber__A__Start].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__A_LETTER_A]),
	)
	states[StateNumber__B__Start].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__B_LETTER_B]),
	)
	states[StateNumber__C__Start].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__C_LETTER_C]),
	)
	states[StateNumber__D__Start].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__D_LETTER_D]),
	)
	states[StateNumber__E__Start].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__E_LETTER_E]),
	)
	states[StateNumber__F__Start].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__F_LETTER_F]),
	)
	states[StateNumber__G__Start].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__G_LETTER_G]),
	)
	states[StateNumber__Model__Basic_0].AppendTransitions(
		parser.NewRuleTransition(states[StateNumber__A__Start], states[StateNumber__Model__Basic_1], nil),
	)
	states[StateNumber__Model__Basic_1].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Model__BlockEnd]),
	)
	states[StateNumber__Model__Basic_2].AppendTransitions(
		parser.NewRuleTransition(states[StateNumber__B__Start], states[StateNumber__Model__Basic_3], nil),
	)
	states[StateNumber__Model__Basic_3].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Model__BlockEnd]),
	)
	states[StateNumber__Model__Basic_4].AppendTransitions(
		parser.NewRuleTransition(states[StateNumber__C__Start], states[StateNumber__Model__Basic_5], nil),
	)
	states[StateNumber__Model__Basic_5].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Model__BlockEnd]),
	)
	states[StateNumber__Model__Basic_6].AppendTransitions(
		parser.NewRuleTransition(states[StateNumber__D__Start], states[StateNumber__Model__Basic_7], nil),
	)
	states[StateNumber__Model__Basic_7].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Model__BlockEnd]),
	)
	states[StateNumber__Model__Basic_8].AppendTransitions(
		parser.NewRuleTransition(states[StateNumber__E__Start], states[StateNumber__Model__Basic_9], nil),
	)
	states[StateNumber__Model__Basic_9].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Model__BlockEnd]),
	)
	states[StateNumber__Model__Basic_10].AppendTransitions(
		parser.NewRuleTransition(states[StateNumber__F__Start], states[StateNumber__Model__Basic_11], nil),
	)
	states[StateNumber__Model__Basic_11].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Model__BlockEnd]),
	)
	states[StateNumber__Model__Basic_12].AppendTransitions(
		parser.NewRuleTransition(states[StateNumber__G__Start], states[StateNumber__Model__Basic_13], nil),
	)
	states[StateNumber__Model__Basic_13].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Model__BlockEnd]),
	)
	states[StateNumber__Model__Basic_14].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Model__Basic_0]),
		parser.NewEpsilonTransition(states[StateNumber__Model__Basic_2]),
		parser.NewEpsilonTransition(states[StateNumber__Model__Basic_4]),
		parser.NewEpsilonTransition(states[StateNumber__Model__Basic_6]),
		parser.NewEpsilonTransition(states[StateNumber__Model__Basic_8]),
		parser.NewEpsilonTransition(states[StateNumber__Model__Basic_10]),
		parser.NewEpsilonTransition(states[StateNumber__Model__Basic_12]),
	)
	states[StateNumber__Model__BlockEnd].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__Model__Stop]),
	)
	states[StateNumber__A_LETTER_A].AppendTransitions(
		parser.NewAtomTransition(states[StateNumber__A__Basic_0], Token_LETTER_A, nil),
	)
	states[StateNumber__A__Basic_0].AppendTransitions(
		parser.NewAtomTransition(states[StateNumber__A__Basic_1], TokenGroup_Identifier, nil),
	)
	states[StateNumber__A__Basic_1].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__A__Stop]),
	)
	states[StateNumber__B_LETTER_B].AppendTransitions(
		parser.NewAtomTransition(states[StateNumber__B__Basic_3], Token_LETTER_B, nil),
	)
	states[StateNumber__B__Basic_0].AppendTransitions(
		parser.NewAtomTransition(states[StateNumber__B__Basic_1], TokenGroup_Identifier, nil),
	)
	states[StateNumber__B__Basic_1].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__B__BlockEnd]),
	)
	states[StateNumber__B_Value_LETTER_B].AppendTransitions(
		parser.NewAtomTransition(states[StateNumber__B__Basic_2], Token_LETTER_B, nil),
	)
	states[StateNumber__B__Basic_2].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__B__BlockEnd]),
	)
	states[StateNumber__B__Basic_3].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__B__Basic_0]),
		parser.NewEpsilonTransition(states[StateNumber__B_Value_LETTER_B]),
	)
	states[StateNumber__B__BlockEnd].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__B__Stop]),
	)
	states[StateNumber__C_LETTER_C].AppendTransitions(
		parser.NewAtomTransition(states[StateNumber__C__Basic_0], Token_LETTER_C, nil),
	)
	states[StateNumber__C__Basic_0].AppendTransitions(
		parser.NewAtomTransition(states[StateNumber__C__Basic_1], TokenGroup_NestedIdentifier, nil),
	)
	states[StateNumber__C__Basic_1].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__C__Stop]),
	)
	states[StateNumber__D_LETTER_D].AppendTransitions(
		parser.NewAtomTransition(states[StateNumber__D__Basic_2], Token_LETTER_D, nil),
	)
	states[StateNumber__D__Basic_0].AppendTransitions(
		parser.NewAtomTransition(states[StateNumber__D__Basic_1], TokenGroup_Identifier, nil),
	)
	states[StateNumber__D__Basic_1].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__D__Stop]),
	)
	states[StateNumber__D__Basic_2].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__D__Basic_0]),
		parser.NewEpsilonTransition(states[StateNumber__D__Basic_1]),
	)
	states[StateNumber__E_LETTER_E].AppendTransitions(
		parser.NewAtomTransition(states[StateNumber__E__Basic_0], Token_LETTER_E, nil),
	)
	states[StateNumber__E__Basic_0].AppendTransitions(
		parser.NewAtomTransition(states[StateNumber__E__Basic_1], TokenGroup_Identifier, nil),
	)
	states[StateNumber__E__Basic_1].AppendTransitions(
		parser.NewAtomTransition(states[StateNumber__E__Basic_2], TokenGroup_NestedIdentifier, nil),
	)
	states[StateNumber__E__Basic_2].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__E__Stop]),
	)
	states[StateNumber__F_LETTER_F].AppendTransitions(
		parser.NewAtomTransition(states[StateNumber__F__Basic_0], Token_LETTER_F, nil),
	)
	states[StateNumber__F__Basic_0].AppendTransitions(
		parser.NewAtomTransition(states[StateNumber__F__Basic_1], TokenGroup_KeywordGroup, nil),
	)
	states[StateNumber__F__Basic_1].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__F__Stop]),
	)
	states[StateNumber__G_LETTER_G].AppendTransitions(
		parser.NewAtomTransition(states[StateNumber__G__Basic_4], Token_LETTER_G, nil),
	)
	states[StateNumber__G__Basic_0].AppendTransitions(
		parser.NewAtomTransition(states[StateNumber__G_Value_LETTER_A], TokenGroup_Identifier, nil),
	)
	states[StateNumber__G_Value_LETTER_A].AppendTransitions(
		parser.NewAtomTransition(states[StateNumber__G__Basic_1], Token_LETTER_A, nil),
	)
	states[StateNumber__G__Basic_1].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__G__BlockEnd]),
	)
	states[StateNumber__G__Basic_2].AppendTransitions(
		parser.NewAtomTransition(states[StateNumber__G_Value_LETTER_B], TokenGroup_Identifier, nil),
	)
	states[StateNumber__G_Value_LETTER_B].AppendTransitions(
		parser.NewAtomTransition(states[StateNumber__G__Basic_3], Token_LETTER_B, nil),
	)
	states[StateNumber__G__Basic_3].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__G__BlockEnd]),
	)
	states[StateNumber__G__Basic_4].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__G__Basic_0]),
		parser.NewEpsilonTransition(states[StateNumber__G__Basic_2]),
	)
	states[StateNumber__G__BlockEnd].AppendTransitions(
		parser.NewEpsilonTransition(states[StateNumber__G__Stop]),
	)
	decisionStates := make([]*parser.RuntimeATNState, 4)
	decisionStates[0] = states[StateNumber__Model__Basic_14]
	decisionStates[1] = states[StateNumber__B__Basic_3]
	decisionStates[2] = states[StateNumber__D__Basic_2]
	decisionStates[3] = states[StateNumber__G__Basic_4]
	decisionMap := make([]*parser.RuntimeATNState, 4)
	decisionMap[0] = states[StateNumber__Model__Basic_14]
	decisionMap[1] = states[StateNumber__B__Basic_3]
	decisionMap[2] = states[StateNumber__D__Basic_2]
	decisionMap[3] = states[StateNumber__G__Basic_4]
	return parser.NewRuntimeATN(states, decisionStates, decisionMap)
}
