// Code generated by typefox.dev/fastbelt/cmd/fastbelt. DO NOT EDIT.

package token_groups

import (
	"strings"
	core "typefox.dev/fastbelt"
	"typefox.dev/fastbelt/lexer"
	"unicode/utf8"
)

const Keyword_a_Idx = 1

var Keyword_a = core.NewTokenType(
	Keyword_a_Idx,
	"a",
	"a",
	0,
	core.TokenKindKeyword,
	0,
	false,
	func(text string, offset int) int {
		if strings.HasPrefix(text[offset:], "a") {
			return 1
		}
		return 0
	},
	[]rune{'a'},
)

const Keyword_b_Idx = 2

var Keyword_b = core.NewTokenType(
	Keyword_b_Idx,
	"b",
	"b",
	0,
	core.TokenKindKeyword,
	0,
	false,
	func(text string, offset int) int {
		if strings.HasPrefix(text[offset:], "b") {
			return 1
		}
		return 0
	},
	[]rune{'b'},
)

const Keyword_c_Idx = 3

var Keyword_c = core.NewTokenType(
	Keyword_c_Idx,
	"c",
	"c",
	0,
	core.TokenKindKeyword,
	0,
	false,
	func(text string, offset int) int {
		if strings.HasPrefix(text[offset:], "c") {
			return 1
		}
		return 0
	},
	[]rune{'c'},
)

const Keyword_d_Idx = 4

var Keyword_d = core.NewTokenType(
	Keyword_d_Idx,
	"d",
	"d",
	0,
	core.TokenKindKeyword,
	0,
	false,
	func(text string, offset int) int {
		if strings.HasPrefix(text[offset:], "d") {
			return 1
		}
		return 0
	},
	[]rune{'d'},
)

const Keyword_e_Idx = 5

var Keyword_e = core.NewTokenType(
	Keyword_e_Idx,
	"e",
	"e",
	0,
	core.TokenKindKeyword,
	0,
	false,
	func(text string, offset int) int {
		if strings.HasPrefix(text[offset:], "e") {
			return 1
		}
		return 0
	},
	[]rune{'e'},
)

const Keyword_f_Idx = 6

var Keyword_f = core.NewTokenType(
	Keyword_f_Idx,
	"f",
	"f",
	0,
	core.TokenKindKeyword,
	0,
	false,
	func(text string, offset int) int {
		if strings.HasPrefix(text[offset:], "f") {
			return 1
		}
		return 0
	},
	[]rune{'f'},
)

const Keyword_g_Idx = 7

var Keyword_g = core.NewTokenType(
	Keyword_g_Idx,
	"g",
	"g",
	0,
	core.TokenKindKeyword,
	0,
	false,
	func(text string, offset int) int {
		if strings.HasPrefix(text[offset:], "g") {
			return 1
		}
		return 0
	},
	[]rune{'g'},
)

const Keyword_h_Idx = 8

var Keyword_h = core.NewTokenType(
	Keyword_h_Idx,
	"h",
	"h",
	0,
	core.TokenKindKeyword,
	0,
	false,
	func(text string, offset int) int {
		if strings.HasPrefix(text[offset:], "h") {
			return 1
		}
		return 0
	},
	[]rune{'h'},
)

const Keyword_nested_Idx = 9

var Keyword_nested = core.NewTokenType(
	Keyword_nested_Idx,
	"nested",
	"nested",
	0,
	core.TokenKindKeyword,
	0,
	false,
	func(text string, offset int) int {
		if strings.HasPrefix(text[offset:], "nested") {
			return 6
		}
		return 0
	},
	[]rune{'n'},
)

const Keyword_one_Idx = 10

var Keyword_one = core.NewTokenType(
	Keyword_one_Idx,
	"one",
	"one",
	0,
	core.TokenKindKeyword,
	0,
	false,
	func(text string, offset int) int {
		if strings.HasPrefix(text[offset:], "one") {
			return 3
		}
		return 0
	},
	[]rune{'o'},
)

const Keyword_two_Idx = 11

var Keyword_two = core.NewTokenType(
	Keyword_two_Idx,
	"two",
	"two",
	0,
	core.TokenKindKeyword,
	0,
	false,
	func(text string, offset int) int {
		if strings.HasPrefix(text[offset:], "two") {
			return 3
		}
		return 0
	},
	[]rune{'t'},
)

const Token_ID_Idx = 12

var Token_ID = core.NewTokenType(
	Token_ID_Idx,
	"ID",
	"ID",
	0,
	core.TokenKindToken,
	0,
	false,
	func(s string, offset int) int {
		input := s[offset:]
		length := len(input)
		state := 0
		acceptedIndex := 0
		index := 0
	loop:
		for index < length {
			r, runeSize := utf8.DecodeRuneInString(input[index:])
			switch state {
			case 0:
				nextState := -1
				next := Token_ID_Next[0]
				lookup := Token_ID_Lookup[0]
				for i, lowHigh := range lookup {
					if rune(lowHigh&0xFFFFFFFF) <= r && r <= rune(lowHigh>>32) {
						nextState = next[i]
						break
					}
				}
				if nextState > -1 {
					state = nextState
				} else {
					break loop
				}
			case 1:
				nextState := -1
				next := Token_ID_Next[1]
				lookup := Token_ID_Lookup[1]
				for i, lowHigh := range lookup {
					if rune(lowHigh&0xFFFFFFFF) <= r && r <= rune(lowHigh>>32) {
						nextState = next[i]
						break
					}
				}
				if nextState > -1 {
					state = nextState
				} else {
					break loop
				}
			default:
				break loop
			}
			index += runeSize
			if Token_ID_Accepting[state] {
				acceptedIndex = index
			}
		}
		return acceptedIndex
	},
	[]rune{'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'},
)
var Token_ID_Lookup = [][]int64{
	{0x0000005A00000041, 0x0000005F0000005F, 0x0000007A00000061},
	{0x0000003900000030, 0x0000005A00000041, 0x0000005F0000005F, 0x0000007A00000061},
}
var Token_ID_Next = [][]int{
	{1, 1, 1},
	{1, 1, 1, 1},
}
var Token_ID_Accepting = [2]bool{
	1: true,
}

const Token_INT_Idx = 13

var Token_INT = core.NewTokenType(
	Token_INT_Idx,
	"INT",
	"INT",
	0,
	core.TokenKindToken,
	0,
	false,
	func(s string, offset int) int {
		input := s[offset:]
		length := len(input)
		state := 0
		acceptedIndex := 0
		index := 0
	loop:
		for index < length {
			r, runeSize := utf8.DecodeRuneInString(input[index:])
			switch state {
			case 0:
				nextState := -1
				next := Token_INT_Next[0]
				lookup := Token_INT_Lookup[0]
				for i, lowHigh := range lookup {
					if rune(lowHigh&0xFFFFFFFF) <= r && r <= rune(lowHigh>>32) {
						nextState = next[i]
						break
					}
				}
				if nextState > -1 {
					state = nextState
				} else {
					break loop
				}
			case 1:
				nextState := -1
				next := Token_INT_Next[1]
				lookup := Token_INT_Lookup[1]
				for i, lowHigh := range lookup {
					if rune(lowHigh&0xFFFFFFFF) <= r && r <= rune(lowHigh>>32) {
						nextState = next[i]
						break
					}
				}
				if nextState > -1 {
					state = nextState
				} else {
					break loop
				}
			default:
				break loop
			}
			index += runeSize
			if Token_INT_Accepting[state] {
				acceptedIndex = index
			}
		}
		return acceptedIndex
	},
	[]rune{'0', '1', '2', '3', '4', '5', '6', '7', '8', '9'},
)
var Token_INT_Lookup = [][]int64{
	{0x0000003900000030},
	{0x0000003900000030},
}
var Token_INT_Next = [][]int{
	{1},
	{1},
}
var Token_INT_Accepting = [2]bool{
	1: true,
}

const Token_WS_Idx = 14

var Token_WS = core.NewTokenType(
	Token_WS_Idx,
	"WS",
	"WS",
	core.SkippedGroup,
	core.TokenKindToken,
	0,
	false,
	func(s string, offset int) int {
		input := s[offset:]
		length := len(input)
		state := 0
		acceptedIndex := 0
		index := 0
	loop:
		for index < length {
			r, runeSize := utf8.DecodeRuneInString(input[index:])
			switch state {
			case 0:
				nextState := -1
				next := Token_WS_Next[0]
				lookup := Token_WS_Lookup[0]
				for i, lowHigh := range lookup {
					if rune(lowHigh&0xFFFFFFFF) <= r && r <= rune(lowHigh>>32) {
						nextState = next[i]
						break
					}
				}
				if nextState > -1 {
					state = nextState
				} else {
					break loop
				}
			case 1:
				nextState := -1
				next := Token_WS_Next[1]
				lookup := Token_WS_Lookup[1]
				for i, lowHigh := range lookup {
					if rune(lowHigh&0xFFFFFFFF) <= r && r <= rune(lowHigh>>32) {
						nextState = next[i]
						break
					}
				}
				if nextState > -1 {
					state = nextState
				} else {
					break loop
				}
			default:
				break loop
			}
			index += runeSize
			if Token_WS_Accepting[state] {
				acceptedIndex = index
			}
		}
		return acceptedIndex
	},
	[]rune{'\u0009', '\u000A', '\u000C', '\u000D', ' '},
)
var Token_WS_Lookup = [][]int64{
	{0x0000000A00000009, 0x0000000D0000000C, 0x0000002000000020},
	{0x0000000A00000009, 0x0000000D0000000C, 0x0000002000000020},
}
var Token_WS_Next = [][]int{
	{1, 1, 1},
	{1, 1, 1},
}
var Token_WS_Accepting = [2]bool{
	1: true,
}

const Token_Identifier_Idx = 15

var Token_Identifier = core.NewTokenGroup(
	Token_Identifier_Idx,
	"Identifier",
	"Identifier",
	[]*core.TokenType{
		Keyword_a,
		Token_ID,
		Token_INT,
	},
)

const Token_KeywordGroup_Idx = 16

var Token_KeywordGroup = core.NewTokenGroup(
	Token_KeywordGroup_Idx,
	"KeywordGroup",
	"KeywordGroup",
	[]*core.TokenType{
		Keyword_one,
		Keyword_two,
	},
)

const Token_NestedIdentifier_Idx = 17

var Token_NestedIdentifier = core.NewTokenGroup(
	Token_NestedIdentifier_Idx,
	"NestedIdentifier",
	"NestedIdentifier",
	[]*core.TokenType{
		Keyword_nested,
		Token_Identifier,
	},
)

const Token_RegexGroup_Idx = 18

var Token_RegexGroup = core.NewTokenGroup(
	Token_RegexGroup_Idx,
	"RegexGroup",
	"RegexGroup",
	[]*core.TokenType{
		Keyword_one,
		Keyword_two,
	},
)

func NewLexer() lexer.Lexer {
	return lexer.NewDefaultLexer(
		Keyword_a,
		Keyword_b,
		Keyword_c,
		Keyword_d,
		Keyword_e,
		Keyword_f,
		Keyword_g,
		Keyword_h,
		Keyword_nested,
		Keyword_one,
		Keyword_two,
		Token_ID,
		Token_INT,
		Token_WS,
	)
}
