// Code generated by typefox.dev/fastbelt/cmd/fastbelt. DO NOT EDIT.

package token_groups

import (
	core "typefox.dev/fastbelt"
	"typefox.dev/fastbelt/lexer"
	"typefox.dev/fastbelt/parser"
	"typefox.dev/fastbelt/util/service"
)

// SetupGeneratedServices sets up the generated services for this grammar.
// If any service is already set, it's not overwritten.
func SetupGeneratedServices(sc *service.Container) {
	if !service.Has[TokenGroupsScopeProvider](sc) {
		service.Put(sc, NewDefaultTokenGroupsScopeProvider(sc))
	}
	if !service.Has[TokenGroupsReferenceLinker](sc) {
		service.Put(sc, NewDefaultTokenGroupsReferenceLinker(sc))
	}
	if !service.Has[TokenGroupsReferencesConstructor](sc) {
		service.Put(sc, NewDefaultTokenGroupsReferencesConstructor(sc))
	}
	if !service.Has[TokenGroupsParserLookahead](sc) {
		service.Put(sc, NewDefaultTokenGroupsParserLookahead())
	}
	if !service.Has[lexer.Lexer](sc) {
		service.Put(sc, NewLexer())
	}
	if !service.Has[parser.Parser](sc) {
		service.Put[parser.Parser](sc, NewParser(sc))
	}
	if !service.Has[parser.ErrorRecoveryStrategy](sc) {
		service.Put[parser.ErrorRecoveryStrategy](sc, parser.NewDefaultErrorRecovery())
	}
	if !service.Has[parser.ErrorMessageProvider](sc) {
		service.Put[parser.ErrorMessageProvider](sc, parser.NewDefaultErrorMessageProvider())
	}
	if !service.Has[core.SymbolContainers](sc) {
		service.Put[core.SymbolContainers](sc, NewSymbolContainers())
	}
}

// SetupGeneratedServerServices sets up the generated language server services for this grammar.
// If any service is already set, it's not overwritten.
func SetupGeneratedServerServices(sc *service.Container) {
	if !service.Has[TokenGroupsCompletionFilter](sc) {
		service.Put(sc, NewDefaultTokenGroupsCompletionFilter())
	}
	if !service.Has[parser.LanguageCompletionAdapter](sc) {
		service.Put[parser.LanguageCompletionAdapter](sc, NewTokenGroupsCompletionAdapter(sc))
	}
}
