// Code generated by typefox.dev/fastbelt/cmd/fastbelt. DO NOT EDIT.

package json

import (
	"fmt"
	"unique"

	core "typefox.dev/fastbelt"
)

type Bools interface {
	core.AstNode

	IsBools()
	IsBool() bool
	BoolToken() *core.Token
	SetBool(value *core.Token)
	IsToken() bool
	TokenToken() *core.Token
	SetToken(value *core.Token)
	IsAux() bool
	AuxToken() *core.Token
	SetAux(value *core.Token)
	IsCore() bool
	CoreToken() *core.Token
	SetCore(value *core.Token)
	IsErr() bool
	ErrToken() *core.Token
	SetErr(value *core.Token)
	IsNode() bool
	NodeToken() *core.Token
	SetNode(value *core.Token)
	IsThis() bool
	ThisToken() *core.Token
	SetThis(value *core.Token)
	IsType() bool
	TypeToken() *core.Token
	SetType(value *core.Token)
	IsUtil() bool
	UtilToken() *core.Token
	SetUtil(value *core.Token)
}

func NewBools() Bools {
	return &BoolsImpl{}
}

type BoolsData struct {
	bool  *core.Token
	token *core.Token
	aux   *core.Token
	core  *core.Token
	err   *core.Token
	node  *core.Token
	this  *core.Token
	_Type *core.Token
	util  *core.Token
}

func (i *BoolsData) IsBools() {}

func (i *BoolsData) ForEachNode(fn func(core.AstNode, unique.Handle[string], int)) {
}

func (i *BoolsData) ForEachReference(fn func(core.UntypedReference, unique.Handle[string], int)) {
}

func (i *BoolsData) IsBool() bool {
	return i != nil && i.bool != nil
}

func (i *BoolsData) BoolToken() *core.Token {
	return i.bool
}

func (i *BoolsData) SetBool(value *core.Token) {
	i.bool = value
}

func (i *BoolsData) IsToken() bool {
	return i != nil && i.token != nil
}

func (i *BoolsData) TokenToken() *core.Token {
	return i.token
}

func (i *BoolsData) SetToken(value *core.Token) {
	i.token = value
}

func (i *BoolsData) IsAux() bool {
	return i != nil && i.aux != nil
}

func (i *BoolsData) AuxToken() *core.Token {
	return i.aux
}

func (i *BoolsData) SetAux(value *core.Token) {
	i.aux = value
}

func (i *BoolsData) IsCore() bool {
	return i != nil && i.core != nil
}

func (i *BoolsData) CoreToken() *core.Token {
	return i.core
}

func (i *BoolsData) SetCore(value *core.Token) {
	i.core = value
}

func (i *BoolsData) IsErr() bool {
	return i != nil && i.err != nil
}

func (i *BoolsData) ErrToken() *core.Token {
	return i.err
}

func (i *BoolsData) SetErr(value *core.Token) {
	i.err = value
}

func (i *BoolsData) IsNode() bool {
	return i != nil && i.node != nil
}

func (i *BoolsData) NodeToken() *core.Token {
	return i.node
}

func (i *BoolsData) SetNode(value *core.Token) {
	i.node = value
}

func (i *BoolsData) IsThis() bool {
	return i != nil && i.this != nil
}

func (i *BoolsData) ThisToken() *core.Token {
	return i.this
}

func (i *BoolsData) SetThis(value *core.Token) {
	i.this = value
}

func (i *BoolsData) IsType() bool {
	return i != nil && i._Type != nil
}

func (i *BoolsData) TypeToken() *core.Token {
	return i._Type
}

func (i *BoolsData) SetType(value *core.Token) {
	i._Type = value
}

func (i *BoolsData) IsUtil() bool {
	return i != nil && i.util != nil
}

func (i *BoolsData) UtilToken() *core.Token {
	return i.util
}

func (i *BoolsData) SetUtil(value *core.Token) {
	i.util = value
}

type BoolsImpl struct {
	core.AstNodeBase
	BoolsData
}

func (i *BoolsImpl) ForEachNode(fn func(core.AstNode, unique.Handle[string], int)) {
	i.BoolsData.ForEachNode(fn)
}

func (i *BoolsImpl) ForEachReference(fn func(core.UntypedReference, unique.Handle[string], int)) {
	i.BoolsData.ForEachReference(fn)
}

func (i *BoolsImpl) Resolve(path core.FragmentPath) (core.AstNode, error) {
	if path.Empty() {
		return i, nil
	}
	field, _ := path.Head()
	switch field {
	case fieldNameAux:
		return nil, fmt.Errorf("BoolsImpl.Resolve: field 'aux' holds a primitive value instead of an ast node")
	case fieldNameBool:
		return nil, fmt.Errorf("BoolsImpl.Resolve: field 'bool' holds a primitive value instead of an ast node")
	case fieldNameCore:
		return nil, fmt.Errorf("BoolsImpl.Resolve: field 'core' holds a primitive value instead of an ast node")
	case fieldNameErr:
		return nil, fmt.Errorf("BoolsImpl.Resolve: field 'err' holds a primitive value instead of an ast node")
	case fieldNameNode:
		return nil, fmt.Errorf("BoolsImpl.Resolve: field 'node' holds a primitive value instead of an ast node")
	case fieldNameThis:
		return nil, fmt.Errorf("BoolsImpl.Resolve: field 'this' holds a primitive value instead of an ast node")
	case fieldNameToken:
		return nil, fmt.Errorf("BoolsImpl.Resolve: field 'token' holds a primitive value instead of an ast node")
	case fieldNameType:
		return nil, fmt.Errorf("BoolsImpl.Resolve: field '_Type' holds a primitive value instead of an ast node")
	case fieldNameUtil:
		return nil, fmt.Errorf("BoolsImpl.Resolve: field 'util' holds a primitive value instead of an ast node")
	default:
		nodePath, _ := core.PathOf(i)
		return nil, fmt.Errorf("BoolsImpl.Resolve: field '%s' does not exist in node '%s' of type 'Bools'", field.Value(), nodePath)
	}
}

type Strings interface {
	core.AstNode

	IsStrings()
	String() string
	StringToken() *core.Token
	SetString(value *core.Token)
	Token() string
	TokenToken() *core.Token
	SetToken(value *core.Token)
	I() string
	IToken() *core.Token
	SetI(value *core.Token)
	J() string
	JToken() *core.Token
	SetJ(value *core.Token)
	Aux() string
	AuxToken() *core.Token
	SetAux(value *core.Token)
	Core() string
	CoreToken() *core.Token
	SetCore(value *core.Token)
	Err() string
	ErrToken() *core.Token
	SetErr(value *core.Token)
	Node() string
	NodeToken() *core.Token
	SetNode(value *core.Token)
	This() string
	ThisToken() *core.Token
	SetThis(value *core.Token)
	Type() string
	TypeToken() *core.Token
	SetType(value *core.Token)
	Util() string
	UtilToken() *core.Token
	SetUtil(value *core.Token)
}

func NewStrings() Strings {
	return &StringsImpl{}
}

type StringsData struct {
	string *core.Token
	token  *core.Token
	i      *core.Token
	j      *core.Token
	aux    *core.Token
	core   *core.Token
	err    *core.Token
	node   *core.Token
	this   *core.Token
	_Type  *core.Token
	util   *core.Token
}

func (i *StringsData) IsStrings() {}

func (i *StringsData) ForEachNode(fn func(core.AstNode, unique.Handle[string], int)) {
}

func (i *StringsData) ForEachReference(fn func(core.UntypedReference, unique.Handle[string], int)) {
}

func (i *StringsData) String() string {
	if i != nil && i.string != nil {
		return i.string.Image
	} else {
		return ""
	}
}

func (i *StringsData) StringToken() *core.Token {
	return i.string
}

func (i *StringsData) SetString(value *core.Token) {
	i.string = value
}

func (i *StringsData) Token() string {
	if i != nil && i.token != nil {
		return i.token.Image
	} else {
		return ""
	}
}

func (i *StringsData) TokenToken() *core.Token {
	return i.token
}

func (i *StringsData) SetToken(value *core.Token) {
	i.token = value
}

func (i *StringsData) I() string {
	if i != nil && i.i != nil {
		return i.i.Image
	} else {
		return ""
	}
}

func (i *StringsData) IToken() *core.Token {
	return i.i
}

func (i *StringsData) SetI(value *core.Token) {
	i.i = value
}

func (i *StringsData) J() string {
	if i != nil && i.j != nil {
		return i.j.Image
	} else {
		return ""
	}
}

func (i *StringsData) JToken() *core.Token {
	return i.j
}

func (i *StringsData) SetJ(value *core.Token) {
	i.j = value
}

func (i *StringsData) Aux() string {
	if i != nil && i.aux != nil {
		return i.aux.Image
	} else {
		return ""
	}
}

func (i *StringsData) AuxToken() *core.Token {
	return i.aux
}

func (i *StringsData) SetAux(value *core.Token) {
	i.aux = value
}

func (i *StringsData) Core() string {
	if i != nil && i.core != nil {
		return i.core.Image
	} else {
		return ""
	}
}

func (i *StringsData) CoreToken() *core.Token {
	return i.core
}

func (i *StringsData) SetCore(value *core.Token) {
	i.core = value
}

func (i *StringsData) Err() string {
	if i != nil && i.err != nil {
		return i.err.Image
	} else {
		return ""
	}
}

func (i *StringsData) ErrToken() *core.Token {
	return i.err
}

func (i *StringsData) SetErr(value *core.Token) {
	i.err = value
}

func (i *StringsData) Node() string {
	if i != nil && i.node != nil {
		return i.node.Image
	} else {
		return ""
	}
}

func (i *StringsData) NodeToken() *core.Token {
	return i.node
}

func (i *StringsData) SetNode(value *core.Token) {
	i.node = value
}

func (i *StringsData) This() string {
	if i != nil && i.this != nil {
		return i.this.Image
	} else {
		return ""
	}
}

func (i *StringsData) ThisToken() *core.Token {
	return i.this
}

func (i *StringsData) SetThis(value *core.Token) {
	i.this = value
}

func (i *StringsData) Type() string {
	if i != nil && i._Type != nil {
		return i._Type.Image
	} else {
		return ""
	}
}

func (i *StringsData) TypeToken() *core.Token {
	return i._Type
}

func (i *StringsData) SetType(value *core.Token) {
	i._Type = value
}

func (i *StringsData) Util() string {
	if i != nil && i.util != nil {
		return i.util.Image
	} else {
		return ""
	}
}

func (i *StringsData) UtilToken() *core.Token {
	return i.util
}

func (i *StringsData) SetUtil(value *core.Token) {
	i.util = value
}

type StringsImpl struct {
	core.AstNodeBase
	StringsData
}

func (i *StringsImpl) ForEachNode(fn func(core.AstNode, unique.Handle[string], int)) {
	i.StringsData.ForEachNode(fn)
}

func (i *StringsImpl) ForEachReference(fn func(core.UntypedReference, unique.Handle[string], int)) {
	i.StringsData.ForEachReference(fn)
}

func (i *StringsImpl) Resolve(path core.FragmentPath) (core.AstNode, error) {
	if path.Empty() {
		return i, nil
	}
	field, _ := path.Head()
	switch field {
	case fieldNameAux:
		return nil, fmt.Errorf("StringsImpl.Resolve: field 'aux' holds a primitive value instead of an ast node")
	case fieldNameCore:
		return nil, fmt.Errorf("StringsImpl.Resolve: field 'core' holds a primitive value instead of an ast node")
	case fieldNameErr:
		return nil, fmt.Errorf("StringsImpl.Resolve: field 'err' holds a primitive value instead of an ast node")
	case fieldNameI:
		return nil, fmt.Errorf("StringsImpl.Resolve: field 'i' holds a primitive value instead of an ast node")
	case fieldNameJ:
		return nil, fmt.Errorf("StringsImpl.Resolve: field 'j' holds a primitive value instead of an ast node")
	case fieldNameNode:
		return nil, fmt.Errorf("StringsImpl.Resolve: field 'node' holds a primitive value instead of an ast node")
	case fieldNameString:
		return nil, fmt.Errorf("StringsImpl.Resolve: field 'string' holds a primitive value instead of an ast node")
	case fieldNameThis:
		return nil, fmt.Errorf("StringsImpl.Resolve: field 'this' holds a primitive value instead of an ast node")
	case fieldNameToken:
		return nil, fmt.Errorf("StringsImpl.Resolve: field 'token' holds a primitive value instead of an ast node")
	case fieldNameType:
		return nil, fmt.Errorf("StringsImpl.Resolve: field '_Type' holds a primitive value instead of an ast node")
	case fieldNameUtil:
		return nil, fmt.Errorf("StringsImpl.Resolve: field 'util' holds a primitive value instead of an ast node")
	default:
		nodePath, _ := core.PathOf(i)
		return nil, fmt.Errorf("StringsImpl.Resolve: field '%s' does not exist in node '%s' of type 'Strings'", field.Value(), nodePath)
	}
}

type StringLists interface {
	core.AstNode

	IsStringLists()
	String() []*core.Token
	SetStringItem(item *core.Token)
	Composite() []*core.Token
	SetCompositeItem(item *core.Token)
	Token() []*core.Token
	SetTokenItem(item *core.Token)
	Int() []*core.Token
	SetIntItem(item *core.Token)
	Uint() []*core.Token
	SetUintItem(item *core.Token)
	Make() []*core.Token
	SetMakeItem(item *core.Token)
	Item() []*core.Token
	SetItemItem(item *core.Token)
	I() []*core.Token
	SetIItem(item *core.Token)
	J() []*core.Token
	SetJItem(item *core.Token)
	Aux() []*core.Token
	SetAuxItem(item *core.Token)
	Core() []*core.Token
	SetCoreItem(item *core.Token)
	Err() []*core.Token
	SetErrItem(item *core.Token)
	Node() []*core.Token
	SetNodeItem(item *core.Token)
	This() []*core.Token
	SetThisItem(item *core.Token)
	Type() []*core.Token
	SetTypeItem(item *core.Token)
	Util() []*core.Token
	SetUtilItem(item *core.Token)
}

func NewStringLists() StringLists {
	return &StringListsImpl{}
}

type StringListsData struct {
	string    []*core.Token
	composite []*core.Token
	token     []*core.Token
	int       []*core.Token
	uint      []*core.Token
	make      []*core.Token
	item      []*core.Token
	i         []*core.Token
	j         []*core.Token
	aux       []*core.Token
	core      []*core.Token
	err       []*core.Token
	node      []*core.Token
	this      []*core.Token
	_Type     []*core.Token
	util      []*core.Token
}

func (i *StringListsData) IsStringLists() {}

func (i *StringListsData) ForEachNode(fn func(core.AstNode, unique.Handle[string], int)) {
}

func (i *StringListsData) ForEachReference(fn func(core.UntypedReference, unique.Handle[string], int)) {
}

func (i *StringListsData) String() []*core.Token {
	return i.string
}

func (i *StringListsData) SetStringItem(item *core.Token) {
	i.string = append(i.string, item)
}

func (i *StringListsData) Composite() []*core.Token {
	return i.composite
}

func (i *StringListsData) SetCompositeItem(item *core.Token) {
	i.composite = append(i.composite, item)
}

func (i *StringListsData) Token() []*core.Token {
	return i.token
}

func (i *StringListsData) SetTokenItem(item *core.Token) {
	i.token = append(i.token, item)
}

func (i *StringListsData) Int() []*core.Token {
	return i.int
}

func (i *StringListsData) SetIntItem(item *core.Token) {
	i.int = append(i.int, item)
}

func (i *StringListsData) Uint() []*core.Token {
	return i.uint
}

func (i *StringListsData) SetUintItem(item *core.Token) {
	i.uint = append(i.uint, item)
}

func (i *StringListsData) Make() []*core.Token {
	return i.make
}

func (i *StringListsData) SetMakeItem(item *core.Token) {
	i.make = append(i.make, item)
}

func (i *StringListsData) Item() []*core.Token {
	return i.item
}

func (i *StringListsData) SetItemItem(item *core.Token) {
	i.item = append(i.item, item)
}

func (i *StringListsData) I() []*core.Token {
	return i.i
}

func (i *StringListsData) SetIItem(item *core.Token) {
	i.i = append(i.i, item)
}

func (i *StringListsData) J() []*core.Token {
	return i.j
}

func (i *StringListsData) SetJItem(item *core.Token) {
	i.j = append(i.j, item)
}

func (i *StringListsData) Aux() []*core.Token {
	return i.aux
}

func (i *StringListsData) SetAuxItem(item *core.Token) {
	i.aux = append(i.aux, item)
}

func (i *StringListsData) Core() []*core.Token {
	return i.core
}

func (i *StringListsData) SetCoreItem(item *core.Token) {
	i.core = append(i.core, item)
}

func (i *StringListsData) Err() []*core.Token {
	return i.err
}

func (i *StringListsData) SetErrItem(item *core.Token) {
	i.err = append(i.err, item)
}

func (i *StringListsData) Node() []*core.Token {
	return i.node
}

func (i *StringListsData) SetNodeItem(item *core.Token) {
	i.node = append(i.node, item)
}

func (i *StringListsData) This() []*core.Token {
	return i.this
}

func (i *StringListsData) SetThisItem(item *core.Token) {
	i.this = append(i.this, item)
}

func (i *StringListsData) Type() []*core.Token {
	return i._Type
}

func (i *StringListsData) SetTypeItem(item *core.Token) {
	i._Type = append(i._Type, item)
}

func (i *StringListsData) Util() []*core.Token {
	return i.util
}

func (i *StringListsData) SetUtilItem(item *core.Token) {
	i.util = append(i.util, item)
}

type StringListsImpl struct {
	core.AstNodeBase
	StringListsData
}

func (i *StringListsImpl) ForEachNode(fn func(core.AstNode, unique.Handle[string], int)) {
	i.StringListsData.ForEachNode(fn)
}

func (i *StringListsImpl) ForEachReference(fn func(core.UntypedReference, unique.Handle[string], int)) {
	i.StringListsData.ForEachReference(fn)
}

func (i *StringListsImpl) Resolve(path core.FragmentPath) (core.AstNode, error) {
	if path.Empty() {
		return i, nil
	}
	field, _ := path.Head()
	switch field {
	case fieldNameAux:
		return nil, fmt.Errorf("StringListsImpl.Resolve: field 'aux' holds a primitive value instead of an ast node")
	case fieldNameComposite:
		return nil, fmt.Errorf("StringListsImpl.Resolve: field 'composite' holds a primitive value instead of an ast node")
	case fieldNameCore:
		return nil, fmt.Errorf("StringListsImpl.Resolve: field 'core' holds a primitive value instead of an ast node")
	case fieldNameErr:
		return nil, fmt.Errorf("StringListsImpl.Resolve: field 'err' holds a primitive value instead of an ast node")
	case fieldNameI:
		return nil, fmt.Errorf("StringListsImpl.Resolve: field 'i' holds a primitive value instead of an ast node")
	case fieldNameInt:
		return nil, fmt.Errorf("StringListsImpl.Resolve: field 'int' holds a primitive value instead of an ast node")
	case fieldNameItem:
		return nil, fmt.Errorf("StringListsImpl.Resolve: field 'item' holds a primitive value instead of an ast node")
	case fieldNameJ:
		return nil, fmt.Errorf("StringListsImpl.Resolve: field 'j' holds a primitive value instead of an ast node")
	case fieldNameMake:
		return nil, fmt.Errorf("StringListsImpl.Resolve: field 'make' holds a primitive value instead of an ast node")
	case fieldNameNode:
		return nil, fmt.Errorf("StringListsImpl.Resolve: field 'node' holds a primitive value instead of an ast node")
	case fieldNameString:
		return nil, fmt.Errorf("StringListsImpl.Resolve: field 'string' holds a primitive value instead of an ast node")
	case fieldNameThis:
		return nil, fmt.Errorf("StringListsImpl.Resolve: field 'this' holds a primitive value instead of an ast node")
	case fieldNameToken:
		return nil, fmt.Errorf("StringListsImpl.Resolve: field 'token' holds a primitive value instead of an ast node")
	case fieldNameType:
		return nil, fmt.Errorf("StringListsImpl.Resolve: field '_Type' holds a primitive value instead of an ast node")
	case fieldNameUint:
		return nil, fmt.Errorf("StringListsImpl.Resolve: field 'uint' holds a primitive value instead of an ast node")
	case fieldNameUtil:
		return nil, fmt.Errorf("StringListsImpl.Resolve: field 'util' holds a primitive value instead of an ast node")
	default:
		nodePath, _ := core.PathOf(i)
		return nil, fmt.Errorf("StringListsImpl.Resolve: field '%s' does not exist in node '%s' of type 'StringLists'", field.Value(), nodePath)
	}
}

type Composites interface {
	core.AstNode

	IsComposites()
	Composite() string
	CompositeNode() core.CompositeNode
	SetComposite(value core.CompositeNode)
	Token() string
	TokenNode() core.CompositeNode
	SetToken(value core.CompositeNode)
	Aux() string
	AuxNode() core.CompositeNode
	SetAux(value core.CompositeNode)
	Core() string
	CoreNode() core.CompositeNode
	SetCore(value core.CompositeNode)
	Err() string
	ErrNode() core.CompositeNode
	SetErr(value core.CompositeNode)
	Node() string
	NodeNode() core.CompositeNode
	SetNode(value core.CompositeNode)
	This() string
	ThisNode() core.CompositeNode
	SetThis(value core.CompositeNode)
	Type() string
	TypeNode() core.CompositeNode
	SetType(value core.CompositeNode)
	Util() string
	UtilNode() core.CompositeNode
	SetUtil(value core.CompositeNode)
}

func NewComposites() Composites {
	return &CompositesImpl{}
}

type CompositesData struct {
	composite core.CompositeNode
	token     core.CompositeNode
	aux       core.CompositeNode
	core      core.CompositeNode
	err       core.CompositeNode
	node      core.CompositeNode
	this      core.CompositeNode
	_Type     core.CompositeNode
	util      core.CompositeNode
}

func (i *CompositesData) IsComposites() {}

func (i *CompositesData) ForEachNode(fn func(core.AstNode, unique.Handle[string], int)) {
	if i.composite != nil {
		fn(i.composite, fieldNameComposite, -1)
	}
	if i.token != nil {
		fn(i.token, fieldNameToken, -1)
	}
	if i.aux != nil {
		fn(i.aux, fieldNameAux, -1)
	}
	if i.core != nil {
		fn(i.core, fieldNameCore, -1)
	}
	if i.err != nil {
		fn(i.err, fieldNameErr, -1)
	}
	if i.node != nil {
		fn(i.node, fieldNameNode, -1)
	}
	if i.this != nil {
		fn(i.this, fieldNameThis, -1)
	}
	if i._Type != nil {
		fn(i._Type, fieldNameType, -1)
	}
	if i.util != nil {
		fn(i.util, fieldNameUtil, -1)
	}
}

func (i *CompositesData) ForEachReference(fn func(core.UntypedReference, unique.Handle[string], int)) {
}

func (i *CompositesData) Composite() string {
	if i != nil && i.composite != nil {
		return i.composite.String()
	} else {
		return ""
	}
}

func (i *CompositesData) CompositeNode() core.CompositeNode {
	return i.composite
}

func (i *CompositesData) SetComposite(value core.CompositeNode) {
	i.composite = value
}

func (i *CompositesData) Token() string {
	if i != nil && i.token != nil {
		return i.token.String()
	} else {
		return ""
	}
}

func (i *CompositesData) TokenNode() core.CompositeNode {
	return i.token
}

func (i *CompositesData) SetToken(value core.CompositeNode) {
	i.token = value
}

func (i *CompositesData) Aux() string {
	if i != nil && i.aux != nil {
		return i.aux.String()
	} else {
		return ""
	}
}

func (i *CompositesData) AuxNode() core.CompositeNode {
	return i.aux
}

func (i *CompositesData) SetAux(value core.CompositeNode) {
	i.aux = value
}

func (i *CompositesData) Core() string {
	if i != nil && i.core != nil {
		return i.core.String()
	} else {
		return ""
	}
}

func (i *CompositesData) CoreNode() core.CompositeNode {
	return i.core
}

func (i *CompositesData) SetCore(value core.CompositeNode) {
	i.core = value
}

func (i *CompositesData) Err() string {
	if i != nil && i.err != nil {
		return i.err.String()
	} else {
		return ""
	}
}

func (i *CompositesData) ErrNode() core.CompositeNode {
	return i.err
}

func (i *CompositesData) SetErr(value core.CompositeNode) {
	i.err = value
}

func (i *CompositesData) Node() string {
	if i != nil && i.node != nil {
		return i.node.String()
	} else {
		return ""
	}
}

func (i *CompositesData) NodeNode() core.CompositeNode {
	return i.node
}

func (i *CompositesData) SetNode(value core.CompositeNode) {
	i.node = value
}

func (i *CompositesData) This() string {
	if i != nil && i.this != nil {
		return i.this.String()
	} else {
		return ""
	}
}

func (i *CompositesData) ThisNode() core.CompositeNode {
	return i.this
}

func (i *CompositesData) SetThis(value core.CompositeNode) {
	i.this = value
}

func (i *CompositesData) Type() string {
	if i != nil && i._Type != nil {
		return i._Type.String()
	} else {
		return ""
	}
}

func (i *CompositesData) TypeNode() core.CompositeNode {
	return i._Type
}

func (i *CompositesData) SetType(value core.CompositeNode) {
	i._Type = value
}

func (i *CompositesData) Util() string {
	if i != nil && i.util != nil {
		return i.util.String()
	} else {
		return ""
	}
}

func (i *CompositesData) UtilNode() core.CompositeNode {
	return i.util
}

func (i *CompositesData) SetUtil(value core.CompositeNode) {
	i.util = value
}

type CompositesImpl struct {
	core.AstNodeBase
	CompositesData
}

func (i *CompositesImpl) ForEachNode(fn func(core.AstNode, unique.Handle[string], int)) {
	i.CompositesData.ForEachNode(fn)
}

func (i *CompositesImpl) ForEachReference(fn func(core.UntypedReference, unique.Handle[string], int)) {
	i.CompositesData.ForEachReference(fn)
}

func (i *CompositesImpl) Resolve(path core.FragmentPath) (core.AstNode, error) {
	if path.Empty() {
		return i, nil
	}
	field, _ := path.Head()
	switch field {
	case fieldNameAux:
		return nil, fmt.Errorf("CompositesImpl.Resolve: field 'aux' holds a primitive value instead of an ast node")
	case fieldNameComposite:
		return nil, fmt.Errorf("CompositesImpl.Resolve: field 'composite' holds a primitive value instead of an ast node")
	case fieldNameCore:
		return nil, fmt.Errorf("CompositesImpl.Resolve: field 'core' holds a primitive value instead of an ast node")
	case fieldNameErr:
		return nil, fmt.Errorf("CompositesImpl.Resolve: field 'err' holds a primitive value instead of an ast node")
	case fieldNameNode:
		return nil, fmt.Errorf("CompositesImpl.Resolve: field 'node' holds a primitive value instead of an ast node")
	case fieldNameThis:
		return nil, fmt.Errorf("CompositesImpl.Resolve: field 'this' holds a primitive value instead of an ast node")
	case fieldNameToken:
		return nil, fmt.Errorf("CompositesImpl.Resolve: field 'token' holds a primitive value instead of an ast node")
	case fieldNameType:
		return nil, fmt.Errorf("CompositesImpl.Resolve: field '_Type' holds a primitive value instead of an ast node")
	case fieldNameUtil:
		return nil, fmt.Errorf("CompositesImpl.Resolve: field 'util' holds a primitive value instead of an ast node")
	default:
		nodePath, _ := core.PathOf(i)
		return nil, fmt.Errorf("CompositesImpl.Resolve: field '%s' does not exist in node '%s' of type 'Composites'", field.Value(), nodePath)
	}
}

type CompositeLists interface {
	core.AstNode

	IsCompositeLists()
	Composite() []core.CompositeNode
	SetCompositeItem(item core.CompositeNode)
	String() []core.CompositeNode
	SetStringItem(item core.CompositeNode)
	Token() []core.CompositeNode
	SetTokenItem(item core.CompositeNode)
	Int() []core.CompositeNode
	SetIntItem(item core.CompositeNode)
	Uint() []core.CompositeNode
	SetUintItem(item core.CompositeNode)
	Make() []core.CompositeNode
	SetMakeItem(item core.CompositeNode)
	Item() []core.CompositeNode
	SetItemItem(item core.CompositeNode)
	I() []core.CompositeNode
	SetIItem(item core.CompositeNode)
	J() []core.CompositeNode
	SetJItem(item core.CompositeNode)
	Aux() []core.CompositeNode
	SetAuxItem(item core.CompositeNode)
	Core() []core.CompositeNode
	SetCoreItem(item core.CompositeNode)
	Err() []core.CompositeNode
	SetErrItem(item core.CompositeNode)
	Node() []core.CompositeNode
	SetNodeItem(item core.CompositeNode)
	This() []core.CompositeNode
	SetThisItem(item core.CompositeNode)
	Type() []core.CompositeNode
	SetTypeItem(item core.CompositeNode)
	Util() []core.CompositeNode
	SetUtilItem(item core.CompositeNode)
}

func NewCompositeLists() CompositeLists {
	return &CompositeListsImpl{}
}

type CompositeListsData struct {
	composite []core.CompositeNode
	string    []core.CompositeNode
	token     []core.CompositeNode
	int       []core.CompositeNode
	uint      []core.CompositeNode
	make      []core.CompositeNode
	item      []core.CompositeNode
	i         []core.CompositeNode
	j         []core.CompositeNode
	aux       []core.CompositeNode
	core      []core.CompositeNode
	err       []core.CompositeNode
	node      []core.CompositeNode
	this      []core.CompositeNode
	_Type     []core.CompositeNode
	util      []core.CompositeNode
}

func (i *CompositeListsData) IsCompositeLists() {}

func (i *CompositeListsData) ForEachNode(fn func(core.AstNode, unique.Handle[string], int)) {
	for j, item := range i.composite {
		fn(item, fieldNameComposite, j)
	}
	for j, item := range i.string {
		fn(item, fieldNameString, j)
	}
	for j, item := range i.token {
		fn(item, fieldNameToken, j)
	}
	for j, item := range i.int {
		fn(item, fieldNameInt, j)
	}
	for j, item := range i.uint {
		fn(item, fieldNameUint, j)
	}
	for j, item := range i.make {
		fn(item, fieldNameMake, j)
	}
	for j, item := range i.item {
		fn(item, fieldNameItem, j)
	}
	for j, item := range i.i {
		fn(item, fieldNameI, j)
	}
	for j, item := range i.j {
		fn(item, fieldNameJ, j)
	}
	for j, item := range i.aux {
		fn(item, fieldNameAux, j)
	}
	for j, item := range i.core {
		fn(item, fieldNameCore, j)
	}
	for j, item := range i.err {
		fn(item, fieldNameErr, j)
	}
	for j, item := range i.node {
		fn(item, fieldNameNode, j)
	}
	for j, item := range i.this {
		fn(item, fieldNameThis, j)
	}
	for j, item := range i._Type {
		fn(item, fieldNameType, j)
	}
	for j, item := range i.util {
		fn(item, fieldNameUtil, j)
	}
}

func (i *CompositeListsData) ForEachReference(fn func(core.UntypedReference, unique.Handle[string], int)) {
}

func (i *CompositeListsData) Composite() []core.CompositeNode {
	return i.composite
}

func (i *CompositeListsData) SetCompositeItem(item core.CompositeNode) {
	i.composite = append(i.composite, item)
}

func (i *CompositeListsData) String() []core.CompositeNode {
	return i.string
}

func (i *CompositeListsData) SetStringItem(item core.CompositeNode) {
	i.string = append(i.string, item)
}

func (i *CompositeListsData) Token() []core.CompositeNode {
	return i.token
}

func (i *CompositeListsData) SetTokenItem(item core.CompositeNode) {
	i.token = append(i.token, item)
}

func (i *CompositeListsData) Int() []core.CompositeNode {
	return i.int
}

func (i *CompositeListsData) SetIntItem(item core.CompositeNode) {
	i.int = append(i.int, item)
}

func (i *CompositeListsData) Uint() []core.CompositeNode {
	return i.uint
}

func (i *CompositeListsData) SetUintItem(item core.CompositeNode) {
	i.uint = append(i.uint, item)
}

func (i *CompositeListsData) Make() []core.CompositeNode {
	return i.make
}

func (i *CompositeListsData) SetMakeItem(item core.CompositeNode) {
	i.make = append(i.make, item)
}

func (i *CompositeListsData) Item() []core.CompositeNode {
	return i.item
}

func (i *CompositeListsData) SetItemItem(item core.CompositeNode) {
	i.item = append(i.item, item)
}

func (i *CompositeListsData) I() []core.CompositeNode {
	return i.i
}

func (i *CompositeListsData) SetIItem(item core.CompositeNode) {
	i.i = append(i.i, item)
}

func (i *CompositeListsData) J() []core.CompositeNode {
	return i.j
}

func (i *CompositeListsData) SetJItem(item core.CompositeNode) {
	i.j = append(i.j, item)
}

func (i *CompositeListsData) Aux() []core.CompositeNode {
	return i.aux
}

func (i *CompositeListsData) SetAuxItem(item core.CompositeNode) {
	i.aux = append(i.aux, item)
}

func (i *CompositeListsData) Core() []core.CompositeNode {
	return i.core
}

func (i *CompositeListsData) SetCoreItem(item core.CompositeNode) {
	i.core = append(i.core, item)
}

func (i *CompositeListsData) Err() []core.CompositeNode {
	return i.err
}

func (i *CompositeListsData) SetErrItem(item core.CompositeNode) {
	i.err = append(i.err, item)
}

func (i *CompositeListsData) Node() []core.CompositeNode {
	return i.node
}

func (i *CompositeListsData) SetNodeItem(item core.CompositeNode) {
	i.node = append(i.node, item)
}

func (i *CompositeListsData) This() []core.CompositeNode {
	return i.this
}

func (i *CompositeListsData) SetThisItem(item core.CompositeNode) {
	i.this = append(i.this, item)
}

func (i *CompositeListsData) Type() []core.CompositeNode {
	return i._Type
}

func (i *CompositeListsData) SetTypeItem(item core.CompositeNode) {
	i._Type = append(i._Type, item)
}

func (i *CompositeListsData) Util() []core.CompositeNode {
	return i.util
}

func (i *CompositeListsData) SetUtilItem(item core.CompositeNode) {
	i.util = append(i.util, item)
}

type CompositeListsImpl struct {
	core.AstNodeBase
	CompositeListsData
}

func (i *CompositeListsImpl) ForEachNode(fn func(core.AstNode, unique.Handle[string], int)) {
	i.CompositeListsData.ForEachNode(fn)
}

func (i *CompositeListsImpl) ForEachReference(fn func(core.UntypedReference, unique.Handle[string], int)) {
	i.CompositeListsData.ForEachReference(fn)
}

func (i *CompositeListsImpl) Resolve(path core.FragmentPath) (core.AstNode, error) {
	if path.Empty() {
		return i, nil
	}
	field, _ := path.Head()
	switch field {
	case fieldNameAux:
		return nil, fmt.Errorf("CompositeListsImpl.Resolve: field 'aux' holds a primitive value instead of an ast node")
	case fieldNameComposite:
		return nil, fmt.Errorf("CompositeListsImpl.Resolve: field 'composite' holds a primitive value instead of an ast node")
	case fieldNameCore:
		return nil, fmt.Errorf("CompositeListsImpl.Resolve: field 'core' holds a primitive value instead of an ast node")
	case fieldNameErr:
		return nil, fmt.Errorf("CompositeListsImpl.Resolve: field 'err' holds a primitive value instead of an ast node")
	case fieldNameI:
		return nil, fmt.Errorf("CompositeListsImpl.Resolve: field 'i' holds a primitive value instead of an ast node")
	case fieldNameInt:
		return nil, fmt.Errorf("CompositeListsImpl.Resolve: field 'int' holds a primitive value instead of an ast node")
	case fieldNameItem:
		return nil, fmt.Errorf("CompositeListsImpl.Resolve: field 'item' holds a primitive value instead of an ast node")
	case fieldNameJ:
		return nil, fmt.Errorf("CompositeListsImpl.Resolve: field 'j' holds a primitive value instead of an ast node")
	case fieldNameMake:
		return nil, fmt.Errorf("CompositeListsImpl.Resolve: field 'make' holds a primitive value instead of an ast node")
	case fieldNameNode:
		return nil, fmt.Errorf("CompositeListsImpl.Resolve: field 'node' holds a primitive value instead of an ast node")
	case fieldNameString:
		return nil, fmt.Errorf("CompositeListsImpl.Resolve: field 'string' holds a primitive value instead of an ast node")
	case fieldNameThis:
		return nil, fmt.Errorf("CompositeListsImpl.Resolve: field 'this' holds a primitive value instead of an ast node")
	case fieldNameToken:
		return nil, fmt.Errorf("CompositeListsImpl.Resolve: field 'token' holds a primitive value instead of an ast node")
	case fieldNameType:
		return nil, fmt.Errorf("CompositeListsImpl.Resolve: field '_Type' holds a primitive value instead of an ast node")
	case fieldNameUint:
		return nil, fmt.Errorf("CompositeListsImpl.Resolve: field 'uint' holds a primitive value instead of an ast node")
	case fieldNameUtil:
		return nil, fmt.Errorf("CompositeListsImpl.Resolve: field 'util' holds a primitive value instead of an ast node")
	default:
		nodePath, _ := core.PathOf(i)
		return nil, fmt.Errorf("CompositeListsImpl.Resolve: field '%s' does not exist in node '%s' of type 'CompositeLists'", field.Value(), nodePath)
	}
}

type Objects interface {
	core.AstNode

	IsObjects()
	Object() Objects
	SetObject(value Objects)
	Token() Objects
	SetToken(value Objects)
	Aux() Objects
	SetAux(value Objects)
	Core() Objects
	SetCore(value Objects)
	Err() Objects
	SetErr(value Objects)
	Node() Objects
	SetNode(value Objects)
	This() Objects
	SetThis(value Objects)
	Type() Objects
	SetType(value Objects)
	Util() Objects
	SetUtil(value Objects)
}

func NewObjects() Objects {
	return &ObjectsImpl{}
}

type ObjectsData struct {
	object Objects
	token  Objects
	aux    Objects
	core   Objects
	err    Objects
	node   Objects
	this   Objects
	_Type  Objects
	util   Objects
}

func (i *ObjectsData) IsObjects() {}

func (i *ObjectsData) ForEachNode(fn func(core.AstNode, unique.Handle[string], int)) {
	if i.object != nil {
		fn(i.object, fieldNameObject, -1)
	}
	if i.token != nil {
		fn(i.token, fieldNameToken, -1)
	}
	if i.aux != nil {
		fn(i.aux, fieldNameAux, -1)
	}
	if i.core != nil {
		fn(i.core, fieldNameCore, -1)
	}
	if i.err != nil {
		fn(i.err, fieldNameErr, -1)
	}
	if i.node != nil {
		fn(i.node, fieldNameNode, -1)
	}
	if i.this != nil {
		fn(i.this, fieldNameThis, -1)
	}
	if i._Type != nil {
		fn(i._Type, fieldNameType, -1)
	}
	if i.util != nil {
		fn(i.util, fieldNameUtil, -1)
	}
}

func (i *ObjectsData) ForEachReference(fn func(core.UntypedReference, unique.Handle[string], int)) {
}

func (i *ObjectsData) Object() Objects {
	if i != nil && i.object != nil {
		return i.object
	} else {
		return nil
	}
}

func (i *ObjectsData) SetObject(value Objects) {
	i.object = value
}

func (i *ObjectsData) Token() Objects {
	if i != nil && i.token != nil {
		return i.token
	} else {
		return nil
	}
}

func (i *ObjectsData) SetToken(value Objects) {
	i.token = value
}

func (i *ObjectsData) Aux() Objects {
	if i != nil && i.aux != nil {
		return i.aux
	} else {
		return nil
	}
}

func (i *ObjectsData) SetAux(value Objects) {
	i.aux = value
}

func (i *ObjectsData) Core() Objects {
	if i != nil && i.core != nil {
		return i.core
	} else {
		return nil
	}
}

func (i *ObjectsData) SetCore(value Objects) {
	i.core = value
}

func (i *ObjectsData) Err() Objects {
	if i != nil && i.err != nil {
		return i.err
	} else {
		return nil
	}
}

func (i *ObjectsData) SetErr(value Objects) {
	i.err = value
}

func (i *ObjectsData) Node() Objects {
	if i != nil && i.node != nil {
		return i.node
	} else {
		return nil
	}
}

func (i *ObjectsData) SetNode(value Objects) {
	i.node = value
}

func (i *ObjectsData) This() Objects {
	if i != nil && i.this != nil {
		return i.this
	} else {
		return nil
	}
}

func (i *ObjectsData) SetThis(value Objects) {
	i.this = value
}

func (i *ObjectsData) Type() Objects {
	if i != nil && i._Type != nil {
		return i._Type
	} else {
		return nil
	}
}

func (i *ObjectsData) SetType(value Objects) {
	i._Type = value
}

func (i *ObjectsData) Util() Objects {
	if i != nil && i.util != nil {
		return i.util
	} else {
		return nil
	}
}

func (i *ObjectsData) SetUtil(value Objects) {
	i.util = value
}

type ObjectsImpl struct {
	core.AstNodeBase
	ObjectsData
}

func (i *ObjectsImpl) ForEachNode(fn func(core.AstNode, unique.Handle[string], int)) {
	i.ObjectsData.ForEachNode(fn)
}

func (i *ObjectsImpl) ForEachReference(fn func(core.UntypedReference, unique.Handle[string], int)) {
	i.ObjectsData.ForEachReference(fn)
}

func (i *ObjectsImpl) Resolve(path core.FragmentPath) (core.AstNode, error) {
	if path.Empty() {
		return i, nil
	}
	field, _ := path.Head()
	switch field {
	case fieldNameAux:
		if i.Aux() == nil {
			nodePath, _ := core.PathOf(i)
			return nil, fmt.Errorf("ObjectsImpl.Resolve: field 'aux' is nil in node '%s'", nodePath)
		}
		child := i.Aux()
		return child.Resolve(path.Tail())
	case fieldNameCore:
		if i.Core() == nil {
			nodePath, _ := core.PathOf(i)
			return nil, fmt.Errorf("ObjectsImpl.Resolve: field 'core' is nil in node '%s'", nodePath)
		}
		child := i.Core()
		return child.Resolve(path.Tail())
	case fieldNameErr:
		if i.Err() == nil {
			nodePath, _ := core.PathOf(i)
			return nil, fmt.Errorf("ObjectsImpl.Resolve: field 'err' is nil in node '%s'", nodePath)
		}
		child := i.Err()
		return child.Resolve(path.Tail())
	case fieldNameNode:
		if i.Node() == nil {
			nodePath, _ := core.PathOf(i)
			return nil, fmt.Errorf("ObjectsImpl.Resolve: field 'node' is nil in node '%s'", nodePath)
		}
		child := i.Node()
		return child.Resolve(path.Tail())
	case fieldNameObject:
		if i.Object() == nil {
			nodePath, _ := core.PathOf(i)
			return nil, fmt.Errorf("ObjectsImpl.Resolve: field 'object' is nil in node '%s'", nodePath)
		}
		child := i.Object()
		return child.Resolve(path.Tail())
	case fieldNameThis:
		if i.This() == nil {
			nodePath, _ := core.PathOf(i)
			return nil, fmt.Errorf("ObjectsImpl.Resolve: field 'this' is nil in node '%s'", nodePath)
		}
		child := i.This()
		return child.Resolve(path.Tail())
	case fieldNameToken:
		if i.Token() == nil {
			nodePath, _ := core.PathOf(i)
			return nil, fmt.Errorf("ObjectsImpl.Resolve: field 'token' is nil in node '%s'", nodePath)
		}
		child := i.Token()
		return child.Resolve(path.Tail())
	case fieldNameType:
		if i.Type() == nil {
			nodePath, _ := core.PathOf(i)
			return nil, fmt.Errorf("ObjectsImpl.Resolve: field '_Type' is nil in node '%s'", nodePath)
		}
		child := i.Type()
		return child.Resolve(path.Tail())
	case fieldNameUtil:
		if i.Util() == nil {
			nodePath, _ := core.PathOf(i)
			return nil, fmt.Errorf("ObjectsImpl.Resolve: field 'util' is nil in node '%s'", nodePath)
		}
		child := i.Util()
		return child.Resolve(path.Tail())
	default:
		nodePath, _ := core.PathOf(i)
		return nil, fmt.Errorf("ObjectsImpl.Resolve: field '%s' does not exist in node '%s' of type 'Objects'", field.Value(), nodePath)
	}
}

type ObjectLists interface {
	core.AstNode

	IsObjectLists()
	Object() []Objects
	SetObjectItem(item Objects)
	Composite() []Objects
	SetCompositeItem(item Objects)
	String() []Objects
	SetStringItem(item Objects)
	Token() []Objects
	SetTokenItem(item Objects)
	Int() []Objects
	SetIntItem(item Objects)
	Uint() []Objects
	SetUintItem(item Objects)
	Make() []Objects
	SetMakeItem(item Objects)
	Item() []Objects
	SetItemItem(item Objects)
	I() []Objects
	SetIItem(item Objects)
	J() []Objects
	SetJItem(item Objects)
	Aux() []Objects
	SetAuxItem(item Objects)
	Core() []Objects
	SetCoreItem(item Objects)
	Err() []Objects
	SetErrItem(item Objects)
	Node() []Objects
	SetNodeItem(item Objects)
	This() []Objects
	SetThisItem(item Objects)
	Type() []Objects
	SetTypeItem(item Objects)
	Util() []Objects
	SetUtilItem(item Objects)
}

func NewObjectLists() ObjectLists {
	return &ObjectListsImpl{}
}

type ObjectListsData struct {
	object    []Objects
	composite []Objects
	string    []Objects
	token     []Objects
	int       []Objects
	uint      []Objects
	make      []Objects
	item      []Objects
	i         []Objects
	j         []Objects
	aux       []Objects
	core      []Objects
	err       []Objects
	node      []Objects
	this      []Objects
	_Type     []Objects
	util      []Objects
}

func (i *ObjectListsData) IsObjectLists() {}

func (i *ObjectListsData) ForEachNode(fn func(core.AstNode, unique.Handle[string], int)) {
	for j, item := range i.object {
		fn(item, fieldNameObject, j)
	}
	for j, item := range i.composite {
		fn(item, fieldNameComposite, j)
	}
	for j, item := range i.string {
		fn(item, fieldNameString, j)
	}
	for j, item := range i.token {
		fn(item, fieldNameToken, j)
	}
	for j, item := range i.int {
		fn(item, fieldNameInt, j)
	}
	for j, item := range i.uint {
		fn(item, fieldNameUint, j)
	}
	for j, item := range i.make {
		fn(item, fieldNameMake, j)
	}
	for j, item := range i.item {
		fn(item, fieldNameItem, j)
	}
	for j, item := range i.i {
		fn(item, fieldNameI, j)
	}
	for j, item := range i.j {
		fn(item, fieldNameJ, j)
	}
	for j, item := range i.aux {
		fn(item, fieldNameAux, j)
	}
	for j, item := range i.core {
		fn(item, fieldNameCore, j)
	}
	for j, item := range i.err {
		fn(item, fieldNameErr, j)
	}
	for j, item := range i.node {
		fn(item, fieldNameNode, j)
	}
	for j, item := range i.this {
		fn(item, fieldNameThis, j)
	}
	for j, item := range i._Type {
		fn(item, fieldNameType, j)
	}
	for j, item := range i.util {
		fn(item, fieldNameUtil, j)
	}
}

func (i *ObjectListsData) ForEachReference(fn func(core.UntypedReference, unique.Handle[string], int)) {
}

func (i *ObjectListsData) Object() []Objects {
	return i.object
}

func (i *ObjectListsData) SetObjectItem(item Objects) {
	i.object = append(i.object, item)
}

func (i *ObjectListsData) Composite() []Objects {
	return i.composite
}

func (i *ObjectListsData) SetCompositeItem(item Objects) {
	i.composite = append(i.composite, item)
}

func (i *ObjectListsData) String() []Objects {
	return i.string
}

func (i *ObjectListsData) SetStringItem(item Objects) {
	i.string = append(i.string, item)
}

func (i *ObjectListsData) Token() []Objects {
	return i.token
}

func (i *ObjectListsData) SetTokenItem(item Objects) {
	i.token = append(i.token, item)
}

func (i *ObjectListsData) Int() []Objects {
	return i.int
}

func (i *ObjectListsData) SetIntItem(item Objects) {
	i.int = append(i.int, item)
}

func (i *ObjectListsData) Uint() []Objects {
	return i.uint
}

func (i *ObjectListsData) SetUintItem(item Objects) {
	i.uint = append(i.uint, item)
}

func (i *ObjectListsData) Make() []Objects {
	return i.make
}

func (i *ObjectListsData) SetMakeItem(item Objects) {
	i.make = append(i.make, item)
}

func (i *ObjectListsData) Item() []Objects {
	return i.item
}

func (i *ObjectListsData) SetItemItem(item Objects) {
	i.item = append(i.item, item)
}

func (i *ObjectListsData) I() []Objects {
	return i.i
}

func (i *ObjectListsData) SetIItem(item Objects) {
	i.i = append(i.i, item)
}

func (i *ObjectListsData) J() []Objects {
	return i.j
}

func (i *ObjectListsData) SetJItem(item Objects) {
	i.j = append(i.j, item)
}

func (i *ObjectListsData) Aux() []Objects {
	return i.aux
}

func (i *ObjectListsData) SetAuxItem(item Objects) {
	i.aux = append(i.aux, item)
}

func (i *ObjectListsData) Core() []Objects {
	return i.core
}

func (i *ObjectListsData) SetCoreItem(item Objects) {
	i.core = append(i.core, item)
}

func (i *ObjectListsData) Err() []Objects {
	return i.err
}

func (i *ObjectListsData) SetErrItem(item Objects) {
	i.err = append(i.err, item)
}

func (i *ObjectListsData) Node() []Objects {
	return i.node
}

func (i *ObjectListsData) SetNodeItem(item Objects) {
	i.node = append(i.node, item)
}

func (i *ObjectListsData) This() []Objects {
	return i.this
}

func (i *ObjectListsData) SetThisItem(item Objects) {
	i.this = append(i.this, item)
}

func (i *ObjectListsData) Type() []Objects {
	return i._Type
}

func (i *ObjectListsData) SetTypeItem(item Objects) {
	i._Type = append(i._Type, item)
}

func (i *ObjectListsData) Util() []Objects {
	return i.util
}

func (i *ObjectListsData) SetUtilItem(item Objects) {
	i.util = append(i.util, item)
}

type ObjectListsImpl struct {
	core.AstNodeBase
	ObjectListsData
}

func (i *ObjectListsImpl) ForEachNode(fn func(core.AstNode, unique.Handle[string], int)) {
	i.ObjectListsData.ForEachNode(fn)
}

func (i *ObjectListsImpl) ForEachReference(fn func(core.UntypedReference, unique.Handle[string], int)) {
	i.ObjectListsData.ForEachReference(fn)
}

func (i *ObjectListsImpl) Resolve(path core.FragmentPath) (core.AstNode, error) {
	if path.Empty() {
		return i, nil
	}
	field, index := path.Head()
	switch field {
	case fieldNameAux:
		if index >= len(i.Aux()) {
			nodePath, _ := core.PathOf(i)
			return nil, fmt.Errorf("ObjectListsImpl.Resolve: index %d exceeds length of slice in 'aux' (length=%d) in node '%s'", index, len(i.Aux()), nodePath)
		}
		child := i.Aux()[index]
		if child == nil {
			nodePath, _ := core.PathOf(i)
			return nil, fmt.Errorf("ObjectListsImpl.Resolve: item %d of slice in field 'aux' is nil in node '%s'", index, nodePath)
		}
		return child.Resolve(path.Tail())
	case fieldNameComposite:
		if index >= len(i.Composite()) {
			nodePath, _ := core.PathOf(i)
			return nil, fmt.Errorf("ObjectListsImpl.Resolve: index %d exceeds length of slice in 'composite' (length=%d) in node '%s'", index, len(i.Composite()), nodePath)
		}
		child := i.Composite()[index]
		if child == nil {
			nodePath, _ := core.PathOf(i)
			return nil, fmt.Errorf("ObjectListsImpl.Resolve: item %d of slice in field 'composite' is nil in node '%s'", index, nodePath)
		}
		return child.Resolve(path.Tail())
	case fieldNameCore:
		if index >= len(i.Core()) {
			nodePath, _ := core.PathOf(i)
			return nil, fmt.Errorf("ObjectListsImpl.Resolve: index %d exceeds length of slice in 'core' (length=%d) in node '%s'", index, len(i.Core()), nodePath)
		}
		child := i.Core()[index]
		if child == nil {
			nodePath, _ := core.PathOf(i)
			return nil, fmt.Errorf("ObjectListsImpl.Resolve: item %d of slice in field 'core' is nil in node '%s'", index, nodePath)
		}
		return child.Resolve(path.Tail())
	case fieldNameErr:
		if index >= len(i.Err()) {
			nodePath, _ := core.PathOf(i)
			return nil, fmt.Errorf("ObjectListsImpl.Resolve: index %d exceeds length of slice in 'err' (length=%d) in node '%s'", index, len(i.Err()), nodePath)
		}
		child := i.Err()[index]
		if child == nil {
			nodePath, _ := core.PathOf(i)
			return nil, fmt.Errorf("ObjectListsImpl.Resolve: item %d of slice in field 'err' is nil in node '%s'", index, nodePath)
		}
		return child.Resolve(path.Tail())
	case fieldNameI:
		if index >= len(i.I()) {
			nodePath, _ := core.PathOf(i)
			return nil, fmt.Errorf("ObjectListsImpl.Resolve: index %d exceeds length of slice in 'i' (length=%d) in node '%s'", index, len(i.I()), nodePath)
		}
		child := i.I()[index]
		if child == nil {
			nodePath, _ := core.PathOf(i)
			return nil, fmt.Errorf("ObjectListsImpl.Resolve: item %d of slice in field 'i' is nil in node '%s'", index, nodePath)
		}
		return child.Resolve(path.Tail())
	case fieldNameInt:
		if index >= len(i.Int()) {
			nodePath, _ := core.PathOf(i)
			return nil, fmt.Errorf("ObjectListsImpl.Resolve: index %d exceeds length of slice in 'int' (length=%d) in node '%s'", index, len(i.Int()), nodePath)
		}
		child := i.Int()[index]
		if child == nil {
			nodePath, _ := core.PathOf(i)
			return nil, fmt.Errorf("ObjectListsImpl.Resolve: item %d of slice in field 'int' is nil in node '%s'", index, nodePath)
		}
		return child.Resolve(path.Tail())
	case fieldNameItem:
		if index >= len(i.Item()) {
			nodePath, _ := core.PathOf(i)
			return nil, fmt.Errorf("ObjectListsImpl.Resolve: index %d exceeds length of slice in 'item' (length=%d) in node '%s'", index, len(i.Item()), nodePath)
		}
		child := i.Item()[index]
		if child == nil {
			nodePath, _ := core.PathOf(i)
			return nil, fmt.Errorf("ObjectListsImpl.Resolve: item %d of slice in field 'item' is nil in node '%s'", index, nodePath)
		}
		return child.Resolve(path.Tail())
	case fieldNameJ:
		if index >= len(i.J()) {
			nodePath, _ := core.PathOf(i)
			return nil, fmt.Errorf("ObjectListsImpl.Resolve: index %d exceeds length of slice in 'j' (length=%d) in node '%s'", index, len(i.J()), nodePath)
		}
		child := i.J()[index]
		if child == nil {
			nodePath, _ := core.PathOf(i)
			return nil, fmt.Errorf("ObjectListsImpl.Resolve: item %d of slice in field 'j' is nil in node '%s'", index, nodePath)
		}
		return child.Resolve(path.Tail())
	case fieldNameMake:
		if index >= len(i.Make()) {
			nodePath, _ := core.PathOf(i)
			return nil, fmt.Errorf("ObjectListsImpl.Resolve: index %d exceeds length of slice in 'make' (length=%d) in node '%s'", index, len(i.Make()), nodePath)
		}
		child := i.Make()[index]
		if child == nil {
			nodePath, _ := core.PathOf(i)
			return nil, fmt.Errorf("ObjectListsImpl.Resolve: item %d of slice in field 'make' is nil in node '%s'", index, nodePath)
		}
		return child.Resolve(path.Tail())
	case fieldNameNode:
		if index >= len(i.Node()) {
			nodePath, _ := core.PathOf(i)
			return nil, fmt.Errorf("ObjectListsImpl.Resolve: index %d exceeds length of slice in 'node' (length=%d) in node '%s'", index, len(i.Node()), nodePath)
		}
		child := i.Node()[index]
		if child == nil {
			nodePath, _ := core.PathOf(i)
			return nil, fmt.Errorf("ObjectListsImpl.Resolve: item %d of slice in field 'node' is nil in node '%s'", index, nodePath)
		}
		return child.Resolve(path.Tail())
	case fieldNameObject:
		if index >= len(i.Object()) {
			nodePath, _ := core.PathOf(i)
			return nil, fmt.Errorf("ObjectListsImpl.Resolve: index %d exceeds length of slice in 'object' (length=%d) in node '%s'", index, len(i.Object()), nodePath)
		}
		child := i.Object()[index]
		if child == nil {
			nodePath, _ := core.PathOf(i)
			return nil, fmt.Errorf("ObjectListsImpl.Resolve: item %d of slice in field 'object' is nil in node '%s'", index, nodePath)
		}
		return child.Resolve(path.Tail())
	case fieldNameString:
		if index >= len(i.String()) {
			nodePath, _ := core.PathOf(i)
			return nil, fmt.Errorf("ObjectListsImpl.Resolve: index %d exceeds length of slice in 'string' (length=%d) in node '%s'", index, len(i.String()), nodePath)
		}
		child := i.String()[index]
		if child == nil {
			nodePath, _ := core.PathOf(i)
			return nil, fmt.Errorf("ObjectListsImpl.Resolve: item %d of slice in field 'string' is nil in node '%s'", index, nodePath)
		}
		return child.Resolve(path.Tail())
	case fieldNameThis:
		if index >= len(i.This()) {
			nodePath, _ := core.PathOf(i)
			return nil, fmt.Errorf("ObjectListsImpl.Resolve: index %d exceeds length of slice in 'this' (length=%d) in node '%s'", index, len(i.This()), nodePath)
		}
		child := i.This()[index]
		if child == nil {
			nodePath, _ := core.PathOf(i)
			return nil, fmt.Errorf("ObjectListsImpl.Resolve: item %d of slice in field 'this' is nil in node '%s'", index, nodePath)
		}
		return child.Resolve(path.Tail())
	case fieldNameToken:
		if index >= len(i.Token()) {
			nodePath, _ := core.PathOf(i)
			return nil, fmt.Errorf("ObjectListsImpl.Resolve: index %d exceeds length of slice in 'token' (length=%d) in node '%s'", index, len(i.Token()), nodePath)
		}
		child := i.Token()[index]
		if child == nil {
			nodePath, _ := core.PathOf(i)
			return nil, fmt.Errorf("ObjectListsImpl.Resolve: item %d of slice in field 'token' is nil in node '%s'", index, nodePath)
		}
		return child.Resolve(path.Tail())
	case fieldNameType:
		if index >= len(i.Type()) {
			nodePath, _ := core.PathOf(i)
			return nil, fmt.Errorf("ObjectListsImpl.Resolve: index %d exceeds length of slice in '_Type' (length=%d) in node '%s'", index, len(i.Type()), nodePath)
		}
		child := i.Type()[index]
		if child == nil {
			nodePath, _ := core.PathOf(i)
			return nil, fmt.Errorf("ObjectListsImpl.Resolve: item %d of slice in field '_Type' is nil in node '%s'", index, nodePath)
		}
		return child.Resolve(path.Tail())
	case fieldNameUint:
		if index >= len(i.Uint()) {
			nodePath, _ := core.PathOf(i)
			return nil, fmt.Errorf("ObjectListsImpl.Resolve: index %d exceeds length of slice in 'uint' (length=%d) in node '%s'", index, len(i.Uint()), nodePath)
		}
		child := i.Uint()[index]
		if child == nil {
			nodePath, _ := core.PathOf(i)
			return nil, fmt.Errorf("ObjectListsImpl.Resolve: item %d of slice in field 'uint' is nil in node '%s'", index, nodePath)
		}
		return child.Resolve(path.Tail())
	case fieldNameUtil:
		if index >= len(i.Util()) {
			nodePath, _ := core.PathOf(i)
			return nil, fmt.Errorf("ObjectListsImpl.Resolve: index %d exceeds length of slice in 'util' (length=%d) in node '%s'", index, len(i.Util()), nodePath)
		}
		child := i.Util()[index]
		if child == nil {
			nodePath, _ := core.PathOf(i)
			return nil, fmt.Errorf("ObjectListsImpl.Resolve: item %d of slice in field 'util' is nil in node '%s'", index, nodePath)
		}
		return child.Resolve(path.Tail())
	default:
		nodePath, _ := core.PathOf(i)
		return nil, fmt.Errorf("ObjectListsImpl.Resolve: field '%s' does not exist in node '%s' of type 'ObjectLists'", field.Value(), nodePath)
	}
}

type References interface {
	core.AstNode

	IsReferences()
	Reference() *core.Reference[References]
	SetReference(value *core.Reference[References])
	Token() *core.Reference[References]
	SetToken(value *core.Reference[References])
	Aux() *core.Reference[References]
	SetAux(value *core.Reference[References])
	Core() *core.Reference[References]
	SetCore(value *core.Reference[References])
	Err() *core.Reference[References]
	SetErr(value *core.Reference[References])
	Node() *core.Reference[References]
	SetNode(value *core.Reference[References])
	This() *core.Reference[References]
	SetThis(value *core.Reference[References])
	Type() *core.Reference[References]
	SetType(value *core.Reference[References])
	Util() *core.Reference[References]
	SetUtil(value *core.Reference[References])
}

func NewReferences() References {
	return &ReferencesImpl{}
}

type ReferencesData struct {
	reference *core.Reference[References]
	token     *core.Reference[References]
	aux       *core.Reference[References]
	core      *core.Reference[References]
	err       *core.Reference[References]
	node      *core.Reference[References]
	this      *core.Reference[References]
	_Type     *core.Reference[References]
	util      *core.Reference[References]
}

func (i *ReferencesData) IsReferences() {}

func (i *ReferencesData) ForEachNode(fn func(core.AstNode, unique.Handle[string], int)) {
}

func (i *ReferencesData) ForEachReference(fn func(core.UntypedReference, unique.Handle[string], int)) {
	if i.reference != nil {
		fn(i.reference, fieldNameReference, -1)
	}
	if i.token != nil {
		fn(i.token, fieldNameToken, -1)
	}
	if i.aux != nil {
		fn(i.aux, fieldNameAux, -1)
	}
	if i.core != nil {
		fn(i.core, fieldNameCore, -1)
	}
	if i.err != nil {
		fn(i.err, fieldNameErr, -1)
	}
	if i.node != nil {
		fn(i.node, fieldNameNode, -1)
	}
	if i.this != nil {
		fn(i.this, fieldNameThis, -1)
	}
	if i._Type != nil {
		fn(i._Type, fieldNameType, -1)
	}
	if i.util != nil {
		fn(i.util, fieldNameUtil, -1)
	}
}

func (i *ReferencesData) Reference() *core.Reference[References] {
	if i != nil && i.reference != nil {
		return i.reference
	} else {
		return nil
	}
}

func (i *ReferencesData) SetReference(value *core.Reference[References]) {
	i.reference = value
}

func (i *ReferencesData) Token() *core.Reference[References] {
	if i != nil && i.token != nil {
		return i.token
	} else {
		return nil
	}
}

func (i *ReferencesData) SetToken(value *core.Reference[References]) {
	i.token = value
}

func (i *ReferencesData) Aux() *core.Reference[References] {
	if i != nil && i.aux != nil {
		return i.aux
	} else {
		return nil
	}
}

func (i *ReferencesData) SetAux(value *core.Reference[References]) {
	i.aux = value
}

func (i *ReferencesData) Core() *core.Reference[References] {
	if i != nil && i.core != nil {
		return i.core
	} else {
		return nil
	}
}

func (i *ReferencesData) SetCore(value *core.Reference[References]) {
	i.core = value
}

func (i *ReferencesData) Err() *core.Reference[References] {
	if i != nil && i.err != nil {
		return i.err
	} else {
		return nil
	}
}

func (i *ReferencesData) SetErr(value *core.Reference[References]) {
	i.err = value
}

func (i *ReferencesData) Node() *core.Reference[References] {
	if i != nil && i.node != nil {
		return i.node
	} else {
		return nil
	}
}

func (i *ReferencesData) SetNode(value *core.Reference[References]) {
	i.node = value
}

func (i *ReferencesData) This() *core.Reference[References] {
	if i != nil && i.this != nil {
		return i.this
	} else {
		return nil
	}
}

func (i *ReferencesData) SetThis(value *core.Reference[References]) {
	i.this = value
}

func (i *ReferencesData) Type() *core.Reference[References] {
	if i != nil && i._Type != nil {
		return i._Type
	} else {
		return nil
	}
}

func (i *ReferencesData) SetType(value *core.Reference[References]) {
	i._Type = value
}

func (i *ReferencesData) Util() *core.Reference[References] {
	if i != nil && i.util != nil {
		return i.util
	} else {
		return nil
	}
}

func (i *ReferencesData) SetUtil(value *core.Reference[References]) {
	i.util = value
}

type ReferencesImpl struct {
	core.AstNodeBase
	ReferencesData
}

func (i *ReferencesImpl) ForEachNode(fn func(core.AstNode, unique.Handle[string], int)) {
	i.ReferencesData.ForEachNode(fn)
}

func (i *ReferencesImpl) ForEachReference(fn func(core.UntypedReference, unique.Handle[string], int)) {
	i.ReferencesData.ForEachReference(fn)
}

func (i *ReferencesImpl) Resolve(path core.FragmentPath) (core.AstNode, error) {
	if path.Empty() {
		return i, nil
	}
	field, _ := path.Head()
	switch field {
	case fieldNameAux:
		return nil, fmt.Errorf("ReferencesImpl.Resolve: field 'aux' is a cross-reference instead of a container field")
	case fieldNameCore:
		return nil, fmt.Errorf("ReferencesImpl.Resolve: field 'core' is a cross-reference instead of a container field")
	case fieldNameErr:
		return nil, fmt.Errorf("ReferencesImpl.Resolve: field 'err' is a cross-reference instead of a container field")
	case fieldNameNode:
		return nil, fmt.Errorf("ReferencesImpl.Resolve: field 'node' is a cross-reference instead of a container field")
	case fieldNameReference:
		return nil, fmt.Errorf("ReferencesImpl.Resolve: field 'reference' is a cross-reference instead of a container field")
	case fieldNameThis:
		return nil, fmt.Errorf("ReferencesImpl.Resolve: field 'this' is a cross-reference instead of a container field")
	case fieldNameToken:
		return nil, fmt.Errorf("ReferencesImpl.Resolve: field 'token' is a cross-reference instead of a container field")
	case fieldNameType:
		return nil, fmt.Errorf("ReferencesImpl.Resolve: field '_Type' is a cross-reference instead of a container field")
	case fieldNameUtil:
		return nil, fmt.Errorf("ReferencesImpl.Resolve: field 'util' is a cross-reference instead of a container field")
	default:
		nodePath, _ := core.PathOf(i)
		return nil, fmt.Errorf("ReferencesImpl.Resolve: field '%s' does not exist in node '%s' of type 'References'", field.Value(), nodePath)
	}
}

type ReferenceLists interface {
	core.AstNode

	IsReferenceLists()
	Reference() []*core.Reference[References]
	SetReferenceItem(item *core.Reference[References])
	Composite() []*core.Reference[References]
	SetCompositeItem(item *core.Reference[References])
	String() []*core.Reference[References]
	SetStringItem(item *core.Reference[References])
	Token() []*core.Reference[References]
	SetTokenItem(item *core.Reference[References])
	Int() []*core.Reference[References]
	SetIntItem(item *core.Reference[References])
	Uint() []*core.Reference[References]
	SetUintItem(item *core.Reference[References])
	Make() []*core.Reference[References]
	SetMakeItem(item *core.Reference[References])
	Item() []*core.Reference[References]
	SetItemItem(item *core.Reference[References])
	I() []*core.Reference[References]
	SetIItem(item *core.Reference[References])
	J() []*core.Reference[References]
	SetJItem(item *core.Reference[References])
	Aux() []*core.Reference[References]
	SetAuxItem(item *core.Reference[References])
	Core() []*core.Reference[References]
	SetCoreItem(item *core.Reference[References])
	Err() []*core.Reference[References]
	SetErrItem(item *core.Reference[References])
	Node() []*core.Reference[References]
	SetNodeItem(item *core.Reference[References])
	This() []*core.Reference[References]
	SetThisItem(item *core.Reference[References])
	Type() []*core.Reference[References]
	SetTypeItem(item *core.Reference[References])
	Util() []*core.Reference[References]
	SetUtilItem(item *core.Reference[References])
}

func NewReferenceLists() ReferenceLists {
	return &ReferenceListsImpl{}
}

type ReferenceListsData struct {
	reference []*core.Reference[References]
	composite []*core.Reference[References]
	string    []*core.Reference[References]
	token     []*core.Reference[References]
	int       []*core.Reference[References]
	uint      []*core.Reference[References]
	make      []*core.Reference[References]
	item      []*core.Reference[References]
	i         []*core.Reference[References]
	j         []*core.Reference[References]
	aux       []*core.Reference[References]
	core      []*core.Reference[References]
	err       []*core.Reference[References]
	node      []*core.Reference[References]
	this      []*core.Reference[References]
	_Type     []*core.Reference[References]
	util      []*core.Reference[References]
}

func (i *ReferenceListsData) IsReferenceLists() {}

func (i *ReferenceListsData) ForEachNode(fn func(core.AstNode, unique.Handle[string], int)) {
}

func (i *ReferenceListsData) ForEachReference(fn func(core.UntypedReference, unique.Handle[string], int)) {
	for j, item := range i.reference {
		fn(item, fieldNameReference, j)
	}
	for j, item := range i.composite {
		fn(item, fieldNameComposite, j)
	}
	for j, item := range i.string {
		fn(item, fieldNameString, j)
	}
	for j, item := range i.token {
		fn(item, fieldNameToken, j)
	}
	for j, item := range i.int {
		fn(item, fieldNameInt, j)
	}
	for j, item := range i.uint {
		fn(item, fieldNameUint, j)
	}
	for j, item := range i.make {
		fn(item, fieldNameMake, j)
	}
	for j, item := range i.item {
		fn(item, fieldNameItem, j)
	}
	for j, item := range i.i {
		fn(item, fieldNameI, j)
	}
	for j, item := range i.j {
		fn(item, fieldNameJ, j)
	}
	for j, item := range i.aux {
		fn(item, fieldNameAux, j)
	}
	for j, item := range i.core {
		fn(item, fieldNameCore, j)
	}
	for j, item := range i.err {
		fn(item, fieldNameErr, j)
	}
	for j, item := range i.node {
		fn(item, fieldNameNode, j)
	}
	for j, item := range i.this {
		fn(item, fieldNameThis, j)
	}
	for j, item := range i._Type {
		fn(item, fieldNameType, j)
	}
	for j, item := range i.util {
		fn(item, fieldNameUtil, j)
	}
}

func (i *ReferenceListsData) Reference() []*core.Reference[References] {
	return i.reference
}

func (i *ReferenceListsData) SetReferenceItem(item *core.Reference[References]) {
	i.reference = append(i.reference, item)
}

func (i *ReferenceListsData) Composite() []*core.Reference[References] {
	return i.composite
}

func (i *ReferenceListsData) SetCompositeItem(item *core.Reference[References]) {
	i.composite = append(i.composite, item)
}

func (i *ReferenceListsData) String() []*core.Reference[References] {
	return i.string
}

func (i *ReferenceListsData) SetStringItem(item *core.Reference[References]) {
	i.string = append(i.string, item)
}

func (i *ReferenceListsData) Token() []*core.Reference[References] {
	return i.token
}

func (i *ReferenceListsData) SetTokenItem(item *core.Reference[References]) {
	i.token = append(i.token, item)
}

func (i *ReferenceListsData) Int() []*core.Reference[References] {
	return i.int
}

func (i *ReferenceListsData) SetIntItem(item *core.Reference[References]) {
	i.int = append(i.int, item)
}

func (i *ReferenceListsData) Uint() []*core.Reference[References] {
	return i.uint
}

func (i *ReferenceListsData) SetUintItem(item *core.Reference[References]) {
	i.uint = append(i.uint, item)
}

func (i *ReferenceListsData) Make() []*core.Reference[References] {
	return i.make
}

func (i *ReferenceListsData) SetMakeItem(item *core.Reference[References]) {
	i.make = append(i.make, item)
}

func (i *ReferenceListsData) Item() []*core.Reference[References] {
	return i.item
}

func (i *ReferenceListsData) SetItemItem(item *core.Reference[References]) {
	i.item = append(i.item, item)
}

func (i *ReferenceListsData) I() []*core.Reference[References] {
	return i.i
}

func (i *ReferenceListsData) SetIItem(item *core.Reference[References]) {
	i.i = append(i.i, item)
}

func (i *ReferenceListsData) J() []*core.Reference[References] {
	return i.j
}

func (i *ReferenceListsData) SetJItem(item *core.Reference[References]) {
	i.j = append(i.j, item)
}

func (i *ReferenceListsData) Aux() []*core.Reference[References] {
	return i.aux
}

func (i *ReferenceListsData) SetAuxItem(item *core.Reference[References]) {
	i.aux = append(i.aux, item)
}

func (i *ReferenceListsData) Core() []*core.Reference[References] {
	return i.core
}

func (i *ReferenceListsData) SetCoreItem(item *core.Reference[References]) {
	i.core = append(i.core, item)
}

func (i *ReferenceListsData) Err() []*core.Reference[References] {
	return i.err
}

func (i *ReferenceListsData) SetErrItem(item *core.Reference[References]) {
	i.err = append(i.err, item)
}

func (i *ReferenceListsData) Node() []*core.Reference[References] {
	return i.node
}

func (i *ReferenceListsData) SetNodeItem(item *core.Reference[References]) {
	i.node = append(i.node, item)
}

func (i *ReferenceListsData) This() []*core.Reference[References] {
	return i.this
}

func (i *ReferenceListsData) SetThisItem(item *core.Reference[References]) {
	i.this = append(i.this, item)
}

func (i *ReferenceListsData) Type() []*core.Reference[References] {
	return i._Type
}

func (i *ReferenceListsData) SetTypeItem(item *core.Reference[References]) {
	i._Type = append(i._Type, item)
}

func (i *ReferenceListsData) Util() []*core.Reference[References] {
	return i.util
}

func (i *ReferenceListsData) SetUtilItem(item *core.Reference[References]) {
	i.util = append(i.util, item)
}

type ReferenceListsImpl struct {
	core.AstNodeBase
	ReferenceListsData
}

func (i *ReferenceListsImpl) ForEachNode(fn func(core.AstNode, unique.Handle[string], int)) {
	i.ReferenceListsData.ForEachNode(fn)
}

func (i *ReferenceListsImpl) ForEachReference(fn func(core.UntypedReference, unique.Handle[string], int)) {
	i.ReferenceListsData.ForEachReference(fn)
}

func (i *ReferenceListsImpl) Resolve(path core.FragmentPath) (core.AstNode, error) {
	if path.Empty() {
		return i, nil
	}
	field, _ := path.Head()
	switch field {
	case fieldNameAux:
		return nil, fmt.Errorf("ReferenceListsImpl.Resolve: field 'aux' is a cross-reference instead of a container field")
	case fieldNameComposite:
		return nil, fmt.Errorf("ReferenceListsImpl.Resolve: field 'composite' is a cross-reference instead of a container field")
	case fieldNameCore:
		return nil, fmt.Errorf("ReferenceListsImpl.Resolve: field 'core' is a cross-reference instead of a container field")
	case fieldNameErr:
		return nil, fmt.Errorf("ReferenceListsImpl.Resolve: field 'err' is a cross-reference instead of a container field")
	case fieldNameI:
		return nil, fmt.Errorf("ReferenceListsImpl.Resolve: field 'i' is a cross-reference instead of a container field")
	case fieldNameInt:
		return nil, fmt.Errorf("ReferenceListsImpl.Resolve: field 'int' is a cross-reference instead of a container field")
	case fieldNameItem:
		return nil, fmt.Errorf("ReferenceListsImpl.Resolve: field 'item' is a cross-reference instead of a container field")
	case fieldNameJ:
		return nil, fmt.Errorf("ReferenceListsImpl.Resolve: field 'j' is a cross-reference instead of a container field")
	case fieldNameMake:
		return nil, fmt.Errorf("ReferenceListsImpl.Resolve: field 'make' is a cross-reference instead of a container field")
	case fieldNameNode:
		return nil, fmt.Errorf("ReferenceListsImpl.Resolve: field 'node' is a cross-reference instead of a container field")
	case fieldNameReference:
		return nil, fmt.Errorf("ReferenceListsImpl.Resolve: field 'reference' is a cross-reference instead of a container field")
	case fieldNameString:
		return nil, fmt.Errorf("ReferenceListsImpl.Resolve: field 'string' is a cross-reference instead of a container field")
	case fieldNameThis:
		return nil, fmt.Errorf("ReferenceListsImpl.Resolve: field 'this' is a cross-reference instead of a container field")
	case fieldNameToken:
		return nil, fmt.Errorf("ReferenceListsImpl.Resolve: field 'token' is a cross-reference instead of a container field")
	case fieldNameType:
		return nil, fmt.Errorf("ReferenceListsImpl.Resolve: field '_Type' is a cross-reference instead of a container field")
	case fieldNameUint:
		return nil, fmt.Errorf("ReferenceListsImpl.Resolve: field 'uint' is a cross-reference instead of a container field")
	case fieldNameUtil:
		return nil, fmt.Errorf("ReferenceListsImpl.Resolve: field 'util' is a cross-reference instead of a container field")
	default:
		nodePath, _ := core.PathOf(i)
		return nil, fmt.Errorf("ReferenceListsImpl.Resolve: field '%s' does not exist in node '%s' of type 'ReferenceLists'", field.Value(), nodePath)
	}
}

var (
	fieldNameType      = unique.Make("_Type")
	fieldNameAux       = unique.Make("aux")
	fieldNameBool      = unique.Make("bool")
	fieldNameComposite = unique.Make("composite")
	fieldNameCore      = unique.Make("core")
	fieldNameErr       = unique.Make("err")
	fieldNameI         = unique.Make("i")
	fieldNameInt       = unique.Make("int")
	fieldNameItem      = unique.Make("item")
	fieldNameJ         = unique.Make("j")
	fieldNameMake      = unique.Make("make")
	fieldNameNode      = unique.Make("node")
	fieldNameObject    = unique.Make("object")
	fieldNameReference = unique.Make("reference")
	fieldNameString    = unique.Make("string")
	fieldNameThis      = unique.Make("this")
	fieldNameToken     = unique.Make("token")
	fieldNameUint      = unique.Make("uint")
	fieldNameUtil      = unique.Make("util")
)

var JsonSyntheticFactories = map[string]func() core.AstNode{
	"Bools":          func() core.AstNode { return NewBools() },
	"CompositeLists": func() core.AstNode { return NewCompositeLists() },
	"Composites":     func() core.AstNode { return NewComposites() },
	"ObjectLists":    func() core.AstNode { return NewObjectLists() },
	"Objects":        func() core.AstNode { return NewObjects() },
	"ReferenceLists": func() core.AstNode { return NewReferenceLists() },
	"References":     func() core.AstNode { return NewReferences() },
	"StringLists":    func() core.AstNode { return NewStringLists() },
	"Strings":        func() core.AstNode { return NewStrings() },
}
