// Copyright 2025 TypeFox GmbH
// This program and the accompanying materials are made available under the
// terms of the MIT License, which is available in the project root.

package generator

import (
	"go/format"
	"runtime"
	"sort"
	"strings"

	core "typefox.dev/fastbelt"
	"typefox.dev/fastbelt/internal/grammar"
	"typefox.dev/fastbelt/util/codegen"
)

const CardinalityOne = ""
const CardinalityOptional = "?"
const CardinalityZeroOrMore = "*"
const CardinalityOneOrMore = "+"

func NewRootNode() codegen.Node {
	node := codegen.NewNode()
	node.AppendLine("// Code generated by typefox.dev/fastbelt/cmd/fastbelt. DO NOT EDIT.")
	node.AppendLine()
	return node
}

func FormatIfPossible(text string) string {
	formatted, err := format.Source([]byte(text))
	if err != nil {
		return text
	}
	return string(formatted)
}

func eol() string {
	if runtime.GOOS == "windows" {
		return "\r\n"
	}
	return "\n"
}

var EOL = eol()

const Indent = "    "

func EOLIndent(count int) string {
	return EOL + strings.Repeat(Indent, count)
}

func WriteSB(sb *strings.Builder, texts ...string) {
	for _, text := range texts {
		sb.WriteString(text)
	}
}

type GetAllKeywordsResult struct {
	Keywords []grammar.Keyword
	ByValue  map[string]int
}

func GetAllKeywords(grammr grammar.Grammar) GetAllKeywordsResult {
	keywords := map[string]grammar.Keyword{}
	allNodes := []grammar.Keyword{}
	for node := range core.AllChildren(grammr) {
		if keyword, ok := node.(grammar.Keyword); ok {
			keywords[keyword.Value()] = keyword
			allNodes = append(allNodes, keyword)
		}
	}
	return keysFromMap(keywords, allNodes)
}

type GetAllTokenDeclsResult struct {
	TopLevel  []grammar.TokenDecl
	ModeLevel []grammar.TokenDecl
	All       []grammar.TokenDecl
}

func GetAllTokenDecls(grammr grammar.Grammar) GetAllTokenDeclsResult {
	topLevel := []grammar.TokenDecl{}
	modeLevel := []grammar.TokenDecl{}
	for node := range core.AllChildren(grammr) {
		if tokenDecl, ok := node.(grammar.TokenDecl); ok {
			_, ok := tokenDecl.Container().(grammar.TokenDeclUsage)
			if ok {
				modeLevel = append(modeLevel, tokenDecl)
			} else {
				topLevel = append(topLevel, tokenDecl)
			}
		}
	}
	all := make([]grammar.TokenDecl, 0, len(topLevel)+len(modeLevel))
	copy(all, topLevel)
	copy(all[len(topLevel):], modeLevel)
	return GetAllTokenDeclsResult{
		All:       all,
		TopLevel:  topLevel,
		ModeLevel: modeLevel,
	}
}

func keysFromMap(m map[string]grammar.Keyword, allNodes []grammar.Keyword) GetAllKeywordsResult {
	keywords := []grammar.Keyword{}
	for _, v := range m {
		keywords = append(keywords, v)
	}
	sort.Slice(keywords, func(i, j int) bool {
		return keywords[i].Value() < keywords[j].Value()
	})
	byValue := map[string]int{}
	for i, k := range keywords {
		byValue[k.Value()] = i
	}
	return GetAllKeywordsResult{
		Keywords: keywords,
		ByValue:  byValue,
	}
}

func GeneratedTokenName(t core.AstNode) string {
	switch t := t.(type) {
	case grammar.TokenDecl:
		return "Token_" + t.Name()
	case grammar.TokenGroup:
		return "TokenGroup_" + t.Name()
	case grammar.Keyword:
		return "Keyword_" + grammar.KeywordName(t)
	default:
		panic("unexpected type")
	}
}

func GeneratedTokenIdxName(t core.AstNode) string {
	return GeneratedTokenName(t) + "_Idx"
}

func KeywordValue(k grammar.Keyword) string {
	return k.Value()[1 : len(k.Value())-1]
}

func RegexpValue(tokenImage string) string {
	return tokenImage[1 : len(tokenImage)-1]
}

// topoSort returns uniqueTargets sorted so that child elements appear before
// their parent element.
func topoSort(uniqueTargets []string, parents map[string][]string, ascending bool) []string {
	targetSet := map[string]bool{}
	for _, t := range uniqueTargets {
		targetSet[t] = true
	}
	visited := map[string]bool{}
	result := []string{}
	var visit func(name string)
	visit = func(name string) {
		if visited[name] {
			return
		}
		visited[name] = true
		for _, parent := range parents[name] {
			visit(parent)
		}
		if ascending {
			// Prepend so children end up before parents in the final slice.
			result = append([]string{name}, result...)
		} else {
			// Append so parents end up after children in the final slice.
			result = append(result, name)
		}
	}
	for _, t := range uniqueTargets {
		visit(t)
	}
	// Keep only types that were in uniqueTargets (visit may have walked ancestors
	// not in the set; filter them out while preserving order).
	filtered := result[:0]
	for _, t := range result {
		if targetSet[t] {
			filtered = append(filtered, t)
		}
	}
	return filtered
}
